### ISSUE TITLE
[Bug]: 每次切换模型后回复都为空

### ISSUE THREAD

**Issue by cao888** [GaiZhenbiao/ChuanhuChatGPT#1007]
### 这个bug是否已存在现有issue了？

- [X] 我确认没有已有issue，且已阅读**常见问题**。

### 错误表现

使用openai的api时
只有处于加载网页后，不切换模型，使用默认模型时，可以正常收到回复，如果切换模型，则回复都为空

### 复现操作

如下图所示，Get User Name: admin是刷新页面，默认模型是GPT4 Turbo，当切换到GPT3.5 Turbo 16K后，回复结果全都是空。
即使再切换回GPT4 Turbo，回复也是空
尝试过将GPT3.5 Turbo 16K设为默认模型，则也会出现如上情况。

![微信截图_20231222004620](https://github.com/GaiZhenbiao/ChuanhuChatGPT/assets/36356389/2d5960ed-ced4-4105-afed-d38932b5097b)

### 运行环境

- OS: 
- Browser: 
- Gradio version: 
- Python version: 

### 帮助解决

- [ ] 我愿意协助解决！

**Comment by pwq111111** [comment]
我也是这样，代码中找不到问题

**Comment by Keldos-Li** [comment]
未能复现这个问题

**Comment by chenditc** [comment]
我复现了这个问题，然后我把 GPT4 的 endpoint 换成了我自己部署的 vLLM endpoint，从 server log 对比发现，回复空的请求里，“stop” 参数传的是 ['']，正常回复的 stop 参数传的是 []。怀疑是在重置参数的时候有问题，我看看能不能找到这个对应的 bug 是啥

**Comment by chenditc** [comment]
在 Llama 模型上可以复现，我提交了一个 fix PR：https://github.com/GaiZhenbiao/ChuanhuChatGPT/pull/1063

**Comment by Keldos-Li** [comment]
Close via #1063
