### ISSUE TITLE
[其他] 代码块中的直引号("/')在二次读取格式化被显示为弯引号(“”/‘’)

### ISSUE THREAD

**Issue by Miloxing** [GaiZhenbiao/ChuanhuChatGPT#102]
### 错误描述
代码中引号不是英文

### 复现操作
1. 正常完成本地部署
2. 在对话框中要求 ChatGPT “编写程序删除txt中的字符串”
3. ChatGPT 输出代码中引号是半角

### 错误截图
![0F6D1BDE-9F5D-4517-AD6D-0A6F04070534](https://user-images.githubusercontent.com/30035495/224224855-7d867d7b-1270-4d4a-b753-154350af4243.png)

### 其他
chatgpt输出文字过程中是英文引号，写完之后变成中文了，貌似是显示问题。

**Comment by Keldos-Li** [comment]
Resolved with bd419af2ec56000875251c3958d047b4d0a920b6  ([Chuanhu](https://github.com/GaiZhenbiao))
