### ISSUE TITLE
[Bug]: Chrome 在模型选择框旁边显示密码提示框

### ISSUE THREAD

**Issue by stingshen** [GaiZhenbiao/ChuanhuChatGPT#1020]
### 这个bug是否已存在现有issue了？

- [X] 我确认没有已有issue，且已阅读**常见问题**。

### 错误表现

![image](https://github.com/GaiZhenbiao/ChuanhuChatGPT/assets/6214067/34023c31-664f-4eef-9f6e-175de0adf7fe)

这个密码提示框不应该出现，比较阻挡视线。。

### 复现操作

1. 把 chuanhuchat配置成需要用户名密码的模式
2. 使用用户名密码登陆，使用 chrome 保存用户名密码
3. 点击模型选择框，弹出密码提示框

### 运行环境

- OS: Ubuntu 18.04
- Browser: Chrome Version 120.0.6099.109
- Gradio version: 3.43.2
- Python version: 3.9.17

### 帮助解决

- [X] 我愿意协助解决！

**Comment by astorm-z** [comment]
+1
