### ISSUE TITLE
[Bug]: docker方式部署，除可发送消息、选择模型进行对话，其他所有按钮点击后无任何反应。——一种可能的解决方式：在Cloudflare中，“速度”→“优化”→“内容优化”→将Rocket Loader™选项关闭。

### ISSUE THREAD

**Issue by C-Dragon8** [GaiZhenbiao/ChuanhuChatGPT#1023]
### 这个bug是否已存在现有issue了？

- [X] 我确认没有已有issue，且已阅读**常见问题**。

### 错误表现

通过服务器部署后，网页除了可以发送消息，其他所有按钮点击无反应。见下图红框：
![2024-01-05_164547](https://github.com/GaiZhenbiao/ChuanhuChatGPT/assets/49544089/d01eec43-891b-4cee-bb28-dccda16e8a23)

### 复现操作

1. 正常完成服务器部署；
2. 正常配置Base Url、API Key；
3. 网页除了可以发送消息，其他所有按钮（见图）点击无反应；
4. 手机端登录网页后，除按钮点击无反应外，输入框也无显示，只能查看到对话记录；
5. 已尝试：按照“常见问题”文档，进行依赖安装、升级，重新通过服务器docker部署等方案，无法解决此问题。

### 运行环境

- OS: Ubuntu 22.04
- Browser: Chrome、Safari
- Gradio version: 3.43.2
- Python version: 3.10.12

### 帮助解决

- [ ] 我愿意协助解决！

**Comment by MZhao-ouo** [comment]
![image](https://github.com/GaiZhenbiao/ChuanhuChatGPT/assets/70903329/37269ee0-4863-4fc9-b2eb-5e79f8a25337)
[请检查 Nginx 配置文件](https://github.com/GaiZhenbiao/ChuanhuChatGPT/wiki/%E4%BD%BF%E7%94%A8%E6%95%99%E7%A8%8B#%E9%85%8D%E7%BD%AE-nginx-%E5%8F%8D%E5%90%91%E4%BB%A3%E7%90%86)

**Comment by C-Dragon8** [comment]
> ![image](https://private-user-images.githubusercontent.com/70903329/294448303-37269ee0-4863-4fc9-b2eb-5e79f8a25337.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDQ0NTg5MjEsIm5iZiI6MTcwNDQ1ODYyMSwicGF0aCI6Ii83MDkwMzMyOS8yOTQ0NDgzMDMtMzcyNjllZTAtNDg2My00ZmM5LWIyZWItNWU3OWY4YTI1MzM3LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAxMDUlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMTA1VDEyNDM0MVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTk5NDE3YzY1MDQyYTM2YzQ1NWI3OWQyNDdkYTEzYjRkYzlkMWQwZTI0OWMxZWNkZDI4NmM2MjAzMzQwMmMzODYmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.Mct1qRlvz9chrTkfcXSa6ztVkJNst9j32U9Qh6oCrcw) 请检查 [Nginx 配置文件](https://github.com/GaiZhenbiao/ChuanhuChatGPT/wiki/%E4%BD%BF%E7%94%A8%E6%95%99%E7%A8%8B#%E9%85%8D%E7%BD%AE-nginx-%E5%8F%8D%E5%90%91%E4%BB%A3%E7%90%86)

感谢您的回复。我是在宝塔面板上配置的反向代理规则，Nginx版本为1.24.0。nginx.conf配置文件也是配置正确的，该问题仍然存在。

**Comment by Keldos-Li** [comment]
可以打开浏览器的控制台查看报错，这个错误的原因是js加载出错，排查下面的原因：
- 是否使用了不匹配的gradio版本，检查python运行环境中使用的gradio是否正确……（或排查是否安装过gpt academic的修改版gradio等）
- 是否打开了不必要的Nginx安全设置，参考 #982.

**Comment by C-Dragon8** [comment]
> 可以打开浏览器的控制台查看报错，这个错误的原因是js加载出错，排查下面的原因：
> 
> * 是否使用了不匹配的gradio版本，检查python运行环境中使用的gradio是否正确……（或排查是否安装过gpt academic的修改版gradio等）
> * 是否打开了不必要的Nginx安全设置，参考 [[本地部署]:  Connection Error #982](https://github.com/GaiZhenbiao/ChuanhuChatGPT/issues/982).

感谢您的答复。

- gradio版本：3.43.2。部署过gpt academic，但没安装过其修改版gradio，gpt academic一切正常，未出现问题。此外，通过`pip check`检查依赖关系，也并未报错。
- 按照[https://github.com/GaiZhenbiao/ChuanhuChatGPT/issues/982](url)，我并未开启不必要的Nginx安全设置。
- 打开控制台报错显示如下图：
<img width="833" alt="2024-01-06_112642" src="https://github.com/GaiZhenbiao/ChuanhuChatGPT/assets/49544089/2b8f6397-68e0-4196-a099-cef94cdff077">

目前尚未解决该问题，使用IP地址＋端口号可以正常使用，但这种方式不安全。

**Comment by XudongLiu** [comment]
可以配置成系统服务，然后再用Nginx，应该可以的
[Unit]
Description=for Gradio
After=network.target

[Service]
#这里填写你安装ubuntu的用户和用户组
User=XXX
Group=XXX

#这里填写启动文件的位置
WorkingDirectory=/opt/XX

ExecStart=/opt/XXX/venv/bin/python /opt/XXXXX/ChuanhuChatbot.py

[Install]
WantedBy=multi-user.target
~

Ng的配置

 location / {
      proxy_connect_timeout 60;
      proxy_read_timeout 60;
      proxy_send_timeout 60;
      proxy_intercept_errors off;
      proxy_http_version 1.1;
      proxy_set_header        Host            $http_host;
      proxy_set_header        X-Real-IP            $remote_addr;
      proxy_set_header        X-Forwarded-For            $proxy_add_x_forwarded_for;
      proxy_set_header        X-Forwarded-Proto            $scheme;
      proxy_pass http://127.0.0.1:7860;

  }
  #好像Gradio的ws协议是通过/queue路径的，所以这里加上
  location /queue {
      proxy_pass http://127.0.0.1:7860;
      proxy_http_version 1.1;
      proxy_set_header Upgrade $http_upgrade;
      proxy_set_header Connection Upgrade;
  }

@C-Dragon8 希望能够帮到你

**Comment by Keldos-Li** [comment]
- 另外，可参考 #723

**Comment by C-Dragon8** [comment]
@XudongLiu @Keldos-Li 感谢两位大佬所提供的解决方案。我都尝试了。

@XudongLiu 在您的解决方案中，我确保按照你所述进行设置，我新建了一个gradio.service文件，并且确认该服务已Active。服务器重启后仍然出现我此前的问题。

@Keldos-Li 在您提供的issue #723中，我完全按照所述设置网站的配置文件，仍然出现我此前的问题。

再次感谢两位耐心解答。

**Comment by Keldos-Li** [comment]
额，我不确定，或者试试清楚浏览器缓存，关闭广告拦截插件等等……但从你之前的回复来看，如果ip+端口直接访问没问题但网址访问有问题，大概率仍然是服务器配置写法的问题……

或许 @LaoJiuYes 有空帮忙看看这个问题吗？

**Comment by C-Dragon8** [comment]
> 额，我不确定，或者试试清楚浏览器缓存，关闭广告拦截插件等等……但从你之前的回复来看，如果ip+端口直接访问没问题但网址访问有问题，大概率仍然是服务器配置写法的问题……
> 
> 或许 @LaoJiuYes 有空帮忙看看这个问题吗？

@Keldos-Li  嗯...清除浏览器缓存我今天没试，但我重启容器和nginx了，我还尝试了浏览器无痕窗口，还是老样子。早休息。

**Comment by C-Dragon8** [comment]
@LaoJiuYes 好的，感谢大佬的回复。

- 我使用docker方式安装。
```
docker run -d --name ChuanhuChat \
	-v ~/ChuanhuChatGPT/history:/app/history \
	-v ~/ChuanhuChatGPT/config.json:/app/config.json \
	-p 7860:7860 \
	tuchuanhuhuhu/chuanhuchatgpt:latest
```
- 我采用IP+端口方式访问时，登录界面正常，页面显示正常，按钮功能正常，是否使用科学上网工具都正常。
- 我不使用代理，config.json文件中代理行都是注释掉的。
```
// 自定义使用代理（请替换代理URL）
// "https_proxy": "http://127.0.0.1:1079",
// "http_proxy": "http://127.0.0.1:1079",
```
- 本地DNS我没修改过，默认的。
- 一旦使用自定义域名访问就会出现问题，除了发送消息可以，其他按钮无反应。是否使用科学上网工具都会出现，chrome、edge、safari都试过了，包括无痕模式。
![image](https://github.com/GaiZhenbiao/ChuanhuChatGPT/assets/49544089/c73e4810-474d-40d5-b430-a794aa1e43b0)

这一张是使用IP+端口方式访问的：
![image](https://github.com/GaiZhenbiao/ChuanhuChatGPT/assets/49544089/ea3aa28d-53f4-4291-8742-b54208128359)

**Comment by C-Dragon8** [comment]
@LaoJiuYes 麻烦您能帮我指出图片哪里有问题吗？对比issue #723我没有检查出来。

**Comment by C-Dragon8** [comment]
@LaoJiuYes 我尝试了仍然没有解决问题，这个位置怎么写？您能给我一个参考吗？
![image](https://github.com/GaiZhenbiao/ChuanhuChatGPT/assets/49544089/128a5416-95e3-448a-bc1c-fb23b7b591f8)

**Comment by C-Dragon8** [comment]
@LaoJiuYes 我新建了个站点，部署SSL后，把location后面的替换为您刚才所说的，问题依旧存在，其他所有配置都没动

**Comment by C-Dragon8** [comment]
> > @LaoJiuYes 我新建了个站点，部署SSL后，把location后面的替换为您刚才所说的，问题依旧存在，其他所有配置都没动
> 
> 你找川虎 @GaiZhenbiao 你的配置也不能放在这，容易泄露隐私 。你其他配置不知道是否还有问题，我觉得你付点幸苦费让川虎直接给你远程比较好。因为你的问题绝对不止反代这么简单。

好的，多谢！

**Comment by C-Dragon8** [comment]
经过连续几天的排查，终于找到了问题的解决方式：在Cloudflare中，“速度”→“优化”→“内容优化”→将Rocket Loader™选项关闭。

经测试，使用宝塔面板默认的反向代理方式，而不对网站配置文件作更改，也可以。

再次感谢各位大佬耐心解答和回复。 @LaoJiuYes @Keldos-Li @XudongLiu @MZhao-ouo
