### ISSUE TITLE
[功能请求]: 每次登陆都开启新的一段对话

### ISSUE THREAD

**Issue by ParkerLyu01** [GaiZhenbiao/ChuanhuChatGPT#1028]
### 相关问题

不熟悉这个“历史记录”这个概念的朋友，可能会一直在同一段对话里一直聊

### 可能的解决办法

每次登陆都新开一个聊天对话

### 帮助开发

- [ ] 我愿意协助开发！

**Comment by Keldos-Li** [comment]
Close via 40a0cc7018628b47948bd1a00e474e2350b45fe1
