### ISSUE TITLE
[功能请求]: 提供对 Copilot 的支持

### ISSUE THREAD

**Issue by Nativu5** [GaiZhenbiao/ChuanhuChatGPT#1029]
### 相关问题

这个项目：https://github.com/aaamoon/copilot-gpt4-service 已经实现了从 Copilot CLI 中提取 GPT-4 的功能，经过我的测试，ChuanhuGPT 只需要修改 GPT-4 的 API Base 就可以使用。但是，该项目不支持流式传输，必须在 ChuanhuGPT 的左下角页面处设置 stream 为 false 才能正常使用。

### 可能的解决办法

解决思路有两个：

1. 在 GPT-4 的基础上继承一个 GPT-4-Copilot，将 Stream 默认设置成否。
2. 在配置文件中提供一个选项，可以设置默认的 stream 行为。

### 帮助开发

- [X] 我愿意协助开发！

**Comment by Keldos-Li** [comment]
这违反相关使用政策……原仓库也被封了
