### ISSUE TITLE
[Docker] docker部署时自动精简对话

### ISSUE THREAD

**Issue by dongmuhds** [GaiZhenbiao/ChuanhuChatGPT#103]
### 错误描述
最新docker部署的时候会自动精简对话
### 复现操作
输入相应的问题后,会自动发送我们刚刚聊了什么

### 错误截图
![image-20230310142014800](http://121.4.172.195:1005/uploads/2023_03/2023_03_image-20230310142014800_63d6a70921f51bb4.png)

### 终端（控制台）中的错误报告
无报错

**Comment by geekhuashan** [comment]
我也是

**Comment by oj8k** [comment]
我也是 真的头痛这个怎么关掉,

**Comment by GaiZhenbiao** [comment]
这个是新加入的在上下文过长时自动精简对话的功能，原本是报错🤔️

**Comment by GaiZhenbiao** [comment]
或者也可以改成在上下文过长时，自动删除早期的对话记录（聊天框中仍然显示），以实现连续对话

**Comment by dongmuhds** [comment]
我即使是用很短的文本也会出现这种状况，是否没有加内容判断？

**Comment by oj8k** [comment]
> 我也是 真的头痛这个怎么关掉,
已回退23.03.08没有这个功能很舒服

**Comment by GaiZhenbiao** [comment]
好的，现在已经把无限对话的策略修改为删除早期对话。早期对话仍然会被显示在聊天框中，也可以被保存/加载，但是不会被提交给GPT。
