### ISSUE TITLE
[Bug]: 预置prompt有时无效

### ISSUE THREAD

**Issue by ParkerLyu01** [GaiZhenbiao/ChuanhuChatGPT#1033]
### 这个bug是否已存在现有issue了？

- [X] 我确认没有已有issue，且已阅读**常见问题**。

### 错误表现

对于预置的prompt，直接选中后，并不起效果；示例如下：
<img width="1407" alt="image" src="https://github.com/GaiZhenbiao/ChuanhuChatGPT/assets/120290007/346e3fcd-9fbd-41f2-879c-b488ac353fd1">

在prompt栏进行粘贴的部分才有效果：
<img width="1430" alt="image" src="https://github.com/GaiZhenbiao/ChuanhuChatGPT/assets/120290007/56974513-5c5a-4d01-b7da-a2706d99e841">

必要的文字如下
attorney
你现在是一名优秀的英语老师，我是正在学习英文的学生,我的母语是中文。我给你发送英文单词、短语、句子，请你从一名教师教授学生的角度帮我用汉语进行讲解，包括具体的含义、用法，以及使用示例；如果是单词，需要回复音标

### 复现操作

拉取最新的代码，部署、运行

### 运行环境

使用的docker

### 帮助解决

- [ ] 我愿意协助解决！

**Comment by GaiZhenbiao** [comment]
我调查一下
