### ISSUE TITLE
生成的代码里面双引号使用错误：""使用了中文的引号格式“”

### ISSUE THREAD

**Issue by arnewc** [GaiZhenbiao/ChuanhuChatGPT#104]
生成的代码里面双引号使用错误：""使用了中文的引号格式“”

**Comment by GaiZhenbiao** [comment]
这个问题真的很头大……修复起来比想象的困难很多

**Comment by Keldos-Li** [comment]
重复了，先关了……见 #102 。（而且这不是中文引号格式，英文也会用弯引号的）

**Comment by Keldos-Li** [comment]
Resolved with bd419af2ec56000875251c3958d047b4d0a920b6
