### ISSUE TITLE
[Bug]: 使用gpt-vision识图 发送多张图片时，前端无法正确显示，只能正确显示第一张

### ISSUE THREAD

**Issue by Mchousexuxu** [GaiZhenbiao/ChuanhuChatGPT#1040]
### 这个bug是否已存在现有issue了？

- [X] 我确认没有已有issue，且已阅读**常见问题**。

### 错误表现

gpt-vision单词可识别多张图片，当我们使用chuanhu时也可以发送多张图片，但是只能正确显示第一张，效果如下：
![image](https://github.com/GaiZhenbiao/ChuanhuChatGPT/assets/133076068/0eaf3700-37c5-4bb0-a686-b04ec9de2c72)
![image](https://github.com/GaiZhenbiao/ChuanhuChatGPT/assets/133076068/467e0334-8067-4a8e-8e6c-123ce454d403)
后台日志显示 这是两张不同的照片，但是前端却只能正确显示第一张

### 复现操作

使用gpt-vision

### 错误日志

```shell
null
```

### 运行环境

- OS: 
- Browser: 
- Gradio version: 
- Python version: 

### 帮助解决

- [X] 我愿意协助解决！

### 补充说明

null

**Comment by Xtaiyang** [comment]
我得也是，而且手机端在上传一张图片分析之后就不能上传知识库了，只能新建对话上传

**Comment by GaiZhenbiao** [comment]
已经在 https://github.com/GaiZhenbiao/ChuanhuChatGPT/commit/414815f44ca0741fa6bdbf50fbe44184e8ed5ff0 （最新版）中修复
