### ISSUE TITLE
[功能请求]: HIDE_MY_KEY 加入到配置中

### ISSUE THREAD

**Issue by z-henry** [GaiZhenbiao/ChuanhuChatGPT#1043]
### 相关问题

我直接用的docker pull的方式部署的，
如果能将HIDE_MY_KEY 不能为配置控制，每次更新就需要自己重新构建image

### 可能的解决办法

是否可以考虑将HIDE_MY_KEY 集成到config.json中

### 帮助开发

- [ ] 我愿意协助开发！

**Comment by GaiZhenbiao** [comment]
<img width="625" alt="image" src="https://github.com/GaiZhenbiao/ChuanhuChatGPT/assets/51039745/fb71a3d7-b59e-4827-b7df-fe8dcdad4076">

支持的
