### ISSUE TITLE
[Bug]: Changing Language to English/German does not work

### ISSUE THREAD

**Issue by Nitschi** [GaiZhenbiao/ChuanhuChatGPT#1046]
### 这个bug是否已存在现有issue了？

- [X] 我确认没有已有issue，且已阅读**常见问题**。

### 错误表现

Changing language in the settings does not work

### 复现操作

All models

### 错误日志

```shell
I don't speak chinese
```

### 运行环境

- OS: On HugginFace
- Browser: 
- Gradio version: 
- Python version: 

### 帮助解决

- [ ] 我愿意协助解决！

**Comment by Keldos-Li** [comment]
Hi, you could create a Repository Secret called `LANGUAGE` and set it to `en_US` for you Huggingface Space in the space settings. Visit [our tutorial](https://github.com/GaiZhenbiao/ChuanhuChatGPT/wiki/使用教程#设置space) for more info (Sorry it's in Chinese; I think you can translate that into English using google translate or something :-) )
