### ISSUE TITLE
[功能请求]: 添加用户使用token数记录

### ISSUE THREAD

**Issue by fanzhixin** [GaiZhenbiao/ChuanhuChatGPT#1048]
### 相关问题

在添加用户后，在history文件夹下，只有聊天的历史记录，用户可以在用户界面看到自己使用的token数，但管理员，无法从后台看到用户使用的token数

### 可能的解决办法

最简单快速的方法，将前台每次请求显示的消耗token数，记录到history里每个用户的文件夹下，比如tokens_日期.txt,方便管理员统计

### 帮助开发

- [X] 我愿意协助开发！

**Comment by Keldos-Li** [comment]
- Duplicate with #510
