### ISSUE TITLE
[其他] Matplotlib GUI 调用警告

### ISSUE THREAD

**Issue by slideslide** [GaiZhenbiao/ChuanhuChatGPT#105]
### 错误描述
无法调用matplotlib GUI

### 复现操作
1. 正常完成本地部署
2. 在对话框中要求 ChatGPT “列出常用极限公式”

```console
UserWarning: Starting a Matplotlib GUI outside of the main thread will likely fail.
  fig = plt.figure(figsize=(0.01, 0.01))
```

#### 桌面系统
> **请填写以下列表：**

OS: Windows10

**Comment by Keldos-Li** [comment]
是不是输出到一半给程序终止了？😂
参考： #91

**Comment by slideslide** [comment]
> 是不是输出到一半给程序终止了？😂 参考： #91

不一样，#91我也遇到过。我这次报错后依旧给了正确内容，只是有报错，让我好奇要是有Matplotlib GUI会输出什么给我。

**Comment by Keldos-Li** [comment]
那就是一个Warning啊……那没问题，就是“will likely fail”，以及输出卡一点……就是正常调用了Matplotlib GUI的。
~~看来还是mac不行~~

**Comment by slideslide** [comment]
> 那就是一个Warning啊……那没问题，就是“will likely fail”，以及输出卡一点……就是正常调用了Matplotlib GUI的。 ~看来还是mac不行~

这样，吓得我以为调用失败。
