### ISSUE TITLE
请升级duckduckgo的版本，并重新安装gradio：

### ISSUE THREAD

**Issue by jamsnrihk** [GaiZhenbiao/ChuanhuChatGPT#1059]
请升级duckduckgo的版本，并重新安装gradio：
```
pip install duckduckgo-search --upgrade
pip install gradio==3.43.2
```
经过我的测试，这样可以解决在线搜索不能用的问题。在最新的依赖中，我提升了duckduckgo的版本。

_Originally posted by @GaiZhenbiao in https://github.com/GaiZhenbiao/ChuanhuChatGPT/issues/939#issuecomment-1813997827_

**Comment by jamsnrihk** [comment]
按照您说的做了，不用docker部署，可以在线搜索。用docker部署，还是报错。

**Comment by SWcoffee** [comment]
duckduckgo-search==4.1.1
