### ISSUE TITLE
[功能请求]: Claude API模式支持切换Claude 3 Haiku, Claude 3 Sonnet, Claude 3 Opus模型

### ISSUE THREAD

**Issue by Morpheusr** [GaiZhenbiao/ChuanhuChatGPT#1062]
### 可能的解决办法

我希望支持切换Claude 3 Haiku, Claude 3 Sonnet, Claude 3 Opus模型

### 帮助开发

- [ ] 我愿意协助开发！

### 补充说明

https://www.anthropic.com/news/claude-3-family
Claude API控制台
https://console.anthropic.com/dashboard

**Comment by GaiZhenbiao** [comment]
现在支持啦！
<img width="617" alt="image" src="https://github.com/GaiZhenbiao/ChuanhuChatGPT/assets/51039745/3d7c1cb1-ce85-4084-abbc-55ffd21ffc0b">
