### ISSUE TITLE
[Bug]: 在選取Claude 3 Opus, Claude 3 Sonnet 模型下, 按下開始新的聊天, System prompt會被清空(即使已經打勾"新建對話保留Prompt")

### ISSUE THREAD

**Issue by tomkuo1124** [GaiZhenbiao/ChuanhuChatGPT#1066]
### 这个bug是否已存在现有issue了？

- [X] 我确认没有已有issue，且已阅读**常见问题**。

### 错误表现

https://github.com/GaiZhenbiao/ChuanhuChatGPT/assets/137477635/cfc1f63e-6e24-4947-8a07-6ed8d92ddb9b

請版主參考這問題複製流程影片, 感謝版主

### 复现操作

1. 確保System Prompt勾選"新建對話保留Prompt"
2. 把模型換成Claude 3 Opus, Claude 3 Sonnet
3. 點 + 來開啟新的聊天
4. 發現System Prompt被清空

### 运行环境

- OS: 
- Browser: 
- Gradio version: 
- Python version: 

### 帮助解决

- [ ] 我愿意协助解决！

**Comment by GaiZhenbiao** [comment]
确实存在这个问题！我修复一下～

**Comment by GaiZhenbiao** [comment]
现在应该修复了～

**Comment by tomkuo1124** [comment]
再次感恩版主大大的快速回覆修改! 感恩
