### ISSUE TITLE
[Bug]: 输出内容包含数学公式，无法以LaTeX 格式正常显示

### ISSUE THREAD

**Issue by chaoyi1987** [GaiZhenbiao/ChuanhuChatGPT#1076]
### 这个bug是否已存在现有issue了？

- [X] 我确认没有已有issue，且已阅读**常见问题**。

### 错误表现

当我输入问题：请详细解释一下正态分布的概率密度函数的意义，尽可能举例说明，数学公式使用$$，返回如下内容
![1710322329413](https://github.com/GaiZhenbiao/ChuanhuChatGPT/assets/10733836/1fd650d9-a51f-4db1-b4d2-23b2663050dc)
我希望返回的样式是如下的：
![1710322414848](https://github.com/GaiZhenbiao/ChuanhuChatGPT/assets/10733836/deeb2699-cd1d-4a89-b9bd-302e92d4ae40)

### 复现操作

输入问题：请详细解释一下正态分布的概率密度函数的意义，尽可能举例说明，数学公式使用$$

### 运行环境

- OS: 
- Browser: 
- Gradio version: 
- Python version: 

### 帮助解决

- [ ] 我愿意协助解决！

**Comment by Keldos-Li** [comment]
你好，我这里测试是完全正常的：
![image](https://github.com/GaiZhenbiao/ChuanhuChatGPT/assets/23137268/877658f0-8a76-4373-af23-b7805551d6f6)

请你确认一下配置中的 _[设置 LaTeX 渲染参数](https://github.com/GaiZhenbiao/ChuanhuChatGPT/wiki/%E4%BD%BF%E7%94%A8%E6%95%99%E7%A8%8B#%E8%AE%BE%E7%BD%AE-latex-%E6%B8%B2%E6%9F%93%E5%8F%82%E6%95%B0)_ 选项，如果可能，也可以导出聊天记录的json文件以供我们排查。

**Comment by Keldos-Li** [comment]
如果仍有问题，请继续回复。

**Comment by chaoyi1987** [comment]
![1723393883355](https://github.com/user-attachments/assets/081d235d-1670-4880-8deb-b5cd106ca5dd)
这个是config.json配置文件的截图
[正态分布讲解.json](https://github.com/user-attachments/files/16574549/default.json)
这个是我导出聊天记录的json文件
![1723393953972](https://github.com/user-attachments/assets/e92fffbb-f15b-42f3-bf70-7299e509a957)
latex显示还是有异常，我现在用的版本是当前最新的版本

**Comment by Keldos-Li** [comment]
是的，从20240618那个版本开始又禁用了latex渲染，这个问题由于gradio的bug之前一直没有解决，我应该在release note里提一句的，抱歉！

see also #1102

**Comment by chaoyi1987** [comment]
那好像这个问题确实挺久了，也不知道啥时候能修复这个问题
