### ISSUE TITLE
could not create share link

### ISSUE THREAD

**Issue by Wenyu520521** [GaiZhenbiao/ChuanhuChatGPT#11]
When I set **demo.launch(share=True)**，the command line reminds me **Could not create share link, please check your internet connection.** However,My internet connection is fine,what sh
![the problem](https://user-images.githubusercontent.com/84794739/222871069-117e1402-9de9-42ce-b6ff-d5c87f2071d0.png)
ould I do to solve this problem?

**Comment by habaneraa** [comment]
This feature is provided by Python library `gradio`. See https://gradio.app/sharing-your-app/

**Comment by sky1713972331** [comment]
Try to close the system proxy.

**Comment by Wenyu520521** [comment]
Thanks for your kindness!






------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "GaiZhenbiao/ChuanhuChatGPT"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2023年3月4日(星期六) 上午10:39
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [GaiZhenbiao/ChuanhuChatGPT] could not create share link (Issue #11)





 
This feature is provided by Python library gradio. See https://gradio.app/sharing-your-app/

**Comment by Wenyu520521** [comment]
Thank you so much!




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "GaiZhenbiao/ChuanhuChatGPT"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2023年3月4日(星期六) 上午10:39
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [GaiZhenbiao/ChuanhuChatGPT] could not create share link (Issue #11)





 
Try to close the system proxy.

**Comment by Wenyu520521** [comment]
> Try to close the system proxy.



> Try to close the system proxy.

Thank you for your advice！I have tried shutting down the stystem proxy, but it didn't work,maybe I didn't do it right.And if I close the system proxy, I can't run the program properly that I asked questions but I couldn't get a response.

**Comment by sky1713972331** [comment]
> > 尝试关闭系统代理。
> 
> > 尝试关闭系统代理。
> 
> 谢谢你的建议！我尝试过关闭系统代理，但是没有用，可能是我没有做对。如果我关闭系统代理，我不能正常运行我问的程序表，请问我，请问我。

You can turn off the system proxy when creating share link and turn it on again when you ask questions to the ChatGPT.

**Comment by sky1713972331** [comment]
If you created the share link, you can show me the screenshot of http://127.0.0.1:7860/ displayed content.

> > > > 尝试关闭系统代理。
> > > 
> > > 
> > > 谢谢你的建议！我尝试过关闭系统代理，但是没有用，可能是我没有做对。如果我关闭系统代理，我不能正常运行我问的程序表。
> > 
> > 
> > You can turn off the system proxy when creating share link and turn it on again when you ask questions to the ChatGPT.
> 
> Thank you for your patience to solve the problem for me, but I have tried the solution you provided, but it still doesn't work. It's so weird.
