### ISSUE TITLE
[Bug]: 配置"hide_history_when_not_logged_in": true后，界面报错

### ISSUE THREAD

**Issue by huangsir11** [GaiZhenbiao/ChuanhuChatGPT#1101]
### 这个bug是否已存在现有issue了？

- [X] 我确认没有已有issue，且已阅读**常见问题**。

### 错误表现

docker部署的
配置"hide_history_when_not_logged_in": true后，界面报错
![image](https://github.com/GaiZhenbiao/ChuanhuChatGPT/assets/161782704/9f52a361-8e51-4d92-9b5e-db6e438f2e23)

### 复现操作

在没修改之前一切正常，为了隐藏历史，修改了该参数，报错

### 运行环境

- OS: 
- Browser: 
- Gradio version: 
- Python version: 

### 帮助解决

- [ ] 我愿意协助解决！

**Comment by GaiZhenbiao** [comment]
修复了，感谢反馈～

**Comment by huangsir11** [comment]
> 修复了，感谢反馈～

不客气哦，应该的，docker什么时候会同步更新呐
