### ISSUE TITLE
前台网页回答对话框显示空白，后台日志正常。

### ISSUE THREAD

**Issue by wuminmin** [GaiZhenbiao/ChuanhuChatGPT#1107]
### 这个bug是否已存在现有issue了？

- [X] 我确认没有已有issue，且已阅读**常见问题**。

### 错误表现

后台日志显示收到了回单，前台网页显示空白

前台：
![微信截图_20240421154906](https://github.com/GaiZhenbiao/ChuanhuChatGPT/assets/16083471/1bf69746-cade-4f60-bc34-9d7a0722752e)

后台：
![image](https://github.com/GaiZhenbiao/ChuanhuChatGPT/assets/16083471/e668d391-f49b-4330-9264-c6b049908641)

### 复现操作

1 正常安装
2 选择Aure OpenAI
3 提出问题
4 前台网页答复是空白的

### 错误日志

```shell
2024-04-21 07:44:50,200 [INFO] [base_model.py:131] ### CHUNK ###: text='天' message=AIMessageChunk(content='天')
chuanhuchatgpt-chuanhuchat-1  | 2024-04-21 07:44:50,201 [INFO] [base_model.py:131] ### CHUNK ###: text='的' message=AIMessageChunk(content='的')
chuanhuchatgpt-chuanhuchat-1  | 2024-04-21 07:44:50,203 [INFO] [base_model.py:131] ### CHUNK ###: text='日期' message=AIMessageChunk(content='日期')
chuanhuchatgpt-chuanhuchat-1  | 2024-04-21 07:44:50,206 [INFO] [base_model.py:131] ### CHUNK ###: text='是' message=AIMessageChunk(content='是')
chuanhuchatgpt-chuanhuchat-1  | 2024-04-21 07:44:50,208 [INFO] [base_model.py:131] ### CHUNK ###: text='202' message=AIMessageChunk(content='202')
chuanhuchatgpt-chuanhuchat-1  | 2024-04-21 07:44:50,209 [INFO] [base_model.py:131] ### CHUNK ###: text='4' message=AIMessageChunk(content='4')
chuanhuchatgpt-chuanhuchat-1  | 2024-04-21 07:44:50,211 [INFO] [base_model.py:131] ### CHUNK ###: text='年' message=AIMessageChunk(content='年')
chuanhuchatgpt-chuanhuchat-1  | 2024-04-21 07:44:50,213 [INFO] [base_model.py:131] ### CHUNK ###: text='4' message=AIMessageChunk(content='4')
chuanhuchatgpt-chuanhuchat-1  | 2024-04-21 07:44:50,214 [INFO] [base_model.py:131] ### CHUNK ###: text='月' message=AIMessageChunk(content='月')
chuanhuchatgpt-chuanhuchat-1  | 2024-04-21 07:44:50,215 [INFO] [base_model.py:131] ### CHUNK ###: text='21' message=AIMessageChunk(content='21')
chuanhuchatgpt-chuanhuchat-1  | 2024-04-21 07:44:50,216 [INFO] [base_model.py:131] ### CHUNK ###: text='日' message=AIMessageChunk(content='日')
chuanhuchatgpt-chuanhuchat-1  | 2024-04-21 07:44:50,217 [INFO] [base_model.py:131] ### CHUNK ###: text='[[' message=AIMessageChunk(content='[[')
chuanhuchatgpt-chuanhuchat-1  | 2024-04-21 07:44:50,218 [INFO] [base_model.py:131] ### CHUNK ###: text='10' message=AIMessageChunk(conte
```

### 运行环境

docker  compose 安装

代码版本
git log --oneline
7231bea (HEAD -> main, origin/main, origin/HEAD) Merged GPT4-V into GPT4-Turbo to accommodate OpenAI's new API change.
5881220 fix [Bug]: 配置"hide_history_when_not_logged_in": true后，界面报错 #1101
fccd3de openai besed RAG uses text-embedding-3-large now.
0c4dc56 feat: improved Chuanhu Assistant behaviour when handling file uploads
c759290 (tag: 20240410) chore: specify python3.10 in Dockerfile
094e66e added numexpr dependency
3f4dde0 fixed file-based RAG
bb92452 fix weird style caused by Gradio introducing prose in chatbot
26c6692 removed chuanhu assistant model entry in example
3fda5bb since available tools can be infered from config, Chuanhu Assistant now uses GPT 3.5 by default, and uses GPT4-Turbo (preview) in Pro mode
faf1d94 code clean up, bumped openai version

Dockerfile是仓库自带的

config是自己的参数

compose.yml文件如下：

version: '3.8'
services:
  chuanhuchat:
    build: .
    ports:
      - "7860:7860"
    volumes:
      - .:/app
      - ./config.json:/app/config.json
    # environment:
    #   - OPENAI_API_KEY=sk-xxxxxxxxxxxxxxxxxxxxxxxxx

### 帮助解决

- [X] 我愿意协助解决！

### 补充说明

用docker正常安装，安装过程没有报错。

**Comment by Caleb66666** [comment]
同样遇到了这个问题，敢问后续有解掉吗？

**Comment by wangfan002** [comment]
同问
