### ISSUE TITLE
[Bug]: 手机上访问切换模型无法显示完全，或很难选取列表最下面的模型

### ISSUE THREAD

**Issue by zswll2** [GaiZhenbiao/ChuanhuChatGPT#1110]
### 这个bug是否已存在现有issue了？

- [X] 我确认没有已有issue，且已阅读**常见问题**。

### 错误表现

如视频，无法正确选取模型

https://github.com/GaiZhenbiao/ChuanhuChatGPT/assets/37688676/a4bb4539-6879-4b78-b9ea-4a6ea4cfaf5c

### 复现操作

全部正确部署，使用docker。

### 运行环境

- OS: Ubuntu 22
- Browser: edge
- Gradio version: 
- Python version: 

### 帮助解决

- [X] 我愿意协助解决！

**Comment by Keldos-Li** [comment]
确实有这个问题。
@GaiZhenbiao 要不要把 model selecte dropdown 的 filterable 改成 False？🤔

**Comment by GaiZhenbiao** [comment]
确实，改一下吧
