### ISSUE TITLE
[功能请求]: GPT4o 已经发布，希望添加模型GPT4o

### ISSUE THREAD

**Issue by fanzhixin** [GaiZhenbiao/ChuanhuChatGPT#1127]
### 相关问题

 GPT4o 选项

### 可能的解决办法

添加模型GPT4o

### 帮助开发

- [X] 我愿意协助开发！

**Comment by vc12345679** [comment]
PR #1128

**Comment by GaiZhenbiao** [comment]
加入了 https://github.com/GaiZhenbiao/ChuanhuChatGPT/commit/ac0a1ea87d5a5293d6622631122562b0fce9202c
