### ISSUE TITLE
[功能请求] Hugging Face上在线体验改为Docker项目

### ISSUE THREAD

**Issue by lrcstars** [GaiZhenbiao/ChuanhuChatGPT#114]
### 该功能请求是否与某个问题相关？
> Docker项目可以复制后配置secrets使用，就不用每次输入key了

**Comment by lrcstars** [comment]
https://huggingface.co/spaces/JohnSmith9982/ChuanhuChatGPT
我是指的这个

好像这个项目直接提交到huggingface创建的docker项目，就可以直接跑了吧，我明天试试

**Comment by lrcstars** [comment]
sdk改成docker后，运行报错：ModuleNotFoundError: No module named 'gradio'
build时看到有日志：
--> RUN pip install --user -r requirements.txt
CACHED
是不是本项目不支持在huggingface以docker方式运行

**Comment by GaiZhenbiao** [comment]
奇怪。不过，我没试过在hugging face上用Docker运行
