### ISSUE TITLE
[功能请求]: 支持 GPT-4o Mini

### ISSUE THREAD

**Issue by Wybxc** [GaiZhenbiao/ChuanhuChatGPT#1144]
### 相关问题

OpenAI 关于推出 GPT4o Mini API 的通知：https://community.openai.com/t/introducing-gpt-4o-mini-in-the-api/871594

### 可能的解决办法

添加模型 GPT-4o Mini

### 帮助开发

- [X] 我愿意协助开发！

**Comment by GaiZhenbiao** [comment]
Added now https://github.com/GaiZhenbiao/ChuanhuChatGPT/commit/a7c3971860ae3185089d49d40689a7a2e0d9584d
