### ISSUE TITLE
[Bug]: o1-mini模型对话报错

### ISSUE THREAD

**Issue by crosswk** [GaiZhenbiao/ChuanhuChatGPT#1160]
### 这个bug是否已存在现有issue了？

- [X] 我确认没有已有issue，且已阅读**常见问题**。

### 错误表现

o1-mini不支持system字段了。

### 复现操作

正常部署最新版本

### 错误日志

```shell
前端报错：
☹️发生了错误：Unsupported value: 'messages[0].role' does not support 'system' with this model. (request id: 2024091403134518573335634751935)


后端报错：
Exception: {"error":{"message":"Unsupported value: 'messages[0].role' does not support 'system' with this model. (request id: 2024091403134518573335634751935)","type":"invalid_request_error","param":"messages[0].role","code":"unsupported_value"}}
```

### 运行环境

- OS: 
- Browser: 
- Gradio version: 
- Python version: 
 

### 帮助解决

- [ ] 我愿意协助解决！

**Comment by GaiZhenbiao** [comment]
应该修复了

**Comment by crosswk** [comment]
o1还不支持流式传输了，能否选择这个模型是，自动关闭流式传输。Unsupported value: 'stream' does not support true with this model. Only the default (false) value is supported. (request id: 202409140926411873031618470080) @GaiZhenbiao

**Comment by GaiZhenbiao** [comment]
在 https://github.com/GaiZhenbiao/ChuanhuChatGPT/commit/226a9b21daa7f43569b40e057ed766f703c47c6a 中，o1 模型的流式传输功能被默认关闭
