### ISSUE TITLE
[Bug]: GPT o1-mini 模型回复内容，前端显示格式问题

### ISSUE THREAD

**Issue by crosswk** [GaiZhenbiao/ChuanhuChatGPT#1163]
### 这个bug是否已存在现有issue了？

- [X] 我确认没有已有issue，且已阅读**常见问题**。

### 错误表现

目前使用o1-mini模型回答问题后，前端首先会显示正常的markdown格式，然后会自动刷新一次，回复的内容都会成为一个段落，这一整个段落很难阅读。
![2024-09-18 22 09 09](https://github.com/user-attachments/assets/10118852-83ef-4e66-9148-30bc02643325)
![2024-09-18 22 09 20](https://github.com/user-attachments/assets/e3a361a7-a39b-4536-9b76-2f175f7bb6c7)

### 复现操作

latest

### 错误日志

```shell
只有截图文件，没有错误日志。
```

### 运行环境

latest

### 帮助解决

- [X] 我愿意协助解决！

### 补充说明

latest

**Comment by crosswk** [comment]
上面截图的API，是o1-mini逆向的api测试结果，使用正常的API效果也是一样的。首先会刷新一个正常的格式，然后自动刷新一下，回复的内容都会挤到一个段落中。

**Comment by GaiZhenbiao** [comment]
还真是，我看看怎么回事
