### ISSUE TITLE
[Docker] 部署后只要有一个问题卡住后面就无法问

### ISSUE THREAD

**Issue by adu19922** [GaiZhenbiao/ChuanhuChatGPT#117]
![Screenshot_20230310_225958_com UCMobile](https://user-images.githubusercontent.com/97271895/224449138-16470424-07c4-4f5c-8a28-e7a4a2330831.jpg)
只要卡住了，后面问什么都没有反应，必须得重启docker才行
这个怎么解决

**Comment by GaiZhenbiao** [comment]
这个通常是网络连接的问题

**Comment by tuteng0915** [comment]
更像是进入了"总结对话内容"的死循环了 :(

**Comment by GaiZhenbiao** [comment]
我检查一波代码👀

**Comment by GaiZhenbiao** [comment]
我重构了核心代码，现在这个问题应该修复了

**Comment by GaiZhenbiao** [comment]
现在加入了timeout，这个问题应该解决了
