### ISSUE TITLE
[Bug]: 1. 大模型回答时无法滚动  2. 回答时切换聊天窗口回答文本位置会发生混乱

### ISSUE THREAD

**Issue by TownsendWu** [GaiZhenbiao/ChuanhuChatGPT#1174]
### 这个bug是否已存在现有issue了？

- [X] 我确认没有已有issue，且已阅读**常见问题**。

### 错误表现

**模型：** azure openai
### bug1
**表现：** 大模型回答时，聊天界面无法滚动

### bug2
**表现：** 大模型回答时，切换聊天窗口会导致聊天界面混乱
**截图：**
![image](https://github.com/user-attachments/assets/8706afef-1707-45da-8662-d29e757fc947)

### 复现操作

1. 正常提问

### 错误日志

```shell
无
```

### 运行环境

- OS:  ubuntu 22
- Browser:  Chrome
- Gradio version:  4.29.0
- Python version:  3.9

### 帮助解决

- [X] 我愿意协助解决！

**Comment by Keldos-Li** [comment]
我也没太搞明白为啥第一个问题为什么会出现。

不过第二个问题的一个解决办法是，在生成时禁用切换聊天窗口。我觉得这个解决办法是可以接受的，可以避免很多潜在的bug。

**Comment by Keldos-Li** [comment]
第一个问题的原因是回答时上方会有一个透明的gradio层用来提示状态，现已后置。
