### ISSUE TITLE
[功能请求] 中文的Prompt模板有吗？/狗头

### ISSUE THREAD

**Issue by Mvrjustid** [GaiZhenbiao/ChuanhuChatGPT#118]
### 该功能请求是否与某个问题相关？
> 描述你遇到的问题~

### 可能的解决办法
> 辛苦弄一下~事成20块马上打来/狗头

### 其他
> 谢谢

**Comment by Keldos-Li** [comment]
不是，我才发现，不是已经有了吗……👿
<img width="778" alt="image" src="https://user-images.githubusercontent.com/23137268/224463248-c9e261c4-b6b8-4c59-a2a2-d66b38a4db4a.png">

Resolved with 165a63a692ee4928989a7839d6a6657be533e792 ([Chuanhu](https://github.com/GaiZhenbiao))
