### ISSUE TITLE
[功能请求] 删除最近一条对话

### ISSUE THREAD

**Issue by WindwithNothing** [GaiZhenbiao/ChuanhuChatGPT#121]
### 该功能请求是否与某个问题相关？
> 官网是能够编辑任意一条对话，提交之后的对话删除并从编辑的位置继续对话。

### 可能的解决办法
> 添加删除最近一条对话的功能，基本能达到与官网相同的效果。

**Comment by GaiZhenbiao** [comment]
<img width="1338" alt="image" src="https://user-images.githubusercontent.com/51039745/224472069-bdd87b5d-a508-4e4b-9560-de5618154bd9.png">

不是已经有了吗

**Comment by WindwithNothing** [comment]
刚试了下确实是删除了最后一条，只是对话框没变化有点迷惑，希望能标记一下删除的对话，比如颜色变灰啥的。

**Comment by GaiZhenbiao** [comment]
我测试了一下，这个功能并没有问题，删除内部历史的同时，也会更新对话框。你用最新版代码再试试？

**Comment by WindwithNothing** [comment]
更新之后都正常运行了，感谢
