### ISSUE TITLE
无论输入什么，都返回 发生了错误，请检查网络连接或者稍后再试

### ISSUE THREAD

**Issue by zijiyue** [GaiZhenbiao/ChuanhuChatGPT#123]
昨天还能正常使用，今天无论输入什么，都返回 发生了错误，请检查网络连接或者稍后再试。
chat_counter - 0
payload: {'model': 'gpt-3.5-turbo', 'messages': [{'role': 'system', 'content': 'You are a helpful assistant.'}, {'role': 'user', 'content': '1'}], 'temperature': 1, 'top_p': 1, 'n': 1, 'stream': True, 'presence_penalty': 0, 'frequency_penalty': 0}
正在尝试使用缩短的context重新生成……
chat_counter - 1
payload: {'model': 'gpt-3.5-turbo', 'messages': [{'role': 'system', 'content': 'You are a helpful assistant.'}, {'role': 'user', 'content': '1'}], 'temperature': 1, 'top_p': 1, 'n': 1, 'stream': False, 'presence_penalty': 0, 'frequency_penalty': 0}

已经更新到最新版本，重装了urllib3
代理可用，能够正常访问官方chat,

clash中加入了如下代码
rules:
- IP-CIDR,127.0.0.1,DIRECT
- DOMAIN-SUFFIX,openai.com,你的代理规则

仍然不能解决问题，请问是哪里出错了？

**Comment by Keldos-Li** [comment]
<img width="476" alt="image" src="https://user-images.githubusercontent.com/23137268/224482992-0d05659f-51bf-4192-a774-e92d09421d7d.png">
？有没有一种可能……

**Comment by zijiyue** [comment]
> > <img alt="image" width="476" src="https://user-images.githubusercontent.com/23137268/224482992-0d05659f-51bf-4192-a774-e92d09421d7d.png">
> 
> ？有没有一种可能……

我文件中里没加中文，是删除的，还是不行

**Comment by GaiZhenbiao** [comment]
也不应该删除啊😂应该替换成你的代理规则

**Comment by zijiyue** [comment]
> 也不应该删除啊😂应该替换成你的代理规则

rules:
- IP-CIDR,127.0.0.1,DIRECT
- DOMAIN-SUFFIX,openai.com,Global
- 这样还是没效果。。。 我这个肯定是代理问题吗？
-

**Comment by zijiyue** [comment]
![`~S36M 4M(T%}Z X95~FBCK](https://user-images.githubusercontent.com/127596777/224490256-ef5ff447-f82c-4980-a04b-809f813504b5.png)
在Hugging Face里也是同样的问题，/(ㄒoㄒ)/~~
小白真的很难受

**Comment by GaiZhenbiao** [comment]
新版代码大幅度改进了代码质量，去试试吧～

**Comment by zijiyue** [comment]
问题解决了，目测是代理太垃圾的问题，解决方法是：换代理。
换了一个10元每月20G的死贵大厂代理，然后一路畅通。
目测是现在OpenAI只有美国的IP能上，还不能是野鸡IP ，用的人太多也会被拒
我上个号已经被封了（OpenAI目前查的太严了）

**Comment by kia-423** [comment]
![image](https://user-images.githubusercontent.com/127377770/224656884-69ea7768-26cc-4d57-9b1a-9b5a9e49d3fd.png)
![image](https://user-images.githubusercontent.com/127377770/224656896-521bb691-69ce-4e0e-b465-c8294f075fda.png)
兄弟，你知道这怎么弄吗，我一直出错
