### ISSUE TITLE
[功能请求] 建议保留API_URL参数

### ISSUE THREAD

**Issue by zgl018** [GaiZhenbiao/ChuanhuChatGPT#124]
建议保留API_URL参数，需要用到反代后的地址

**Comment by GaiZhenbiao** [comment]
什么意思？

**Comment by zgl018** [comment]
> 什么意思？

某些在国内的需要用cloudflare workers反代openai api 。
这样对比用梯子来说可控且风险小，旧版本http post直接可以改请求url 。
新版本用了gradio后开发上是方便了，但灵活性变差了，没找到哪里可以改url的，除非改本机hosts再搭个反代中转，这就更麻烦了

**Comment by zgl018** [comment]
> 什么意思？

因为openai封禁了很多机房ip
但cloudflare workers这种方式是最稳定的

**Comment by GaiZhenbiao** [comment]
代码里把这个URL换一下，应该就行了。
