### ISSUE TITLE
[本地部署]跑了直接报错

### ISSUE THREAD

**Issue by chechuangfeng** [GaiZhenbiao/ChuanhuChatGPT#126]
<img width="1633" alt="image" src="https://user-images.githubusercontent.com/3196849/224503343-e0d1b3e6-8d5d-401b-948b-ae05ddf654d3.png">

想知道怎么开启debug模式，获取更多信息。

**Comment by Keldos-Li** [comment]
- 报错等其他输出信息可以在终端或你的 IDE 的控制台中查看。你怎么运行的这个脚本就在哪儿看。
- 关于你的错误，请认真阅读 README 中疑难杂症解决的[这一部分](https://github.com/GaiZhenbiao/ChuanhuChatGPT#%E7%BD%91%E9%A1%B5%E6%8F%90%E7%A4%BA%E9%94%99%E8%AF%AF-something-went-wrong)，以及#44。
- 下次请尽量不要使用这种**毫无信息量**的标题。**试着在标题中给出报错内容，而不是就说个报错**。。。

**Comment by GaiZhenbiao** [comment]
由于长期未回复，暂时关闭此issue。
