### ISSUE TITLE
[本地部署] 连接错误

### ISSUE THREAD

**Issue by han04** [GaiZhenbiao/ChuanhuChatGPT#127]
### 错误描述
网页打开后粘贴上api运行显示错误

### 复现操作
> 你之前干了什么，然后出现了错误呢？
**下次记得把例子删干净**

clone、安装依赖都成功，添加了公网连接用户名和密码，网页打开后粘贴上api 运行显示错误

### 错误截图
![image](https://user-images.githubusercontent.com/34024206/224502999-b29041b8-329f-4f25-bee4-7e082810011f.png)

#### 桌面系统
> **请填写以下列表：**

 - VPS OS: [Debian11]
 - 本机Browser: [Chrome]

#### 运行依赖
> **请填写以下列表：**
> 你可以在终端中依次输入以下指令以查看软件版本：
> ```shell
> pip show gradio
> python --version
> ```
- Gradio version:3.20.1
- Python (或Python3) version: Python 3.9.2

**Comment by GaiZhenbiao** [comment]
请提供终端打印的报错信息

**Comment by han04** [comment]
终端没有报错

```
root@racknerd-67b462:/opt/ChuanhuChatGPT# python3 ChuanhuChatbot.py
Loading template...
Loading template...
Loading template...
川虎的温馨提示：访问 http://localhost:7860 查看界面
Running on local URL:  http://0.0.0.0:7860

To create a public link, set `share=True` in `launch()`.
```

**Comment by JuWuhe** [comment]
同问此问题，不过我是部署在云服务器上的。使用Clash做代理或者URL反代都会出现此问题，终端没有任何报错

**Comment by JuWuhe** [comment]
补充一下截图，curl是能通的，其中打码的部分是反代链接和APIKEY
![image](https://user-images.githubusercontent.com/55908948/224544553-c1c453cb-7e69-42e5-bca8-ffa234973bc6.png)

**Comment by JuWuhe** [comment]
解决了，取消掉用户名和密码的设置，直接demo.launch就好了，不知道为什么

**Comment by hnuzhoulin** [comment]
index.42794ed1.js:4 WebSocket connection to 'ws://192.168.XXX.X1:7860/queue/join' failed: 

我也是这个错，估计是ws没有匹配用户名密码功能

**Comment by magehsiii** [comment]
> index.42794ed1.js:4 WebSocket connection to 'ws://192.168.XXX.X1:7860/queue/join' failed:
> 
> 我也是这个错，估计是ws没有匹配用户名密码功能
可以参考这个
#89

**Comment by han04** [comment]
@magehsiii  谢谢！
