### ISSUE TITLE
[功能请求] 是否可以作为ChatGPT的中转服务器来使用？

### ISSUE THREAD

**Issue by peiyun1982** [GaiZhenbiao/ChuanhuChatGPT#128]
### 需求背景：
首先我发现了一个非常好用的利用ChatGPT进行翻译的浏览器插件。在插件里需要填写API和ChatGPT网址。所以用这个插件的时候必须要翻墙。
![屏幕截图 2023-03-12 113631](https://user-images.githubusercontent.com/16250376/224522984-c8360e39-553f-4da4-8af5-aaf78c288246.png)

### 可能的解决办法
现在ChuanhuChatGPT既然可以在海外服务器上部署GPT服务，是否可以作为任何需要用到GPT服务的中转服务器来使用呢？
比如我这个插件就可以这样填写：
![111](https://user-images.githubusercontent.com/16250376/224522989-9d245dd8-1ec4-4359-90b3-7200782ac1fa.png)

如果能实现，会非常方便！
只是个建议，请参考。

**Comment by GaiZhenbiao** [comment]
你要找的是不是：V2ray

**Comment by peiyun1982** [comment]
> 你要找的是不是：V2ray

我搭建了自己的V2ray，只是要用上面那个翻译插件的话需要先开翻墙软件，比较麻烦。
我以为ChuanhuGPT实现这个功能会很方便，故有此一问。

**Comment by GaiZhenbiao** [comment]
抱歉，没有计划做类似的功能。
