### ISSUE TITLE
建议加个黑色主题切换

### ISSUE THREAD

**Issue by catcherxuefeng** [GaiZhenbiao/ChuanhuChatGPT#13]
rt

**Comment by GaiZhenbiao** [comment]
本来就支持呀，跟随系统亮暗色mo s 。
<img width="1420" alt="image" src="https://user-images.githubusercontent.com/51039745/222873393-f582730b-618b-4d2b-a205-c74424a5f18f.png">

**Comment by catcherxuefeng** [comment]
> 本来就支持呀，跟随系统亮暗色模式。 <img alt="image" width="1420" src="https://user-images.githubusercontent.com/51039745/222873393-f582730b-618b-4d2b-a205-c74424a5f18f.png">

明白了
