### ISSUE TITLE
[其他] “网页提示错误 Something went wrong”的另一个解决办法？

### ISSUE THREAD

**Issue by AaronDon2018** [GaiZhenbiao/ChuanhuChatGPT#131]
“疑难杂症解决”下“网页提示错误 Something went wrong”给的的方法不太清楚该怎么弄，大佬可以详细地说一下怎么“设置代理软件，将127.0.0.1加入直连”吗？
## 临时的解决方法
先说我现在的解决办法是：在关闭Clash的情况下运行app打开网页，然后再打开clash科学上网进行对话...试了几次是可行的

## 遇到的错误
在网上没查到怎么弄...我试着把
- IP-CIDR,127.0.0.1,DIRECT
加入Clash配置文件中，截图：
![image](https://user-images.githubusercontent.com/46737150/224534595-89800098-cd9b-4f07-920e-52b24a9c13bc.png)
（应该是这样弄吧？）
但是出了报错了：
![image](https://user-images.githubusercontent.com/46737150/224534622-1fdad8ec-8a64-4245-859c-9e3319502062.png)

**Comment by mhql** [comment]
应该是你有pip或urlib3新版本，请求https会出错，这是一个比较著名的bug，解决办法是设置proxy环境变量改成http访问，具体你可以百度或知乎。

**Comment by MZhao-ouo** [comment]
你写错了，ip后面的/n是子网掩码的意思，不是端口号。你可以试试改成
```
- IP-CIDR,127.0.0.1/8,DIRECT
```

**Comment by qitume** [comment]
> “疑难杂症解决”下“网页提示错误 Something went wrong”给的的方法不太清楚该怎么弄，大佬可以详细地说一下怎么“设置代理软件，将127.0.0.1加入直连”吗？
> 
> ## 临时的解决方法
> 先说我现在的解决办法是：在关闭Clash的情况下运行app打开网页，然后再打开clash科学上网进行对话...试了几次是可行的
> 
> ## 遇到的错误
> 在网上没查到怎么弄...我试着把
> 
> * IP-CIDR,127.0.0.1,DIRECT
>   加入Clash配置文件中，截图：
>   ![image](https://user-images.githubusercontent.com/46737150/224534595-89800098-cd9b-4f07-920e-52b24a9c13bc.png)
>   （应该是这样弄吧？）
>   但是出了报错了：
>   ![image](https://user-images.githubusercontent.com/46737150/224534622-1fdad8ec-8a64-4245-859c-9e3319502062.png)

谢谢楼主，直接按楼主的方式弄了

**Comment by qitume** [comment]
> 你写错了，ip后面的/n是子网掩码的意思，不是端口号。你可以试试改成
> 
> ```
> - IP-CIDR,127.0.0.1/8,DIRECT
> ```

可以，这样解决了问题

**Comment by wzf842321317** [comment]
![image](https://user-images.githubusercontent.com/48514232/226513006-0ec6da19-e393-402a-aaf5-04b29174cc48.png)
我并不会搞这个，谁能把这个操作清晰化

**Comment by zhangjing-GitHub-Code** [comment]
您好，我在Android 15(ColorOS)上也经常遇到此类问题。
还有很恶心的问题是，在Issue/commit页面，观察到刷出来了一瞬间正常内容，然后立刻被替换为Can't load, try again.并且无限循环。
请问有什么高招吗
