### ISSUE TITLE
无法第二次输入 

### ISSUE THREAD

**Issue by libiaoliang** [GaiZhenbiao/ChuanhuChatGPT#133]
感谢提交 issue! 请尽可能完整填写以下信息，帮助我们更好地定位问题~ 
如果你不知道怎么填写，请先点击编辑框上方的“Preview”在预览中查看我们的说明，然后点击“Write”在空白行处填写信息~
![Uploading image.png…]()

### 错误描述
无法第二次输入，已经加入两个规则，先打开窗口后再打开的clash

### 错误截图
![Uploading image.png…]()

### 终端（控制台）中的错误报告
```console
F:\python\anaconda\envs\test\python.exe C:\Users\Administrator\Desktop\中转\ChuanhuChatGPT-main\ChuanhuChatbot.py 
Loading template...
Loading template...
Loading template...
川虎的温馨提示：访问 http://localhost:7860 查看界面
Running on local URL:  http://127.0.0.1:7860

To create a public link, set `share=True` in `launch()`.
Building prefix dict from the default dictionary ...
Loading model from cache C:\Users\ADMINI~1\AppData\Local\Temp\jieba.cache
Loading model cost 0.912 seconds.
Prefix dict has been built successfully.
```

### 运行环境
> **请填写以下列表：**

 - OS: [Windows10]
 - Browser: [e.g]
 - Gradio version
 - Python (或Python3) version:

### 其他
> 补充说明

**Comment by GaiZhenbiao** [comment]
请重新上传截图。截图没上传成功你就发出来了😂

**Comment by libiaoliang** [comment]
不知道为什么上传不上去图片，总之：百度搜索最开始的错误红字后，引入jieba模块加入下列代码
jieba.setLogLevel(jieba.logging.INFO)
pychram中的报错消失，但问题依然存在，procharm和ui界面都没有任何红字或提示，出错后procharm‘To create a public link, set `share=True` in `launch()`.之后也没有新的语句出现’，能够点击输入框下方按钮。但依然无法输入。我自己测试的一个简短的调用api的代码也能够正常对话。
![screenshot-127 0 0 1_7860-2023 03 13-13_18_36](https://user-images.githubusercontent.com/95110455/224614567-eb8492df-49bd-4899-a037-9e198821f6bd.png)

**Comment by EchoShoot** [comment]
很可能是账号被封了，我就是第一个可以回答，第二句开始没响应，然后登录我的账号显示已经被封了

**Comment by GaiZhenbiao** [comment]
我表示同情❤️‍🩹
*川虎ChatGPT应该不是导致封号的原因，很可能是因为你的帐号来路不正，比如是买来的。

**Comment by libiaoliang** [comment]
呃。。。应该不会吧，我现在的chatgpt网页版和api还是能正常对话的

**Comment by libiaoliang** [comment]
错误似乎解决，前天把edge的自动翻译关掉后能够正常使用，今天出现了新问题，已提交

**Comment by libiaoliang** [comment]
错误似乎解决，前天把edge的自动翻译关掉后能够正常使用，今天出现了行问题，已提交
