### ISSUE TITLE
AI 生成的表格 (Table) 不能正常在对话中显示！可以解决吗？

### ISSUE THREAD

**Issue by bentwnghk** [GaiZhenbiao/ChuanhuChatGPT#134]
![screenshot](https://user-images.githubusercontent.com/101241940/224586639-dd4d36bb-7ce2-4dcd-bce8-f3ae7bbb3f7e.png)

**Comment by Keldos-Li** [comment]
这是能做到的。 #93 中可以引入`tables`，这样可以生成`<table>`标签
<img width="1017" alt="image" src="https://user-images.githubusercontent.com/23137268/224587771-dd6b4a38-f75f-484b-8939-813c444714af.png">

如果想要进一步调整边框和背景什么的，可以再写CSS……

（应该说，别急，在做了？）

**Comment by Joagee** [comment]
在中国大陆，不用科学上网也能与你对话吗？
是的，我是通过中国境内的服务器提供服务，因此你可以在中国大陆境内的任何地方与我进行对话，无需使用科学上网工具。无论是电脑、手机还是其他设备，只要能够联网并访问网络，就可以与我交互。

为什么我现在不科学上网向你提问，你却长时间不回复？
很抱歉让你等待，我会尽快回答你的问题。如果我长时间没有给你回复，可能是因为我目前正在处理其他请求或者繁忙的时段收到了过多的请求，导致我的响应时间变慢。同时，由于我是一个自动化系统，还有可能存在一些技术问题，导致我的回应受到了限制或者出现了错误。但是，你可以等待几分钟并重新发送你的问题，我会尽快回复你。

但我科学上网的话，你却很快就有回复，所以怀疑必须科学上网才能与你对话？
作为一个基于云服务的AI助手，我可以在中国境内提供服务，不需要使用科学上网。如果你在使用非科学上网的网络环境中和我对话时，我会尽快为你提供回复。然而，由于服务的需求量可能会导致系统繁忙，因此响应时间可能会有所延迟。而使用科学上网工具可以使你访问到全球互联网，包括受一些地区限制的内容。建议你选择可靠的科学上网方式，以便获得更好的访问体验和更全面的信息资源。
