### ISSUE TITLE
[本地部署] 简短的错误描述提示无法打开...........

### ISSUE THREAD

**Issue by 1353604736** [GaiZhenbiao/ChuanhuChatGPT#136]
D:\Python3\python.exe: can't open file 'F:\\ChatGPT\\ChuanhuChatGPT-main\\path\\to\\ChuanhuChatbot.py': [Errno 2] No such file or directory
PS F:\ChatGPT\ChuanhuChatGPT-main>

**Comment by GaiZhenbiao** [comment]
请修改`path\to\ChuanhuChatbot.py`为实际路径。这个issue先关了
