### ISSUE TITLE
一直等待/SSL Error 使用clash进行配置提示error：payload error

### ISSUE THREAD

**Issue by WUXM5** [GaiZhenbiao/ChuanhuChatGPT#138]
您好，按照文档进行操作配置，提示报错，如下：
![1678696089805](https://user-images.githubusercontent.com/77671587/224646949-af9449d6-876c-4f14-91d3-54f64e129b46.jpg)
![image](https://user-images.githubusercontent.com/77671587/224647028-7906a861-6f0d-4c1f-ba25-69ca30444511.png)
还请协助看下该如何配置，谢谢

**Comment by GaiZhenbiao** [comment]
会不会是有两个“rules”模块？另外你不应该在这里问Clash问题

**Comment by WUXM5** [comment]
已经排查只有1个rules模块，抱歉，可以关闭此问题了，谢谢

**Comment by WUXM5** [comment]
> 会不会是有两个“rules”模块？另外你不应该在这里问Clash问题

已经排查只有1个rules模块，抱歉，可以关闭此问题了，谢谢

**Comment by GaiZhenbiao** [comment]
汗😓……我发现我在Readme里给出的的Clash规则是错误的……现在已经更正了，你去试试吧🤧
