### ISSUE TITLE
[历史文件Json解析错误] 读取历史文件后，发送信息报错

### ISSUE THREAD

**Issue by Neu-bee** [GaiZhenbiao/ChuanhuChatGPT#139]
### 错误描述
1.  读取历史文件后，在predict或者predictall部分报错
报错内容看不出来哪里有问题，我自己测了一下数据，进行了调试

2.  debug之后，发现request发送的json格式不对
本来应该是：
 history = [{"role": "user", "content": "hello?"}]
这种格式，重复嵌套组装成为了：
history = [{"role": "user", "content": {"role": "user", "content": "hello? are you there"}},
           {"role": 'assistant', "content": {"role": 'assistant', "content": "Hello! How can I assist you today?"}},
           {"role": "user", "content": "echo 456"}]
这种格式，content后面不是字符串了，麻烦修改一下，辛苦啦

### 复现操作
> 你之前干了什么，然后出现了错误呢？
1. 服务器部署
2. 加载历史文件
3. 点击发送，提示error

### 错误截图
openai接口返回： {'error': {'message': "{'role': 'user', 'content': 'hello? are you there'} is not of type 'string' - 'messages.0.content'", 'type': 'invalid_request_error', 'param': None, 'code': None}}

### 运行环境
> **请填写以下列表：**
 - OS: openeuler
 - Browser: *
 - Gradio version: *
 - Python (或Python3) version:  python3.9

### 其他
我中间有自己修改过你们的代码逻辑，如果是不是源代码的问题，还请见谅，打扰作者了

**Comment by Neu-bee** [comment]
还有，我能一起参与写吗，我做java+vue的，python也会点，改改这种小bug没问题的

**Comment by GaiZhenbiao** [comment]
已经修复啦，你测试试试？
好呀，欢迎一起写👏提交PR就行了

**Comment by Neu-bee** [comment]
> 已经修复啦，你测试试试？ 好呀，欢迎一起写👏提交PR就行了

OK，新代码pull下来没问题了

**Comment by Keldos-Li** [comment]
Resolved by d759751fc65cd786fd641b4fe8c69bff05516e73 ([Chuanhu](https://github.com/GaiZhenbiao)).
