### ISSUE TITLE
额度用完了就没法用了啊

### ISSUE THREAD

**Issue by TT-IPIP** [GaiZhenbiao/ChuanhuChatGPT#140]
还是搭建https://github.com/Chanzhaoyu/chatgpt-bot
没额度可以用accessToken的

**Comment by jarrywen** [comment]
用这么快，我有3个账号，1个账号都还没用完
accessToken是什么，是要到哪里申请吗？

**Comment by jarrywen** [comment]
> 

明白了，是另外一个项目，有空去搭建看看
