### ISSUE TITLE
[本地部署] 出现截图错误Something went wrong

### ISSUE THREAD

**Issue by 1353604736** [GaiZhenbiao/ChuanhuChatGPT#143]
又来叨扰
![QQ截图20230313223654](https://user-images.githubusercontent.com/12869582/224735122-4270ee46-891c-425b-b3af-b08ad6bb11e4.png)

**Comment by 1353604736** [comment]
还是代理问题，已解决，麻烦了，127.0.0.1设置走代理

**Comment by Keldos-Li** [comment]
见 README [这部分](https://github.com/GaiZhenbiao/ChuanhuChatGPT#网页提示错误-something-went-wrong)

以及：
* #131
*  #48 

-----

写到一半你自己解决了吼

@1353604736 大哥你如果之后还有问题就接着在这儿问吧，别开新的issue了……反正大概你也是别的信息不看，issue开了又关掉……
