### ISSUE TITLE
[功能请求] 把聊天记录导出为markdown格式的文件

### ISSUE THREAD

**Issue by jarrywen** [GaiZhenbiao/ChuanhuChatGPT#147]
### 该功能请求是否与某个问题相关？
> 描述你遇到的问题~
语雀上记录学习笔记，复制非常不方便，如果能导出markdown格式的文件，再倒入到语雀就很方便了。

### 可能的解决办法
> 增加一个按钮，除了保存为json，也可以保存为markdown格式
> 或者每一个chatGPT回复内容右上角增加一个copy按钮，把markdown的内容保存到剪贴板。

### 其他
> 如果再复杂点，可以提供一个markdown编辑器，再编辑器里面可以向ai提问，回复后直接返回到鼠标位置，例如Notion AI功能

**Comment by jarrywen** [comment]
或者有没有工具，可以把保存到json转为markdown文件

**Comment by tuteng0915** [comment]
对于markdown格式具体有什么需求吗？以什么形式来区别ChatGPT和用户的内容？如果可以的话，可以手动编辑一条作为样例吗？

**Comment by jarrywen** [comment]
就按川虎ChatGPT上的聊天记录展示的格式就可以

**Comment by tuteng0915** [comment]
可是标准的markdown语法并不支持像gradio.chatbot那样以文字气泡的形式记录，亦无对于分栏、居右等格式的语法。因此，还是建议您给出一条您所期望的markdown形式。

**Comment by GaiZhenbiao** [comment]
这确实可以做。@tuteng0915 我想他要的不是带着气泡一模一样的，而是用markdown标题“assistant”“user”这样分割就行了。

**Comment by GaiZhenbiao** [comment]
现在加入了这个功能

**Comment by xingfanxia** [comment]
@GaiZhenbiao 目前的md输出好像不是 standard md flavor

![Monosnap Preview 对话历史记录 md — ChuanhuChatGPT 2023-03-29 04-56-21](https://user-images.githubusercontent.com/8936233/228528179-f51c8867-38a3-4a1f-b919-41dc2c5bf98f.jpg)

sublist没法渲染
