### ISSUE TITLE
[本地部署] requests和toekn 数量异常

### ISSUE THREAD

**Issue by AllenYkl** [GaiZhenbiao/ChuanhuChatGPT#148]
想问一下为什么request和token的数量会一下子多这么多。根据页面统计只用了53个token，但是去openAI的官网上查询用量就发现多出来很多。以下是截图

![1678801380499](https://user-images.githubusercontent.com/105541324/225020098-87407d48-2515-467e-8bdb-06b9ffb99bb4.png)

**Comment by GaiZhenbiao** [comment]
这显示的是总用量吧，不止53token这个问题

**Comment by AllenYkl** [comment]
不是总用量，您看时间。
这个就是单次request出现的用量，所以很疑惑

> 这显示的是总用量吧，不止53token这个问题

**Comment by Keldos-Li** [comment]
<img width="670" alt="image" src="https://user-images.githubusercontent.com/23137268/225233056-2521e959-44f7-4ef9-b46d-c82b27a218d2.png">
我这里试了试没出现问题……您再补充一下相关信息？

**Comment by AllenYkl** [comment]
> <img alt="image" width="670" src="https://user-images.githubusercontent.com/23137268/225233056-2521e959-44f7-4ef9-b46d-c82b27a218d2.png">
> 
> 我这里试了试没出现问题……您再补充一下相关信息？

嗯好的谢谢，我再做一些测试

**Comment by GaiZhenbiao** [comment]
现在有准确的token计数了

**Comment by AllenYkl** [comment]
> 现在有准确的token计数了

嗯，非常感谢
