### ISSUE TITLE
It seems dialog saving is not working

### ISSUE THREAD

**Issue by hyyz17200** [GaiZhenbiao/ChuanhuChatGPT#15]
Thanks for this project. 

Everything seems to be functioning as expected, however, I am experiencing an issue with the save dialog. When I click on it, nothing happens. Interestingly, the loading dialog button works perfectly fine. 

Just to keep you informed, I have been running the project using Docker, as I have been experiencing errors when attempting to run the project directly. 

I have tried accessing the project on both Firefox and Chrome, and unfortunately, the issue persists on both browsers.

**Comment by GaiZhenbiao** [comment]
There's no dialog... haven't figured that out yet. Currently it saves the history file directly beside the `.py` file.

**Comment by hyyz17200** [comment]
Ah, I see. So it's a function that still incomplete? 
Since I am running it through Docker, I was unable to find any history file. Nonetheless, it is not a major concern since it can be resolved once the export function is completed.

**Comment by GaiZhenbiao** [comment]
Now this function should be more intuitive. Try the latest version.
