### ISSUE TITLE
[功能请求] 早点支持GPT4模型

### ISSUE THREAD

**Issue by thewintersun** [GaiZhenbiao/ChuanhuChatGPT#150]
早点支持GPT4模型

**Comment by GaiZhenbiao** [comment]
我还没拿到API测试资格🤧

**Comment by GaiZhenbiao** [comment]
现在加入了模型选择功能。但是我还不知道GPT4的模型叫什么😂

**Comment by FlyBirdF** [comment]
> 现在加入了模型选择功能。但是我还不知道GPT4的模型叫什么😂
关注一下这个计数的项目就知道模型叫啥了
https://github.com/openai/tiktoken/blob/main/tiktoken/model.py😂

**Comment by yxmnjxzx** [comment]
const (
	GPT432K0314             = "gpt-4-32k-0314"
	GPT432K                 = "gpt-4-32k"
	GPT40314                = "gpt-4-0314"
	GPT4                    = "gpt-4"
	GPT3Dot5Turbo0301       = "gpt-3.5-turbo-0301"
	GPT3Dot5Turbo           = "gpt-3.5-turbo"
	GPT3TextDavinci003      = "text-davinci-003"
	GPT3TextDavinci002      = "text-davinci-002"
	GPT3TextCurie001        = "text-curie-001"
	GPT3TextBabbage001      = "text-babbage-001"
	GPT3TextAda001          = "text-ada-001"
	GPT3TextDavinci001      = "text-davinci-001"
	GPT3DavinciInstructBeta = "davinci-instruct-beta"
	GPT3Davinci             = "davinci"
	GPT3CurieInstructBeta   = "curie-instruct-beta"
	GPT3Curie               = "curie"
	GPT3Ada                 = "ada"
	GPT3Babbage             = "babbage"
)

**Comment by GaiZhenbiao** [comment]
已经加入啦
