### ISSUE TITLE
[本地部署] 本地部署和使用Hugging Face时，在发送消息后均收到“JSON解析错误”提示

### ISSUE THREAD

**Issue by pageLeo** [GaiZhenbiao/ChuanhuChatGPT#151]
### 错误描述
> 本地部署和使用Hugging Face时，在发送消息后均收到“JSON解析错误”提示

### 复现操作
> 1. 正常完成本地部署
> 2. 在对话框中发送“简述你是谁”或其他测试信息至ChatGPT后收到“JSON解析错误。请重置对话。收到的内容: "error": {”提示
> 3. 在Hugging Face体验时也如此

### 错误截图
报错见截图最下端
![屏幕截图 2023-03-15 103620](https://user-images.githubusercontent.com/127913885/225193427-5c2abaa6-a4ce-4f2c-a34f-f9de9945b3b0.png)
——————————————————————

### 终端（控制台）中的错误报告
> 无错误报告，终端中显示均正常，只是在返回信息的位置为空，无任何显示。

#### 桌面系统
 - OS: Windows11 22H2
 - Browser: Chrome,

#### 运行依赖
- Gradio Version: 3.21.0
- Python version:Python 3.10.7

**Comment by Keldos-Li** [comment]
感觉这几个都挺像的：
- #94 
- #145
- #146

我先给标 dublicate 了哈，然后也请先关注那几个issue。

**Comment by GaiZhenbiao** [comment]
你是不是没填写API Key？

**Comment by MZhao-ouo** [comment]
长时间无回应，Closed
