### ISSUE TITLE
[功能请求] docker部署后续在线升级

### ISSUE THREAD

**Issue by haohaoget** [GaiZhenbiao/ChuanhuChatGPT#153]
### 该功能请求是否与某个问题相关？
> docker部署后由于需要某些新开发的功能只能重新部署。

### 可能的解决办法
> 在线下载github中的py文件并替换升级

### 其他
> 补充说明

**Comment by Nativu5** [comment]
建议直接使用 watchtower 镜像定期拉取最新的项目镜像。
