### ISSUE TITLE
utils.py: predict_all函数的一个小虫

### ISSUE THREAD

**Issue by tuteng0915** [GaiZhenbiao/ChuanhuChatGPT#156]
utils.py, predict_all函数：
```
214   chatbot.append((parse_text(inputs), parse_text(content)))
```
应改为：
···
chatbot[-1] = (parse_text(inputs), parse_text(content))
···

**Comment by tuteng0915** [comment]
以及对于ProxyError异常没有进行return，不知是笔误还是有意为之

**Comment by GaiZhenbiao** [comment]
这一行的逻辑并没有问题。覆盖最后一条的做法没有道理。

ProxyError确实有点问题，修复了。

**Comment by tuteng0915** [comment]
> 这一行的逻辑并没有问题。覆盖最后一条的做法没有道理。

不，您可以参考您在stream_predict中的实现，并检查predict_all的第4行代码

**Comment by tuteng0915** [comment]
现在的实现会导致chatbox中重复出现用户的提问

**Comment by GaiZhenbiao** [comment]
我预计这时候应该点一下Retry或者重置对话，不过确实会有重复问题。

**Comment by tuteng0915** [comment]
predict_all 中没有 yield

> chatbot[-1] = (parse_text(inputs), parse_text(content))

这样改肯定不会有问题滴
