### ISSUE TITLE
[Docker] 服务器公网IP无法访问

### ISSUE THREAD

**Issue by jiang54** [GaiZhenbiao/ChuanhuChatGPT#159]
### 错误描述
> 你好，我是服务器小白，第一次部署这个玩意，不太了解步骤，我按照那个帖子上面的代码，运行了一遍，服务器好像提示已经成功。但是我上不去。想请教是什么原因？

### 复现操作
> ![image](https://user-images.githubusercontent.com/24377958/225303100-695ae87a-db68-4e05-bb70-0a840105d4fa.png)
我运行了上面的代码，替换了key 账号 密码

### 错误截图
>
![image](https://user-images.githubusercontent.com/24377958/225308572-bff9f5a9-a879-487e-97af-d3ac997abba0.png)

### 终端（控制台）中的错误报告
> ![image](https://user-images.githubusercontent.com/24377958/225303438-d9a70cca-1298-42fc-868b-edaeea2370f6.png)

```console
This site can’t be reached
took too long to respond.
```

### 运行环境
> Windows 11 

- OS:实例状态	
运行中
地域和可用区	
广州   |   广州四区
套餐类型	
通用型
实例规格	
CPU: 2核 内存: 2GB
系统盘	
40GB SSD云硬盘
流量包	
300GB/月（带宽：4Mbps）

### 其他
> 补充说明

**Comment by GaiZhenbiao** [comment]
如果服务器在国内，需要进行备案。另外服务器本身也需要代理。

**Comment by lilyblessing** [comment]
防火墙处理了吗？端口开放了吗

**Comment by jiang54** [comment]
> 如果服务器在国内，需要进行备案。另外服务器本身也需要代理。

我只有ip没域名可以备案吗

**Comment by jiang54** [comment]
> 防火墙处理了吗？端口开放了吗
[lighthouse@VM-12-15-centos ~]$ sudo firewall-cmd --permanent --zone=public --add-port=7860/tcp
FirewallD is not running
请问我需要开启防火墙吗？

**Comment by lilyblessing** [comment]
> > 请问我需要开启防火墙吗？
你截图的ip暴露了；反代了用域名访问才需要备案。
如果我没记错国内服务器提供商是有额外防火墙的，需要去控制台开放

**Comment by jiang54** [comment]
> [lighthouse@VM-12-15-centos ~]$ sudo firewall-cmd --list-ports
7860/tcp
[lighthouse@VM-12-15-centos ~]$ sudo ss -tuln | grep 7860
tcp    LISTEN     0      128       *:7860                  *:*                  
[lighthouse@VM-12-15-centos ~]$ sudo netstat -tuln | grep 7860
tcp        0      0 0.0.0.0:7860            0.0.0.0:*               LISTEN  

我应该是打开了，但是还是上不去，是什么原因呢？

**Comment by jiang54** [comment]
> > > 请问我需要开启防火墙吗？
> 
> 你截图的ip暴露了；反代了用域名访问才需要备案。 如果我没记错国内服务器提供商是有额外防火墙的，需要去控制台开放

[lighthouse@VM-12-15-centos ~]$ sudo firewall-cmd --list-ports
7860/tcp
[lighthouse@VM-12-15-centos ~]$ sudo ss -tuln | grep 7860
tcp    LISTEN     0      128       *:7860                  *:*                  
[lighthouse@VM-12-15-centos ~]$ sudo netstat -tuln | grep 7860
tcp        0      0 0.0.0.0:7860            0.0.0.0:*               LISTEN    
我应该是打开了，但是还是上不去，是什么原因呢？

**Comment by jiang54** [comment]
> > > 请问我需要开启防火墙吗？
> 
> 你截图的ip暴露了；反代了用域名访问才需要备案。 如果我没记错国内服务器提供商是有额外防火墙的，需要去控制台开放

![image](https://user-images.githubusercontent.com/24377958/225310525-9ed9b357-310a-4c35-9ab2-99a066b745b4.png)
太谢谢你了！我找到了，服务器还有个端口管理器

**Comment by lilyblessing** [comment]
国内服务器需要代理跳板才能访问，openai最近在大量封禁服务区域以外访问的账号。
如果使用代理，不建议用香港、俄罗斯区域的代理；有较大可能封号。

**Comment by lthero-big** [comment]
建议直接把api.openai.com替换成国内能访问的api，[具体查看](https://github.com/noobnooc/noobnooc)
