### ISSUE TITLE
[其他] 今天的响应回答很慢，还不如官网网页版

### ISSUE THREAD

**Issue by gq1378** [GaiZhenbiao/ChuanhuChatGPT#162]
如题，大概5秒以上才能开始出，而且光标速度不如之前。网速没有问题。不知道是chatgpt服务器的问题，还是代码有问题，还是？

**Comment by GaiZhenbiao** [comment]
我感觉还可以
![ezgif-5-edd8719b16](https://user-images.githubusercontent.com/51039745/225323564-500d2699-1f16-4f80-a5b1-52095d91f286.gif)

**Comment by GaiZhenbiao** [comment]
对比Plus：
![ezgif-5-edd8719b16](https://user-images.githubusercontent.com/51039745/225324698-4824c609-aa8e-4b0e-ba22-cb7d9324a8b3.gif)

**Comment by GaiZhenbiao** [comment]
对比Plus：
![ezgif-4-574501ec97](https://user-images.githubusercontent.com/51039745/225325191-c3945a69-d2f2-4e1f-b35d-2c37d15d394c.gif)

**Comment by gq1378** [comment]
好吧。应该是我的问题。

https://user-images.githubusercontent.com/32167450/225330409-34297a43-7e08-4440-a7c5-542c18ddc529.mov

**Comment by gq1378** [comment]
今天更严重了，直接无法出答案了，等10几秒钟之后：☹️发生了错误：读取超时，无法获取对话。请检查网络连接，或者API-Key是否有效。官网速度没有任何问题。还是用playground好了。

**Comment by Keldos-Li** [comment]
或许openai对免费用户进行了一定限制……？
- #180

**Comment by tuteng0915** [comment]
我也是，流式的不好用了，一次性返回结果的还可以，但也需要等很久~50s

**Comment by MZhao-ouo** [comment]
非代码问题，先关掉了
