### ISSUE TITLE
使用gpt-4模型的时候返回JSON解析错误。请重置对话。收到的内容: “error”: { “message”: “That model does not exist”, “type”: “invalid_request_error”, “param”: null, “code”: null }}

### ISSUE THREAD

**Issue by mushengLenzer** [GaiZhenbiao/ChuanhuChatGPT#164]
使用gpt-4模型的时候返回JSON解析错误。请重置对话。收到的内容: “error”: { “message”: “That model does not exist”, “type”: “invalid_request_error”, “param”: null, “code”: null }}
请问是我的账户不支持gpt-4，还是软件不支持呢

**Comment by Keldos-Li** [comment]
或许openai开放GPT-4 api的waitlist并没有那么快……

是的，你应该没法用GPT-4。

（所以其实gpt4的相关代码可以写在另一个分支里，到时候正式出了再拉取orz，避免出现这种issue）QAQ

**Comment by GaiZhenbiao** [comment]
GPT 4模型还没有正式推出，你不在内测名单里就会这样
