### ISSUE TITLE
[功能请求] 总结对话（减少token）时加上system prompt

### ISSUE THREAD

**Issue by ysy95109** [GaiZhenbiao/ChuanhuChatGPT#167]
### 该功能请求是否与某个问题相关？
> 总结对话后，system prompt的内容会丢失，导致AI忘记人设。

### 可能的解决办法
> 在总结对话后，在上下文的开头重新添加system prompt。

### 其他
> 无。

**Comment by GaiZhenbiao** [comment]
system prompt永远在，但是用于总结对话prompt设置的不好，导致AI忘记人设🤔️

**Comment by Keldos-Li** [comment]
May be resolved or improved by d2b07881da31617ab12e7204d236d12e873d0bfa ([Chuanhu](https://github.com/GaiZhenbiao)).

**Comment by ysy95109** [comment]
> system prompt永远在，但是用于总结对话prompt设置的不好，导致AI忘记人设🤔️

我的意思是，总结时可以不把system prompt优化掉，让context里面始终保留这一条。
比如总结之后的下一次指令的context应该是类似：[systemPrompt, 总结, 新指令]

**Comment by GaiZhenbiao** [comment]
是的，一直是这样的。实际上System Prompt不会直接进入Context，而是在每次发送数据前添加到Context头部，因此绝对不会被丢失。

**Comment by ysy95109** [comment]
> 是的，一直是这样的。实际上System Prompt不会直接进入Context，而是在每次发送数据前添加到Context头部，因此绝对不会被丢失。

但是既然这样的话不应该会忘记人设呀，我给它的所有人设都放在了system prompt里，它忘得非常干净，一丝一毫都不记得了……

**Comment by ysy95109** [comment]
> May be resolved or improved by [d2b0788](https://github.com/GaiZhenbiao/ChuanhuChatGPT/commit/d2b07881da31617ab12e7204d236d12e873d0bfa) ([Chuanhu](https://github.com/GaiZhenbiao)).

This may help, but not always reliable.

**Comment by Keldos-Li** [comment]
> May be resolved or improved by [d2b0788](https://github.com/GaiZhenbiao/ChuanhuChatGPT/commit/d2b07881da31617ab12e7204d236d12e873d0bfa) ([Chuanhu](https://github.com/GaiZhenbiao)).

↑ _那句话是对可能关闭issue的一个相关commit引用标记，把说那句话的我当机器人吧。_

-----

我的测试是总结对话没有影响system prompt的失效与否，但是及时经过新的commit，它仍可能不会给出扮演的角色，而是告诉你：
> 我是一个AI语言模型，您在使用AI辅助工具“Q&A Chatbot”与我进行了一段对话，……

另外，某些system prompt也会导致总结失败，比如：
<img width="769" alt="image" src="https://user-images.githubusercontent.com/23137268/225521589-cba42aa9-7572-4e07-b035-d34bdf18256f.png">

**Comment by tuteng0915** [comment]
maybe solve by #157
可能不是忘记了 system prompt 而导致的脱离人设，而是总结对话的内容中没有任何人设信息，而被heavily attend到了，使得看上去有些脱离人设

**Comment by ysy95109** [comment]
> 

哦哦，我说明的不够严谨。我的意思是，在总结时ai依然记得自己的人设，但之后我再问它的时候他就完全失忆了，只会回答“我是一个AI模型blabla”

**Comment by tuteng0915** [comment]
> maybe solve by #157 可能不是忘记了 system prompt 而导致的脱离人设，而是总结对话的内容中没有任何人设信息，而被heavily attend到了，使得看上去有些脱离人设

我的锅，是主动触发“总结对话”功能的话，与这个PR无关

**Comment by ysy95109** [comment]
经过测试，问题已经解决，现在关闭这个issue。
