### ISSUE TITLE
[功能请求] 能不能把字体弄小一点，或者对话框高度高一点

### ISSUE THREAD

**Issue by thewintersun** [GaiZhenbiao/ChuanhuChatGPT#169]
能不能把字体弄小一点，或者聊天框的高度大一些。
现在对话框里只能显示12行的文字，
很多时候回复的消息比较长的时候， 需要拉动对话框里面的滚动条才能看到所有的消息，感觉不太方便。

或者那个对话框是textbox还是啥的，可以自己拉高的也行。

**Comment by GaiZhenbiao** [comment]
现在应该好些了
