### ISSUE TITLE
[Docker] 更新新版本后，再次出现something went wrong

### ISSUE THREAD

**Issue by dadaoerv** [GaiZhenbiao/ChuanhuChatGPT#171]
### 错误描述
之前的docker版本，安装后，除了不能反代（127.0.0.1直连不会设置，设置了也没用），用服务器的ip+端口访问是正常的。
![image](https://user-images.githubusercontent.com/46274596/225518517-0821c732-32eb-43e5-8da8-a35c7b321f7c.png)

### 复现操作
删除docker和镜像，重新拉取和安装后，出现something went wrong，无法使用。

如上图，加入直连，还是怎么弄，都是不能解决。更换vps，不同的系统，不同的ip，故障依旧。

昨天用了一天的老版本，很好用，生产力工具。

### 错误截图
![image](https://user-images.githubusercontent.com/46274596/225518177-c8c1a484-c3f9-48c7-afe6-b95e088124be.png)

### 终端（控制台）中的错误报告

```console
(请使用错误报告替换本行)
```

### 运行环境
> **请填写以下列表：**

- OS: [e.g. Linux Ubuntu]
- Docker version:
- Gradio version:
- Python (或Python3) version:

### 其他
> 补充说明

**Comment by GaiZhenbiao** [comment]
我有时候也会碰到这种情况，刷新几下网页就好了……服务端看不到任何访问记录，我也不知道为啥🤧

**Comment by dadaoerv** [comment]
刷新了我数次，并且我回退了所有docker的版本，安装了我原来能用的老版本（之前会删掉所有文件和镜像），安装了我原来能用的23.3.10版本，居然也是something went wrong，这在我更新前是彻底能用的啊、、、、、清空浏览器数据也不行。

完全懵逼

**Comment by GaiZhenbiao** [comment]
太怪了，这应该是Gradio的问题。我找到了几个相关的讨论：
https://github.com/gradio-app/gradio/issues/2700
https://discuss.huggingface.co/t/error-connection-errored-out-during-processing/23439/2
gradio说这个问题已经在3.11版本中修复了。你可以看看你的gradio版本：
```
pip list | grep gradio
```
然后试着升级一下它：
```
pip install gradio --upgrade
pip install packaging --upgrade
```
你可以试着不使用docker，直接安装。

**Comment by dadaoerv** [comment]
已经解决，很简单，关闭用户名密码即可。
by the way

docker run -d --name chatgpt \
	-e my_api_key="sk-xxxxxxxxxxxxxxxxxxxxxxxxx" \
	--restart always \
	-v ~/chatGPThistory:/app/history \
	-p 780607860 \
	tuchuanhuhuhu/chuanhuchatgpt:latest

**Comment by GaiZhenbiao** [comment]
也还是很奇怪。我自己部署到服务器的时候设置了账号密码，并没有碰到什么问题。anyway，感觉不是我能解决的，这应该由`gradio`来解决。

**Comment by rayguo01** [comment]
我单独部署在centOS服务器上，gradio版本3.24.1，也是同样的错误。关闭用户认证就好了。还没有解决方法么？
