### ISSUE TITLE
[本地部署] Expecting value: line 1 column 1 (char 0)

### ISSUE THREAD

**Issue by kbwzy** [GaiZhenbiao/ChuanhuChatGPT#174]
感谢提交 issue! 请尽可能完整填写以下信息，帮助我们更好地定位问题~ 
如果你不知道怎么填写，请先点击编辑框上方的“Preview”在预览中查看我们的说明，然后在空白行处填写信息~
![image](https://user-images.githubusercontent.com/12123683/225585347-590ee320-79f8-47aa-8271-1508de924b77.png)

### 错误描述
> 请简明描述该错误。另外，请注意替换issue标题中的“简短的错误描述”。

### 复现操作
> 你之前干了什么，然后出现了错误呢？例如：
> 1. 正常完成本地部署
> 2. 在对话框中要求 ChatGPT “你是谁？”
> 3. ChatGPT 输出部分内容后程序无任何报错日志，但是web弹出上述错误框。

### 错误截图
> 如果可以，请提供错误的截图，如本地部署的网页截图与终端错误报告的截图。

### 终端（控制台）中的错误报告
> 如果可以，请复制终端中的主要错误报告。

```console
(请使用错误报告替换本行)
```

#### 桌面系统
> **请填写以下列表：**

 - OS: win11
 - Browser: chrome

**Comment by GaiZhenbiao** [comment]
看Readme！
