### ISSUE TITLE
后面会使用gpt4.0吗

### ISSUE THREAD

**Issue by baiyi-os** [GaiZhenbiao/ChuanhuChatGPT#175]
### 该功能请求是否与某个问题相关？
> 描述你遇到的问题~

### 可能的解决办法
> 如果可以，给出一个解决思路~

### 其他
> 补充说明

**Comment by GaiZhenbiao** [comment]
现在加入了GPT4的切换功能，但暂时还不能用，除非你通过了GPT4 API内测
