### ISSUE TITLE
[本地部署] NameError: name 'postprocess' is not defined

### ISSUE THREAD

**Issue by OneMiOne** [GaiZhenbiao/ChuanhuChatGPT#176]
感谢提交 issue! 请尽可能完整填写以下信息，帮助我们更好地定位问题~ 
如果你不知道怎么填写，请先点击编辑框上方的“Preview”在预览中查看我们的说明，然后在空白行处填写信息~

### 错误描述
> 请简明描述该错误。另外，请注意替换issue标题中的“简短的错误描述”。
Traceback (most recent call last):
  File "main.py", line 44, in <module>
    gr.Chatbot.postprocess = postprocess
NameError: name 'postprocess' is not defined
### 复现操作
> 你之前干了什么，然后出现了错误呢？例如：
> 1.我在Replit上面部署Python
> 2.复制ChuanhuChatGPT.PY中的内容复制过去，输入自己的Api
> 3.点击Run之后报错以上错误
### 错误截图
> 如果可以，请提供错误的截图，如本地部署的网页截图与终端错误报告的截图。

### 终端（控制台）中的错误报告
> 如果可以，请复制终端中的主要错误报告。

```console
(请使用错误报告替换本行)
```

#### 桌面系统
> **请填写以下列表：**

 - OS: [e.g. Windows11 22H2]
 - Browser: [e.g. Chrome, safari]

#### 运行依赖
> **请填写以下列表：**
> 你可以在终端中依次输入以下指令以查看软件版本：
> ```shell
> pip show gradio
> python --version
> ```
> （如果你使用Python3，请将`pip`替换为`pip3`，`python`替换为`python3`）

- Gradio version:
- Python (或Python3) version:

### 其他
> 补充说明
一开始的几个版本可以部署成功，今天最新一版出现的问题，我知道这报错的意思但不知道哪里出了问题

**Comment by tuteng0915** [comment]
什么是`main.py`??????

**Comment by tuteng0915** [comment]
> 复制ChuanhuChatGPT.PY中的内容复制过去
> 一开始的几个版本可以部署成功，今天最新一版出现的问题，我知道这报错的意思但不知道哪里出了问题

我表示不理解

**Comment by OneMiOne** [comment]
> 什么是`main.py`??????

就是新建的一个脚本，我本身也不太会用这个网站，所以我是把ChuanhuChatGPT.PY里面的内容复制过去，显示这个错误，之后我也试过按你的教程来在它那上面部署，也是出现同样的错误，就是用你的命令行进行下载，部署

我之前在看了你的视频然后大概可能是3月10日左右的用这个脚本是没有问题的，可以部署成功，然后我看到GPT4发布了，也看你更新了新的模型，所以更新，然后出现的这个错误

**Comment by Keldos-Li** [comment]
不清楚你部署的细节。不过可以猜测你哪里没做对。

之前这个脚本只在一个文件里就写完了。但随着功能的增加脚本变长，这个脚本被拆分为了主文件chuanhuchatbot.py, 次文件utils.py, presets.py，运行时主文件需要引用另外俩文件的内容。

你看看要不把另外俩个文件内容也都复制进你的main.py看看……

另外本issue与本项目仓库关系不大，您最好能自己查阅资料解决后续问题～

**Comment by OneMiOne** [comment]
> 

不好意思，我刚才又去试了一次，我的问题，我用命令行按照你们的教程来直接部署可以运行了，应该是就是没调用到那两个次文件，感谢解答，谢谢
