### ISSUE TITLE
[本地部署] 选择模型时出现问题

### ISSUE THREAD

**Issue by ackness** [GaiZhenbiao/ChuanhuChatGPT#177]
### 错误描述
选择模型时出现多个勾

### 复现操作
随便选择一个模型, 出现多个勾, 然后他会打勾随机一个相同开头的模型, 取消时同理.

### 错误截图

<img width="229" alt="image" src="https://user-images.githubusercontent.com/19150500/225626605-c91dab38-f354-47fe-b41a-f5bafae7b041.png">

<img width="317" alt="image" src="https://user-images.githubusercontent.com/19150500/225627163-9ecf7eb4-1f12-4293-81d6-a77e3390292d.png">

**Comment by GaiZhenbiao** [comment]
这是gradio的bug。请升级到最新版gradio，方法在readme里。
