### ISSUE TITLE
[本地部署] 读取超时，无法获取对话。请检查网络连接，或者API-Key是否有效

### ISSUE THREAD

**Issue by gaoqixuan** [GaiZhenbiao/ChuanhuChatGPT#178]
感谢提交 issue! 请尽可能完整填写以下信息，帮助我们更好地定位问题~ 
如果你不知道怎么填写，请先点击编辑框上方的“Preview”在预览中查看我们的说明，然后在空白行处填写信息~

### 错误描述
> 请简明描述该错误。另外，请注意替换issue标题中的“简短的错误描述”。

### 复现操作
> 你之前干了什么，然后出现了错误呢？例如：
> 1. 正常完成本地部署
> 2. 在对话框中要求 ChatGPT “以LaTeX格式输出三角函数”
> 3. ChatGPT 输出部分内容后程序被自动终止

### 错误截图
> 如果可以，请提供错误的截图，如本地部署的网页截图与终端错误报告的截图。

### 终端（控制台）中的错误报告
> 如果可以，请复制终端中的主要错误报告。

```console
(请使用错误报告替换本行)
```

#### 桌面系统
> **请填写以下列表：**

 - OS: [e.g. Windows11 22H2]
 - Browser: [e.g. Chrome, safari]

#### 运行依赖
> **请填写以下列表：**
> 你可以在终端中依次输入以下指令以查看软件版本：
> ```shell
> pip show gradio
> python --version
> ```
> （如果你使用Python3，请将`pip`替换为`pip3`，`python`替换为`python3`）

- Gradio version:
- Python (或Python3) version:

### 其他
> 补充说明

**Comment by zijiyue** [comment]
+1，后端完全没报错

**Comment by tuteng0915** [comment]
> bad issue means?

Means: Reporter did not provide any useful information, such as how to reproduce, operating environment, output information, etc, making it impossible for developers to solve the problem.

**Comment by a1848580190** [comment]
ok thanks

**Comment by Keldos-Li** [comment]
因有提供更详细信息的同类issue，本issue先关闭。
- #180
