### ISSUE TITLE
生成的编程代码不可以直接粘贴

### ISSUE THREAD

**Issue by tonyklose1984** [GaiZhenbiao/ChuanhuChatGPT#18]
生成的编程代码直接粘贴会报错，发现符号都成为了中文符号，需要手动替换，请在下个版本帮忙更新。

**Comment by GaiZhenbiao** [comment]
我测试了一下，是正常半角的呀。你的prompt是什么？

**Comment by Jerry-FaGe** [comment]
> 生成的编程代码直接粘贴会报错，发现符号都成为了中文符号，需要手动替换，请在下个版本帮忙更新。

怕不是你的浏览器自动把半角符号给翻译了

**Comment by hb-0** [comment]
有时候还会莫名其妙的换行，可能是转义字符没有正确处理

**Comment by hb-0** [comment]
<img width="714" alt="image" src="https://user-images.githubusercontent.com/22149306/222937116-e4f11bc7-0ea7-439b-b50f-70b0e305653f.png">

**Comment by GaiZhenbiao** [comment]
现在这个问题应该解决了
