### ISSUE TITLE
[本地部署] ☹️发生了错误：连接超时，无法获取对话。请检查网络连接，或者API-Key是否有效。

### ISSUE THREAD

**Issue by a1848580190** [GaiZhenbiao/ChuanhuChatGPT#180]
### 错误描述
在文本框输入who are you,后端也会有输出
![image](https://user-images.githubusercontent.com/48507904/225643669-336b7658-7b97-41c6-a5d6-2978b1df8efe.png)
但是最终会出现错误，连接超时，无法获取对话。请检查网络连接，或者API-Key是否有效。
我可以登录外网，可以正常访问，也检查了我的API-key，更新为最新的api-key

### 复现操作
> 你之前干了什么，然后出现了错误呢？

1. 正常完成本地部署，但我有些疑问，在我完成本地部署时是否正确部署了，我的clash界面如下
![image](https://user-images.githubusercontent.com/48507904/225644162-02ee8a9e-c5a8-4796-9366-39969a528751.png)
配置界面如下
![image](https://user-images.githubusercontent.com/48507904/225644263-7b57b784-b059-40c3-9ff0-24acf434396e.png)
127.0.0.1设置如下
![image](https://user-images.githubusercontent.com/48507904/225644466-42897e15-0bd3-41d1-bcef-5174355b5d77.png)
注意：如果选择http，将会出现另一个连接问题，只有这样才不会出现那个问题
2. 在对话框中要求 ChatGPT 回答who are you
3. ChatGPT 输出内容为空白

### 错误截图
![image](https://user-images.githubusercontent.com/48507904/225642982-e7901a01-fabe-4a13-9816-558938f04059.png)

### 终端（控制台）中的错误报告
终端没有报告错误
![image](https://user-images.githubusercontent.com/48507904/225644838-b238f346-30f4-4d5e-af72-80ed4f704e13.png)

```console
(请使用错误报告替换本行)
```

#### 桌面系统
> **请填写以下列表：**

 - OS:  Windows10
 - Browser: Chrome

#### 运行依赖
![image](https://user-images.githubusercontent.com/48507904/225645178-4b4f3a19-3cb4-4f73-a72a-d212e7c90d8a.png)
![image](https://user-images.githubusercontent.com/48507904/225645289-2b0c37cf-5098-4ddc-813d-506b416d8873.png)

- Gradio version: 3.21.0
- Python (或Python3) version: 3.8.13

### 其他
> 补充说明

**Comment by 1353604736** [comment]
也出现一样问题

**Comment by LeMatin1** [comment]
问题+1，官方网页可以正常访问

**Comment by GaiZhenbiao** [comment]
你打开TUN模式试试？

**Comment by Keldos-Li** [comment]
说实话，我刚才也老是出现同样的错误。。。。。只能多刷新几次

**Comment by libiaoliang** [comment]
解决了，狗openai在搞限流，我绑定了一张空额度的信用卡，立刻就快了

**Comment by AllenYkl** [comment]
我也是。只要勾选了实时传输就会报错 

“发生了错误：读取超时，无法获取对话。请检查网络连接，或者API-Key是否有效。”

不勾选就能正常使用

**Comment by AllenYkl** [comment]
> 我也是。只要勾选了实时传输就会报错
> 
> “发生了错误：读取超时，无法获取对话。请检查网络连接，或者API-Key是否有效。”
> 
> 不勾选就能正常使用

更新：
使用"gpt-3.5-turbo-0301"就不会出现上述情况

**Comment by a1848580190** [comment]
> 



> 你打开TUN模式试试？

TUN模式是开的

**Comment by a1848580190** [comment]
更新一下。今天早上只改变了两个设置就可以正常使用了，仅供参考。
![image](https://user-images.githubusercontent.com/48507904/225789920-a1489574-916d-4fe8-b506-cf2194197f43.png)
setting这里system proxy还是要选择http
![image](https://user-images.githubusercontent.com/48507904/225790001-d944b05d-41ea-4e54-bb6d-c998e291c98e.png)
general这里关闭mixin
剩下的可以参考我issue的图片。

**Comment by a1848580190** [comment]
> > 关闭实时传输后会正常一段时间，一会又会出现这个问题
> 
> 同样的问题，但是这个issue写得太烂了

哈哈哈哈哈哈哈哈哈哈哈哈哈哈哈哈哈哈哈，我也感觉也得很烂

**Comment by Keldos-Li** [comment]
> > 同样的问题，但是这个issue写得太烂了
> 
> 
> 
> 哈哈哈哈哈哈哈哈哈哈哈哈哈哈哈哈哈哈哈，我也感觉也得很烂

哈哈哈 说实话可能这个issue确实终端能提供的信息太少了😂，或许我昨天不该给那个人的打bad issue（一些自我反思(/ω＼)

不过感觉上是open ai的问题……

**Comment by Natavidad** [comment]
还是连接不了网，而且生成不了共享的链接
