### ISSUE TITLE
无法收到回复

### ISSUE THREAD

**Issue by KingkingLiu** [GaiZhenbiao/ChuanhuChatGPT#182]
future: <Task finished name='1bz5sbqzaox_0' coro=<Queue.process_events() done, defined at /usr/local/lib/python3.9/site-packages/gradio/queueing.py:343> exception=AttributeError("'AsyncRequest' object has no attribute '_json_response_data'")>

**Comment by MZhao-ouo** [comment]
请提供更多信息

**Comment by Keldos-Li** [comment]
_Originally posted in https://github.com/GaiZhenbiao/ChuanhuChatGPT/issues/163#issuecomment-1472296954_

> future: <Task finished name='1bz5sbqzaox_0' coro=<Queue.process_events() done, defined at /usr/local/lib/python3.9/site-packages/gradio/queueing.py:343> exception=AttributeError("'AsyncRequest' object has no attribute '_json_response_data'")>

无法复现，未提供更多信息，长时间未更新，先行关闭该 issue。

如还未解决请尝试拉取最新代码。
