### ISSUE TITLE
[功能请求] 希望能增加用户一键删除除开头的sys命名外前五条聊天记录，甚至进一步可以删除任意一条之前的聊天记录

### ISSUE THREAD

**Issue by libiaoliang** [GaiZhenbiao/ChuanhuChatGPT#184]
### 该功能请求是否与某个问题相关？
> 连续对话长度不够，总结对话比较鸡肋（可以试一下保留最近七对对话）

### 可能的解决办法
> 暂时先添加用户一键删除除开头的sys命名外前五对聊天记录的功能，之后可以考虑增加删除历史记录甚至修改历史记录的的图形化界面，在没有更好的智能解决token上限方法前让用户可以选择手动操作控制上报的信息。

### 其他
> 补充说明

**Comment by tuteng0915** [comment]
> 连续对话长度不够，总结对话比较鸡肋（可以试一下保留最近七对对话）
related to #157

**Comment by GaiZhenbiao** [comment]
现在加了一个这样的按钮
