### ISSUE TITLE
发生了错误：连接超时，无法获取对话。请检查网络连接，或者API-Key是否有效。

### ISSUE THREAD

**Issue by pacowong12345** [GaiZhenbiao/ChuanhuChatGPT#185]
开了代理,api key没错,能连上CHATGPT官网,是出什么问题了吗,怎解决,网络接的是校园网
![批注 2023-03-17 111818](https://user-images.githubusercontent.com/69738704/225804100-d58171a6-d11c-4725-93a4-e78ad3b425d9.png)

**Comment by Keldos-Li** [comment]
感谢提出，最近有蛮多同样问题反馈的。为了避免重复，请前往以下issue讨论：
- #180 

本issue先关掉了。
