### ISSUE TITLE
[功能请求] 建议加入代理选项，并让用户可以在GUI填写

### ISSUE THREAD

**Issue by frostime** [GaiZhenbiao/ChuanhuChatGPT#189]
### 该功能请求是否与某个问题相关？
> OpenAI API 端口可能需要代理才能访问

### 可能的解决办法

request 本身是有 Proxy 参数的，只需要把这个参数放到 GUI 让用户填写即可

![image](https://user-images.githubusercontent.com/27268127/225818098-2ef5b592-ebe2-4cfd-b117-813655205381.png)

**Comment by Keldos-Li** [comment]
Related：
- #173

**Comment by MZhao-ouo** [comment]
建议使用代理软件的分流规则，需要的话可自行修改代码，暂时认为不需要在GUI里添加，先Close掉了

**Comment by MZhao-ouo** [comment]
可以先用#205 的pr版本测试一下
