### ISSUE TITLE
[功能请求] 关于使用联网搜索

### ISSUE THREAD

**Issue by lilyblessing** [GaiZhenbiao/ChuanhuChatGPT#190]
### 该功能请求是否与某个问题相关？
> 现在联网搜索是类似与[EX-chatgpt](https://github.com/circlestarzero/EX-chatGPT) 那种调用外部 API 接口 ( Google,WolframAlpha,WikiMedia )来实现的吗？
如果是的话，这些api接口的用量应该是有限制的，用量这些是暂时由开发者承担的吗？
如果超量会产生资费问题，可以的话让用户自行创建比较好。

### 可能的解决办法
> 将API等交由用户自己承担，用配置文件导入。

**Comment by WangRongsheng** [comment]
除了duckduckgo search，我们希望引入更多的Google、Wiki search，这是一个值得发展的idea

**Comment by Keldos-Li** [comment]
> 除了duckduckgo search，我们希望引入更多的Google、Wiki search，这是一个值得发展的idea

你是否在寻找，川虎参与开发的这个仓库：https://github.com/MZhao-ouo/Llama_Difu

**Comment by MZhao-ouo** [comment]
目前用的是爬虫的方式实现的，没有使用API。不过通过API调用搜索在开发计划中

**Comment by Keldos-Li** [comment]
该issue被视为一个**问题**，已经有了明确解答，先关闭了。
