### ISSUE TITLE
始终无法使用Expecting value: line 1 column 1 (char 0)

### ISSUE THREAD

**Issue by CrushDemo01** [GaiZhenbiao/ChuanhuChatGPT#201]
感谢提交 issue! 请尽可能完整填写以下信息，帮助我们更好地定位问题~ 
如果你不知道怎么填写，请先点击编辑框上方的“Preview”在预览中查看我们的说明，然后点击“Write”在空白行处填写信息~

### 错误描述
> 在chatGPT官网可以使用，但是用这个项目会有这个问题始终无法使用Expecting value: line 1 column 1 (char 0)。

### 复现操作
> 你之前干了什么，然后出现了错误呢？例如：
> 1. 正常完成本地部署
> 2. 询问了“你好”

### 错误截图
> 如果可以，请提供错误的截图，如本地部署的网页截图与终端错误报告的截图。
![image](https://user-images.githubusercontent.com/69375777/226105433-b3bb06aa-a174-482c-a3c3-32421691bbbc.png)

其他没有任何错误

### 运行环境
> **请填写以下列表：**

 - Windows11 22H2
 - Browser: edge
 - Gradio version:
 - Python (或Python3) version:
aiofiles           23.1.0
aiohttp            3.8.4
aiosignal          1.3.1
altair             4.2.2
anyio              3.6.2
async-timeout      4.0.2
attrs              22.2.0
certifi            2022.12.7
charset-normalizer 3.1.0
click              8.1.3
colorama           0.4.6
contourpy          1.0.7
cycler             0.11.0
duckduckgo-search  2.8.5
entrypoints        0.4
fastapi            0.94.1
ffmpy              0.3.0
filelock           3.10.0
fonttools          4.39.2
frozenlist         1.3.3
fsspec             2023.3.0
gradio             3.21.0
h11                0.14.0
httpcore           0.16.3
httpx              0.23.3
huggingface-hub    0.13.2
idna               3.4
Jinja2             3.1.2
jsonschema         4.17.3
kiwisolver         1.4.4
latex2mathml       3.75.1
linkify-it-py      2.0.0
Markdown           3.4.1
markdown-it-py     2.2.0
MarkupSafe         2.1.2
matplotlib         3.7.1
mdit-py-plugins    0.3.3
mdtex2html         1.2.0
mdurl              0.1.2
multidict          6.0.4
numpy              1.24.2
orjson             3.8.7
packaging          23.0
pandas             1.5.3
Pillow             9.4.0
pip                22.3
pydantic           1.10.6
pydub              0.25.1
pyparsing          3.0.9
pypinyin           0.48.0
pyrsistent         0.19.3
python-dateutil    2.8.2
python-multipart   0.0.6
pytz               2022.7.1
PyYAML             6.0
regex              2022.10.31
requests           2.28.2
rfc3986            1.5.0
setuptools         65.5.0
six                1.16.0
sniffio            1.3.0
socksio            1.0.0
starlette          0.26.1
tiktoken           0.3.2
toolz              0.12.0
tqdm               4.65.0
typing_extensions  4.5.0
uc-micro-py        1.0.1
urllib3            1.26.15
uvicorn            0.21.1
websockets         10.4
yarl               1.8.2

### 其他
> 补充说明

**Comment by Keldos-Li** [comment]
看 README 的 [这部分](https://github.com/GaiZhenbiao/ChuanhuChatGPT#网页提示错误-something-went-wrong)。

Duplicate with 
- #43 
- #48 
- #85
- #174 
- #197
