### ISSUE TITLE
[功能请求] 增加自己的database

### ISSUE THREAD

**Issue by bloomin1** [GaiZhenbiao/ChuanhuChatGPT#202]
想問一下會以後增加功能去導入自己pdf,word等文件然後詢問的?

另外我想問, 如果想要導入信件,email等等讓chatbot根據自己數據庫和用戶的指示去分析然後回答的, 這樣可以實現的?

**Comment by learnCodeON** [comment]
我知道一个网站能到达你说的要求，它的名字叫PandaGPT，这个需要收费，但是每天有免费的使用次数。你能把文件传输到这个网站，向机器人问文件当中的内容。这个网站支持的文件格式有pdf，是否支持其他的文件格式我不清楚。[https://www.pandagpt.io/](url)

**Comment by bloomin1** [comment]
那個我知道 不好用的
