### ISSUE TITLE
布局太小气

### ISSUE THREAD

**Issue by g-wellsa** [GaiZhenbiao/ChuanhuChatGPT#204]
聊天区域能不宽广点，每个回答item能不能添加copy选项，还有上下文联系的问题，最好根据字的多少动态减少，加入摘要功能

**Comment by g-wellsa** [comment]
另外能不能加入对app端的接口支持

**Comment by Keldos-Li** [comment]
梳理了下您的功能请求，有以下几点，不知道有没有理解对您的意思：
- **加宽对话框宽度**（我觉得目前布局还行，对话框宽度是根据页面宽度动态调整的）
- **为回答的聊天气泡增加copy按钮**（gradio框架限制了我们的开发）
- **根据历史对话的长度自动总结对话**（相关讨论：#157）
- **加入对app端的接口支持**（我没有理解）

**Comment by g-wellsa** [comment]
加入对app端的接口支持，就是我想在app端调用接口，而不是app之间对接chatgpt

**Comment by g-wellsa** [comment]
加入对app端的接口支持，就是我想在app端调用接口，而不是app直接对接chatgpt

**Comment by g-wellsa** [comment]
应该是加高聊天区域

**Comment by Keldos-Li** [comment]
做一些回应吧。。
- 目前对话框的高度是综合考虑了网页端和手机端的效果的，如果你有其他想法可以给出原型草图给我们参考；
- 目前没有找到gradio引入js的办法，该项功能可能不在计划中，如有需要可尝试自行用一些油猴脚本或浏览器插件实现；
- 正在讨论可行性与必要性；
- 我还是没理解，因为我们也是调用openai的接口。如果你想要尝试开发app，可以参考我们的代码。
