### ISSUE TITLE
在最新版的项目中gradio和duckduckgo_search有兼容性问题

### ISSUE THREAD

**Issue by learnCodeON** [GaiZhenbiao/ChuanhuChatGPT#206]
我在安装了新版的项目时，一直不能正常运行（以前能正常运行的）。当我在根据“README.md”下面的“疑难杂症解决”的“pip install gradio --upgrade --force-reinstall”运行这句话的时候，出现了下面这个错误：
<img width="872" alt="image" src="https://user-images.githubusercontent.com/127178633/226152616-6c747c3e-d0af-4fbb-a84c-e41985e15641.png">
根据上面这张图片里面的提示，我知道了gradio里面有一个叫conda-repo-cli的库，conda-repo-cli需要的requests的版本是2.28.1。但是，当我下载2.28.1版本的requests时，又出现了下面这个错误：
<img width="857" alt="image" src="https://user-images.githubusercontent.com/127178633/226152695-1719454a-1e0d-49c2-ae86-3a057e4125e6.png">
根据上面这张图，可以知道duckduckgo-search需要requests的版本要大于等于2.28.2。

结合两图可知：gradio和duckduckgo_search有兼容性问题，因为conda-repo-cli和
duckduckgo_search需要的requests的版本不一致。

**Comment by GaiZhenbiao** [comment]
我目前安装了`gradio--3.22.0`，`requests==2.28.2`和`duckduckgo_search==2.8.5`，没有兼容性问题。其实这种报错大部分时候可以忽略，毕竟还是会安装成功，大概率跑起来也不会有什么问题。

**Comment by issacqin** [comment]
gradio模块安装有问题，我在armbian里面。request安装了

**Comment by issacqin** [comment]
> gradio模块安装有问题，我在armbian里面。request安装了

同环境下安装docker就可以run，另外，发现主程序没问题，但是用户名密码认证程序有问题，login以后页面没有反应。

**Comment by GaiZhenbiao** [comment]
奇怪了，怎么这么多人说密码认证有问题。我自己一直在用，一直也没问题。

**Comment by learnCodeON** [comment]
> 奇怪了，怎么这么多人说密码认证有问题。我自己一直在用，一直也没问题。

可能是网络问题，我今天使用ChuanhuChatGPT时，有的时候报错，换一个网络节点能解决大部分问题。
