### ISSUE TITLE
[功能请求] 希望增加对pdf等文件的解析，帮助进行学术论文的概括。

### ISSUE THREAD

**Issue by CrushDemo01** [GaiZhenbiao/ChuanhuChatGPT#208]
### 该功能请求是否与某个问题相关？
> 希望增加对pdf等文件的解析。

### 可能的解决办法
> 我看类似于 [ChatPaper](https://github.com/kaixindelele/ChatPaper) 和 [researchgpt](https://github.com/mukulpatnaik/researchgpt) 做了相关的项目，但实测不太好用。

### 其他
> 补充说明

**Comment by CrushDemo01** [comment]
[ChatPaper](https://github.com/kaixindelele/ChatPaper)

[researchgpt](https://github.com/mukulpatnaik/researchgpt)

**Comment by Keldos-Li** [comment]
Duplicate with 
- #202

**Comment by Keldos-Li** [comment]
Resolved by  
- 加入GPT Index 8fdf34ee5f9d2bc7c87ef0a7433bd69ec102412d ([Chuanhu](https://github.com/GaiZhenbiao))
- 加入GPT Index功能 49612ba3a183ecefec9866b29e4cff3d8a287594 ([Chuanhu](https://github.com/GaiZhenbiao))
- 修复依赖 5457fcd379a9f63f1357ce403aa379e0b5f752c6 ([Chuanhu](https://github.com/GaiZhenbiao))
- 修复哈希值出错的问题 bc488e1572102f801db3b52060f811076b417b25 ([Chuanhu](https://github.com/GaiZhenbiao))
- 优化prompt dbdf4dbb3be4bf246e86d541a93bcf1472029fd2 ([Chuanhu](https://github.com/GaiZhenbiao))
- 修复token占用过高的问题 883ed1352f4f08746f2af9aca66aa913714c3bae ([Chuanhu](https://github.com/GaiZhenbiao))
- 改进索引逻辑 c87ba04daecc200b47111b0789a3b701afeb8a18 ([Chuanhu](https://github.com/GaiZhenbiao))
