### ISSUE TITLE
[给其他用户的提示]把bat文件默认浏览器改成谷歌的方式

### ISSUE THREAD

**Issue by Lineasynene** [GaiZhenbiao/ChuanhuChatGPT#209]
右键编辑chatgpt - windows.bat
倒数第二行的改为以下路径：（大概率谷歌默认安装在这里，自定义安装和其他浏览器的改成自己的路径）
start C:\Program" "Files" "(x86)\Google\Chrome\Application\chrome.exe "http://127.0.0.1:7860/

注意点：路径里如果有空格，要用“”框起来

**Comment by Keldos-Li** [comment]
Resolved by 4b845f902cd54b95825a8564de1673cb3b8bb2f8 ([Chuanhu](https://github.com/GaiZhenbiao)).
