### ISSUE TITLE
希望增加用户名密码登录方式进入

### ISSUE THREAD

**Issue by yanhuahoudeye** [GaiZhenbiao/ChuanhuChatGPT#21]
在个人搭建的服务器中通过服务器地址访问会直接进入聊天，能否在进入聊天之前，添加一个个人认证模块，用户名密码登录？

**Comment by chenhengjie123** [comment]
gradio自带这个用户名密码登录验证的能力，可以参考：
https://gradio.app/sharing-your-app/#authentication

**Comment by zgl018** [comment]
加密码就把最后一句改为
demo.queue().launch(server_name="0.0.0.0", server_port=7860,auth=("username", "pass"))
