### ISSUE TITLE
更新到23.03.19后，用户名密码认证程序有问题，login页面没有反应 !

### ISSUE THREAD

**Issue by bentwnghk** [GaiZhenbiao/ChuanhuChatGPT#211]
![login](https://user-images.githubusercontent.com/101241940/226220406-dce6190f-fc9d-4f46-bb2c-2873b3063056.png)

**Comment by ziyuanz96** [comment]
实测应该是gradio的最新版本导致的问题，我通过安装gradio 3.21.0之前版本可以解决。
`pip install gradio==3.21.0`

**Comment by MZhao-ouo** [comment]
Gradio的问题，Closed

**Comment by GaiZhenbiao** [comment]
我也遇到了这个问题，gradio的代码出问题了

**Comment by Mvrjustid** [comment]
> 

在这个回复当前的版本也有这个问题，但是退回gradio==3.21.0之后出现了另一个问题：

Traceback (most recent call last):
  File "D:\lab\ChuanhuChatGPT-main\ChuanhuChatbot.py", line 62, in <module>
    theme=gr.themes.Soft(
TypeError: set() got an unexpected keyword argument 'button_primary_background_fill'

**Comment by Promisery** [comment]
gradio 3.23.0已经修复了
