### ISSUE TITLE
[封号]使用share=true之后，只是做了两次测试访问，第二天就被封号了

### ISSUE THREAD

**Issue by wxpftd** [GaiZhenbiao/ChuanhuChatGPT#214]
感谢提交 issue! 请尽可能完整填写以下信息，帮助我们更好地定位问题~ 
如果你不知道怎么填写，请先点击编辑框上方的“Preview”在预览中查看我们的说明，然后点击“Write”在空白行处填写信息~

### 错误描述
> 请简明描述该错误。
使用share=true之后，只是做了两次测试访问，第二天就被封号了

### 复现操作
> 你之前干了什么，然后出现了错误呢？例如：
> 1. 正常完成本地部署
> 2. 在对话框中要求 ChatGPT “以LaTeX格式输出三角函数”
> 3. ChatGPT 输出部分内容后程序被自动终止

### 错误截图
> 如果可以，请提供错误的截图，如本地部署的网页截图与终端错误报告的截图。
<img width="1131" alt="image" src="https://user-images.githubusercontent.com/5720352/226226878-24e5b161-9141-48a2-b809-91cacd7c6b5e.png">

### 终端（控制台）中的错误报告
> 如果可以，请复制终端中的主要错误报告。

```console
(请使用错误报告替换本行)
```

### 运行环境
> **请填写以下列表：**

 - OS: ubuntu
 - Browser: Chrome
 - Gradio version:
 - Python (或Python3) version: Python 3.10.6

### 其他
> 补充说明

**Comment by MZhao-ouo** [comment]
应该是你的账号有问题，最好用自己的手机号注册，Closed
