### ISSUE TITLE
[本地部署] 启动项目报错

### ISSUE THREAD

**Issue by zhangminggeek** [GaiZhenbiao/ChuanhuChatGPT#215]
感谢提交 issue! 请尽可能完整填写以下信息，帮助我们更好地定位问题~ 
如果你不知道怎么填写，请先点击编辑框上方的“Preview”在预览中查看我们的说明，然后在空白行处填写信息~

### 错误描述

安装完成后，执行 `python ChuanhuChatbot.py` 启动项目报错

### 复现操作

1. 按照文档安装完成依赖
2. 执行 `python ChuanhuChatbot.py`
3. 控制台报错

### 错误截图
> 如果可以，请提供错误的截图，如本地部署的网页截图与终端错误报告的截图。

### 终端（控制台）中的错误报告
> 如果可以，请复制终端中的主要错误报告。

```console
[root@test-frontd01 ChuanhuChatGPT]# python ChuanhuChatbot.py
  File "ChuanhuChatbot.py", line 92
    placeholder=f"OpenAI API-key...",
                                   ^
SyntaxError: invalid syntax
```

#### 桌面系统
> **请填写以下列表：**

 - OS: CentOS Linux 7

#### 运行依赖
> **请填写以下列表：**
> 你可以在终端中依次输入以下指令以查看软件版本：
> ```shell
> pip show gradio
> python --version
> ```
> （如果你使用Python3，请将`pip`替换为`pip3`，`python`替换为`python3`）

- Gradio version: 8.1.2
- Python (或Python3) version: 2.7.5

### 其他
> 补充说明

**Comment by yhxiong** [comment]
python的版本低，更新到3.8以上的python就行。
