### ISSUE TITLE
本地部署之后运行提示“Error”

### ISSUE THREAD

**Issue by kaesi0** [GaiZhenbiao/ChuanhuChatGPT#217]
### 错误描述
> 本地部署之后运行提示“Error”，已将openai.com加入代理规则，无论开关代理，输入之后提交均提示这个错误

### 错误截图
>
![image](https://user-images.githubusercontent.com/23182344/226239558-bf6bf078-dbe6-45d7-b4d0-b107103df077.png)

**Comment by Keldos-Li** [comment]
请提供更多的信息，如终端中的报错内容等。

**Comment by wzf842321317** [comment]
Something went wrong
Expecting value: line 1 column 1 (char 0)

![image](https://user-images.githubusercontent.com/48514232/226502328-77bfd334-5fc8-421a-a0da-d6827941e434.png)

**Comment by hexiaoen** [comment]
me too

**Comment by wzf842321317** [comment]
后台没有任何日志输出，前台也没有任何输出

**Comment by hexiaoen** [comment]
看到解决方法了，说是127.0.0.1的地址被代理了。

**Comment by Keldos-Li** [comment]
请首先查看 README 中的相关疑难解答。

相关issue：
- #43
- #48
- #131
（更多一致的issue不再给出）

**Comment by Keldos-Li** [comment]
issue原作者的问题表现似乎有所不同，但也请尝试拉取较新的代码重试。同时也有一定概率是openai的问题。

**Comment by GaiZhenbiao** [comment]
你的代码版本似乎比较旧，建议下载最新版代码。
