### ISSUE TITLE
[功能请求] 改进在线搜索结果的排版效果

### ISSUE THREAD

**Issue by dannywen2** [GaiZhenbiao/ChuanhuChatGPT#224]
在线搜索的结果没有换行，能否把搜索结果排版一下，目前看起来很乱

**Comment by dannywen2** [comment]
新版本的在线搜索结果显示位置有问题，应该在左边而不是右边

**Comment by Keldos-Li** [comment]
确实哦，两个问题：
1. 检索结果被错误地显示在用户气泡中；
2. 检索结果未含条换行。

<img width="915" alt="image" src="https://user-images.githubusercontent.com/23137268/226304485-3f04e38e-f59b-47d7-99ab-614751d57f69.png">

**Comment by Keldos-Li** [comment]
May be resolved by 079c7eb6a07dc01ce58d074017bb767ebef90bec ([Chuanhu](https://github.com/GaiZhenbiao)).

-----

（现在搜索结果不会被直接显示。当然之前直接显示url也不对。或许效果仍有改进空间？）

**Comment by Keldos-Li** [comment]
（帮你把代码链接放出来（（
https://github.com/GaiZhenbiao/ChuanhuChatGPT/blob/079c7eb6a07dc01ce58d074017bb767ebef90bec/chat_func.py#L348-L354

**Comment by dannywen2** [comment]
1.在线搜索的url超链接有时能能点击有时候是失效的，能点开的链接是当前页面打开，能否在新页面打开
2.点重新生成按钮后，在线搜索结果的排版又乱了，而且成英文结果了
