### ISSUE TITLE
[本地部署] API-key默认为""，启动报错

### ISSUE THREAD

**Issue by xianweicui** [GaiZhenbiao/ChuanhuChatGPT#225]
### 错误描述
不修改代码中的 my_api_key，不定义 api_key.txt，保持 my_api_key=""，启动服务后，输入API-key报错，
错误信息：“发生了错误：API key长度不是51位，请检查是否输入正确”
输入的API-key没问题，如果修改默认值 my_api_key="API-key"启动服务，则正常运行。
![image](https://user-images.githubusercontent.com/93915043/226299001-bd6d0428-c01d-41ff-8161-3e7ae94d9414.png)

### 复现操作
> 1. 正常完成环境部署
> 2. 执行 python ChuanhuChatbot.py
> 3. 控制台输入API-key，执行报错

**Comment by GaiZhenbiao** [comment]
我刚刚测试了下，没有问题。你试试最新版代码？

**Comment by GaiZhenbiao** [comment]
最新版代码中，需要按enter提交Key
