### ISSUE TITLE
代码显示超出容器

### ISSUE THREAD

**Issue by panlina** [GaiZhenbiao/ChuanhuChatGPT#226]
### 错误描述
如题，一行代码太长会超出容器

### 复现操作
让它生成一段代码

### 错误截图
<img width="650" alt="image" src="https://user-images.githubusercontent.com/18240847/226308751-47106099-aa08-4598-a4a1-852967b8c2f5.png">

### 运行环境

 - Browser: Chrome

**Comment by Keldos-Li** [comment]
！我解决一下哈
