### ISSUE TITLE
[本地部署] AttributeError: module 'gradio' has no attribute 'themes'

### ISSUE THREAD

**Issue by Nevermore1213** [GaiZhenbiao/ChuanhuChatGPT#228]
### 错误截图
> 如果可以，请提供错误的截图，如本地部署的网页截图与终端错误报告的截图。
![image](https://user-images.githubusercontent.com/73946601/226314173-e64d0e9d-e637-4a18-b6a7-7561d301377f.png)

#### 桌面系统
> win10 Chrome

#### 运行依赖
全部安装完成

### 其他
> 补充说明

**Comment by GaiZhenbiao** [comment]
更新最新版Gradio即可。见readme。
