### ISSUE TITLE
[功能请求] GPT Index使用教程和增加索引文件demo

### ISSUE THREAD

**Issue by WangRongsheng** [GaiZhenbiao/ChuanhuChatGPT#230]
### 该功能请求是否与某个问题相关？
> 描述你遇到的问题~

GPT Index使用教程和增加索引文件demo

### 可能的解决办法
> 如果可以，给出一个解决思路~

- 增加【索引文件上传】的demo索引
- 在README添加简要的GPT Index使用方法

**Comment by Keldos-Li** [comment]
有道理，我觉得还需要在README中提示勾选”在线搜索“或使用本地索引会**大大耗费tokens**🥲（zhende

**Comment by WangRongsheng** [comment]
> 有道理，我觉得还需要在README中提示勾选”在线搜索“或使用本地索引会**大大耗费tokens**🥲（zhende

good job
