### ISSUE TITLE
[功能请求] 最新版客户端会自动把换行符过滤，希望调整回换行符不过滤的版本

### ISSUE THREAD

**Issue by newpolymerization** [GaiZhenbiao/ChuanhuChatGPT#232]
### 该功能请求是否与某个问题相关？
> 最新版上传一些换行符比较多的代码的时候，换行符会被过滤然后所有代码会缩成一团，ChatGPT 对换行符实际上也是会正常阅读的，有换行符的问题ChatGPT能够更好的理解语法。

### 可能的解决办法
> 不要删除换行符

**Comment by Keldos-Li** [comment]
还真是？用户发送的换行符被挤掉了。我checkout一下是哪个commit引入的。

**Comment by GaiZhenbiao** [comment]
这个就是新的`parse_text`函数引起的。具体地说，是这一句：
```
if line.strip() != "":
                new_lines.append(line)
```
但是如果不过滤，code_fence会出问题。

**Comment by Keldos-Li** [comment]
Should be fixed by:
- 大幅度改进了输入输出解析。 90d39c30417719e9b819b0ea78f7c62d7646441a ([Chuanhu](https://github.com/GaiZhenbiao))
- 以及其他后续commit（懒得找了）
