### ISSUE TITLE
[本地部署] 选择模型里面的GPT-4无法调取

### ISSUE THREAD

**Issue by angle07231** [GaiZhenbiao/ChuanhuChatGPT#233]
### 错误描述
> GPT-3.5正常工作，切换到GPT-4提示JSON解析错误。请重置对话。收到的内容: “error”: { “message”: “The model: gpt-4 does not exist”, “type”: “invalid_request_error”, “param”: null, “code”: “model_not_found” }}

### 复现操作
> 你之前干了什么，然后出现了错误呢？例如：
> 1. 正常完成本地部署。已经升级PLUS.
> 2. GPT-3.5工作正常。
> 3. GPT-4的4个模型都是同样的报错。

### 终端（控制台）中的错误报告
> INFO:root:输入为：123
INFO:root:使用流式传输
INFO:root:实时回答模式
INFO:root:输入token计数: 8
0it [00:00, ?it/s]INFO:root:    "error": {
INFO:root:        "message": "The model: `gpt-4` does not exist",
INFO:root:        "type": "invalid_request_error",
INFO:root:        "param": null,
INFO:root:        "code": "model_not_found"
INFO:root:    }
INFO:root:}
8it [00:00, 143.70it/s]
INFO:root:传输完毕。当前token计数为[528, 537, 29, 8]
INFO:root:回答为：

#### 桌面系统
> **请填写以下列表：**

 - OS: [e.g. Windows10 ]
 - Browser: [Firefox]

#### 运行依赖
> **请填写以下列表：**
> 你可以在终端中依次输入以下指令以查看软件版本：
> ```shell
> pip show gradio
Name: gradio
Version: 3.22.1
Summary: Python library for easily interacting with trained machine learning models
Home-page:
Author:
Author-email: Abubakar Abid <team@gradio.app>, Ali Abid <team@gradio.app>, Ali Abdalla <team@gradio.app>, Dawood Khan <team@gradio.app>, Ahsen Khaliq <team@gradio.app>, Pete Allen <team@gradio.app>, Ömer Faruk Özdemir <team@gradio.app>
License:
Location: C:\Python311\Lib\site-packages
Requires: aiofiles, aiohttp, altair, fastapi, ffmpy, fsspec, httpx, huggingface-hub, jinja2, markdown-it-py, markupsafe, matplotlib, mdit-py-plugins, numpy, orjson, pandas, pillow, pydantic, pydub, python-multipart, pyyaml, requests, typing-extensions, uvicorn, websockets
Required-by:

> python --version
> Python 3.11.2

**Comment by Keldos-Li** [comment]
Duplicate with
- #164 

另外，就是报错的字面意思，对使用api的请求，“The model: gpt-4 does not exist”。
