### ISSUE TITLE
[本地部署]Server disconnected without sending a response.

### ISSUE THREAD

**Issue by chuyueye** [GaiZhenbiao/ChuanhuChatGPT#239]
### 错误描述
设置代理不成功

### 复现操作

> 1. 正常完成本地部署
> 2. 在对话框中要求 ChatGPT “以LaTeX格式输出三角函数”
> 3. Server disconnected without sending a response.

### 错误截图
> 如果可以，请提供错误的截图，如本地部署的网页截图与终端错误报告的截图。

### 终端（控制台）中的错误报告
什么都没有

```console
(请使用错误报告替换本行)
```

#### 桌面系统
> **请填写以下列表：**

 - OS: [macos latest]
 - Browser: [ Chrome latest]

#### 运行依赖
> **请填写以下列表：**
> 你可以在终端中依次输入以下指令以查看软件版本：
> ```shell
> pip show gradio
> python --version
> ```
> （如果你使用Python3，请将`pip`替换为`pip3`，`python`替换为`python3`）

- Gradio version:
- Python (或Python3) version:

### 其他
> 补充说明

**Comment by GaiZhenbiao** [comment]
最新版代码加入了地区检测功能。
