### ISSUE TITLE
带要点的列表 错误渲染，可以修复吗？

### ISSUE THREAD

**Issue by bentwnghk** [GaiZhenbiao/ChuanhuChatGPT#243]
![listing](https://user-images.githubusercontent.com/101241940/226507303-afaa7935-3598-4b91-83f9-f7c2ed05485f.png)

应该是: 1, 2, 3, 4, 5
现在是: 1, 1, 1, 1, 1

**Comment by Keldos-Li** [comment]
感谢反馈。Transferred into #235
