### ISSUE TITLE
[其他] Hugging Face中UI存在问题

### ISSUE THREAD

**Issue by Ssiswent** [GaiZhenbiao/ChuanhuChatGPT#244]
感谢提交 issue! 请尽可能完整填写以下信息，帮助我们更好地定位问题~ 
如果你不知道怎么填写，请先点击编辑框上方的“Preview”在预览中查看我们的说明，然后点击“Write”在空白行处填写信息~

### 错误描述
> AI回复看不见

### 复现操作
> 你之前干了什么，然后出现了错误呢？例如：
> 1. 正常完成Hugging Face 中的 Space 部署
> 2. 在对话框中随便提问
> 3. ChatGPT 输出看不见

### 错误截图
![image](https://user-images.githubusercontent.com/37449310/226507674-8b36ac6d-323e-4ea9-974d-06d0e15f3a39.png)
![image](https://user-images.githubusercontent.com/37449310/226507738-c1c33913-bd04-461e-9b60-020c9a8398aa.png)

**Comment by GaiZhenbiao** [comment]
Huggingface上的Gradio版本比较旧，存在很多样式方面的问题。现在这个问题已经修复了，我删除了Huggingface上微信样式相关的代码。

**Comment by Ssiswent** [comment]
> Huggingface上的Gradio版本比较旧，存在很多样式方面的问题。现在这个问题已经修复了，我删除了Huggingface上微信样式相关的代码。

感谢，请问Huggingface上可以默认设置一个API Key吗，我尝试修改代码但是无效

**Comment by Keldos-Li** [comment]
![image](https://user-images.githubusercontent.com/23137268/226519190-0488bfe9-3b65-40c1-aec3-442d05c35dcb.png)

其实觉得聊天窗口高度和气泡的边距都有问题……应该是hugging face又不支持直接引用gradio的样式文件。回头看一看加个fallback。

**Comment by Ssiswent** [comment]
感谢，请问Huggingface上可以默认设置一个API Key吗，我尝试修改代码但是无效

**Comment by GaiZhenbiao** [comment]
> 感谢，请问Huggingface上可以默认设置一个API Key吗，我尝试修改代码但是无效

支持在UI里设置呀

**Comment by Ssiswent** [comment]
> 

我想的是像部署在本地一样，在代码里面设置好，就不用在web输入了= =

**Comment by Keldos-Li** [comment]
神奇，huggingface自己好像不支持暗色模式，导致我们自己固定设置暗色模式的变量会发生一些奇怪效果：
<img width="1272" alt="image" src="https://user-images.githubusercontent.com/23137268/226929904-6a68d697-2798-4064-8e7d-9bd0d7def0e5.png">

**Comment by kylechandev** [comment]
> > 
> 
> 我想的是像部署在本地一样，在代码里面设置好，就不用在web输入了= =

在`app.py`文件里面修改就可以了

**Comment by Ssiswent** [comment]
> > > 
> > 
> > 
> > 我想的是像部署在本地一样，在代码里面设置好，就不用在web输入了= =
> 
> 在`app.py`文件里面修改就可以了

本地部署的可以在这个文件修改，Hugging face我设置了不生效。。

**Comment by kylechandev** [comment]
> > > > 
> > > 
> > > 
> > > 我想的是像部署在本地一样，在代码里面设置好，就不用在web输入了= =
> > 
> > 
> > 在`app.py`文件里面修改就可以了
> 
> 本地部署的可以在这个文件修改，Hugging face我设置了不生效。。

不是，本地部署是在`ChuanhuChatbot.py`文件里设置，我一开始部署到Hugging face，也是去`ChuanhuChatbot.py`这个文件里去设置的，然后没效果，后来我看了一下代码，应该在`app.py`这个文件里修改，这里面也有一个api-key字段，就是web页面的那个输入框，把key直接写在代码里就ok了，我这样操作后可以直接用了，你可以再试试看
