### ISSUE TITLE
[功能请求] 增加IP归属地的提示，如果为国内IP地址，提示用户有API违规风险

### ISSUE THREAD

**Issue by ramblezhang** [GaiZhenbiao/ChuanhuChatGPT#245]
### 该功能请求是否与某个问题相关？
> 
![image](https://user-images.githubusercontent.com/36092557/226508946-380a6411-3e15-4cce-81ac-83760e8ed1a0.png)
按照openai的用户协议，如果在非支持区域（国内）调用API的话，有可能导致封号，建议在页面上根据IP归属地提示。
因为目前API调用并未受到限制，很可能在使用时，忘了科学上网，对自己的账号带来风险。

### 可能的解决办法
> 请求一个远端IP归属地的检查服务，如果归属地不在国内的话，页面显著位置有所提示。比如使用ipstack API或ipapi.co API的服务

```import requests

# Make a request to the ipapi.co API with your public IP address
response = requests.get('https://ipapi.co/json/')

# Parse the JSON response
data = response.json()

# Print the location information
print('Country:', data['country_name'])
print('Region:', data['region'])
print('City:', data['city'])
print('Latitude:', data['latitude'])
print('Longitude:', data['longitude'])
```

### 其他
>

**Comment by GaiZhenbiao** [comment]
<img width="496" alt="image" src="https://user-images.githubusercontent.com/51039745/226511044-8004d3ad-deb9-4232-84db-efbd03c1a331.png">

加入了
