### ISSUE TITLE
使用深色模式， 字体就会看不见

### ISSUE THREAD

**Issue by changeche01** [GaiZhenbiao/ChuanhuChatGPT#246]
部署使用上挺好的，很棒。

有一个样式的问题，在苹果手机，或者电脑上，使用深色模式， 字体就会看不见。 这个可能要加一个样式选择按钮，选择不同的样式

**Comment by GaiZhenbiao** [comment]
你等待一会儿，字体就会逐渐变成白色，就可见了。这个是全局transition导致的。现在修复了。
