### ISSUE TITLE
【本地部署】已拉取最新版本，运行仍报No module named gradio

### ISSUE THREAD

**Issue by linbo0** [GaiZhenbiao/ChuanhuChatGPT#249]
gradio也已按指引重装了

ubuntu@VM-0-2-ubuntu:~/ChuanhuChatGPT$ sudo git pull https://github.com/GaiZhenbiao/ChuanhuChatGPT.git main -f
From https://github.com/GaiZhenbiao/ChuanhuChatGPT
 * branch            main       -> FETCH_HEAD
Already up to date.
ubuntu@VM-0-2-ubuntu:~/ChuanhuChatGPT$ python ChuanhuChatbot.py 
Traceback (most recent call last):
  File "ChuanhuChatbot.py", line 6, in <module>
    import gradio as gr
ImportError: No module named gradio

**Comment by jing332** [comment]
我也遇到了这个问题，用PyCharm导入项目，自动创建了个虚拟环境venv后就好了.
然后用 `.\ChuanhuChatGPT\venv\Scripts\python.exe .\ChuanhuChatGPT\ChuanhuChatbot.py` 运行

**Comment by jing332** [comment]
已经装了， `pip install -r requirements.txt` 运行正常， 执行pip list 里也有 `gradio 3.22.1`。
这就奇了怪了,可能是我电脑的python环境问题

**Comment by MZhao-ouo** [comment]
是，这个需要你自己折腾一下
