### ISSUE TITLE
跑起来之后，输入问题好像就没反应了，也没报错

### ISSUE THREAD

**Issue by LeiYao123** [GaiZhenbiao/ChuanhuChatGPT#25]
代码里就只改了 key
![image](https://user-images.githubusercontent.com/99799032/222940666-f2b41c02-edb3-4752-b630-2abfa5c115e3.png)
![image](https://user-images.githubusercontent.com/99799032/222940681-d0362bd1-af9a-40cb-912b-9e4d88c59363.png)

**Comment by arnoldlxa** [comment]
api被墙了，换一种方式：用cloudflare反代api，使用 Cloudflare Workers 解决 OpenAI 和 ChatGPT 的 API 无法访问的问题，参考内容（https://github.com/noobnooc/noobnooc/discussions/9）

**Comment by earthcoin123** [comment]
代码里设置APIkey后，目前传递的apikey不正确。
如果在代码里设置APIkey，需要修改如下
def set_apikey(new_api_key, myKey):
-    old_api_key = myKey
+   new_api_key = myKey
但是这样改的话就不可以在网页前台修改apikey了，在前台修改是无效的，系统会一直使用代码里设置的APIkey。
