### ISSUE TITLE
[其他] ip检测bug

### ISSUE THREAD

**Issue by zhiwenzeng** [GaiZhenbiao/ChuanhuChatGPT#252]
1、使用代理时，get_geoip中requests.get('https://ipapi.co/json/', timeout=5)返回的data数据为：{'error': True, 'reason': 'RateLimited', 'message': 'Visit https://ipapi.co/ratelimited/ for details'}；
2、关闭代理后运行正常并且代理显示为"中国"，切换代理后refresh刷新后依旧显示"中国"

**Comment by GaiZhenbiao** [comment]
你是不是刷新太频繁了？到达了速率限制。IP检测是在服务区启动的时候检测的，不是在页面刷新的时候检测的。

**Comment by GaiZhenbiao** [comment]
现在加入了这方面的错误恢复。

**Comment by zhiwenzeng** [comment]
> 你是不是刷新太频繁了？达到了速度限制。IP检测是在服务器启动的时候检测的，不是在页面刷新的时候检测的。

我看过代码，ip检测是启动时只检测一次。在使用过程中，我将代理修改为其他节点，依旧显示启动时的检测结果。提这个是因为切换代理后并没有刷新检测结果，而是需要重启程序。
