### ISSUE TITLE
[功能请求] 程序可以配置为连接外部API地址时通过SOCKS5代理服务

### ISSUE THREAD

**Issue by xiao2c** [GaiZhenbiao/ChuanhuChatGPT#256]
### 该功能请求是否与某个问题相关？
> 服务器在国内或者香港等地直接连接API可能面临被封号

### 可能的解决办法
> Python request 支持使用socks代理服务，是否可以加一个配置socks服务地址和是否用代理的开关，这样可以通过其他外网代理服务器连接API就没有风险

**Comment by GaiZhenbiao** [comment]
目前支持从环境变量中获取HTTPS代理，或者，也可以在UI中设定。

**Comment by YuanfengZhang** [comment]
py ./chuanhuchatbot.py后可以在终端输出看到相关信息：
![image](https://user-images.githubusercontent.com/71358306/226775900-d4c76d3f-4f19-4330-99e4-4ade6ddbb1a8.png)
