### ISSUE TITLE
修复了有序列表和无序列表显示问题，却出现了另一个问题！

### ISSUE THREAD

**Issue by bentwnghk** [GaiZhenbiao/ChuanhuChatGPT#257]
所有下拉列表选项不正常地显示！
![dropdown_list1](https://user-images.githubusercontent.com/101241940/226597737-93c78a83-a4bc-4f96-b3e2-3866752f9326.png)
![dropdown_list2](https://user-images.githubusercontent.com/101241940/226597744-50f8af9f-99c5-48bd-87bb-d55b526e7435.png)
![dropdown_list3](https://user-images.githubusercontent.com/101241940/226597749-8ba09e92-5d67-49dc-b554-fa7ebb2be8f1.png)

**Comment by Keldos-Li** [comment]
我知道哪里写错了。我推一个hotfix吧

**Comment by bentwnghk** [comment]
问题仍然存在呢

**Comment by Keldos-Li** [comment]
什么牛马gradio……

**Comment by Keldos-Li** [comment]
before: 
- Chrome <img width="332" alt="image" src="https://user-images.githubusercontent.com/23137268/226609665-be3103b3-8691-45de-973f-d960c661e989.png">
- Safari <img width="336" alt="image" src="https://user-images.githubusercontent.com/23137268/226610008-20156e30-c631-4314-b0f5-4283f26a01be.png">

now:
Chrome <img width="323" alt="image" src="https://user-images.githubusercontent.com/23137268/226609760-459cdc6c-45b5-4174-9832-964e44811699.png">
Safari <img width="356" alt="image" src="https://user-images.githubusercontent.com/23137268/226610160-ac00a807-db6a-42b8-95f0-9d0714f710b3.png">


应该都解决了。吧。。。感谢反馈~

**Comment by bentwnghk** [comment]
了不起！这次完全解决了问题。
