### ISSUE TITLE
在ChuanhuChatbot.py中设置APIkey后验证出错，提示“发生了未知错误Orz”

### ISSUE THREAD

**Issue by earthcoin123** [GaiZhenbiao/ChuanhuChatGPT#26]
在ChuanhuChatbot.py中设置my_api_key后，在网页中提示要验证APIkey，敲回车验证APIkey时出错，提示“发生了未知错误Orz”
![1](https://user-images.githubusercontent.com/36220186/222946551-bf24e546-9944-4353-90b4-2aba9700a12c.jpg)
![2](https://user-images.githubusercontent.com/36220186/222946560-da123b13-980f-42c1-9d9a-74f456d9402e.jpg)

**Comment by earthcoin123** [comment]
原来不验证apikey也可以直接使用，问题关闭。

**Comment by Methaned** [comment]
![image](https://user-images.githubusercontent.com/129674003/229359405-9134be1d-2fbe-4dba-bc62-ab5982b6d138.png)
我也是验证出错但是尝试对话不行。只会回复我请求过于频繁

**Comment by angelo1018** [comment]
请求失败，请检查API-key是否正确。

**Comment by fword-newbie** [comment]
我也有你這個問題，我看一下command line輸出
```
openai.error.RateLimitError: You exceeded your current quota, please check your plan and billing details.
```
去帳戶查看一下發現免費api份額只到4/1，也就是說，現在該付錢了。
