### ISSUE TITLE
创建共享连接不生效

### ISSUE THREAD

**Issue by githubzhangfei** [GaiZhenbiao/ChuanhuChatGPT#260]
demo.queue().launch(share=False)  # 改为 share=True 可以创建公开分享链接
改为True后不生效，没有视频中的效果，本人不会pyhton，Java出身，勿喷

**Comment by githubzhangfei** [comment]
我的好了，昨天配置错了，感谢大佬@Keldos-Li

**Comment by githubzhangfei** [comment]
配置问题

**Comment by Insanepioneer** [comment]
能问问怎么解决的吗
