### ISSUE TITLE
发送消息提示：Something went wrong Expecting value: line 1 column 1 (char 0)

### ISSUE THREAD

**Issue by WUXM5** [GaiZhenbiao/ChuanhuChatGPT#261]
最开始运行时，终端提示“module 'gradio' has no attribute 'themes' ”
后续更新了gradio库，使用pip install --upgrade gradio来更新。
再次运行时，可以运行成功，然后向GPT发送消息时提示如下：
![image](https://user-images.githubusercontent.com/77671587/226641123-17e75a6d-0842-464b-943e-0d5ef591038f.png)

**Comment by GaiZhenbiao** [comment]
请提供终端报错信息。

**Comment by 15237735357** [comment]
怎么解决的啊

**Comment by grimraider** [comment]
同问，怎么解决的？

**Comment by yannqi** [comment]
关掉代理就行
https://github.com/AUTOMATIC1111/stable-diffusion-webui/issues/9150
