### ISSUE TITLE
[树莓派上部署]成功启动但浏览器无法打开。

### ISSUE THREAD

**Issue by shuangleo** [GaiZhenbiao/ChuanhuChatGPT#264]
树莓派上部署，成功启动。
```
川虎的温馨提示：访问 http://localhost:7860 查看界面
Running on local URL:  http://127.0.0.1:7860

To create a public link, set `share=True` in `launch()
```
苹果电脑上访问ip:7860，浏览器显示【嗯… 无法访问此页面】。
之前的版本这么部署就没问题，升级后反而不行了。不知何故，小白求解，谢谢！

**Comment by GaiZhenbiao** [comment]
请提供更详细的信息。你是不是把终端窗口关掉了？

**Comment by shuangleo** [comment]
并没有关闭终端窗口。上一个版本我都是后台运行的，很稳定，路由器端口转发后外网也能访问。这次照猫画虎，内网都打不开。想不通为什么。本地没试过。

发自我的iPhone手机
________________________________
发件人: Chuan Hu ***@***.***>
发送时间: Wednesday, March 22, 2023 10:40:02 AM
收件人: GaiZhenbiao/ChuanhuChatGPT ***@***.***>
抄送: shuangleo ***@***.***>; Author ***@***.***>
主题: Re: [GaiZhenbiao/ChuanhuChatGPT] [树莓派上部署]成功启动但浏览器无法打开。 (Issue #264)


请提供更详细的信息。你是不是把终端窗口关掉了？

―

**Comment by Xueheng-Li** [comment]
碰到了同样问题，即使是同一台机子，只要用内网 ip ，就无法打开了。

**Comment by shuangleo** [comment]
原来不止我一个。那还是老老实实先用初代版本吧。

发自我的iPhone手机
________________________________
发件人: Xueheng-Li ***@***.***>
发送时间: Thursday, March 23, 2023 11:22:09 PM
收件人: GaiZhenbiao/ChuanhuChatGPT ***@***.***>
抄送: shuangleo ***@***.***>; Author ***@***.***>
主题: Re: [GaiZhenbiao/ChuanhuChatGPT] [树莓派上部署]成功启动但浏览器无法打开。 (Issue #264)


碰到了同样问题，即使是同一台机子，只要用内网 ip ，就无法打开了。

―

**Comment by Keldos-Li** [comment]
Duplicate with
-  #293
