### ISSUE TITLE
甲骨文arm[Docker] 简短的错误描述

### ISSUE THREAD

**Issue by lunhui11** [GaiZhenbiao/ChuanhuChatGPT#265]
### 错误描述
> 报错

### 复现操作
> 登陆之后你好

### 错误截图
> 
![Screenshot_2023-03-22-02-07-16-112_com android browser](https://user-images.githubusercontent.com/91612926/226702190-816ec78b-7f3a-40a0-a70d-9b5ea881ddba.jpg)

### 终端（控制台）中的错误报告
> 如果可以，请复制终端中的主要错误报告。

```console
(请使用错误报告替换本行)
```

### 运行环境
> **请填写以下列表：**

- OS: [e.g. Linux Ubuntu]
- Docker version:
- Gradio version:
- Python (或Python3) version:

### 其他
> 补充说明

**Comment by GaiZhenbiao** [comment]
#85
