### ISSUE TITLE
[功能请求] 提供代理API_URL参数

### ISSUE THREAD

**Issue by tastypear** [GaiZhenbiao/ChuanhuChatGPT#267]
### 该功能请求是否与某个问题相关？
> 为程序提供一个可选的 API_URL 参数

### 可能的解决办法
> 如果可以，给出一个解决思路~
即 Docker 或 py 启动参数中加入代理（镜像）API_URL 用于替代 api.openai.com
已测试直接替换项目中的 api.openai.com 可用，但每次 git pull 后替换有些麻烦

### 其他
> 补充说明

**Comment by MZhao-ouo** [comment]
可以在高级选项里修改

**Comment by Keldos-Li** [comment]
Duplicate with #189 

And already resolved by f4e0fdd381e080edf8ced8974e09073355abb272 ([MZhao](https://github.com/MZhao-ouo))

<hr>

请更改网页中“高级”tab中的相关设置。
