### ISSUE TITLE
[本地部署] 简短的错误描述

### ISSUE THREAD

**Issue by Andynorior** [GaiZhenbiao/ChuanhuChatGPT#268]
感谢提交 issue! 请尽可能完整填写以下信息，帮助我们更好地定位问题~ 
如果你不知道怎么填写，请先点击编辑框上方的“Preview”在预览中查看我们的说明，然后在空白行处填写信息~

### 错误描述
>
![image](https://user-images.githubusercontent.com/125937448/226741951-960bc7c3-7049-4173-b678-a8b57297c94c.png)

### 复现操作
> 按照教程来的

**Comment by GaiZhenbiao** [comment]
请自行搜索解决
