### ISSUE TITLE
[功能请求] 咱就是说有没有可能出一个本地exe的版本啊，python应该可以出exe可执行文件的吧

### ISSUE THREAD

**Issue by Pinkuburu** [GaiZhenbiao/ChuanhuChatGPT#269]
### 其他
> 其实问题就是如标题，想要一个本地exe版本，使用方便的

**Comment by dannywen2** [comment]
自己用pyinstaller -F 打包啊

**Comment by Owenfly** [comment]
感谢提醒

**Comment by Owenfly** [comment]
![image](https://user-images.githubusercontent.com/55825205/226804400-8a6f58f6-9624-4c2d-a8b4-f726125ef413.png)
打包后管理员运行执行失败，能看看是怎么回事吗

**Comment by dannywen2** [comment]
我打包也失败了，但是报错和你的不一样

**Comment by Owenfly** [comment]
我放弃打包了，命令行也挺快的-------- 原始邮件 --------发件人： dannywen2 ***@***.***>日期： 2023年3月22日周三 14:18收件人： GaiZhenbiao/ChuanhuChatGPT ***@***.***>抄送： Owenfly ***@***.***>, Comment ***@***.***>主    题： Re: [GaiZhenbiao/ChuanhuChatGPT] [功能请求] 咱就是说有没有可能出一个本地exe的版本啊，python应该可以出exe可执行文件的吧 (Issue #269)
我打包也失败了，但是报错和你的不一样

**Comment by q751654992** [comment]
![image](https://user-images.githubusercontent.com/40224144/226964372-76c580bc-e487-4f4b-9ce2-15e2eab8f714.png)
打包后运行报错

**Comment by Owenfly** [comment]
仔细想想根本没必要打包啊，这个作者还一直在更新中，后面不还要打包。根本没必要

**Comment by iskoldt-X** [comment]
> 仔细想想根本没必要打包啊，这个作者还一直在更新中，后面不还要打包。根本没必要

你说的对

**Comment by Keldos-Li** [comment]
请在discussion中讨论：
- #302
