### ISSUE TITLE
[其他] 简短的错误描述

### ISSUE THREAD

**Issue by mc622426** [GaiZhenbiao/ChuanhuChatGPT#270]
感谢提交 issue! 请尽可能完整填写以下信息，帮助我们更好地定位问题~ 
如果你不知道怎么填写，请先点击编辑框上方的“Preview”在预览中查看我们的说明，然后点击“Write”在空白行处填写信息~

### 错误描述
> 进入网页，输入命令后，控制台报错
### 复现操作
> 你之前干了什么，然后出现了错误呢？例如：
> 1. 正常完成本地部署
> 2. 在对话框中随便输入
> 3. 控制台报错

### 终端（控制台）中的错误报告
> requests.exceptions.ConnectionError: HTTPSConnectionPool(host='api.openai.com', port=443): Max retries exceeded with url: /v1/chat/completions (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x000001DBBED311C0>: Failed to establish a new connection: [WinError 10060] 由于连接方在一段时间后没有正确答复或连接的主机没有反应，连接尝试失败。'))

**Comment by Keldos-Li** [comment]
Duplicate with 
- #258
