### ISSUE TITLE
Something went wrong Expecting value: line 1 column 1 (char 0) 

### ISSUE THREAD

**Issue by lixibi** [GaiZhenbiao/ChuanhuChatGPT#271]
感谢提交 issue! 请尽可能完整填写以下信息，帮助我们更好地定位问题~ 
如果你不知道怎么填写，请先点击编辑框上方的“Preview”在预览中查看我们的说明，然后在空白行处填写信息~

### 错误描述
> mac系统 使用源码部署

### 复现操作
> 你之前干了什么，然后出现了错误呢？例如：
 发送信息提示
Something went wrong
Expecting value: line 1 column 1 (char 0)

<img width="843" alt="image" src="https://user-images.githubusercontent.com/11870963/226781414-669f8056-f03e-4731-8dbc-220d4de75e2f.png">
<img width="888" alt="image" src="https://user-images.githubusercontent.com/11870963/226781446-5af82153-b3a9-47f5-b3e4-1d2efe1ec337.png">

**Comment by MZhao-ouo** [comment]
检查你的代理设置，127.0.0.1不要被代理
