### ISSUE TITLE
[Docker] 使用 docker compose 配置了用户名和密码后, 出现Something went wrong

### ISSUE THREAD

**Issue by huanfeng** [GaiZhenbiao/ChuanhuChatGPT#272]
### 错误描述
> 使用 docker compose 配置了用户名和密码后, 出现Something went wrong

### 复现操作
> 配置了用户名和密码后, 登录正常, 但进行任何后续操作时, 出现 Something went wrong 错误
如果将用户名和密码删除, 则工作正常

### 错误截图
> 如果可以，请提供错误的截图，如部署的网页截图与控制台错误报告的截图。

### 终端（控制台）中的错误报告
> docker compose logs 中没有任何错误

### 运行环境
> **请填写以下列表：**

- OS: Linux Ubuntu 22.04
- Docker version: ce 23.0.1
- Gradio version: docker 镜像默认
- Python (或Python3) version: docker 镜像默认

### 其他
> 补充说明

**Comment by GaiZhenbiao** [comment]
Websocket配置可能有问题。
