### ISSUE TITLE
[本地部署] Something went wrong Expecting value: line 1 column 1 (char 0)

### ISSUE THREAD

**Issue by Fanrito** [GaiZhenbiao/ChuanhuChatGPT#273]
感谢提交 issue! 请尽可能完整填写以下信息，帮助我们更好地定位问题~ 
如果你不知道怎么填写，请先点击编辑框上方的“Preview”在预览中查看我们的说明，然后在空白行处填写信息~

### 错误描述
> 输入api-key后出现错误弹窗，三种输入api-key的方式都出现同样问题

### 复现操作
> 1. 正常完成本地部署
> 2. 在图形页面上输出api-key
> 3. 弹出错误Something went wrong
Expecting value: line 1 column 1 (char 0)
> 4. 停止运行，在项目文件夹中添加api_key.txt和auth.json
> 5. 重新运行，依然弹出错误Something went wrong
Expecting value: line 1 column 1 (char 0)

### 错误截图
> 如果可以，请提供错误的截图，如本地部署的网页截图与终端错误报告的截图。
![image](https://user-images.githubusercontent.com/96723391/226784866-1b36656d-f3f2-49af-b1de-2bb5be58ec10.png)

### 终端（控制台）中的错误报告
> 终端没有错误报告

```consolehttps://docs.github.com/github/writing-on-github/getting-started-with-writing-and-formatting-on-github/basic-writing-and-formatting-syntax
(请使用错误报告替换本行)
```

#### 桌面系统
> **请填写以下列表：**

 - OS: Windows 10
 - Browser: Eage

#### 运行依赖
> **请填写以下列表：**
> 你可以在终端中依次输入以下指令以查看软件版本：
> ```shell
> pip show gradio
> python --version
> ```
> （如果你使用Python3，请将`pip`替换为`pip3`，`python`替换为`python3`）

- Gradio version: 3.23.0
- Python (或Python3) version: 3.10.10

### 其他
> 补充说明

**Comment by GaiZhenbiao** [comment]
#85
