### ISSUE TITLE
[其他] 不显示代码段

### ISSUE THREAD

**Issue by WindChime-Echo** [GaiZhenbiao/ChuanhuChatGPT#275]
### 错误描述
不显示代码段。

### 复现操作
> 你之前干了什么，然后出现了错误呢？例如：
1. 正常完成本地部署
2. 在对话框中要求 ChatGPT “elementui中自定义校验表单”
3. ChatGPT 输出部分内容后代码段显示
 

你可以使用 element-ui 中的自定义校验规则，通过自定义函数来实现满足条件时不触发校验。具体实现步骤如下：

定义一个自定义校验规则函数，该函数接受当前校验字段值和表单数据对象作为参数，并返回 true 或 false。
在需要进行校验的字段上，设置对应的自定义校验规则，可以使用数组形式设置多个校验规则。
在校验时，先判断是否满足不触发校验的条件，如果满足则不进行校验，否则进行校验。
以下是一个示例代码，演示了如何在 element-ui 中实现在满足条件时不触发校验的功能：

```

```

在上面的示例代码中，我们定义了一个名为 customValidator 的自定义校验函数，该函数判断年龄是否小于 18 岁，如果满足该条件，则不进行校验，否则对名称进行校验。在名称的校验规则中，我们设置了该自定义校验函数，并将触发方式设置为 blur。这样当输入框失去焦点时进行校验，只有在年龄大于等于 18 岁时才会进行名称校验。

通过这种方式，你可以在 element-ui 的校验中实现满足条件时不触发校验的功能。

### 运行环境
> **请填写以下列表：**

 - OS: [e.g. Windows10 22H2]
 - Browser: [e.g. Chrome, safari]
 - Gradio version:
 - Python (或Python3) version:

**Comment by Keldos-Li** [comment]
Should be fixed by  
- 解决大段代码的渲染问题 70ec74266733f9c8b6d41882d29231bf178f20e4 ([Chuanhu](https://github.com/GaiZhenbiao))
- 改进HTML检测逻辑 6d9a18cda23d07de3cdcf70ff91d61541e79f9e8 ([Chuanhu](https://github.com/GaiZhenbiao))
