### ISSUE TITLE
[其他] gpt-4模块不存在了

### ISSUE THREAD

**Issue by LinLL** [GaiZhenbiao/ChuanhuChatGPT#277]
感谢提交 issue! 请尽可能完整填写以下信息，帮助我们更好地定位问题~ 
如果你不知道怎么填写，请先点击编辑框上方的“Preview”在预览中查看我们的说明，然后点击“Write”在空白行处填写信息~
### 错误描述
> “error”: { “message”: “The model: gpt-4 does not exist”, “type”: “invalid_request_error”, “param”: null, “code”: “model_not_found” }}

### 复现操作
> 你之前干了什么，然后出现了错误呢？例如：
> 1. 正常完成本地部署
> 2. 选择gpt-4，无法正常输出，gpt-3运行正常

### 运行环境
> **请填写以下列表：**

 - OS: mac
 - Browser: chrome
 - Gradio version:
 - Python (或Python3) version:3.10

**Comment by MZhao-ouo** [comment]
得有GPT-4的API资格才能用

**Comment by LinLL** [comment]
反馈好快，刚看到文档，准备关了，继续支持。
