### ISSUE TITLE
复制项目在页面上在线跑出现错误

### ISSUE THREAD

**Issue by xuedue** [GaiZhenbiao/ChuanhuChatGPT#278]
感谢提交 issue! 请尽可能完整填写以下信息，帮助我们更好地定位问题~ 
如果你不知道怎么填写，请先点击编辑框上方的“Preview”在预览中查看我们的说明，然后点击“Write”在空白行处填写信息~

### 错误描述
> 请简明描述该错误。
JSON解析错误。请重置对话。收到的内容: "error": { "message": "You exceeded your current quota, please check your plan and billing details.", "type": "insufficient_quota", "param": null, "code": null }}

### 复现操作
> 你之前干了什么，然后出现了错误呢？例如：
> 1. 正常完成本地部署
> 2. 在对话框中要求 ChatGPT “以LaTeX格式输出三角函数”
> 3. ChatGPT 输出部分内容后程序被自动终止

### 错误截图
> 如果可以，请提供错误的截图，如本地部署的网页截图与终端错误报告的截图。
![image](https://user-images.githubusercontent.com/37701943/226792955-2ae0a87e-bd52-4177-9a2f-e0661a2ab651.png)
### 终端（控制台）中的错误报告
> 如果可以，请复制终端中的主要错误报告。

```console
(请使用错误报告替换本行)
```

### 运行环境
> **请填写以下列表：**

 - OS: [e.g. Windows11 22H2]
 - Browser: [e.g. Chrome, safari]
 - Gradio version:
 - Python (或Python3) version:

### 其他
> 补充说明

**Comment by MZhao-ouo** [comment]
你是不是把配额用完了

**Comment by GaiZhenbiao** [comment]
你的配额用完了。

**Comment by little-rookie-at-UJS** [comment]
但是我没有用过啊

**Comment by Keldos-Li** [comment]
> 但是我没有用过啊

你可能把OpenAI提供的配额用完了（**或到期了**）。你可以在 https://platform.openai.com/account/usage 中查看您的用量和余额。

https://github.com/GaiZhenbiao/ChuanhuChatGPT/wiki/常见问题#you-exceeded-your-current-quota-please-check-your-plan-and-billing-details
