### ISSUE TITLE
[其他] AI回复的代码段内容混乱的问题

### ISSUE THREAD

**Issue by 1353604736** [GaiZhenbiao/ChuanhuChatGPT#279]
![catsxp_screenshot](https://user-images.githubusercontent.com/12869582/226793668-d002002b-e03d-40a4-b827-e687083eaf0d.png)

**Comment by Keldos-Li** [comment]
Duplicate with 
- #218 

-------

另外应该已经在最新的代码中被解决了。请尝试更新。

- 大幅度改进了输入输出解析 90d39c30417719e9b819b0ea78f7c62d7646441a  ([Chuanhu](https://github.com/GaiZhenbiao)).
