### ISSUE TITLE
[功能请求] 增加纯文本模式以能够复制LaTex代码

### ISSUE THREAD

**Issue by Sarfflow** [GaiZhenbiao/ChuanhuChatGPT#280]
### 该功能请求是否与某个问题相关？

我在进行有关于数学的提问时，注意到其中的 LaTex 公式总是会被渲染。但我需要复制这些公式的原始LaTex代码以用于写作。因此希望增加一个选项，让这些公式以纯文本的方式显示出来。

### 可能的解决办法

可以增加一个选项，允许用户选择是否以纯文本格式显示 LaTex 公式。如果用户选择这个选项，消息将以简单的文本形式显示公式，而不会进行渲染。

**Comment by Keldos-Li** [comment]
你可以以 markdown 格式下载聊天记录。

**Comment by Sarfflow** [comment]
感谢解答！不过这样不太方便。我自己加了一个Textbox组件解决了问题。
