### ISSUE TITLE
[本地部署] 出现something went wrong 提示

### ISSUE THREAD

**Issue by Heathlia** [GaiZhenbiao/ChuanhuChatGPT#281]
<img width="378" alt="image" src="https://user-images.githubusercontent.com/99574412/226797839-7d8add10-8c37-4ab0-a345-c447fc5cb63a.png">

**Comment by Keldos-Li** [comment]
看 README 的 [这部分](https://github.com/GaiZhenbiao/ChuanhuChatGPT#常见问题)。


Duplicate with 
- #48 
- #85
- 等等太多了
