### ISSUE TITLE
[功能请求] 自动隐藏侧边栏

### ISSUE THREAD

**Issue by HaleyCH** [GaiZhenbiao/ChuanhuChatGPT#282]
### 该功能请求是否与某个问题相关？
> 描述你遇到的问题~

昨天看评论区说UI不够成熟，感觉可能是因为第一眼不够简洁，还有就是说可能chatbot不是很方便使用。所以我想着可以自动隐藏侧边栏

### 可能的解决办法
> 如果可以，给出一个解决思路~

在我的 [newUI](https://github.com/HaleyCH/ChuanhuChatGPT-hch/tree/newUI) branch里已经有了基础的实现。我不确定是否要提交pr。或许可以先看看。

### 其他
> 补充说明

我目前写的版本十分简陋，也不方便后续添加固定侧边栏方案，如有好方法，请知会我。

**Comment by HaleyCH** [comment]
宽屏模式自动隐藏
窄屏默认显示
<img width="1541" alt="截屏2023-03-22 12 19 00" src="https://user-images.githubusercontent.com/29998135/226801268-873fcca7-01ee-44ec-9cd2-793839b0bad9.png">
<img width="1543" alt="截屏2023-03-22 12 19 09" src="https://user-images.githubusercontent.com/29998135/226801275-8d2aa93f-6dd9-4fd1-abe7-7ed9c1a04819.png">
<img width="495" alt="截屏2023-03-22 12 19 23" src="https://user-images.githubusercontent.com/29998135/226801289-594bf972-f960-40a1-ae0e-62901d57c708.png">

**Comment by Keldos-Li** [comment]
我还在想应该特意限制聊天窗口宽度呢_(:з」∠)_（是的，gradio也特意对主内容的宽度做了限制。）
过宽的聊天窗口的视觉体验是不利于用户接收信息的，也并不美观（这是个人观点）。

至于配置内容要不要自动隐藏……这是另一个问题。我个人会觉得不隐藏也挺好。

**Comment by HaleyCH** [comment]
对于限制聊天窗口宽度，我个人认为这是必要的。刚刚在看的时候也是感觉1000px左右maxWidth就够了。

但是配置内容还是我认为除了`填写api key`和`System prompt`，其他的还是隐藏比较好。
从开发者角度而言，肯定是一眼能看到越多有效信息越好。
但是就用户而言或许第一眼见到的界面过于复杂会影响体验和心情。

不过说到底，如果能找到一个在gradio里用js的好方法就没那么多事了（

### 补充（1000px左右的界面）：
<img width="1006" alt="截屏2023-03-22 13 04 56" src="https://user-images.githubusercontent.com/29998135/226807447-40fd2cdb-5587-41a7-b494-046a625452b4.png">

**Comment by HaleyCH** [comment]
加了固定任务栏选项，这下应该皆大欢喜了（（（

https://github.com/HaleyCH/ChuanhuChatGPT-hch/blob/b11a6ae45e8b0123cb0d43930795ba84edaba8b3/ChuanhuChatbot.py#L175

还有 是不是该开个js的branch做一下js文件加载支持。

<img width="571" alt="截屏2023-03-23 11 07 39" src="https://user-images.githubusercontent.com/29998135/227090858-97d42724-ff54-46d2-a60d-3383f8fd4312.png">

**Comment by GaiZhenbiao** [comment]
> 加了固定任务栏选项，这下应该皆大欢喜了（（（
> 
> https://github.com/HaleyCH/ChuanhuChatGPT-hch/blob/b11a6ae45e8b0123cb0d43930795ba84edaba8b3/ChuanhuChatbot.py#L175
> 
> 还有 是不是该开个js的branch做一下js文件加载支持。
> 
> <img alt="截屏2023-03-23 11 07 39" width="571" src="https://user-images.githubusercontent.com/29998135/227090858-97d42724-ff54-46d2-a60d-3383f8fd4312.png">

加载的话，参考css文件加载的实现，就是这么简单……

```
with open("custom.css", "r", encoding="utf-8") as f:
    customCSS = f.read()
```

**Comment by Keldos-Li** [comment]
？这样就能直接加载了吗？我好像前几天用这个方法试了没成功（

**Comment by GaiZhenbiao** [comment]
而且SD WebUI的实现里不是已经有加载文件的部分了

**Comment by GaiZhenbiao** [comment]
直接<del>抄</del>借鉴过来就行了

**Comment by HaleyCH** [comment]
就想把 [这里](https://github.com/HaleyCH/ChuanhuChatGPT-hch/blob/b11a6ae45e8b0123cb0d43930795ba84edaba8b3/ChuanhuChatbot.py#L441-L480) 给改一下

但是吧 这个项目结构得要考虑下怎么搭，因为有的js和css是高度耦合的，在考虑要不要写个类啥的

**Comment by HaleyCH** [comment]
btw 我开个draft pr会不会方便点

**Comment by GaiZhenbiao** [comment]
改成reload everything就行了，包括js和css。

**Comment by Keldos-Li** [comment]
额，新建了一个js分支 https://github.com/GaiZhenbiao/ChuanhuChatGPT/compare/js

emm 可能不应该由我来commit，所以我在 36e0fc616924c9328623ad0dd59b947f344b148d 把大家都列为了co-author \_(:з」∠)\_

**Comment by Olimiya** [comment]
是的，非常希望添加这个功能。
