### ISSUE TITLE
[本地部署] 上传pdf文件后，显示索引构建成功，但是返回None

### ISSUE THREAD

**Issue by Theseaway** [GaiZhenbiao/ChuanhuChatGPT#284]
### 错误描述
> 在本地搭建好服务后，上传pdf文件，询问chatGPT"这篇论文讲了什么内容"，返回空值

### 复现操作
> 你之前干了什么，然后出现了错误呢？例如：
> 1. 正常完成本地部署
> 2. 在对话框中要求 ChatGPT 对文件的内容进行理解

### 错误截图
返回内容如下
> ![image](https://user-images.githubusercontent.com/34154011/226806625-331b3d2f-aa11-484a-8f91-0321e0875611.png)

### 终端（控制台）中的错误报告
> 如果可以，请复制终端中的主要错误报告。

```console
langchain\llms\openai.py:169: UserWarning: You are trying to use a chat model. This way of initializing it is no longer supported. Instead, please use: `from langchain.chat_models import ChatOpenAI`
  warnings.warn(

INFO:root:输入为：你可以理解这本书的内容吗
INFO:root:构建索引中……（这可能需要比较久的时间）
INFO:root:找到了缓存的索引文件，加载中……
INFO:root:Question: 你可以理解这本书的内容吗
INFO:llama_index.token_counter.token_counter:> [query] Total LLM token usage: 0 tokens
INFO:llama_index.token_counter.token_counter:> [query] Total embedding token usage: 24 tokens
INFO:root:Response: None
INFO:root:Response: None
```

#### 桌面系统
 - OS: [e.g. Windows11 22H2]
 - Browser: Microsoft Edge 版本 111.0.1661.44 (正式版本) (64 位)

#### 运行依赖
- Gradio version: 3.23.0
- Python (或Python3) version: 3.10.9

**Comment by GaiZhenbiao** [comment]
某些PDF解析可能会出错。能提供一下PDF吗？

**Comment by MZhao-ouo** [comment]
无进展，closed
