### ISSUE TITLE
[本地部署] 正常部署后，不能打开网页，修改后提问就出现“Connection errored out.”

### ISSUE THREAD

**Issue by yhxiong** [GaiZhenbiao/ChuanhuChatGPT#287]
感谢提交 issue! 请尽可能完整填写以下信息，帮助我们更好地定位问题~ 
如果你不知道怎么填写，请先点击编辑框上方的“Preview”在预览中查看我们的说明，然后在空白行处填写信息~
问题：按所有步骤安装成功后，访问http://ip:7860 显示未发送任何数据。

### 错误描述
> 请简明描述该错误。另外，请注意替换issue标题中的“简短的错误描述”。
1：正常完成部署
     1）先安装了python版本3.11.2
     2）下载ChuanhuChatGPT最新包并解压
     3）执行了pip3 install -r requirements.txt
          更新了 gradio，当前版本号Version: 3.23.0
     4）python3 ChuanhuChatbot.py 显示结果如下：
[root@JovialSelfreliant-VM ChuanhuChatGPT]# python3 ChuanhuChatbot.py
INFO:root:获取模板文件名列表
INFO:root:获取文件名列表，目录为templates，文件类型为['.csv', 'json']，是否为纯文本列表True
INFO:root:加载模板文件1 中文Prompts.json，模式为2（0为返回字典和下拉菜单，1为返回下拉菜单，2为返回字典）
INFO:root:Loading template...
INFO:root:您的IP区域：United States。
/usr/local/python3/lib/python3.11/site-packages/gradio/deprecation.py:43: UserWarning: You have unused kwarg parameters in Row, please remove them: {'scale': 1}
  warnings.warn(
/usr/local/python3/lib/python3.11/site-packages/gradio/deprecation.py:43: UserWarning: You have unused kwarg parameters in Files, please remove them: {'multiple': True}
  warnings.warn(
INFO:root:获取模板文件名列表
INFO:root:获取文件名列表，目录为templates，文件类型为['.csv', 'json']，是否为纯文本列表True
INFO:root:获取模板文件名列表
INFO:root:获取文件名列表，目录为templates，文件类型为['.csv', 'json']，是否为纯文本列表True
INFO:root:获取模板文件名列表
INFO:root:获取文件名列表，目录为templates，文件类型为['.csv', 'json']，是否为纯文本列表True
INFO:root:加载模板文件1 中文Prompts.json，模式为1（0为返回字典和下拉菜单，1为返回下拉菜单，2为返回字典）
INFO:root:Loading template...
INFO:root:获取模板文件名列表
INFO:root:获取文件名列表，目录为templates，文件类型为['.csv', 'json']，是否为纯文本列表True
INFO:root:加载模板文件1 中文Prompts.json，模式为1（0为返回字典和下拉菜单，1为返回下拉菜单，2为返回字典）
INFO:root:Loading template...
INFO:root:获取历史记录文件名列表
INFO:root:获取文件名列表，目录为history，文件类型为['.json']，是否为纯文本列表True
INFO:root:获取历史记录文件名列表
INFO:root:获取文件名列表，目录为history，文件类型为['.json']，是否为纯文本列表True
INFO:root:
川虎的温馨提示：访问 http://localhost:7860 查看界面
Running on local URL:  http://127.0.0.1:7860

To create a public link, set `share=True` in `launch()`.

      5）保持服务器运行窗口不关闭，在另外一个网页访问http://ip:7860 显示结果如下：
该网页无法正常运作 未发送任何数据。
ERR_EMPTY_RESPONSE

### 复现操作
> 你之前干了什么，然后出现了错误呢？例如：
 1. 正常完成本地部署
 2。访问http://ip:7860失败。

### 错误截图
> 如果可以，请提供错误的截图，如本地部署的网页截图与终端错误报告的截图。
![Uploading image.png…]()

### 终端（控制台）中的错误报告
> 如果可以，请复制终端中的主要错误报告。

```console：python3 ChuanhuChatbot.py 
![image](https://user-images.githubusercontent.com/44085182/226813445-14e4497e-249b-4c3a-8c2f-949823b03bea.png)

```

#### 桌面系统
> **请填写以下列表：**

 - OS: 
CentOS Linux release 8.5.2111
![image](https://user-images.githubusercontent.com/44085182/226813057-f4b710d2-4cfc-4880-80ca-e521984913c4.png)

 - Browser: [ Chrome]

#### 运行依赖
> **请填写以下列表：**
> 你可以在终端中依次输入以下指令以查看软件版本：
> ```shell
> pip show gradio
> python --version
> ```
> （如果你使用Python3，请将`pip`替换为`pip3`，`python`替换为`python3`）

- Gradio version:3.23.0
- Python (或Python3) version:3.11.2
![image](https://user-images.githubusercontent.com/44085182/226811739-bbb78e98-4b45-4157-9878-d115a83dfa08.png)

### 其他
> 补充说明
1）防火墙的端口7860已打开。
![image](https://user-images.githubusercontent.com/44085182/226811461-7fc61927-ee29-4992-bba8-1ccab1c39e41.png)
2）服务器地址是美国ip，可以访问chat.openai.com/chat.
3)已申请了api_key 并写在api_key.txt中，这两个文件都填好了。
![image](https://user-images.githubusercontent.com/44085182/226812562-b74f1b7b-d1ed-47e9-856e-6656cf88a87a.png)

谢谢！

**Comment by yhxiong** [comment]
搞定了，是作者的ChuanhuChatbot.py代码出问题了。

在ChuanhuChatbot.py最后的一段中缺少服务器和端口的信息。
![image](https://user-images.githubusercontent.com/44085182/226815547-ff4b9843-d26b-4c11-9ddd-2f49d4fe9b4b.png)
修改为：
![image](https://user-images.githubusercontent.com/44085182/226815688-d39c146f-8ac3-43ba-8f97-4a2bc20b5ab9.png)
就成功了！！！

**Comment by yhxiong** [comment]
还没高兴2秒，网页显示成功，但一发送问题就出错了！
![image](https://user-images.githubusercontent.com/44085182/226816515-be0675cf-e46e-4c72-a439-4c8a17717611.png)

**Comment by GaiZhenbiao** [comment]
#89

**Comment by yhxiong** [comment]
多谢！成功了。
备注：
python3.11的routes.py路径发生了改变，在这个位置了：
/usr/local/python3/lib/python3.11/site-packages/gradio/routes.py
