### ISSUE TITLE
[其他] 代码不能以Latex显示，但是代码运行结果可以格式化输出

### ISSUE THREAD

**Issue by JinLongMY** [GaiZhenbiao/ChuanhuChatGPT#288]
感谢提交 issue! 请尽可能完整填写以下信息，帮助我们更好地定位问题~ 
如果你不知道怎么填写，请先点击编辑框上方的“Preview”在预览中查看我们的说明，然后点击“Write”在空白行处填写信息~

![1679464106630](https://user-images.githubusercontent.com/126970551/226813602-01c4dd0a-58df-43de-b439-0c63a8e3647a.jpg)

**Comment by GaiZhenbiao** [comment]
<img width="1003" alt="image" src="https://user-images.githubusercontent.com/51039745/226821470-1709122b-fe65-4b48-9ab7-9eab8b76427e.png">

请尝试升级到最新版的代码。

**Comment by Keldos-Li** [comment]
嘿 我发现了，这样CSS又要稍改一下hhh
