### ISSUE TITLE
[本地部署] Expecting value: line 1 column 1 (char 0)

### ISSUE THREAD

**Issue by wangpre** [GaiZhenbiao/ChuanhuChatGPT#289]
感谢提交 issue! 请尽可能完整填写以下信息，帮助我们更好地定位问题~ 
如果你不知道怎么填写，请先点击编辑框上方的“Preview”在预览中查看我们的说明，然后在空白行处填写信息~

### 错误描述
> 本地部署，M1 pro芯片，打开http://127.0.0.1:7860/ 填写apikey时报错了，已开全局代理
Expecting value: line 1 column 1 (char 0)

### 复现操作
> 你之前干了什么，然后出现了错误呢？例如：
> 1. 正常完成本地部署
> 2. 粘贴apikey就报错了

### 错误截图
> 如果可以，请提供错误的截图，如本地部署的网页截图与终端错误报告的截图。
<img width="1544" alt="image" src="https://user-images.githubusercontent.com/53291931/226812971-1458d39e-890f-47ce-b117-0ebd4d40c7ca.png">
<img width="1051" alt="image" src="https://user-images.githubusercontent.com/53291931/226813004-55f13937-fd29-413d-a31a-307c4cdc7a46.png">

### 终端（控制台）中的错误报告
> 如果可以，请复制终端中的主要错误报告。

```console
(请使用错误报告替换本行)
```

#### 桌面系统
> **请填写以下列表：**

 - OS: Mac Os  13.2.1 (22D68)  
 - Browser: Edge

#### 运行依赖
> **请填写以下列表：**
> 你可以在终端中依次输入以下指令以查看软件版本：
> ```shell
> pip show gradio
> python --version
> ```
> （如果你使用Python3，请将`pip`替换为`pip3`，`python`替换为`python3`）

- Gradio version: 3.23.0
- Python (或Python3) version:  Python 3.9.6

### 其他
> 补充说明

**Comment by GaiZhenbiao** [comment]
#48
