### ISSUE TITLE
[本地部署] 开启代理后总是Error

### ISSUE THREAD

**Issue by 631202349** [GaiZhenbiao/ChuanhuChatGPT#290]
> 感谢提交 issue! 请尽可能完整填写以下信息，帮助我们更好地定位问题~ 
> 请务必先查看 README 中是否已经对您的问题做出了解答。如果没有，请检索issue，查看有没有相同或类似的问题。如果您确信这是一个前人没有遇到的问题，欢迎提交该issue！注意，请编辑issue标题栏“简短的错误描述”部分，也请替换我们的issue模板中的原文。
> 如果您想问的是 `Something went wrong Expecting value: line 1 column 1 (char 0)`，请再好好看一遍 README！！

### 错误描述
操作系统是：ubuntu22.04

### 复现操作
你之前干了什么，然后出现了错误呢？例如：
1. 按照正常步骤安装依赖，在bot.py中添加了我的API
2. 运行时提示：ERROR: Could not install packages due to an EnvironmentError: Missing dependencies for SOCKS support.
3. 因为我在终端中开启了代理所以我安装了pysocks
4. 可以正常启动，没有报错
5. 访问本地网页，IP区域显示为US
6. 但是无法正常访问API，所有区域显示为ERROR
7. 代理经过测试没有问题，如果我unset代理，请求无法创建连接：requests.exceptions.ConnectionError: ('Connection aborted.', ConnectionResetError(104, 'Connection reset by peer'))
8. 开启代理后，程序正常启动，只是无法正常访问API，API也没有问题，余额是充足的
9. 在启动时会提示gr的组件告警，但这和API访问应该没有关系
### 错误截图
如果可以，请提供错误的截图，如本地部署的网页截图与终端错误报告的截图。

### 终端（控制台）中的错误报告
![Uploading image.png…]()
![Uploading image.png…]()

```console
python3 ChuanhuChatbot.py
INFO:root:获取模板文件名列表
INFO:root:获取文件名列表，目录为templates，文件类型为['.csv', 'json']，是否为纯文本列表True
INFO:root:加载模板文件1 中文Prompts.json，模式为2（0为返回字典和下拉菜单，1为返回下拉菜单，2为返回字典）
INFO:root:Loading template...
INFO:root:您的IP区域：United States。
/home/susliks/.local/lib/python3.8/site-packages/gradio/deprecation.py:43: UserWarning: You have unused kwarg parameters in Row, please remove them: {'scale': 1}
  warnings.warn(
/home/susliks/.local/lib/python3.8/site-packages/gradio/deprecation.py:43: UserWarning: You have unused kwarg parameters in Files, please remove them: {'multiple': True}
  warnings.warn(
INFO:root:获取模板文件名列表
INFO:root:获取文件名列表，目录为templates，文件类型为['.csv', 'json']，是否为纯文本列表True
INFO:root:获取模板文件名列表
INFO:root:获取文件名列表，目录为templates，文件类型为['.csv', 'json']，是否为纯文本列表True
INFO:root:获取模板文件名列表
INFO:root:获取文件名列表，目录为templates，文件类型为['.csv', 'json']，是否为纯文本列表True
INFO:root:加载模板文件1 中文Prompts.json，模式为1（0为返回字典和下拉菜单，1为返回下拉菜单，2为返回字典）
INFO:root:Loading template...
INFO:root:获取模板文件名列表
INFO:root:获取文件名列表，目录为templates，文件类型为['.csv', 'json']，是否为纯文本列表True
INFO:root:加载模板文件1 中文Prompts.json，模式为1（0为返回字典和下拉菜单，1为返回下拉菜单，2为返回字典）
INFO:root:Loading template...
INFO:root:获取历史记录文件名列表
INFO:root:获取文件名列表，目录为history，文件类型为['.json']，是否为纯文本列表True
INFO:root:获取历史记录文件名列表
INFO:root:获取文件名列表，目录为history，文件类型为['.json']，是否为纯文本列表True
INFO:root:
川虎的温馨提示：访问 http://localhost:7860 查看界面
Running on local URL:  http://127.0.0.1:7860

To create a public link, set `share=True` in `launch()`.

```

#### 桌面系统
**请填写以下列表：**

 - OS: Ubuntu22.04
 - Browser:Chrome

#### 运行依赖
❯pip3 show gradio
Name: gradio
Version: 3.23.0
Summary: Python library for easily interacting with trained machine learning models
Home-page: None
Author: None
Author-email: Abubakar Abid <team@gradio.app>, Ali Abid <team@gradio.app>, Ali Abdalla <team@gradio.app>, Dawood Khan <team@gradio.app>, Ahsen Khaliq <team@gradio.app>, Pete Allen <team@gradio.app>, Ömer Faruk Özdemir <team@gradio.app>
License: None
Location: /home/susliks/.local/lib/python3.8/site-packages
Requires: httpx, altair, huggingface-hub, ffmpy, requests, markdown-it-py, huggingface-hub, fastapi, pyyaml, jinja2, orjson, matplotlib, typing-extensions, pydub, aiohttp, aiofiles, numpy, pillow, markupsafe, websockets, mdit-py-plugins, python-multipart, pydantic, semantic-version, uvicorn, fsspec, pandas
Required-by:

❯ python3 --version                                                           ⏎
Python 3.8.10

### 其他
补充说明

**Comment by 631202349** [comment]
在试用版中提示：JSON解析错误。请重置对话。收到的内容: "error": { "message": "'' is not of type 'object' - 'messages.2'", "type": "invalid_request_error", "param": null, "code": null }}，难道是我的API问题吗
![](https://api.onedrive.com/v1.0/shares/s!Auu4_u9Pm3cdsiJQBz50vmW9NfkL/root/content)

**Comment by 631202349** [comment]
试用版中可以正常使用了，说明API没有问题
![](https://api.onedrive.com/v1.0/shares/s!Auu4_u9Pm3cdsiPUZnsY5AqIT4bz/root/content)

**Comment by 631202349** [comment]
补一下正文挂掉的图
![](https://api.onedrive.com/v1.0/shares/s!Auu4_u9Pm3cdsiQuYrRX_HcxqbHL/root/content)
![](https://api.onedrive.com/v1.0/shares/s!Auu4_u9Pm3cdsiXtRCW9hVT66OhQ/root/content)

**Comment by 631202349** [comment]
尝试了 #217 将127添加到直连规则中，也无法解决问题
![](https://api.onedrive.com/v1.0/shares/s!Auu4_u9Pm3cdsia_Xv82DSVc6Xvh/root/content)

**Comment by Keldos-Li** [comment]
README中里提供的“你的代理规则”那几个字，试试使用GLOBAL而不是小飞机符号替换……

**Comment by 631202349** [comment]
代理规则那里应该是没有问题，不过我也尝试了使用GLOBAL，没有任何变化
重启了我的虚拟机，竟然神奇的发现报错变成了Something Went Wrong，尝试了README中的方法：
* 添加127.0.0.1到规则中
* 重装urllib3
* 开启TUN模式
以上方法均无效，并且我的终端中没有任何报错输出
同时我在相同环境中使用python调用openai库使用api，可以正常返回，排除了API被墙的可能性
![](https://api.onedrive.com/v1.0/shares/s!Auu4_u9Pm3cdsifyjEuxzn5L2znn/root/content)
![](https://api.onedrive.com/v1.0/shares/s!Auu4_u9Pm3cdsigpkWYNFwu7DiWc/root/content)
![](https://api.onedrive.com/v1.0/shares/s!Auu4_u9Pm3cdsimDBHzKbl8fWdx-/root/content)
![](https://api.onedrive.com/v1.0/shares/s!Auu4_u9Pm3cdsipggTnR5nSPNvHg/root/content)
![](https://api.onedrive.com/v1.0/shares/s!Auu4_u9Pm3cdsitOs0kNXpqFRHZv/root/content)

**Comment by niuwan1** [comment]
@631202349 一样的处理，一样的问题。

添加127.0.0.1到规则中
重装urllib3
开启TUN模式
        以上方法均无效，并且我的终端中没有任何报错输出
        同时我在相同环境中使用python调用openai库使用api，可以正常返回，排除了API被墙的可能性

**Comment by GaiZhenbiao** [comment]
请自行解决。我不想再回答关于代理的问题了。
