### ISSUE TITLE
[本地部署] 启动后报错 localhost not accessible

### ISSUE THREAD

**Issue by dufu1991** [GaiZhenbiao/ChuanhuChatGPT#291]
本地部署，启动了，看到 川虎的温馨提示：访问 http://localhost:7860 查看界面 
网页也能打开一下，然后立即就报错了。

Traceback (most recent call last):
  File "/Users/dufu/Downloads/ChuanhuChatGPT-main/ChuanhuChatbot.py", line 451, in <module>
    demo.queue().launch(share=False, favicon_path="./assets/favicon.png")  # 改为 share=True 可以创建公开分享链接
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/gradio/blocks.py", line 1514, in launch
    raise ValueError(
ValueError: When localhost is not accessible, a shareable link must be created. Please set share=True.

**Comment by fuxin123z** [comment]
?

**Comment by MZhao-ouo** [comment]
长时间无回复，Closed

**Comment by Accurio** [comment]
如果使用代理服务器，需要设置 `HTTP_PROXY`、`HTTPS_PROXY` 和 `NO_PROXY` 环境变量。

```Python
import os
from urllib.request import getproxies

proxies = getproxies()
os.environ["http_proxy"]  = proxies["http"]
os.environ["https_proxy"] = proxies["https"]
os.environ["no_proxy"]    = "localhost, 127.0.0.1/8, ::1"
```
