### ISSUE TITLE
[功能请求] 简明描述你想要增加的功能

### ISSUE THREAD

**Issue by jarrywen** [GaiZhenbiao/ChuanhuChatGPT#295]
### 该功能请求是否与某个问题相关？
> 我不想每次访问都要输入api key，最好可以把api key保存到本地

### 可能的解决办法
> 
方案1:api key放在url上，如https://huggingface.co/spaces/JohnSmith9982/ChuanhuChatGPT/?key=xxxx
方案2:api key保存在cookie或者浏览器的storage上
### 其他
> 建议用第一种方案，虽然不是很安全，但是方便更重要😄
新手，自己也搞了半天，无法在页面初始化的时候，获取到key，用gr.block的更加找不到地方处理。

**Comment by Keldos-Li** [comment]
请参考 README 中安装教程第2步中的方法3:

3. 在文件中设定默认密钥、用户名密码
这样设置的密钥可以在拉取项目更新之后保留。

在项目文件夹中新建这两个文件：api_key.txt 和 auth.json。

在api_key.txt中填写你的API-Key，注意不要填写任何无关内容。

在auth.json中填写你的用户名和密码。

```
{
"username": "用户名",
"password": "密码"
}
```

**Comment by jarrywen** [comment]
写在api_key.txt有两个问题：
1.是访问https://huggingface.co/spaces/JohnSmith9982/ChuanhuChatGPT，可以看到api_key.txt文件内容，就暴露了
2.网站给多人使用的时候，回收api_key，还得修改api_key.txt
