### ISSUE TITLE
[本地部署] 上传文件后未获得索引后的回答

### ISSUE THREAD

**Issue by tulk** [GaiZhenbiao/ChuanhuChatGPT#296]
上传文件后，要求bot输出文档主要内容，bot反馈:
"很抱歉，我无法获取你的本地文件或上传的文档。你需要提供文档的名称或者给出相关链接，我才能够帮助你了解它的内容。"

### 复现操作
按照步骤部署的，
然后在登录界面发现界面没有渲染且无法进入，查了issues之后使用 pip3 install gradio==3.21.0 命令后成功进入
然后上传docx文档，要求bot总结文档主旨
获得以上反馈

**Comment by Keldos-Li** [comment]
再有人标题写“简短的错误描述”不改我真的要自闭了。模板里写的东西都不看的么。。。。

请提供更多信息，看看终端中输出是什么。
