### ISSUE TITLE
[Docker] docker部署不带密码可以正常访问,带用户名和密码之后报错

### ISSUE THREAD

**Issue by vshen009** [GaiZhenbiao/ChuanhuChatGPT#300]
> 感谢提交 issue! 请尽可能完整填写以下信息，帮助我们更好地定位问题~ 
> 请务必先查看 README 中是否已经对您的问题做出了解答。如果没有，请检索issue，查看有没有相同或类似的问题。如果您确信这是一个前人没有遇到的问题，欢迎提交该issue！注意，请编辑issue标题栏“简短的错误描述”部分，也请替换我们的issue模板中的原文。

### 错误描述
带用户名和密码部署docker, 能正常登陆,后面点任何操作,都有一个报错,请看截图

### 复现操作
描述出现错误的操作步骤。

### 错误截图
<img width="641" alt="image" src="https://user-images.githubusercontent.com/24835634/226861681-6b424a9b-37f2-4a6d-82a8-327b66951e5a.png">

### 终端（控制台）中的错误报告
终端没报错
```console
(请使用错误报告替换本行)
```

### 运行环境
**请填写以下列表：**

- OS: [e.g. Linux Ubuntu]
- Docker version:
- Server: Docker Engine - Community
 Engine:
  Version:          23.0.1
  API version:      1.42 (minimum version 1.12)
  Go version:       go1.19.5
  Git commit:       bc3805a
  Built:            Thu Feb  9 19:46:47 2023
  OS/Arch:          linux/amd64
  Experimental:     false
 containerd:
  Version:          1.6.18
  GitCommit:        2456e983eb9e37e47538f59ea18f2043c9a73640
 runc:
  Version:          1.1.4
  GitCommit:        v1.1.4-0-g5fd4c4d
 docker-init:
  Version:          0.19.0
  GitCommit:        de40ad0
- Gradio version:
- Python (或Python3) version:

### 其他
补充说明

**Comment by Keldos-Li** [comment]
Duplicate with 
- #211 

-----

可通过更新gradio到3.23.0解决。
```shell
pip install gradio --upgrade --force-reinstall
```
