### ISSUE TITLE
启动不了

### ISSUE THREAD

**Issue by hi609** [GaiZhenbiao/ChuanhuChatGPT#301]
PS E:\下载\ChuanhuChatGPT-main> python ChuanhuChatbot.py
Traceback (most recent call last):
  File "E:\下载\ChuanhuChatGPT-main\ChuanhuChatbot.py", line 62, in <module>
    theme=gr.themes.Soft(
AttributeError: module 'gradio' has no attribute 'themes'
PS E:\下载\ChuanhuChatGPT-main>

**Comment by Keldos-Li** [comment]
Duplicate with 
- #228 

-----

更新gradio与其他依赖：
```
pip install -r requirements.txt --upgrade
```
