### ISSUE TITLE
[远程部署] 部署在VPS上，运行显示报错

### ISSUE THREAD

**Issue by usuku** [GaiZhenbiao/ChuanhuChatGPT#307]
Centos VPS上部署，运行时报错，信息如下

[centos@ip-xxx-xx-xx-xxx ChuanhuChatGPT]$ python ChuanhuChatbot.py
  File "ChuanhuChatbot.py", line 159
    placeholder=f"OpenAI API-key...",
                                   ^
SyntaxError: invalid syntax

**Comment by Keldos-Li** [comment]
Duplicate with 
- #215

-----
请升级python版本。
