### ISSUE TITLE
[BUG] 当使用索引功能时只会输出中文

### ISSUE THREAD

**Issue by oashua** [GaiZhenbiao/ChuanhuChatGPT#308]
> 感谢提交 issue! 请尽可能完整填写以下信息，帮助我们更好地定位问题~ 
> 如果您确信这是一个我们的 bug，而不是因为您的原因部署失败，欢迎提交该issue！如果您不能确定这是bug还是您的问题，请选择其他类型的issue模板。
> 注意，请编辑issue标题栏“简短的错误描述”部分，也请替换我们的issue模板中的原文。

### 错误描述
问题和索引文件都是英文，会输出中文，但是同样的无索引英文问题回答是英文

### 复现操作
你之前干了什么，然后出现了bug呢？例如：
1. 正常使用

### 错误截图
![image](https://user-images.githubusercontent.com/58935410/226899699-b3ac6718-8f0f-4017-b466-f8b5cc3ef15d.png)

### 终端（控制台）中的错误报告
如果可以，请复制终端中的主要错误报告。

```console
(请使用错误报告替换本行)
```

### 运行环境
**请填写以下列表：**

 - Browser: huggingface

### 其他
补充说明

**Comment by MZhao-ouo** [comment]
最新版本更新语言选择功能
