### ISSUE TITLE
[Docker] 部署docker后报错`Connection errored out`

### ISSUE THREAD

**Issue by nashor1** [GaiZhenbiao/ChuanhuChatGPT#309]
使用如下命令构建docker容器
docker run -d --name chatgpt \
	-e my_api_key="" \
	-e USERNAME="" \
	-e PASSWORD="" \
	-v ~/chatGPThistory:/app/history \
	-p 7860:7860 \
	--net=host tuchuanhuhuhu/chuanhuchatgpt:latest
vps里面有全局代理部署所以使用--net=host参数部署docker容器部署之后成功访问页面
![image](https://user-images.githubusercontent.com/115065774/226910900-36d3f0ed-ffa7-480c-9fe1-6302c81d866e.png)
发送信息error
![image](https://user-images.githubusercontent.com/115065774/226910525-052c391a-7d72-4924-b8a4-798545b64f67.png)

**Comment by Keldos-Li** [comment]
请参考
- #89

和 #89 中可见 reference 的所有issue。

**Comment by Keldos-Li** [comment]
久无回复。
请尝试更新并看看其他ISSUE与Discussion。
