### ISSUE TITLE
字符串问题，不知道是这个模型的问题还是软件的问题

### ISSUE THREAD

**Issue by slideslide** [GaiZhenbiao/ChuanhuChatGPT#31]
if __name__ == '__main__':
    text().run()会被变成if name == ‘main’:
text().run()，并且很多符号的输出都有问题。

**Comment by slideslide** [comment]
看起来是因为支持markdown语法导致的

**Comment by GaiZhenbiao** [comment]
最新版脚本应该修复了这个问题

**Comment by slideslide** [comment]
> 最新版脚本应该修复了这个问题

感谢

**Comment by slideslide** [comment]
> 最新版脚本应该修复了这个问题

# 我尝试了最新版脚本，但依旧有这个问题，所有的符号都被转义成markdown语法了。就像这个文本框一样。

**Comment by slideslide** [comment]
网页源代码如下：<br>
" if "
<strong>name</strong>
“ == ‘"
<strong>main</strong>
”':“
<br>
"textPic().run()"
<br>
