### ISSUE TITLE
[BUG] 上传索引文件後，之後整個GUI都BUG了

### ISSUE THREAD

**Issue by NitcanKen** [GaiZhenbiao/ChuanhuChatGPT#311]
> 感谢提交 issue! 请尽可能完整填写以下信息，帮助我们更好地定位问题~ 
> 如果您确信这是一个我们的 bug，而不是因为您的原因部署失败，欢迎提交该issue！如果您不能确定这是bug还是您的问题，请选择其他类型的issue模板。
> 注意，请编辑issue标题栏“简短的错误描述”部分，也请替换我们的issue模板中的原文。

### 错误描述
ERROR:asyncio:Task exception was never retrieved
future: <Task finished name='jn9q6iairo_2' coro=<Queue.process_events() done, defined at C:\Users\asdzx\AppData\Local\Programs\Python\Python310\lib\site-packages\gradio\queueing.py:343> exception=AttributeError("'AsyncRequest' object has no attribute '_json_response_data'")>
但終端還能輸出最後一次。
再輸入一次就直接 遠端主機已強制關閉一個現存的連線。

### 复现操作
上传索引文件，並使用它

### 错误截图
![image](https://user-images.githubusercontent.com/74598580/226945920-96ff494b-7be8-437a-b31a-571cc8c86e67.png)
![image](https://user-images.githubusercontent.com/74598580/226946396-4eca1a42-c149-4d1e-90fd-44bf24fb6ac3.png)
![image](https://user-images.githubusercontent.com/74598580/226947170-ef17d7b8-3103-42a0-a88c-a4595d559cf9.png)

### 终端（控制台）中的错误报告

```console
ERROR:asyncio:Task exception was never retrieved
future: <Task finished name='jn9q6iairo_2' coro=<Queue.process_events() done, defined at C:\Users\asdzx\AppData\Local\Programs\Python\Python310\lib\site-packages\gradio\queueing.py:343> exception=AttributeError("'AsyncRequest' object has no attribute '_json_response_data'")>
```

### 运行环境
**请填写以下列表：**

 - OS: [e.g. Windows11 22H2]
 - Browser: [e.g. Chrome, safari]
 - Gradio version:
 - Python (或Python3) version:

### 其他
补充说明

**Comment by Keldos-Li** [comment]
尝试更新我们的脚本和所有依赖，尤其是gradio。
