### ISSUE TITLE
回答中的有序列表序号全是1

### ISSUE THREAD

**Issue by panlina** [GaiZhenbiao/ChuanhuChatGPT#312]
### 错误描述
回答中的有序列表序号全是1。在别的客户端没有遇见过，怀疑是渲染列表的问题。在devtool可以看到列表的每个项目被渲染为了一个`<ol>`（应该是列表被渲染为`<ol>`，每个项目被渲染为`<li>`）。

### 复现操作
问一个会回答有序列表的问题，比如怎样做某件事的步骤。

### 错误截图
<img width="629" alt="image" src="https://user-images.githubusercontent.com/18240847/226973104-37f7abae-7228-4376-848b-5a4675578939.png">

### 运行环境
 - Browser: Chrome

**Comment by Keldos-Li** [comment]
21号的代码确实有这个bug，但在当天晚上已经被修复了。请更新最新的代码。

- #235
