### ISSUE TITLE
[功能请求] 保留发送失败的文本

### ISSUE THREAD

**Issue by yhweb** [GaiZhenbiao/ChuanhuChatGPT#321]
### 该功能请求是否与某个问题相关？
打开页面 发送问题文本 这时候如果返回error 发送的文本也不显示  刷新后 文本还要手动打一边 感觉有点傻乎乎的

### 可能的解决办法
能不能做成像qq那样 发送失败仍然显示发送的文本  这样就能复制 或者刷新后再次粘贴发送 不用在手动打一遍

**Comment by Keldos-Li** [comment]
应该大概好久之前就解决了👾
