### ISSUE TITLE
README中的clash代码报错，无法切换到配置文件

### ISSUE THREAD

**Issue by KingDariaDu** [GaiZhenbiao/ChuanhuChatGPT#322]
![image](https://user-images.githubusercontent.com/50005109/227105061-132e8617-db06-4a8f-bc69-4838fcdfd697.png)
![image](https://user-images.githubusercontent.com/50005109/227105082-ec093767-1a12-4d79-8db5-f17dcc09c668.png)

**Comment by LeeJianbo** [comment]
你弄好了没

**Comment by MZhao-ouo** [comment]
你得把”你的代理规则“改成自己的呀

**Comment by KingDariaDu** [comment]
> 你得把"你的代理规则"改成自己的呀
需要改成什么内容，我第一次使用clash

**Comment by Keldos-Li** [comment]
前往讨论：
- #328
