### ISSUE TITLE
[其他] 使用Hugging Face部署到私人空间后，app页白屏

### ISSUE THREAD

**Issue by B416-JAFLY** [GaiZhenbiao/ChuanhuChatGPT#323]
### 错误描述
使用Hugging Face部署到私人空间后，app页白屏，没有界面显示

### 复现操作

打开一键部署链接，点击
![image](https://user-images.githubusercontent.com/90920682/227110094-60279035-ff74-49a7-875a-33ac5def1414.png)
后等待至部署完成，我的私人空间里出现一个复制；

### 错误截图
![image](https://user-images.githubusercontent.com/90920682/227110226-9aa8c92a-e8a6-4b49-bc8c-189ba58e13a1.png)

### 运行环境

 - OS: [Windows11 22H2]
 - Browser: [edge 111]

**Comment by Keldos-Li** [comment]
huggingface的私人space有各种限制和问题，如无法在safari中使用等，改成公共space应该就没有问题了。

不管怎样，我们无法解决该问题。
