### ISSUE TITLE
如果使用nginx进行反向代理时出现Something Went Wrong如何进行配置

### ISSUE THREAD

**Issue by KaiChiu-Lui** [GaiZhenbiao/ChuanhuChatGPT#330]
up要不建一个交流群呗。
看到readme说127.0.01被代理时会出现这个错误。但如果用nginx用反向代理的话就是对本机的ip进行代理啊，请问这种情况下应该怎么配置Nginx|ChuanhuGPT.py
PS:用nginx进行反向代理是因为生成的共享链接网速太卡了，所以部署了台海外服务器，利用nginx进行反向代理到应用时，能进入并看到页面，但是使用任何按钮就会出现Something Went Wrong

**Comment by GaiZhenbiao** [comment]
看Readme和其他issue

**Comment by Keldos-Li** [comment]
- #161
- #89
