### ISSUE TITLE
[本地部署] 加载完聊天记录的代码相关回复还是会文本错乱，夹杂代码

### ISSUE THREAD

**Issue by 1353604736** [GaiZhenbiao/ChuanhuChatGPT#331]
![catsxp_screenshot](https://user-images.githubusercontent.com/12869582/227131227-b3667e4a-5add-48c6-9bfa-ad28597fc942.png)

**Comment by hua-hua666** [comment]
同样是这个问题，代码显示乱码，很影响体验

**Comment by GaiZhenbiao** [comment]
新版代码修复了这个问题
