### ISSUE TITLE
[Docker] 2023-3-23 latest docker版本，docker内重启python ChuanghuChatbot.py出错

### ISSUE THREAD

**Issue by Alexzspace** [GaiZhenbiao/ChuanhuChatGPT#335]
启动docker成功后，进入容器打算修改一下python内容和html内容，修改好后在容器内重新python3 ChuanhuChatBot.py
出错
显示7860端口占用

在容器内尝试kill -9 1  也不行，杀不死docker进程

请问通过docker启动修改完后想重启py该如何操作呢

**Comment by xmlv** [comment]
没有特别好的没办法，如果机器上没有太多其他重要进程的话，重启吧
