### ISSUE TITLE
[其他]深色模式后看不清ChatGPT说的话

### ISSUE THREAD

**Issue by kylechandev** [GaiZhenbiao/ChuanhuChatGPT#336]
> 感谢提交 issue! 请尽可能完整填写以下信息，帮助我们更好地定位问题~ 
> 请务必先查看 README 中是否已经对您的问题做出了解答。如果没有，请检索issue，查看有没有相同或类似的问题。如果您确信这是一个前人没有遇到的问题，欢迎提交该issue！注意，请编辑issue标题栏“简短的错误描述”部分，也请替换我们的issue模板中的原文。

### 错误描述
一键部署到Hugging Face后，如果Mac切换到深色模式，这时候Chrome也自动换到深色模式，然后就出现了如标题描述的现象（2023.3.23 19:08新部署），之前本地部署的时候也有这个情况。不知道是不是我的问题

搜了一下issues，发现有之前有人提过[#246](https://github.com/GaiZhenbiao/ChuanhuChatGPT/issues/246)，不过我这里尝试了后貌似还是存在问题

### 错误截图
<img width="942" alt="截屏2023-03-23 下午7 05 24" src="https://user-images.githubusercontent.com/41043115/227185589-3f638b37-5272-481e-8d8c-b949c27dd715.png">

### 运行环境
Mac, Chrome, Hugging Face部署

**Comment by GaiZhenbiao** [comment]
现在修复了huggingface版本的这个bug。感谢反馈！

**Comment by Keldos-Li** [comment]
其实我昨天提过了hhh
- https://github.com/GaiZhenbiao/ChuanhuChatGPT/issues/244#issuecomment-1479631786
