### ISSUE TITLE
[BUG] 使用 Docker Tag 23.03.23 带“认证参数”创建并启动容器，功能无法使用。

### ISSUE THREAD

**Issue by jackrao168** [GaiZhenbiao/ChuanhuChatGPT#339]
使用 Docker Tag 23.03.23，带“认证参数”创建并启动容器，能打开登录页面，能正常输入创建容器时设定的用户名及密码登录，登录后页面正常展示，但只要向ChatGPT提问，或者点击“新的话题”按钮，就会报错。
报错提示：“Something went wrong Connection errored out.”

如果创建容器时，不带“认证参数”，则功能正常。

**Comment by debugAllTheTime** [comment]
同样的问题+1

**Comment by Keldos-Li** [comment]
- #89

**Comment by jackrao168** [comment]
根据 #89 提供的方法问题已经解决。
