### ISSUE TITLE
[BUG] 代码块中的__XXX__被错误地渲染为加粗

### ISSUE THREAD

**Issue by wjcper2008** [GaiZhenbiao/ChuanhuChatGPT#340]
问题描述，Python代码输出__XXX__双下划线起止的代码(正文或代码块中)，都无法正确被解析为 字面量。而是被markdown渲染为加粗。

**Comment by slideslide** [comment]
> 问题描述，Python代码输出__XXX__双下划线起止的代码(正文或代码块中)，都无法正确被解析为 字面量。而是被markdown渲染为加粗。

不仅如此，还有很多其他markdown和代码有冲突的部分

**Comment by GaiZhenbiao** [comment]
最新版代码中应该已经解决了这个问题
