### ISSUE TITLE
[功能请求] ChatGPT自动处理文档

### ISSUE THREAD

**Issue by OYcedar** [GaiZhenbiao/ChuanhuChatGPT#341]
### 该功能请求是否与某个问题相关？
> 最近在机翻一个游戏，文本量很多，想着导出为XML文件后再依赖CHATGPT一句一句的翻译，
一句句处理太烦了，想问可不可以提供个自动化处理，ai回复的内容可以不用考虑。

### 可能的解决办法
> 如果可以，给出一个解决思路~
在翻译的时候，如果遇到token上限，直接重新对话再进行翻译，这个功能只能在本地运行。

**Comment by learnCodeON** [comment]
使用python里面的xpath、bs4.BeautifulSoup、正则表达式等技术能处理xml文件。这样能把你需要的文本提取到一个列表里面。在这之后，可以使用python控制鼠标，把列表里面的文本逐个放到翻译软件去翻译，做到自动化翻译。

**Comment by GaiZhenbiao** [comment]
不在计划中。
