### ISSUE TITLE
[其他] “You exceeded your current quota, please check your plan and billing details” 新注册的号没有免费额度

### ISSUE THREAD

**Issue by KKBBQLIU520199** [GaiZhenbiao/ChuanhuChatGPT#342]
### 错误描述
JSON解析错误。请重置对话。收到的内容: “error”: { “message”: “You exceeded your current quota, please check your plan and billing details.”, “type”: “insufficient_quota”, “param”: null, “code”: null }}

### 复现操作
1. 正常完成Hubgging Face、注册账号、复制空间、新建Key粘贴至Hubgging Face API-Key位置
2. 随机提问一个问题-点击发送

### 错误截图
![image](https://user-images.githubusercontent.com/128715639/227266423-74421471-9778-40b1-bbc0-487bf50cb4af.png)

### 运行环境
**请填写以下列表：**

 - OS: Windows10
 - Browser: Edge

### 其他
之前也在Openai translator 用到API-Key，也是这个错误提醒，提醒配额不足，但我是新账户，应该是有$18美元额度吧，但是我查看Openai空间里的Usage：本月使用记录是0，但是Free trial usage也是“You've used $0.00 out of the $0.00 total credit granted to you.”
我不明白怎么是0免费额度。
感谢了解的朋友解答

**Comment by woodchen-ink** [comment]
登录openai网站，查看额度，我3月上半旬申请的新账号就只有5美元额度了

**Comment by chauncyzhang** [comment]
估计是你买的号已经被号贩子用完了

**Comment by KKBBQLIU520199** [comment]
> 估计是你买的号已经被号贩子用完了

我查了三月使用记录是0，额度也是0/0，按理说要不就是0/18或者0/5吧，这样表示额度已用完，而且三月是没有使用记录的。 难道说这个额度是一次性的，不是每个月刷新的

**Comment by learnCodeON** [comment]
账户余额需要到这里看。
<img width="867" alt="屏幕截图_2023-03-24" src="https://user-images.githubusercontent.com/127178633/227413222-87916988-7470-4efe-bdf8-934666277168.png">

**Comment by zhanglong1117** [comment]
你注册的手机号是在接码网站上接的话，那就有可能是这个手机号不是第一次注册的了，我之前也遇到过

**Comment by KKBBQLIU520199** [comment]
> 账户余额需要到这里看。
> <img alt="屏幕截图_2023-03-24" width="867" src="https://user-images.githubusercontent.com/127178633/227413222-87916988-7470-4efe-bdf8-934666277168.png">

是的，我看到就是这里0/0了，感谢

**Comment by KKBBQLIU520199** [comment]
> 你注册的手机号是在接码网站上接的话，那就有可能是这个手机号不是第一次注册的了，我之前也遇到过

我猜也是，嫌麻烦直接买了，所以没料到这个坑。

**Comment by GaiZhenbiao** [comment]
与本项目无关

**Comment by newmou** [comment]
> 账户余额需要到这里看。 <img alt="屏幕截图_2023-03-24" width="867" src="https://user-images.githubusercontent.com/127178633/227413222-87916988-7470-4efe-bdf8-934666277168.png">
请问我有额度也还是报相同的错误怎么办呢？
<img width="546" alt="image" src="https://github.com/GaiZhenbiao/ChuanhuChatGPT/assets/49665616/d7774336-c284-4941-9272-5c3776e3fe93">

**Comment by Keldos-Li** [comment]
@newmou 你的免费额度在6月1日到期了。

![image](https://github.com/GaiZhenbiao/ChuanhuChatGPT/assets/23137268/788dc9b0-3a3f-443e-a286-5d8d4283a333)

**Comment by woodchen-ink** [comment]
> 如何购买？

https://woodchen.ink/1241.html，绑卡教程
