### ISSUE TITLE
[BUG] 在使用auth=(账号,密码) 的时候 ws 链接异常导致无法正常使用

### ISSUE THREAD

**Issue by xgd16** [GaiZhenbiao/ChuanhuChatGPT#347]
[BUG] 在使用auth=(账号,密码) 的时候 ws 链接异常导致无法正常使用

**Comment by GaiZhenbiao** [comment]
请使用Nginx反向代理

**Comment by xgd16** [comment]
<img width="1297" alt="image" src="https://user-images.githubusercontent.com/42709773/227440054-ffab5e13-137d-4e1a-962f-d7aa4fe48e32.png">
使用的正是nginx反向代理 这是我的配置

**Comment by GaiZhenbiao** [comment]
nginx.conf里也需要配置

**Comment by xgd16** [comment]
这个就是 nginx.conf 的配置内容
