### ISSUE TITLE
[功能请求] 添加多个本地验证用户

### ISSUE THREAD

**Issue by wuchanghui5220** [GaiZhenbiao/ChuanhuChatGPT#349]
### 该功能请求是否与某个问题相关？
> 是否可以添加多个本地验证的用户，并在history 目录创建以用户命名的子目录，保存各个用户的会话记录。每个用户只可以访问自己的会话记录。

主要是解决局域网内其他用户的上网代理问题，ChatGPT账号问题。

### 可能的解决办法
> 如果可以，给出一个解决思路~

### 其他
> 补充说明

**Comment by fredyj** [comment]
貌似要开发用户系统，权限体系
集成ldap
并且用户数据存储，集成到sqlite里面

**Comment by GaiZhenbiao** [comment]
暂无此方面的计划。

**Comment by sgpublic** [comment]
同请求此功能，希望开发大大后续考虑一下 ❤️
