### ISSUE TITLE
项目运行1天后请求gpt的api失败

### ISSUE THREAD

**Issue by magehsiii** [GaiZhenbiao/ChuanhuChatGPT#35]
提示：
![image](https://user-images.githubusercontent.com/127069746/223009219-c73c9725-dc9d-48ca-934a-64751bc26355.png)
重新运行项目后可以正常访问，看报错是openai.error.APIConnectionError: Error communicating with OpenAI: ('Connection aborted.', ConnectionResetError(10054, '远程主机强迫关闭了一个现有的连接。', None, 10054, None))

**Comment by GaiZhenbiao** [comment]
尝试一下最新版脚本？看看问题是否仍然存在。

**Comment by GaiZhenbiao** [comment]
试试最新的脚本。这个issue先关闭了。
