### ISSUE TITLE
运行报错

### ISSUE THREAD

**Issue by ChenziSC** [GaiZhenbiao/ChuanhuChatGPT#351]
![image](https://user-images.githubusercontent.com/20588811/227438758-577665e7-a228-444e-bdef-679f3c221477.png)

**Comment by GaiZhenbiao** [comment]
更新依赖！

**Comment by GaiZhenbiao** [comment]
看最新的Readme，新增了使用官方源安装依赖的说明。请查看:)

**Comment by ChenziSC** [comment]
> 看最新的Readme，新增了使用官方源安装依赖的说明。请查看:)

解决了，感谢
