### ISSUE TITLE
[其他] 点击发送时一直提示“Something went wrong Connection errored out.”

### ISSUE THREAD

**Issue by sillyboy110** [GaiZhenbiao/ChuanhuChatGPT#352]
ubuntu 18 docker环境，点击发发送后就提示，“Something went wrong Connection errored out.”，怀疑是某个样式文件没加载，但一直没找到证据。在win10 pc上倒是能正常运行
![image](https://user-images.githubusercontent.com/1071192/227439635-41866a41-04df-4ff4-9cea-021082fd14ef.png)

**Comment by GaiZhenbiao** [comment]
看Readme！看其他Issue！
