### ISSUE TITLE
[BUG] java代码没有被全部放进代码块

### ISSUE THREAD

**Issue by 5yxcanwin** [GaiZhenbiao/ChuanhuChatGPT#353]
> 感谢提交 issue! 请尽可能完整填写以下信息，帮助我们更好地定位问题~ 
> 如果您确信这是一个我们的 bug，而不是因为您的原因部署失败，欢迎提交该issue！如果您不能确定这是bug还是您的问题，请选择其他类型的issue模板。
> 注意，请编辑issue标题栏“简短的错误描述”部分，也请替换我们的issue模板中的原文。

### 错误描述
返回的Java代码块中，java代码没有被全部放进代码块

### 复现操作
你之前干了什么，然后出现了bug呢？例如：
1. 正常完成本地部署
2. 在对话框中要求 ChatGPT 以Java写出快速排序
3. ChatGPT 输出的代码段没有被全部包裹

### 错误截图
<img width="863" alt="企业微信截图_16796385611386" src="https://user-images.githubusercontent.com/86546923/227440571-6960a76c-fb0a-41bf-b568-01bd9e7bf3d8.png">

### 终端（控制台）中的错误报告
终端没有报错，返回正常
<img width="466" alt="企业微信截图_16796385897106" src="https://user-images.githubusercontent.com/86546923/227440637-889f5314-c0d2-4951-86a3-4f2722baf0b2.png">

### 运行环境
**请填写以下列表：**

 - OS: [e.g. Windows11 22H2]linux
 - Browser: [e.g. Chrome, safari]e.g.
 - Gradio version:未指定版本
 - Python (或Python3) version:Python3.8

**Comment by Keldos-Li** [comment]
请更新我们的最新项目代码。该问题已在之前被修复。
<img width="1191" alt="image" src="https://user-images.githubusercontent.com/23137268/227453691-479a38b7-e74b-4d59-b592-db98e5e125cc.png">
如更新后仍有问题请继续回复本issue，并提供有问题的对话的json格式对话历史记录。
