### ISSUE TITLE
 [远程部署] 使用Nginx Proxy Manager报错 Something went wrong Connection errored out

### ISSUE THREAD

**Issue by xianglongwei** [GaiZhenbiao/ChuanhuChatGPT#354]
> 感谢提交 issue! 请尽可能完整填写以下信息，帮助我们更好地定位问题~ 
> 请务必先查看 README 中是否已经对您的问题做出了解答。如果没有，请检索issue，查看有没有相同或类似的问题。如果您确信这是一个前人没有遇到的问题，欢迎提交该issue！注意，请编辑issue标题栏“简短的错误描述”部分，也请替换我们的issue模板中的原文。

### 错误描述
在使用npm代理地址时候出现报错Something went wrong Connection errored out 服务端无报错。
![image](https://user-images.githubusercontent.com/52027227/227441723-737323d8-6a45-4bc3-8271-360591cb37bb.png)

### 复现操作
修改源码最后一项都无法进行代理
![image](https://user-images.githubusercontent.com/52027227/227441921-38c79bbd-ecc7-416f-bba7-c96c5d9f6f47.png)

### 错误截图

![image](https://user-images.githubusercontent.com/52027227/227441723-737323d8-6a45-4bc3-8271-360591cb37bb.png)
### 终端（控制台）中的错误报告
无任何报错。
如果可以，请复制终端中的主要错误报告。

```console
index.37b24c07.js:4 WebSocket connection to 'ws://chatgpt.codeyour.top/queue/join' failed: 

```
![image](https://user-images.githubusercontent.com/52027227/227443551-49e336ac-a5a7-42fe-bc99-7950d5a4e5cc.png)

### 运行环境
**请填写以下列表：**

OS:ubuntu
Python 3.10.9

### 其他
补充说明
公网IP就可以正常访问，代理后就无法访问。不清楚应该怎么设置，使用最后nginx代理也是不行。

**Comment by kayeah82** [comment]
> 我出现同样的问题，可以正常登录。只是一对话就出现“Something went wrong Connection errored out ”

刚测试后，关闭认证就无此问题，开启认证就有。

**Comment by Garretqaq** [comment]
我也有同样的问题，用分享链接就可以访问但是用ip端口就不能访问
![1679716271090](https://user-images.githubusercontent.com/98604743/227690491-9527b7d2-e1ed-45f5-b848-b00ee6edb2e6.png)

**Comment by Keldos-Li** [comment]
看 [这里的](https://github.com/GaiZhenbiao/ChuanhuChatGPT/wiki/%E5%B8%B8%E8%A7%81%E9%97%AE%E9%A2%98#something-went-wrong-connection-errored-out) 参见

**Comment by Garretqaq** [comment]
谢谢已解决，采用nginx按照配置代理成https，后端访问就解决该问题
