### ISSUE TITLE
[功能请求] 在 requirements.txt 写入依赖版本信息

### ISSUE THREAD

**Issue by fiyen** [GaiZhenbiao/ChuanhuChatGPT#356]
### 该功能请求是否与某个问题相关？
> 描述你遇到的问题~

作者你好，项目非常棒，但是在requirements.txt中所有的依赖都没有版本信息，我在安装依赖时碰到了无穷无尽的import不存在模块的问题，有些通过重新安装某些模块解决了，有些因为不知道各模块之间的版本对应关系始终无法解决。比如，llama_index中langchain.schema和AI21模块不存在，怀疑是llama_index和langchain版本不对应造成的。

### 可能的解决办法
> 如果可以，给出一个解决思路~

希望补充所有依赖的版本信息

### 其他
> 补充说明

**Comment by Keldos-Li** [comment]
确实。最近这些库更新得都太不道德了……要疯了 
感觉现在好多issue都是依赖的问题。

我不是作者，但提供一个我目前能用的各个库的版本是
```
colorama            0.4.6
duckduckgo-search   2.8.5
gradio              3.22.1
langchain           0.0.105
llama-index         0.4.25
mdtex2html          1.2.0
Pygments            2.14.0
pypinyin            0.48.0
socksio             1.0.0
tiktoken            0.3.1
tqdm                4.65.0
```

可能太老了。得看看有没有更新但同时稳定的。

**Comment by GaiZhenbiao** [comment]
> 运行 `pip3 install -r requirements.txt` 一上来就报错：
> 
> ```
> Collecting gradio
>   Using cached gradio-3.23.0-py3-none-any.whl (15.8 MB)
> Collecting mdtex2html
>   Using cached mdtex2html-1.2.0-py3-none-any.whl (13 kB)
> Collecting pypinyin
>   Using cached pypinyin-0.48.0-py2.py3-none-any.whl (1.4 MB)
> ERROR: Could not find a version that satisfies the requirement tiktoken (from -r requirements.txt (line 4)) (from versions: none)
> ERROR: No matching distribution found for tiktoken (from -r requirements.txt (line 4))
> WARNING: You are using pip version 20.1.1; however, version 23.0.1 is available.
> You should consider upgrading via the '/Users/Versus/.pyenv/versions/3.7.9/bin/python3.7 -m pip install --upgrade pip' command.
> ```
> 
> 同上建议固定版本

你这个源里根本没有tiktoken。建议用官方源试试。

**Comment by fiyen** [comment]
> 确实。最近这些库更新得都太不道德了……要疯了 感觉现在好多issue都是依赖的问题。
> 
> 我不是作者，但提供一个我目前能用的各个库的版本是
> 
> ```
> colorama            0.4.6
> duckduckgo-search   2.8.5
> gradio              3.22.1
> langchain           0.0.105
> llama-index         0.4.25
> mdtex2html          1.2.0
> Pygments            2.14.0
> pypinyin            0.48.0
> socksio             1.0.0
> tiktoken            0.3.1
> tqdm                4.65.0
> ```
> 
> 可能太老了。得看看有没有更新但同时稳定的。
> 
> 另外大家怎么都喜欢改我issue模板的标题格式？……

试了一下，仍然不行，这个llama_index和langchain还是有问题，0.0.105和llama_index没有对应的版本。

**Comment by GaiZhenbiao** [comment]
如果找不到依赖项，建议使用pypi官方源：
```
pip config set global.index-url https://pypi.org/simple
```
