### ISSUE TITLE
[BUG] Huggingface部署以后显示“☹️发生了错误：API key长度不是51位，请检查是否输入正确。”，无法使用

### ISSUE THREAD

**Issue by althougha** [GaiZhenbiao/ChuanhuChatGPT#357]
如题，谢谢！

**Comment by Keldos-Li** [comment]
我靠，你还开个新的……开个新的吧，你里面该填的信息该改的信息也没填呀……
下次请用edit编辑你自己的issue comment
<img width="1123" alt="image" src="https://user-images.githubusercontent.com/23137268/227469340-e17d8942-06dc-46a8-8df0-46fb5b3eb0c3.png">


------

你在hugging face中填上api key了吗？？

**Comment by althougha** [comment]
收到，谢谢，我这里的问题，我以为duplicate以后直接就可以用了。
