### ISSUE TITLE
mac下使用docker无法启用share模式

### ISSUE THREAD

**Issue by yyihuan** [GaiZhenbiao/ChuanhuChatGPT#36]
# 问题描述
依赖冲突导致无法本地安装，使用了docker
但因为网络环境build不成功，我重新写了个dockerfile文件（换源，但针对arm处理器）。但是启动后发现，host模式不可用(docker不支持mac和win的host模式)，只能使用端口转发。但是并不清楚share所使用的端口号，无法实现公网访问功能。
另外建议提供一个docker-compose.yml，方便将日志和聊天记录输出到挂载点。

# 环境
macbook m1
docker
dockerfile
”“” Dockerfile
FROM ubuntu:20.04
RUN sed -i 's/ports.ubuntu.com/mirrors.ustc.edu.cn/g' /etc/apt/sources.list
RUN sed -i 's/focal/jammy/g' /etc/apt/sources.list
RUN apt-get update && apt-get install -y python3 python3-pip build-essential
RUN pip config set global.index-url https://mirrors.aliyun.com/pypi/simple
RUN pip install openai gradio markdown
ENV PATH=/root/.local/bin:$PATH
COPY . /app
WORKDIR /app
ENV my_api_key empty
CMD ["python3", "-u", "ChuanhuChatbot.py", "2>&1", "|", "tee", "/var/log/application.log"]
“”“

# 输出
”“”
Running on local URL: [http://0.0.0.0:80](http://0.0.0.0/)

Could not create share link. Please check your internet connection or our status page: https://status.gradio.app/
“”“

**Comment by iskoldt-X** [comment]
把python 脚本这里改成，

demo.launch(server_name="0.0.0.0", server_port=80)

重新build, 然后是否可以实现端口转发？

仓库自动build 镜像已经在路上了。

**Comment by yyihuan** [comment]
> 

还是不行，这里主要问题应该是，share功能使用了web服务以外的端口去打洞。你给的样例里使用的是host模式，等价于映射了所有端口，自然没问题。但我使用的是mac，而docker在mac上不支持host，另外host模式本身并不安全（缺乏隔离），按说是需要尽量避免使用的。
另外我偷个懒不另开issue了，目前使用发现有一个问题是，生成的代码里，引号会使用中文引号，而不是英语的引号。

**Comment by iskoldt-X** [comment]
> > 
> 
> 还是不行，这里主要问题应该是，share功能使用了web服务以外的端口去打洞。你给的样例里使用的是host模式，等价于映射了所有端口，自然没问题。但我使用的是mac，而docker在mac上不支持host，另外host模式本身并不安全（缺乏隔离），按说是需要尽量避免使用的。 另外我偷个懒不另开issue了，目前使用发现有一个问题是，生成的代码里，引号会使用中文引号，而不是英语的引号。

把python 脚本最后一行改成这个：
demo.launch(server_name="0.0.0.0", server_port=80)

然后构建镜像，运行的时候使用 -p 指定端口，我实测了，可以使用。

试试我构建好的镜像：

docker run -d --name chat   -t  -e my_api_key="your api key here"  -p 567:80 iskoldt/chuanhuchatgpt:arm

**Comment by iskoldt-X** [comment]
@GaiZhenbiao 建议老哥直接把 server_name="0.0.0.0", server_port=7860 加到主线里面

**Comment by GaiZhenbiao** [comment]
现在默认运行的地址改成了`0.0.0.0`，端口没有显式设置（会有诡异的端口冲突问题），默认为`7860`。现在GitHub Actions已经部署成功了。感谢@iskoldt-X的贡献～
