### ISSUE TITLE
[功能请求] 使用在线搜索后，点击来源连接希望能另开一个网页

### ISSUE THREAD

**Issue by Owenfly** [GaiZhenbiao/ChuanhuChatGPT#360]
### 该功能请求是否与某个问题相关？
> 在线搜索后，想查看来源网址，直接在当前网页打开了，造成之前问的问题都没了

### 可能的解决办法
> 如果可以，给出一个解决思路~

### 其他
> 补充说明

**Comment by Keldos-Li** [comment]
Duplicate with: 
- https://github.com/GaiZhenbiao/ChuanhuChatGPT/issues/224#issuecomment-1477133856

但是先开着好了。

**Comment by GaiZhenbiao** [comment]
按住`command`(macOS)或者`Ctrl`(Windows)点击链接就好了。多大点事……
