### ISSUE TITLE
[BUG] 对话中发出带有html标签的内容会被浏览器渲染

### ISSUE THREAD

**Issue by SexySteak** [GaiZhenbiao/ChuanhuChatGPT#361]
### 错误描述
对话中使用html标签的内容会被浏览器渲染
比方说，我的问题中发出`<h1> 测试<h1/>`，发出去后会变成一个标题，其他标签同理

不过看起来数据被正确的发送了，后台也显示正确的数据，chatGPT也回复正常的回答。应该只是前端的问题

### 错误截图
![image](https://user-images.githubusercontent.com/86149525/227490637-bae49bea-18ca-4374-aaf2-f379e87bb5fe.png)

**Comment by GaiZhenbiao** [comment]
解决了
