### ISSUE TITLE
[BUG] “./assets/favicon.png” not exist.

### ISSUE THREAD

**Issue by fiyen** [GaiZhenbiao/ChuanhuChatGPT#366]
> 感谢提交 issue! 请尽可能完整填写以下信息，帮助我们更好地定位问题~ 
> 如果您确信这是一个我们的 bug，而不是因为您的原因部署失败，欢迎提交该issue！如果您不能确定这是bug还是您的问题，请选择其他类型的issue模板。
> 注意，请编辑issue标题栏“简短的错误描述”部分，也请替换我们的issue模板中的原文。
ChuanhuChatbot.py有几个favicon.ico写成了favicon.png，有几率触发错误。

### 错误描述
请简明描述该bug。

### 复现操作
你之前干了什么，然后出现了bug呢？例如：
1. 正常完成本地部署
2. 在对话框中要求 ChatGPT “以LaTeX格式输出三角函数”
3. ChatGPT 输出部分内容后程序被自动终止

### 错误截图
如果可以，请提供错误的截图，如本地部署的网页截图与终端错误报告的截图。

### 终端（控制台）中的错误报告
如果可以，请复制终端中的主要错误报告。

```console
(请使用错误报告替换本行)
```

### 运行环境
**请填写以下列表：**

 - OS: [e.g. Windows11 22H2]
 - Browser: [e.g. Chrome, safari]
 - Gradio version:
 - Python (或Python3) version:

### 其他
补充说明

**Comment by Keldos-Li** [comment]
@MZhao-ouo 出来背锅！（

**Comment by GaiZhenbiao** [comment]
@MZhao-ouo 出来背锅！（

**Comment by MZhao-ouo** [comment]
已修复

**Comment by GaiZhenbiao** [comment]
emm，我刚刚也推了个fix

**Comment by Keldos-Li** [comment]
？？你们这冲突的有点厉害（（
解决思路这么不一样的吗
