### ISSUE TITLE
输入长文本，按发送后会溢出 !

### ISSUE THREAD

**Issue by bentwnghk** [GaiZhenbiao/ChuanhuChatGPT#367]
![text_spill](https://user-images.githubusercontent.com/101241940/227525785-d0d59a52-bda2-4366-a6c2-0639bb36e460.png)

**Comment by GaiZhenbiao** [comment]
修复啦

**Comment by bentwnghk** [comment]
还有一个问题：不自然的换行
"autobiography" is one word
![unnatural_linebreak](https://user-images.githubusercontent.com/101241940/227535540-f7432445-187d-4c50-889c-1f2cc4bbac13.png)
