### ISSUE TITLE
编号列表1. 1. 1. …

### ISSUE THREAD

**Issue by bentwnghk** [GaiZhenbiao/ChuanhuChatGPT#369]
如果编号列表项目中包含子选项，则编号列表中的编号不正确
![numbered_list](https://user-images.githubusercontent.com/101241940/227535846-ebdbfd9d-3911-437c-9ee7-704d7f6b4a07.png)

**Comment by Keldos-Li** [comment]
能附一下json格式的对话历史记录吗

**Comment by Keldos-Li** [comment]
神奇，应该是列表中穿插换行问题导致的\ _(:з」∠)\_
<img width="1521" alt="image" src="https://user-images.githubusercontent.com/23137268/227545304-83869242-553d-46e1-8c09-454dad08ca5f.png">

这样确实会导致markdown认不出这是一个连续的列表。。。

**Comment by bentwnghk** [comment]
有办法可以解决这个问题吗？

**Comment by Keldos-Li** [comment]
目前几乎所有公开提供的markdown转html的 python 库都有各种各样的问题，川虎哥已经几乎完全手动重写了这部分的转换函数……
额，反正就，也不好说。

**Comment by msia121** [comment]
同样碰到这个问题。

**Comment by Keldos-Li** [comment]
Should be resolved via 8161b722712877e7648705f1d7c066493ed4a1c8.
<img width="1408" alt="image" src="https://github.com/GaiZhenbiao/ChuanhuChatGPT/assets/23137268/b3f9ba55-aae9-4903-87ee-e820083a386a">
