### ISSUE TITLE
能否增加代理配置？

### ISSUE THREAD

**Issue by w905581962** [GaiZhenbiao/ChuanhuChatGPT#37]
能否在配置文件上增加代理功能？
例如Socks，只需IP：端口的形式就可以

**Comment by iskoldt-X** [comment]
这个是否可以解决你的问题
https://github.com/GaiZhenbiao/ChuanhuChatGPT#%E4%BD%BF%E7%94%A8%E6%8A%80%E5%B7%A7

**Comment by iskoldt-X** [comment]
哦，那应该容易做到，只需要在shell 里运行类似这个命令再运行python 脚本就可以吧：
export ALL_PROXY=socks5://127.0.0.1:1080

**Comment by GaiZhenbiao** [comment]
建议使用Clash等软件的分流功能，代理API域名。

**Comment by kbwzy** [comment]
> 

我是通过修改以下地方解决的：
![image](https://user-images.githubusercontent.com/12123683/225829037-6e35b478-819c-49f8-8b45-b772c986a3de.png)
服务器端做到既不需要整台服务器全局，通过requests只代理Chatgpt接口。
