### ISSUE TITLE
 用户输入部分，不自然的换行 !

### ISSUE THREAD

**Issue by bentwnghk** [GaiZhenbiao/ChuanhuChatGPT#374]
![Screenshot_20230324_234225_Chrome](https://user-images.githubusercontent.com/101241940/227573960-236b0f4a-49bb-40f2-94ae-9f1e4b554394.jpg)

**Comment by Keldos-Li** [comment]
ead342edcea32964bc51b80c6f9d0a93b5eee6f2 引入的问题
- https://github.com/GaiZhenbiao/ChuanhuChatGPT/issues/367#issuecomment-1482809675
