### ISSUE TITLE
[功能请求] 希望加入保存配置

### ISSUE THREAD

**Issue by ackness** [GaiZhenbiao/ChuanhuChatGPT#375]
### 该功能请求是否与某个问题相关？
每次重新启动的时候 不能够加载 API地址 以及 代理地址, 希望可以想保存api key 一样保存配置文件

### 可能的解决办法
希望可以想保存api key 一样保存配置文件

**Comment by Keldos-Li** [comment]
api host的似乎还没加到config.json中，但是由于ISSUE基本解决，先关了QAQ

Resolve via #455 and #479
