### ISSUE TITLE
[Docker] 本地build的镜像报Something went wrong

### ISSUE THREAD

**Issue by bh-ying** [GaiZhenbiao/ChuanhuChatGPT#376]
![图片3](https://user-images.githubusercontent.com/106149875/227610058-bac35356-e488-4dda-8228-f5b56691976b.png)
![图片2](https://user-images.githubusercontent.com/106149875/227610083-a09f1ebd-0e46-4578-931f-1e1947a4bae8.png)

**Comment by Keldos-Li** [comment]
图片太糊了……

请参考同类issue，尤其是：
- #89
