### ISSUE TITLE
[代码风格] vscode 默认配置flake8 一堆报错告警

### ISSUE THREAD

**Issue by kcloze** [GaiZhenbiao/ChuanhuChatGPT#377]
### 复现操作
系统：mac 13.2.1
编辑器: vs code
一堆报错，看着有点不爽，有什么方式可以取消告警吗？

### 错误截图

![image](https://user-images.githubusercontent.com/1489176/227668741-7d3b0874-d692-4df8-904d-1a899c0b7dba.png)

**Comment by Keldos-Li** [comment]
如果不爽，可以关掉flake8:

在vs code的`settings.json`中更改以下值
```
"python.linting.flake8Enabled": false,
```

……

**Comment by MZhao-ouo** [comment]
看起来都是一些在其他文件中定义的函数和变量，可能是vscode配置的问题，建议用搜索引擎或ChatGPT解决

**Comment by kcloze** [comment]
加了一些参数可以忽略一些：
--ignore=E402,F841,F401,E302,E305,D103,F405,F541,E722
