### ISSUE TITLE
huggingface部署之后对话保存到本地，重新加载没有用

### ISSUE THREAD

**Issue by hylic51891** [GaiZhenbiao/ChuanhuChatGPT#380]
### 该功能请求是否与某个问题相关？
有保存对话到本地的功能和在线保存对话记录然后加载的功能，但是本地对话(.md)文件重新上传之后，不能继续当时的对话，而是每次在回答的时候重复一次上传对话的内容

### 可能的解决办法
上传本地对话记录之后用在线保存对话历史记录的方式加载

### 其他
补充说明

**Comment by Keldos-Li** [comment]
如需继续讨论，请前往：
- #454
