### ISSUE TITLE
[本地部署] 运行python脚本没有反应

### ISSUE THREAD

**Issue by tumibloom** [GaiZhenbiao/ChuanhuChatGPT#381]
### 错误描述
我按提示进行并无报错，但是打开localhost无法打开

### 错误截图
<img width="987" alt="image" src="https://user-images.githubusercontent.com/100983761/227704170-f099b6f6-7470-4dc0-bf52-a214a99da12a.png">

 - OS: Windows11 22H2
 - Browser:Chrome

**Comment by AneonCode** [comment]
> 

你的这个看起来并没有成功运行起来，按照README再配置一下试试，可能哪个地方出错了。
另外，如果成功运行起来了的话，会一条访问`http://127.0.0.1:7860`的提示

**Comment by tumibloom** [comment]
> > 
> 
> 你的这个看起来并没有成功运行起来，按照 README 再配置一下试试，可能哪个地方出错了。 另外，如果成功运行起来了的话，会一条访问`http://127.0.0.1:7860`的提示

###这是我的重新配置
![image](https://user-images.githubusercontent.com/100983761/227707927-15144ca5-9fcd-40e2-963a-c2d7bda83b4b.png)
![image](https://user-images.githubusercontent.com/100983761/227707988-7b291cda-473c-4ba7-85e6-cf2cf07176b3.png)
我不知道为什么还是不行

**Comment by Keldos-Li** [comment]
所以您终端的表现是，运行脚本
```shell
python3 ChuanhuChatbot.py
```
结果什么也没有发生吗？

**Comment by tumibloom** [comment]
> 所以您终端的表现是，运行脚本
> 
> ```shell
> python3 ChuanhuChatbot.py
> ```
> 
> 结果什么也没有发生吗？

对

**Comment by Keldos-Li** [comment]
额，这也太怪了。。。。如果您已经确认脚本文件路径正确但是 PowerShell 没有响应，或许可以尝试以下几个方法：

1. 确认您是否有打开多个 PowerShell 窗口，并确认您的脚本没有在其他窗口中运行。如果有，请关闭其他窗口并重新运行脚本。
2. 尝试使用管理员权限打开 PowerShell 窗口。右键单击 PowerShell 快捷方式并选择“以管理员身份运行”，然后再次尝试运行脚本。
3. 尝试重启 PowerShell 和计算机。这可以帮助清除任何可能导致 PowerShell 无响应的问题。

**Comment by tumibloom** [comment]
> 额，这也太怪了……如果您已经确认脚本文件路径正确但是 PowerShell 没有响应，或许可以尝试以下几个方法：
> 
> 1. 确认您是否有打开多个 PowerShell 窗口，并确认您的脚本没有在其他窗口中运行。如果有，请关闭其他窗口并重新运行脚本。
> 2. 尝试使用管理员权限打开 PowerShell 窗口。右键单击 PowerShell 快捷方式并选择「以管理员身份运行」，然后再次尝试运行脚本。
> 3. 尝试重启 PowerShell 和计算机。这可以帮助清除任何可能导致 PowerShell 无响应的问题。

我都试过了，包括cmd，我也试过了，就是没反应，我用的是直接Download ZIP的文件。

**Comment by xmlv** [comment]
自己插几行print代码进去调试一下，看看跑没跑起来，以及跑到哪里去了

**Comment by tumibloom** [comment]
问题经过重装Python后解决
