### ISSUE TITLE
[本地部署] 简短的错误描述

### ISSUE THREAD

**Issue by tiwentichat** [GaiZhenbiao/ChuanhuChatGPT#382]
> 感谢提交 issue! 请尽可能完整填写以下信息，帮助我们更好地定位问题~ 
> 在一切开始之前，请确保您已经阅读过 [常见问题](https://github.com/GaiZhenbiao/ChuanhuChatGPT/wiki/常见问题) 页面，查看它是否已经对您的问题做出了解答。如果没有，请检索issue与discussion，查看有没有相同或类似的问题。
> 如果您确信这是一个前人没有遇到的问题，欢迎提交该issue！
> 注意，请编辑issue标题栏“简短的错误描述”部分，也请替换我们的issue模板中的正文（但不要把所有内容都删完）。
> 请不要再提交 `Something went wrong Expecting value: line 1 column 1 (char 0)` 和 代理配置 相关的问题，请再看一遍 常见问题 页，实在不行请前往discussion。

### 错误描述
python3 chuanhuchatgpt.py时出错，说没有llama_index

### 复现操作
你之前干了什么，然后出现了错误呢？例如：
1. 正常完成本地部署
2. 然后python3 ChuanhuChatGPT.py,然后报错

### 错误截图

'''
python3 ChuanhuChatbot.py
Traceback (most recent call last):
  File "/Users/apple/codework/ChuanhuChatGPT/ChuanhuChatbot.py", line 10, in <module>
    from modules.overwrites import *
  File "/Users/apple/codework/ChuanhuChatGPT/modules/overwrites.py", line 4, in <module>
    from llama_index import Prompt
ModuleNotFoundError: No module named 'llama_index'
'''

### 终端（控制台）中的错误报告
如上

#### 桌面系统
**请填写以下列表：**

 - OS: [例如：macos]
 - Browser: [：Chrome,]

#### 运行依赖
**请填写以下列表：**
> 你可以在终端中依次输入以下指令以查看软件版本：
> ```shell
> pip show gradio
> python --version
> ```

- Gradio version:3.23.0
- Python version:3.9.6

### 其他
补充说明:上周的某个版本是部署成功，填入key后不能正常使用，怀疑是网络拥堵，后来没继续测试。
今天是最新版本，然后就出了这个报错

**Comment by GaiZhenbiao** [comment]
https://github.com/GaiZhenbiao/ChuanhuChatGPT/wiki/常见问题#no-matching-distribution-found-for-package-如tiktoken
