### ISSUE TITLE
客户端

### ISSUE THREAD

**Issue by Cagsirn** [GaiZhenbiao/ChuanhuChatGPT#384]
老板，能不能直接打个安装包出来，直接装就完了，这个还得下载Python，每次打开都得去点那个脚本。脚本关掉就没法用了，这用起来不方便啊

**Comment by GaiZhenbiao** [comment]
嫌麻烦嫌麻烦建议去用Hugging Face版：https://huggingface.co/spaces/JohnSmith9982/ChuanhuChatGPT
