### ISSUE TITLE
本地部署可以运行成功，但是一直报错

### ISSUE THREAD

**Issue by zf617525633** [GaiZhenbiao/ChuanhuChatGPT#387]
本地运行，挂了梯子，随便修改什么都报图形的错误
![image](https://user-images.githubusercontent.com/1791283/227717462-f4592a07-3ba5-480f-a784-7464938c246d.png)

**Comment by zf617525633** [comment]
请帮忙看看是什么问题？

**Comment by GaiZhenbiao** [comment]
Issue模板内容里都这么写了😫
<img width="915" alt="image" src="https://user-images.githubusercontent.com/51039745/227717531-a15cefbe-3003-4ab0-94a0-d39e5e56b888.png">

**Comment by Keldos-Li** [comment]
可能我在bug模板里没写本地部署模板的这几行，但是我都这么写了😫
![image](https://user-images.githubusercontent.com/23137268/227718232-2d24b5ee-f16e-4498-98eb-7297717d8a38.png)
