### ISSUE TITLE
[功能请求]: 修改主题配置文件

### ISSUE THREAD

**Issue by HaleyCH** [GaiZhenbiao/ChuanhuChatGPT#393]
### 相关问题

就像#320 里提到， Gradio的主题有问题。
而且，从 长远来看，目前这个主题里的`primary-hue`是乱的也不是什么好事。
<img width="275" alt="截屏2023-03-25 23 05 23" src="https://user-images.githubusercontent.com/29998135/227725435-9ab7508e-3175-47e6-a5e9-bb945735b920.png">

理论上来讲，它的颜色透明度是和信息权重成正相关的才对，这样才方便后续更换配色等。 （因为在custom.css里要用var(--primary-***)这种强耦合的代码

### 可能的解决办法

重写，其实也不是很麻烦。

还有就是，在setting里加一个切换主题。

之前就想搞，但是不知道怎么动态刷新`demo`

### 帮助开发

- [X] 我愿意帮忙帮助开发！

**Comment by Keldos-Li** [comment]
(突然发现我在issue模板里把「帮忙帮助」写重复了 SOS

这个主题是乱的可能是因为……某人是这么写的（我先溜了

https://github.com/GaiZhenbiao/ChuanhuChatGPT/blob/f1946717325cf65b9b443f38ec35fc367655015b/modules/presets.py#L107-L146

**Comment by GaiZhenbiao** [comment]
我的锅，我承认我是乱写的🥹
