### ISSUE TITLE
[本地部署]: 当给出复杂数学公式时，会出现奇怪的东西

### ISSUE THREAD

**Issue by tumibloom** [GaiZhenbiao/ChuanhuChatGPT#394]
### 是否已存在现有反馈与解答？

- [X] 我确认没有已有issue或discussion，且已阅读**常见问题**。

### 是否是一个代理配置相关的疑问？

- [X] 我确认这不是一个代理配置相关的疑问。

### 错误描述

<img width="1280" alt="image" src="https://user-images.githubusercontent.com/100983761/227732913-205a9d27-0c58-4b77-b5af-709a041e74bf.png">
<img width="516" alt="image" src="https://user-images.githubusercontent.com/100983761/227733378-cce57d07-a2da-4095-88a8-3d5d6030c2e1.png">

### 复现操作

就是让他给我几个复杂的数学公式，验证输出的文字是否正确，但显然还是有问题的，但是用其他的却可以正常显示希望可以显示的完美些

### 运行环境

```markdown
- OS: Win11
- Browser: chrome
- Gradio version: 
- Python version: 3.10
```

**Comment by GaiZhenbiao** [comment]
<img width="821" alt="image" src="https://user-images.githubusercontent.com/51039745/227735417-ede9316d-2019-4342-b290-70a2cb29c6af.png">

试着更新到最新版脚本

**Comment by tumibloom** [comment]
> <img alt="image" width="821" src="https://user-images.githubusercontent.com/51039745/227735417-ede9316d-2019-4342-b290-70a2cb29c6af.png">
> 
> 试着更新到最新版脚本

经过我测试，好像时浏览器的锅：
**chrome：**
<img width="819" alt="image" src="https://user-images.githubusercontent.com/100983761/227752231-e5e8cf3f-5b01-4b4a-8d0b-3baab831e20d.png">
**Edge：**
<img width="827" alt="image" src="https://user-images.githubusercontent.com/100983761/227752242-5f679c0d-223e-4a81-a98d-7033532eb202.png">
** FireFox：**
<img width="853" alt="image" src="https://user-images.githubusercontent.com/100983761/227752255-b6102570-a975-41cd-92af-4a8a454fccd8.png">
这算是奇怪的bug吗

**Comment by GaiZhenbiao** [comment]
你给的这几个截图看着都挺正常的。Chrome那个可能GPT没有以LaTex格式给出公式。

**Comment by tumibloom** [comment]
> 你给的这几个截图看着都挺正常的。Chrome那个可能GPT没有以LaTex格式给出公式。

对，在输出的过程中提示latex 的格式错误，一个黄色提示还有一个红色提示但是太快了，没截上图

**Comment by Keldos-Li** [comment]
> 对，在输出的过程中提示latex 的格式错误，一个黄色提示还有一个红色提示但是太快了，没截上图

系正常现象。某些latex语法需要包涵起始记号和结束记号，当结束记号未被输出时提示语法错误问题不大。

**Comment by tumibloom** [comment]
本问题算是结束，目前的解决办法是，让他以laTex格式输出，他的输出就变的正常了
