### ISSUE TITLE
用户输入部分，不自然的换行 ! 最新更新后问题再次出现

### ISSUE THREAD

**Issue by bentwnghk** [GaiZhenbiao/ChuanhuChatGPT#398]
[https://github.com/GaiZhenbiao/ChuanhuChatGPT/issues/374]

**Comment by Keldos-Li** [comment]
请提供网页截图、终端中gpt输出截图、该段对话的json格式历史记录。

**Comment by bentwnghk** [comment]
看似是这条commit造成的，把你之前改好的改掉了
https://github.com/GaiZhenbiao/ChuanhuChatGPT/commit/a3e85518bdfc230d113b5bfecb440a7956888170

**Comment by Keldos-Li** [comment]
emm 草

**Comment by bentwnghk** [comment]
Thanks!
