### ISSUE TITLE
[功能请求]: 连续对话中，给OpenAI提交的数据中，自动忽略最早的若干条问答，以提高连续对话的体验

### ISSUE THREAD

**Issue by ramblezhang** [GaiZhenbiao/ChuanhuChatGPT#400]
### 相关问题

连续对话场景，当token达到接近4096后就无法继续对话了，只能重新发起对话。

### 可能的解决办法

在token接近4096时（含system prompt），提交给openai的内容自动忽略最早的若干条问答（比如减少1000-2000token？），也可以在页面上增加一个选择框，让用户决定忽略最早的多少条历史对话。

### 帮助开发

- [ ] 我愿意协助开发！

**Comment by GaiZhenbiao** [comment]
emm按理说会有自动总结对话的功能，看上去有点问题……

**Comment by GaiZhenbiao** [comment]
现在应该没问题了
