### ISSUE TITLE
[Docker]: 设置USERNAME和password以后无法正确获得ip地址

### ISSUE THREAD

**Issue by Suiiiii** [GaiZhenbiao/ChuanhuChatGPT#403]
### 是否已存在现有反馈与解答？

- [X] 我确认没有已有issue或discussion，且已阅读**常见问题**。

### 是否是一个代理配置相关的疑问？

- [X] 我确认这不是一个代理配置相关的疑问。

### 错误描述

如果我设置USERNAME和password以后，就无法正确获得我的ip地址。
部署时不使用username和password就可以正常使用

### 复现操作

如同错误描述，
在使用username和password以后，无法正确获得ip也就无法正常使用。
如果去掉username和password就可以正常使用

### 运行环境

```markdown
- OS: 
- Browser: 
- Gradio version: 
- Python version:
```

**Comment by Keldos-Li** [comment]
- #89

**Comment by Keldos-Li** [comment]
Duplicate and no response.
