### ISSUE TITLE
[功能请求]: 一种减少Token，增加回复质量的方法论述

### ISSUE THREAD

**Issue by 1353604736** [GaiZhenbiao/ChuanhuChatGPT#411]
### 相关问题

发送问题是中文，后台直接转翻译换成英文发出提问给chatgpt，然后chatgpt回复英文后，直接翻译转换成中文显示出来

### 可能的解决办法

发送问题是中文，后台直接转翻译换成英文发出提问给chatgpt，然后chatgpt回复英文后，直接翻译转换成中文显示出来

### 帮助开发

- [ ] 我愿意协助开发！

### 补充说明

发送问题是中文，后台直接转翻译换成英文发出提问给chatgpt，然后chatgpt回复英文后，直接翻译转换成中文显示出来

**Comment by tumibloom** [comment]
多次翻译可能会导致翻译之后很奇怪吧

**Comment by xingfanxia** [comment]
建议加入百度
