### ISSUE TITLE
[其他]: Hugging Face代码貌似不是最新的

### ISSUE THREAD

**Issue by debugAllTheTime** [GaiZhenbiao/ChuanhuChatGPT#414]
### 是否已存在现有反馈与解答？

- [X] 我确认没有已有issue或discussion，且已阅读**常见问题**。

### 错误描述

[其他]: Hugging Face代码貌似不是最新的

### 复现操作

Hugging Face代码貌似不是最新的。好多功能没有加上去

### 运行环境

```markdown
- OS: 
- Browser: 
- Gradio version: 
- Python version: 
(或您的其他运行环境信息)
```

**Comment by MZhao-ouo** [comment]
已经更新啦
