### ISSUE TITLE
[Bug]: 总结对话不会显示数据且会自己消失

### ISSUE THREAD

**Issue by CNAHYZ** [GaiZhenbiao/ChuanhuChatGPT#416]
### 这个bug是否已存在现有issue了？

- [X] 我确认没有已有issue。

### 错误表现

使用总结对话，几秒后就不会显示，自己发送同样内容没有问题

https://user-images.githubusercontent.com/33870926/227871074-ca367201-a385-4695-a6fd-09804eb8b326.mp4

日志没有任何问题
![image](https://user-images.githubusercontent.com/33870926/227871283-65496488-9fa1-4af6-89bf-4b24a546a271.png)

### 复现操作

1.服务器端部署
2.其他接口正常

### 运行环境

```markdown
- OS: 
- Browser: 
- Gradio version: 
- Python version:
```

**Comment by CNAHYZ** [comment]
![QQ录屏20230327152554 (1)](https://user-images.githubusercontent.com/33870926/227872832-05858b95-5f9c-4de8-8fa6-87229f4d2ed7.gif)

**Comment by CNAHYZ** [comment]
> 这算是个feature，不会让总结对话的内容出现在历史记录中🤔️
现在的情况是不会显示，难道设计如此？

**Comment by CNAHYZ** [comment]
> 这算是个feature，不会让总结对话的内容出现在历史记录中🤔️

现在的情况是不会显示，难道设计如此？

**Comment by GaiZhenbiao** [comment]
> > 这算是个feature，不会让总结对话的内容出现在历史记录中🤔️
> 
> 现在的情况是不会显示，难道设计如此？

是的，我的考虑是让这个按钮点击之后减少token更像是一个操作，而不是自动发送消息，你觉得不太好吗？🤔️

**Comment by hcaihao** [comment]
这什么奇怪的设计。。。

而且点了总结以后显示一下再消失，再点重试又显示出来，让人费解

**Comment by GaiZhenbiao** [comment]
现在改成会正常显示了。同时修改了一下策略，尽可能保留用户对话。
