### ISSUE TITLE
[功能请求]: 后台log可否显示使用者的IP或者其他身份识别信息

### ISSUE THREAD

**Issue by OkamiFeng** [GaiZhenbiao/ChuanhuChatGPT#417]
### 相关问题

后台log可否显示使用者的IP或者其他身份识别信息

### 可能的解决办法

gradio不会，俺也不知道。。。貌似用flask里面的request

### 帮助开发

- [ ] 我愿意协助开发！

**Comment by Keldos-Li** [comment]
现在可以显示设置的用户名
