### ISSUE TITLE
[远程部署]: ModuleNotFoundError: No module named '_ctypes'

### ISSUE THREAD

**Issue by hfzhanghfcool** [GaiZhenbiao/ChuanhuChatGPT#426]
### 是否已存在现有反馈与解答？

- [X] 我确认没有已有issue或discussion，且已阅读**常见问题**。

### 是否是一个代理配置相关的疑问？

- [X] 我确认这不是一个代理配置相关的疑问。

### 错误描述

使用python3 ChuanhuChatbot.py启动
报
ModuleNotFoundError: No module named '_ctypes'

### 复现操作

按readme的教程一步一步安装

### 运行环境

```markdown
- OS: 
- Docker version: 
- Gradio version: 
- Python version:
```

**Comment by Keldos-Li** [comment]
`_ctypes`为Python内置模块，通常情况下，Python的标准安装程序应该包括 '_ctypes' 模块。如果你使用的是自定义的Python安装或虚拟环境，则需要确保 '_ctypes' 模块已正确安装。

请尝试重新安装Python或更改Python环境。
