### ISSUE TITLE
无法保存对话，无法读取对话

### ISSUE THREAD

**Issue by hazeyi** [GaiZhenbiao/ChuanhuChatGPT#43]
提示：
Something went wrong
Expecting value: 1ine 1 column 1 (char o)

**Comment by hazeyi** [comment]
现在什么功能都用不了 全部提示 error Expecting value: 1ine 1 column 1 (char o)

**Comment by GaiZhenbiao** [comment]
将`127.0.0.1`加到代理的DIRECT规则中就行了。我今天就遇到了这个问题😂
