### ISSUE TITLE
[远程部署]:  主页theme.css 报404

### ISSUE THREAD

**Issue by Qwenjin** [GaiZhenbiao/ChuanhuChatGPT#433]
### 是否已存在现有反馈与解答？

- [X] 我确认没有已有issue或discussion，且已阅读**常见问题**。

### 是否是一个代理配置相关的疑问？

- [X] 我确认这不是一个代理配置相关的疑问。

### 错误描述

服务器搭建的，用nginx反代到本地7890端口，然后有个theme.css的文件报404了，我看代码目录和assets目录没这个文件，是在Python某个包里面吗？

### 复现操作

直接部署就报该css文件404了

### 运行环境

```markdown
- OS: centos7
- Docker version: 
- Gradio version: 
- Python version: 3.8
```

**Comment by GaiZhenbiao** [comment]
请附上更详细的错误报告，以及gradio版本。我建议你可以升级到python 3.9+，gradio 3.23.0试试还存不存在问题

**Comment by Qwenjin** [comment]
> 请附上更详细的错误报告，以及gradio版本。我建议你可以升级到python 3.9+，gradio 3.23.0试试还存不存在问题

已修复，nginx配置所有静态文件也走proxy_pass
