### ISSUE TITLE
[功能请求]: 适配黑夜模式

### ISSUE THREAD

**Issue by Yang-Kyle** [GaiZhenbiao/ChuanhuChatGPT#436]
### 相关问题

> 个人喜欢把浏览器调成暗色系 不过这导致我看不清 ChatGPT 说话的内容了
ChatGPT 回复的字颜色较浅 看着不明显 在哪部署都有不明显的情况

### 可能的解决办法

提供上传背景图片或者自己调色的功能 这是我的提议

### 帮助开发

- [ ] 我愿意协助开发！

### 补充说明

![Yeah](https://user-images.githubusercontent.com/79508698/228245985-2af1c79a-e4b3-42db-aae6-863486e8e3ee.png)

**Comment by GaiZhenbiao** [comment]
emm……也许我不应该删除HG版的暗色模式样式……我改改

**Comment by Keldos-Li** [comment]
? 我看抱抱脸自己也妹更新啊（……这是用插件手动给网页加了暗色模式吗QAQ

**Comment by Yang-Kyle** [comment]
谢谢啦 这可太舒服了 (๑•̀ㅂ•́)و✧

**Comment by kayx23** [comment]
@GaiZhenbiao 我这边配色是这种，也看不清楚，对hugging face 不太熟悉，感觉跟这个问题有关，帮忙看看？

![image](https://user-images.githubusercontent.com/39619599/230032464-e4413b21-7f91-4ffd-99b2-864cc9912e4c.png)

**Comment by GaiZhenbiao** [comment]
> @GaiZhenbiao 我这边配色是这种，也看不清楚，对hugging face 不太熟悉，感觉跟这个问题有关，帮忙看看？
> 
> ![image](https://user-images.githubusercontent.com/39619599/230032464-e4413b21-7f91-4ffd-99b2-864cc9912e4c.png)

https://huggingface.co/spaces/JohnSmith9982/ChuanhuChatGPT/discussions/40

**Comment by kayx23** [comment]
@GaiZhenbiao 看了上面提供的链接内容。我其实是换了一个未登陆 hugging face 的浏览器来测试一下 public space 是什么效果，因为还想提供给几个朋友使用。在不登陆HF账号的情况下，好像没什么好办法来enforce这个设置？

**Comment by GaiZhenbiao** [comment]
> @GaiZhenbiao 看了上面提供的链接内容。我其实是换了一个未登陆 hugging face 的浏览器来测试一下 public space 是什么效果，因为还想提供给几个朋友使用。在不登陆HF账号的情况下，好像没什么好办法来enforce这个设置？
> 
> edit: 确认一下，这个是HF平台那侧的问题嘛？

是的，这是HG的问题，默认只有亮色模式。
