### ISSUE TITLE
更新后Connection errored out

### ISSUE THREAD

**Issue by FuYon** [GaiZhenbiao/ChuanhuChatGPT#44]
![1678122182570](https://user-images.githubusercontent.com/57851695/223179978-70249f3d-2811-4c21-b8d8-bb14afc3ec78.png)

**Comment by FuYon** [comment]
把代理关掉依然会链接不上

**Comment by FuYon** [comment]
![1678123555814](https://user-images.githubusercontent.com/57851695/223185174-6577f9ea-5374-4453-93ab-34e5ed0a9b52.png)
![1678123555805](https://user-images.githubusercontent.com/57851695/223185209-c2506180-2d6a-4bd3-805b-1904dab113fe.png)

**Comment by GaiZhenbiao** [comment]
关闭代理，启动App，开启代理，然后试试能不能用。如果能，说明是代理的规则有问题。

**Comment by xjzhou** [comment]
我也遇到，这个怎么处理呢？
