### ISSUE TITLE
输出的内容出现汉字重复乱码

### ISSUE THREAD

**Issue by niko015** [GaiZhenbiao/ChuanhuChatGPT#445]
![微信截图_20230329142421](https://user-images.githubusercontent.com/113090047/228444539-d27958a0-e2a0-4046-9275-553c8113f48b.png)
每次结束输出的时候，已完成输出的内容就会变成这样，提的问题也会变成这样

**Comment by GaiZhenbiao** [comment]
请试着升级到最新版。这个问题我倒是从来没遇见过

**Comment by Keldos-Li** [comment]
应该是浏览器自动翻译问题，且久未回复，先关了。
