### ISSUE TITLE
[功能请求]: 聊天记录支持按照不同聊天id和不同用户分开

### ISSUE THREAD

**Issue by Gary2018X** [GaiZhenbiao/ChuanhuChatGPT#447]
### 相关问题

无

### 可能的解决办法

history改为多层嵌套的字典存储

### 帮助开发

- [X] 我愿意协助开发！

**Comment by Keldos-Li** [comment]
Resolved with b9dc38bd4d6b1f0e3d372d9d3b36c7576ee38287.
