### ISSUE TITLE
[功能请求]: 能否在启动py中添加配置项中指定深色/浅色模式

### ISSUE THREAD

**Issue by fm9333** [GaiZhenbiao/ChuanhuChatGPT#448]
### 相关问题

我在多个手机浏览器上访问测试，发现手机使用的深色模式，网页也自动变更为黑暗模式，但是很多字体颜色没有变更或配置错误，有些只有按钮颜色，没有文本，以及有些文本在黑色背景下看不见等，是否能指定使用浅色/深色的UI页面。

### 可能的解决办法

增加页面指定深色/浅色模式配置项

### 帮助开发

- [ ] 我愿意协助开发！

**Comment by Keldos-Li** [comment]
早前一版曾经存在问题，但很快修复了。请下载最新版。

我们目前写的应该没有问题，如果还有问题，提供一下你是在哪里测试的？服务器部署或者本地部署在手机上用ip打开吗？还是huggingface？

另外浏览器有打开暗色模式插件吗？有没有可能是冲突了？

**Comment by lijiachang** [comment]
建议在页面中可选强制深色模式，白天用深色模式也很常见

**Comment by Keldos-Li** [comment]
又重新研究了一下，gradio框架的深色模式实现方法和我们自己定义的类的深色模式实现方法有点点不一样……然后现在又是按系统亮暗色的……

好吧，或许能做，但比较麻烦（不是很想加这个功能

（或许可以试着白天切系统的亮暗色😢

**Comment by Keldos-Li** [comment]
我知道怎么搞了。但别急。这个需求往后靠靠……

**Comment by Keldos-Li** [comment]
现在高级设置中增加了亮暗色切换按钮。希望大家喜欢💕
