### ISSUE TITLE
[功能请求]: 可交互和cache的聊天历史

### ISSUE THREAD

**Issue by xingfanxia** [GaiZhenbiao/ChuanhuChatGPT#454]
### 相关问题

不相关

### 可能的解决办法

像官网或https://github.com/Chanzhaoyu/chatgpt-web 一样保存一个可以交互的聊天历史栏, 并且不会因为刷新过期, 根据user session cache?

### 帮助开发

- [X] 我愿意协助开发！

**Comment by Gary2018X** [comment]
gradio不知道好不好弄
