### ISSUE TITLE
[功能请求]: Robot text and Human text markdown rendering

### ISSUE THREAD

**Issue by xingfanxia** [GaiZhenbiao/ChuanhuChatGPT#458]
### 相关问题

目前的对话框没有支持markdown rendering, 只有代码的rendering, 希望加入full markdown 支持

### 可能的解决办法

对前端没有太多研究, 应该有渲染库?

### 帮助开发

- [X] 我愿意协助开发！

**Comment by Keldos-Li** [comment]
天，我们现在的一堆显示bug就是因为处于markdown渲染环境才导致的QAQ，还有啥不支持的markdown rendering吗

另：用户发送的文本不经过markdown渲染，目前策略是只渲染gpt的文本。

**Comment by xingfanxia** [comment]
> 天，我们现在的一堆显示bug就是因为处于markdown渲染环境才导致的QAQ，还有啥不支持的markdown rendering吗
> 
> 另：用户发送的文本不经过markdown渲染，目前策略是只渲染gpt的文本。

- 比如现在有numbering list但是没有相应的缩进
- 用户文本有injection 风险?

**Comment by xingfanxia** [comment]
不好意思, 验证了一下是有style的. 就是不太明显lol

**Comment by Keldos-Li** [comment]
其实是有缩进的。但需要gpt非常规范地给出列表：
```
1. xxx
2. xxx
   1. 111
3. xxx
```

一旦gpt在列表之间给了空行，列表渲染就完蛋啦，这个库就会把它当成新列表。

或许之后可以试试手动在列表项目之间加<p>
