### ISSUE TITLE
在hugging face上可以对上传的pdf提问，但本地部署就不行，总是返回error。

### ISSUE THREAD

**Issue by ddkk3000** [GaiZhenbiao/ChuanhuChatGPT#459]
### 这个bug是否已存在现有issue了？

- [X] 我确认没有已有issue。

### 错误表现

api用的是同一个
![msedge_RiE7o4favV](https://user-images.githubusercontent.com/10786234/228531710-35983305-de52-4f20-81af-eda6e5375b96.png)

### 复现操作

运行程序，报错

### 错误日志

```shell
报错内容是：openai.error.InvalidRequestError: This model's maximum context length is 4097 tokens. However, your messages resulted in 5250 tokens. Please reduce the length of the messages.
```

### 运行环境

```markdown
- OS: win11
- Browser: edge-chrome
- Gradio version: 
- Python version:
```

**Comment by GaiZhenbiao** [comment]
建议升级到最新版脚本

**Comment by ddkk3000** [comment]
我刚刚下载的啊。10分钟以前。请问怎么查看版本。

----------




--------------原始邮件--------------
发件人："Chuan&nbsp;Hu ***@***.***&gt;;
发送时间：2023年3月29日(星期三) 晚上8:15
收件人："GaiZhenbiao/ChuanhuChatGPT" ***@***.***&gt;;
抄送："ddkk3000 ***@***.***&gt;;"Author ***@***.***&gt;;
主题：Re: [GaiZhenbiao/ChuanhuChatGPT] 在hugging face上可以对上传的pdf提问，但本地部署就不行，总是返回error。 (Issue #459)
-----------------------------------

 

 
建议升级到最新版脚本

**Comment by Keldos-Li** [comment]
使用git下载的可以在页底看到commit信息。如果不是这么下的可能是unkown就算了。

<img width="455" alt="image" src="https://user-images.githubusercontent.com/23137268/228538087-637b5d56-83bd-4d15-a87b-e3d9e528f68e.png">
