### ISSUE TITLE
请问怎么关闭服务

### ISSUE THREAD

**Issue by xmlv** [GaiZhenbiao/ChuanhuChatGPT#46]
请问怎么合理的关闭服务，ctrl-C 会提示关闭中，再来一次看起来是退了，但是看起来会堵死，导致下次启动的时候报 getaddrinfo failed

**Comment by GaiZhenbiao** [comment]
这应该是gradio的bug。我发现，不填写`server_port`参数可以解决这个问题。

**Comment by GaiZhenbiao** [comment]
server_name参数最好也不填，即最后一行：
```
demo.queue().launch(share=False) # 改为 share=True 可以创建公开分享链接
```
