### ISSUE TITLE
[功能请求]: 支持自适应切换4.0和3.5的tokens数

### ISSUE THREAD

**Issue by slideslide** [GaiZhenbiao/ChuanhuChatGPT#462]
### 这个bug是否已存在现有issue了？

- [X] 我确认没有已有issue。

### 错误表现

看官方文档上说4.0能够支持8196个tokens
![image](https://user-images.githubusercontent.com/86949124/228606333-bd48df1f-6567-4156-bec5-f2d413a0e4c2.png)
而网页依旧在调整为4.0后在3500tokens的时候自动续写

### 复现操作

在调整为4.0后，在3500tokens的时候自动续写

### 运行环境

```markdown
- OS: 
- Browser: 
- Gradio version: 
- Python version:
```

**Comment by Keldos-Li** [comment]
我改成feature request吧

**Comment by GaiZhenbiao** [comment]
现在各个模型有分离的token软上限啦
```
MODEL_SOFT_TOKEN_LIMIT = {
    "gpt-3.5-turbo": {
        "streaming": 3500,
        "all": 3500
    },
    "gpt-3.5-turbo-0301": {
        "streaming": 3500,
        "all": 3500
    },
    "gpt-4": {
        "streaming": 7500,
        "all": 7500
    },
    "gpt-4-0314": {
        "streaming": 7500,
        "all": 7500
    },
    "gpt-4-32k": {
        "streaming": 31000,
        "all": 31000
    },
    "gpt-4-32k-0314": {
        "streaming": 31000,
        "all": 31000
    }
}
```

**Comment by slideslide** [comment]
> 现在各个模型有分离的token软上限啦
> 
> ```
> MODEL_SOFT_TOKEN_LIMIT = {
>     "gpt-3.5-turbo": {
>         "streaming": 3500,
>         "all": 3500
>     },
>     "gpt-3.5-turbo-0301": {
>         "streaming": 3500,
>         "all": 3500
>     },
>     "gpt-4": {
>         "streaming": 7500,
>         "all": 7500
>     },
>     "gpt-4-0314": {
>         "streaming": 7500,
>         "all": 7500
>     },
>     "gpt-4-32k": {
>         "streaming": 31000,
>         "all": 31000
>     },
>     "gpt-4-32k-0314": {
>         "streaming": 31000,
>         "all": 31000
>     }
> }
> ```

tks QWQ
