### ISSUE TITLE
[Bug]: 付费API的额度显示不正确

### ISSUE THREAD

**Issue by OkamiFeng** [GaiZhenbiao/ChuanhuChatGPT#467]
### 这个bug是否已存在现有issue了？

- [X] 我确认没有已有issue。

### 错误表现

付费API的总额度还是显示的免费的部分。
解决方案如下
```
def get_subscription_data(openai_api_key, subscription_url):
    headers = {
        "Content-Type": "application/json",
        "Authorization": f"Bearer {openai_api_key}"
    }
    
    timeout = timeout_all
    proxies = get_proxies()
    response = requests.get(
        subscription_url,
        headers=headers,
        timeout=timeout,
        proxies=proxies,
    )
    
    if response.status_code == 200:
        data = response.json()
        return data
    else:
        raise Exception(f"API request failed with status code {response.status_code}: {response.text}")   

SUBSCRIPTION_API_URL='https://api.openai.com/dashboard/billing/subscription'
subscription_data=get_subscription_data(openai_api_key, SUBSCRIPTION_API_URL)
balance = subscription_data['system_hard_limit_usd']
```

### 复现操作

-

**Comment by MZhao-ouo** [comment]
> 付费API的总额度还是显示的免费的部分。 解决方案如下

感谢提供了一个新的api，不过我没看懂这句话是什么意思🥲
目前的策略是，当还有免费额度时显示总额度和已用额度，免费额度用完的话就显示当月用的总金额

**Comment by OkamiFeng** [comment]
> > 付费API的总额度还是显示的免费的部分。
> 
> 感谢提供了一个新的api，不过我没看懂这句话是什么意思🥲 目前的策略是，当还有免费额度时显示总额度和已用额度，免费额度用完的话就显示当月用的总金额

比如说，我的额度是如下图所示。但是显示的是 $11.47/$18，而不是$11.47/120
![image](https://user-images.githubusercontent.com/125006534/228784370-32b73816-e551-4e53-bfea-fadc78245d72.png)

**Comment by MZhao-ouo** [comment]
> > > > 付费API的总额度还是显示的免费的部分。
> > > 
> > > 
> > > 感谢提供了一个新的api，不过我没看懂这句话是什么意思🥲 目前的策略是，当还有免费额度时显示总额度和已用额度，免费额度用完的话就显示当月用的总金额
> > 
> > 
> > 比如说，我的额度是如下图所示。但是显示的是 $11.47/$18，而不是$11.47/120 ![image](https://user-images.githubusercontent.com/125006534/228784370-32b73816-e551-4e53-bfea-fadc78245d72.png)
> 
> response格式：
> 
> ```
> {
>   "object": "billing_subscription",
>   "has_payment_method": true,      
>   "canceled": false,
>   "canceled_at": null,
>   "delinquent": null,
>   "access_until": 1685577600,      
>   "soft_limit": 1600000,
>   "hard_limit": 2000000,
>   "system_hard_limit": 2000000,    
>   "soft_limit_usd": 96.0,
>   "hard_limit_usd": 120.0,
>   "system_hard_limit_usd": 120.0,  
>   "plan": {
>     "title": "Pay-as-you-go",
>     "id": "payg"
>   },
>   "account_name": "个人信息打码处理",
>   "po_number": null,
>   "billing_email": null,
>   "tax_ids": null,
>   "billing_address": {
>     "city": "Cedar Rapids",
>     "line1": "4086 Bailey Drive",
>     "line2": null,
>     "state": "IA",
>     "country": "US",
>     "postal_code": "52401"
>   },
>   "business_address": null
> }
> ```

我觉得没问题🤔优先显示免费额度

**Comment by Keldos-Li** [comment]
如果后面限额确实是120那应该也可以再加一个余额？（我也去做成进度条形式的？
