### ISSUE TITLE
[功能请求]: 支援繁體中文輸出

### ISSUE THREAD

**Issue by den13501** [GaiZhenbiao/ChuanhuChatGPT#468]
### 相关问题

目前介面中的下拉選單選擇中文後，左方輸入問題得到的機器人回答經常是簡體中文的，希望可以加入選項定義由繁體中文回答，謝謝。

### 可能的解决办法

右方的选择回复语言由"中文"改为"简中"与'繁中"

### 帮助开发

- [ ] 我愿意协助开发！

**Comment by GaiZhenbiao** [comment]
<img width="263" alt="image" src="https://user-images.githubusercontent.com/51039745/228780220-b5eeaf90-c69e-4017-9fe8-6fb53394a945.png">

现在有啦
