### ISSUE TITLE
[功能请求]: 想要图片生成功能！

### ISSUE THREAD

**Issue by kiddog99** [GaiZhenbiao/ChuanhuChatGPT#470]
### 可能的解决办法

跪求增加api key调用图片生成的模型，这样对话中就可以生成图片了

### 帮助开发

- [ ] 我愿意协助开发！

**Comment by Keldos-Li** [comment]
现在可以使用 Midjourney 和 dalle 生成图片~

**Comment by Fr3027** [comment]
请教下dalle生成图片的时候可以指定尺寸吗，现在只有1024*1024的
