### ISSUE TITLE
[Docker]: 多用户的docker run要怎么写？

### ISSUE THREAD

**Issue by wubin2** [GaiZhenbiao/ChuanhuChatGPT#472]
### 是否已存在现有反馈与解答？

- [X] 我确认没有已有issue或discussion，且已阅读**常见问题**。

### 是否是一个代理配置相关的疑问？

- [X] 我确认这不是一个代理配置相关的疑问。

### 错误描述

根据说明新建了api_key.txt和auth.json设置多用户的新功能，但按之前的做法无法生效，请问多用户的docker run要怎么写？
另外，增加了多用户是不是可以进一步开发限制用户是否能选择模型等功能。
谢谢大佬！

### 复现操作

1、正常git pull
2、正常本地docker build
3、正常docker run

**Comment by Sligcm** [comment]
同问。

**Comment by Keldos-Li** [comment]
现在，请使用新的配置在config.json中的方式来运行。
