### ISSUE TITLE
部署完成后无法访问，显示detail：not found

### ISSUE THREAD

**Issue by harrisonyao** [GaiZhenbiao/ChuanhuChatGPT#474]
{"detail":"Not Found"}

**Comment by Keldos-Li** [comment]
请提供更多信息……

**Comment by kayeah82** [comment]
当我在Nginx中配置二级路径时，也出现该错误。

**Comment by Keldos-Li** [comment]
原issue作者未提供更多信息……
 @kayeah82 如需要在二级路径下配置可以参考一下我们兄弟软件的说明：https://github.com/binary-husky/gpt_academic/blob/master/docs/WithFastapi.md
不过，我们的配置有所不同，也需要改一些底层代码。你可能需要自己摸索一下。
