### ISSUE TITLE
[本地部署]: 部署完成后提示ImportError: cannot import name 'ServiceContext' from 'llama_index'

### ISSUE THREAD

**Issue by yolend88** [GaiZhenbiao/ChuanhuChatGPT#475]
### 是否已存在现有反馈与解答？

- [X] 我确认没有已有issue或discussion，且已阅读**常见问题**。

### 是否是一个代理配置相关的疑问？

- [X] 我确认这不是一个代理配置相关的疑问。

### 错误描述

在本地部署完成，在运行的时候，出现以下报错：
Traceback (most recent call last):
  File "C:\ChuanhuChatGPT-main\ChuanhuChatbot.py", line 10, in <module>
    from modules.overwrites import *
  File "C:\ChuanhuChatGPT-main\modules\overwrites.py", line 9, in <module>
    from modules.llama_func import *
  File "C:\ChuanhuChatGPT-main\modules\llama_func.py", line 4, in <module>
    from llama_index import GPTSimpleVectorIndex, ServiceContext
ImportError: cannot import name 'ServiceContext' from 'llama_index' (C:\Users\batman\AppData\Local\Programs\Python\Python310\lib\site-packages\llama_index\__init__.py)

### 复现操作

无法正常部署，本地部署的最后一步出现错误。

### 错误日志

```shell
Traceback (most recent call last):
  File "C:\ChuanhuChatGPT-main\ChuanhuChatbot.py", line 10, in <module>
    from modules.overwrites import *
  File "C:\ChuanhuChatGPT-main\modules\overwrites.py", line 9, in <module>
    from modules.llama_func import *
  File "C:\ChuanhuChatGPT-main\modules\llama_func.py", line 4, in <module>
    from llama_index import GPTSimpleVectorIndex, ServiceContext
ImportError: cannot import name 'ServiceContext' from 'llama_index' (C:\Users\batman\AppData\Local\Programs\Python\Python310\lib\site-packages\llama_index\__init__.py)
```

### 运行环境

```markdown
- OS: win10
- Browser: chrome
- Gradio version: 3.22.1
- Python version: Python 3.10.8
```

**Comment by vincentqin-sys** [comment]
执行： pip install -r requirements.txt --upgrade

**Comment by iHomeSoft** [comment]
pip install --upgrade llama_index，解决问题

**Comment by lance2016** [comment]
我也遇到了这个问题，升级包也没用，当前包版本是llama-index  0.4.32

**Comment by HopeZZZ** [comment]
我也遇到了这个问题，升级python pip 都试过了，无法解决

**Comment by iHomeSoft** [comment]
Downloading llama_index-0.5.2.tar.gz (161 kB)，升级这个版本，实测解决问题！
![image](https://user-images.githubusercontent.com/13914422/229021499-d4a106c3-8a15-4309-a5f1-01e1158ae171.png)
新版本中定义了ServiceContext！

**Comment by scordl327** [comment]
我刚刚更新了 还是有Traceback (most recent call last):
  File "d:\ProjectNas\PythonProject\0331\ChuanhuChatGPT-main\ChuanhuChatbot.py", line 11, in <module>
    from modules.overwrites import *
  File "d:\ProjectNas\PythonProject\0331\ChuanhuChatGPT-main\modules\overwrites.py", line 9, in <module>
    from modules.llama_func import *
  File "d:\ProjectNas\PythonProject\0331\ChuanhuChatGPT-main\modules\llama_func.py", line 4, in <module>
    from llama_index import GPTSimpleVectorIndex, ServiceContext
ImportError: cannot import name 'ServiceContext' from 'llama_index'

**Comment by yolend88** [comment]
执行了pip install --upgrade llama_index，但是包版本还是llama-index 0.4.32，怎么可以升级到llama_index-0.5.2？？

**Comment by Keldos-Li** [comment]
尝试upgrade但没有反应的，请换用官方pypi源，参考：https://github.com/GaiZhenbiao/ChuanhuChatGPT/wiki/常见问题#no-matching-distribution-found-for-package-如tiktoken

**Comment by Keldos-Li** [comment]
已写入 [常见问题](https://github.com/GaiZhenbiao/ChuanhuChatGPT/wiki/常见问题#importerror-cannot-import-name-some-name-from-package-如llama_index) ~

**Comment by separationliu** [comment]
> 

换源的确有效，已解决问题了

**Comment by scordl327** [comment]
切换到PIP原生源后更新下模块，可以解决
