### ISSUE TITLE
[功能请求]: 大佬建议添加默认实时保存聊天记录的功能，重新打开自动加载，不需要的聊天记录可以选择删除的那种

### ISSUE THREAD

**Issue by 1353604736** [GaiZhenbiao/ChuanhuChatGPT#476]
### 可能的解决办法

类似官方chatgpt，自动保存聊天记录，下次登录自动加载，不需要时可以选择删除，这样更自由

### 帮助开发

- [ ] 我愿意协助开发！

**Comment by xingfanxia** [comment]
duplicate of https://github.com/GaiZhenbiao/ChuanhuChatGPT/issues/454

**Comment by Keldos-Li** [comment]
因重复而关闭，如有需要请前往
- #454
