### ISSUE TITLE
[功能请求]: 支持shortcuts以供siri使用

### ISSUE THREAD

**Issue by kavenGw** [GaiZhenbiao/ChuanhuChatGPT#478]
### 可能的解决办法

https://www.tomsguide.com/how-to/how-to-use-chatgpt-with-siri

### 帮助开发

- [ ] 我愿意协助开发！

**Comment by Keldos-Li** [comment]
或许您没有理解我们的程序是怎么运作的……我们也需要您自己提供API Key，Siri捷径也需要您自己提供API Key……嗯。我们不是一个额外的人工智能对话服务提供商。

**Comment by kavenGw** [comment]
你好，我现在的流程是将您提供的工具部署在一个日本的服务器，然后通过香港的代理访问，所以速度还可以。 
如果使用我直接使用上面链接中的教程，则需要直连日本的服务器，非常不稳定，所以如果能通过您的工具api配置sortcut将会方便很多，
