### ISSUE TITLE
Expecting value: line 1 column 1 (char 0)

### ISSUE THREAD

**Issue by Maxsbljvdajj** [GaiZhenbiao/ChuanhuChatGPT#48]
为啥这样啊大佬= = 第一次用 跟着教程搞得 就连powershell也是第一次弄
装好之后http://localhost:7860打开然后输入就弹出这个了
Something went wrong
Expecting value: line 1 column 1 (char 0)

**Comment by GaiZhenbiao** [comment]
见Readme最后的疑难解答
