### ISSUE TITLE
[功能请求]: 能否支持多个api负载均衡

### ISSUE THREAD

**Issue by kkkk24juastin** [GaiZhenbiao/ChuanhuChatGPT#481]
### 相关问题

[功能请求]: 能否支持多个api负载均衡

### 可能的解决办法

可以参考https://github.com/lss233/chatgpt-mirai-qq-bot这个机器人项目

### 帮助开发

- [ ] 我愿意协助开发！

**Comment by Keldos-Li** [comment]
Resolved via #513.
