### ISSUE TITLE
[Bug]: Expecting value: line 1 column 1 (char 0)

### ISSUE THREAD

**Issue by fuxin123z** [GaiZhenbiao/ChuanhuChatGPT#485]
### 这个bug是否已存在现有issue了？

- [X] 我确认没有已有issue。

### 错误表现

Expecting value: line 1 column 1 (char 0)

### 复现操作

无法输出

### 错误日志

```shell
Expecting value: line 1 column 1 (char 0)
```

### 运行环境

```markdown
OS: Windows11 22H2
Browser: Chrome
```

**Comment by Keldos-Li** [comment]
<img width="1123" alt="image" src="https://user-images.githubusercontent.com/23137268/229127694-6c46df6d-002b-4fe3-899d-abeb04f56065.png">

好好看一看啊！https://github.com/GaiZhenbiao/ChuanhuChatGPT/wiki/常见问题#something-went-wrong-expecting-value-line-1-column-1-char-0
