### ISSUE TITLE
[本地部署]: 本地部署完成，访问http://127.0.0.1:7860/，出现UI异常

### ISSUE THREAD

**Issue by yolend88** [GaiZhenbiao/ChuanhuChatGPT#486]
### 是否已存在现有反馈与解答？

- [X] 我确认没有已有issue或discussion，且已阅读**常见问题**。

### 是否是一个代理配置相关的疑问？

- [X] 我确认这不是一个代理配置相关的疑问。

### 错误描述

部署完成，在访问http://127.0.0.1:7860/的时候，UI异常，
控制台出现
index.bd1e689b.js:1          GET https://www.googletagmanager.com/gtag/js?id=UA-156449732-1 net::ERR_SSL_PROTOCOL_ERROR
![image](https://user-images.githubusercontent.com/60383097/229128176-b21bf420-99d0-49bb-8e24-66b70a42000f.png)

### 复现操作

正常完成部署，访问时出现UI显示异常。

### 运行环境

```markdown
- OS: win10
- Browser: Chrome
- Gradio version: 
- Python version:
```

**Comment by Keldos-Li** [comment]
其实呢……感觉应该也算代理问题😂

好神奇，gradio还会加载这些js。或许可以尝试将 googletagmanager.com 也加入代理规则。

**Comment by yolend88** [comment]
全局代理之后没有了js报错，但是UI还是异常
![image](https://user-images.githubusercontent.com/60383097/229151597-d4a912d5-7f8e-41cb-a972-f1ba3ef0f1cd.png)

**Comment by Keldos-Li** [comment]
这也太奇怪了，浏览器的控制台没别的报错或者警告么，清除缓存啥的都试试

**Comment by yolend88** [comment]
没有，就是UI显示不正常，清理了缓存，无痕浏览，都不行，奇了怪了
![image](https://user-images.githubusercontent.com/60383097/229166819-6388bd37-52bf-4027-98aa-ac03a9ad7210.png)

**Comment by lijiachang** [comment]
换个浏览器试试？

**Comment by stevenguoqiang** [comment]
这个问题解决了，我也遇到了形同的问题
