### ISSUE TITLE
[功能请求]: 添加prompt搜索功能

### ISSUE THREAD

**Issue by Olimiya** [GaiZhenbiao/ChuanhuChatGPT#487]
### 相关问题

现在选择prompt的方式是点击下拉框在里面挑选一个，但是下拉框太长以后很难快速选择到想要的prompt。

### 可能的解决办法

能否添加一个前端的功能，将下拉框改为可输入文字的，然后根据输入文字筛选下拉框中的内容？
非常感谢！

### 帮助开发

- [ ] 我愿意协助开发！

**Comment by Keldos-Li** [comment]
寄，我再也不说我会写前端了（（（

虽然这个feature request很有道理，但gradio似乎没原生提供这个功能……（总不可能真让我写JavaScript吧QAQ

**Comment by Olimiya** [comment]
> 寄，我再也不说我会写前端了（（（
> 
> 虽然这个feature request很有道理，但gradio似乎没原生提供这个功能……（总不可能真让我写JavaScript吧QAQ

hhh，看上去很简单的功能，还以为大佬就是咔咔就能更新的事情嘞，:)

**Comment by Gary2018X** [comment]
> 寄，我再也不说我会写前端了（（（
> 
> 虽然这个feature request很有道理，但gradio似乎没原生提供这个功能……（总不可能真让我写JavaScript吧QAQ

可以给gradio提issues
![%)RK8(`~{5PA(@43ARLWE_I](https://user-images.githubusercontent.com/56428019/229278078-22507930-ad0a-440b-93f6-18544d77d014.png)

**Comment by Gary2018X** [comment]
发现其实是支持搜索的 把默认选项去掉后就可以输入搜索了

**Comment by GaiZhenbiao** [comment]
加入这个功能啦
