### ISSUE TITLE
[Bug]: 从列表中加载对话下拉框首次打开时无法选择

### ISSUE THREAD

**Issue by Olimiya** [GaiZhenbiao/ChuanhuChatGPT#488]
### 这个bug是否已存在现有issue了？

- [X] 我确认没有已有issue。

### 错误表现

首次打开网站时，无法从列表中加载对话，点击下拉框不显示以保存的对话。但是在保存一个新的对话以后，就能正确显示历史保存的记录。
![image](https://user-images.githubusercontent.com/35156329/229179396-03cb1222-e372-4221-9461-95ada89e25f1.png)
![image](https://user-images.githubusercontent.com/35156329/229179716-54ccaa23-2ab3-43fc-90b9-aecc7ce4fc91.png)

### 复现操作

1.  通过一键部署，部署到huggingface
2.  对话完毕后保存对话，此时一切正常
3.  关闭网站，重新进入，选择从列表中加载对话，这时候看不到前面保存的对话。

### 运行环境

```markdown
- OS: Windows11 22H2
- Browser: Edge
- Gradio version: 
- Python version:
```

**Comment by Keldos-Li** [comment]
所以提供了一个刷新按钮……

**Comment by Olimiya** [comment]
Oh, Sorry~ 原来是这样用的，:D
