### ISSUE TITLE
在设置IP地址及端口号不用默认的情况和使用用户名及密码后会有连接错误[Bug]: 

### ISSUE THREAD

**Issue by scordl327** [GaiZhenbiao/ChuanhuChatGPT#493]
### 这个bug是否已存在现有issue了？

- [X] 我确认没有已有issue。

### 错误表现

在设置IP地址及端口号不用默认的情况和使用用户名及密码后会有连接错误

### 复现操作

设置端口号及IP地址 新建了用户及密码后 可以进入界面，与OpenAi进行交互时Connection errored out.错误

### 错误日志

```shell
终端并未报错
```

### 运行环境

```markdown
- OS: Win11 22H2
- Browser: Google Chrome
- Gradio version: 3.22.1
- Python version: 3.11.1
```

**Comment by williamz** [comment]
遇到了一样的问题

**Comment by Keldos-Li** [comment]
- #89
