### ISSUE TITLE
[Bug]: 显示C++代码块时出现异常

### ISSUE THREAD

**Issue by githubchry** [GaiZhenbiao/ChuanhuChatGPT#494]
### 这个bug是否已存在现有issue了？

- [x] 我确认没有已有issue。

### 错误表现

每次显示C/C++代码块都会出现显示异常，如下图所示
![image](https://user-images.githubusercontent.com/15260796/229266697-ad341a70-0b01-49a3-8ee5-147e3d5d8882.png)

### 复现操作

1. 在huggingface页面设置token
2. 向ChatGPT提问：请帮我用域套接字写一个双向异步通讯的demo，要求c/c++, linux系统下运行
3. 显示代码块出现异常

### 运行环境

```markdown
- OS: Windows10
- Browser: Edge
```

**Comment by Keldos-Li** [comment]
好吧，可能是我们的pygments并不认为```c++是一个标准语法……
<img width="900" alt="image" src="https://user-images.githubusercontent.com/23137268/229286491-7c7a1d9a-93fa-414d-8f15-bc78cfe5dd7d.png">

**Comment by Keldos-Li** [comment]
先让ChatGPT把所有c++代码块前面都写成cpp吧。改高亮库的意义不是很大。
