### ISSUE TITLE
[Bug]: API 使用情况 division by zero bug

### ISSUE THREAD

**Issue by xingfanxia** [GaiZhenbiao/ChuanhuChatGPT#495]
### 这个bug是否已存在现有issue了？

- [X] 我确认没有已有issue。

### 错误表现

`2023-04-01 06:25:32,516 [ERROR] [openai_func.py:47] API使用情况解析失败:division by zero`

Caused by this line here
```
            usage_percent = round(total_used / (total_used+balance) * 100, 2)
```

### 复现操作

如果没有free credit会出现这个bug

related to https://github.com/GaiZhenbiao/ChuanhuChatGPT/commit/ec10bf7faa610cac1d8ff35a420426fd9f60d3b6

### 运行环境

```markdown
- OS: 
- Browser: 
- Gradio version: 
- Python version:
```

**Comment by Keldos-Li** [comment]
> <img width="495" alt="image" src="https://user-images.githubusercontent.com/23137268/229270252-1fdebf83-345f-47f0-87be-b021ff809cfe.png">
> 
> 我在ui分支刚推了一个改用进度条显示的usage的，有没有空看看你这个显示效果是啥，怕有bug🥺

_Originally posted by @Keldos-Li in https://github.com/GaiZhenbiao/ChuanhuChatGPT/issues/449#issuecomment-1488264867_
            
行吧，果然有bug……我的问题
