### ISSUE TITLE
[Bug]: Docker中的空ENV my_api_key覆盖了config.json中的api key

### ISSUE THREAD

**Issue by Eralien** [GaiZhenbiao/ChuanhuChatGPT#499]
### 这个bug是否已存在现有issue了？

- [x] 我确认没有已有issue，且已阅读**常见问题**。

### 错误表现

我试图去构建不需要去每次填写api key的docker。由于使用需求不能暴露api key到命令行，我试图使用默认被gitignore的config.json来传递api key和proxy设定. 但是由于DockerFile中设置了默认ENV my_api_key empty, 因此在[modules/config.py#L36](https://github.com/GaiZhenbiao/ChuanhuChatGPT/blob/a2436f41a4a9d3f36d96b4ce5ec507d41970776e/modules/config.py#L36) 使用dict.get去获得默认值时，os.environ['my_api_key']为'empty', 覆盖了config.json中给出的值，导致无法正常使用

### 复现操作

1. 在根目录下添加config.json，其中填写openai_api_key字段
2. `docker built -t custom_docker .` 构建docker
3. 按照README中方式启动container, 假设其name为chatgpt
4. `docker logs chatgpt`查看错误

### 错误日志

```shell
ERROR:root:Please give a api key
```

### 运行环境

- OS: Ubuntu 18.04
- Browser: Microsoft Edge
- Gradio version: Docker default
- Python version: Docker default Python 3.9

### 帮助解决

- [x] 我愿意协助解决！

### 补充说明

我目前的解决方案：直接将Dockerfile中的ENV my_api_key empty 去掉即可在我的需求下正常运行。但是我不清楚这样做会不会影响到其他使用方式的功能，所以我只在我fork的工程上这样改，没有提PR。
其他方式：直接将[modules/config.py#L36](https://github.com/GaiZhenbiao/ChuanhuChatGPT/blob/a2436f41a4a9d3f36d96b4ce5ec507d41970776e/modules/config.py#L36)改为 
```python
my_api_key = my_api_key if os.environ.get("my_api_key", "empty") == "empty" else os.environ["my_api_key"]
```
如果有哪种方式是比较合适的，我可以提交PR

**Comment by Keldos-Li** [comment]
@HsunGong
可能得麻烦您看一下

**Comment by Keldos-Li** [comment]
突然想到现在那么多地方都设了相关设置，docker json txt的优先级到底该怎么排列QAQ 可能这个得先定下来……？🤔

**Comment by HsunGong** [comment]
同意 https://github.com/GaiZhenbiao/ChuanhuChatGPT/issues/499#issuecomment-1493052055 这个说法

之前的代码只是为了让config.json的优先级最低，使得版本兼容以前老的设置。

另外，从常理上讲，环境变量的优先级的确应该比config.json里面更高？欢迎大家讨论。

---

当然，如果能去掉环境变量的设置，统统改成读取config.json文件是最好的。

----

至于 https://github.com/GaiZhenbiao/ChuanhuChatGPT/issues/499#issue-1650348336 这个问题，我的建议是修改Dockerfile，并去掉https://github.com/GaiZhenbiao/ChuanhuChatGPT/blob/a2436f41a4a9d3f36d96b4ce5ec507d41970776e/Dockerfile#L12 这行，因为不显式地设置ENV也能够通过 `-e`添加环境变量，这个时候原始的config.json的读取不会有问题。

**Comment by HsunGong** [comment]
根据上面的内容，我们应该在wiki里面推荐大家都在config里面设置api-key等相关参数，而不是使用环境变量覆盖。（因而dockerfile里也不必再给出ENV的layer）

**Comment by GaiZhenbiao** [comment]
环境变量我认为有必要保留，在Docker部署和Hugging Face部署时都很有用。在Hugging Face上，只需要添加一个Repo Secret就行了。

**Comment by weisong82** [comment]
@HsunGong 现在key设置的地方太多了，多人使用页面已经出现一个比较奇怪的问题：
 有某同志浏览器保存了auth的密码，进入主界面后默默的直接替换了页面上api-key ****这个password字段。 导致后续调用全部失败。   因为这个地方的key优先级又高于各种配置

**Comment by HsunGong** [comment]
优先级的逻辑是这样的：网站重载key > 环境变量key > config.json的key，这个感觉还算合理。
我看到最新的commit里，docker里面的my_api_key的参数已经去掉了。

---

https://github.com/GaiZhenbiao/ChuanhuChatGPT/issues/499#issuecomment-1508823422 这个是因为浏览器的问题吧？按理说auth的密码不应该替换api-key（或者是api-key给他新增一个class，使得密码自动补全不在这个上面进行）

**Comment by Keldos-Li** [comment]
一般不会有这种问题，如误有这种奇怪状况需要彻底避免，也可以workaround：
https://github.com/GaiZhenbiao/ChuanhuChatGPT/blob/0f313bc0f1739a9f4cccc5923a8759232226a07c/modules/presets.py#L39

原议题视为已解决~
