### ISSUE TITLE
[本地部署]: ModuleNotFoundError: No module named 'modules.config'; 'modules' is not a package

### ISSUE THREAD

**Issue by Owenfly** [GaiZhenbiao/ChuanhuChatGPT#501]
### 是否已存在现有反馈与解答？

- [X] 我确认没有已有issue或discussion，且已阅读**常见问题**。

### 是否是一个代理配置相关的疑问？

- [X] 我确认这不是一个代理配置相关的疑问。

### 错误描述

![image](https://user-images.githubusercontent.com/55825205/229292899-29dc13db-5200-44c2-8b4b-abd9ba8898c6.png)

### 复现操作

拉取最新代码后，出现问题

### 错误日志

```shell
Traceback (most recent call last):
  File "E:\workspace\ChuanhuChatGPT\ChuanhuChatbot.py", line 8, in <module>
    from modules.config import *
ModuleNotFoundError: No module named 'modules.config'; 'modules' is not a package
PS E:\workspace\ChuanhuChatGPT> pip install modules
Looking in indexes: https://mirrors.aliyun.com/pypi/simple
Requirement already satisfied: modules in c:\users\86158\appdata\local\programs\python\python310\lib\site-packages (1.0.0)
```

### 运行环境

```markdown
- OS: 
- Browser: 
- Gradio version: 
- Python version:
```

**Comment by Keldos-Li** [comment]
看上去好像没获取全部的更新？您是使用git pull更新的吗？或许可以检查下项目文件夹里的modules文件夹里有没有config.py文件(´・ω・`)

**Comment by Owenfly** [comment]
我后面删除了，重新用git clone ，但还是出现了该问题。modules文件夹里有config.py文件




软工191&nbsp;翁隆鹏
***@***.***



&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "GaiZhenbiao/ChuanhuChatGPT"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2023年4月1日(星期六) 晚上10:25
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [GaiZhenbiao/ChuanhuChatGPT] [本地部署]: 拉取最新代码后运行不了 (Issue #501)





 
看上去好像没获取全部的更新？您是使用git pull更新的吗？或许可以检查下项目文件夹里的modules文件夹里有没有config.py文件(´・ω・`)

**Comment by Keldos-Li** [comment]
神奇，试着在`modules`文件夹内新建一个名为`__init__.py`的空文件？

**Comment by Owenfly** [comment]
> 神奇，试着在`modules`文件夹内新建一个名为`__init__.py`的空文件？

谢谢，可以了

**Comment by Keldos-Li** [comment]
现已在 [常见问题](https://github.com/GaiZhenbiao/ChuanhuChatGPT/wiki/常见问题#modulenotfounderror-no-module-named-modulesmodule-name-modules-is-not-a-package) 中更新~
