### ISSUE TITLE
[Bug]: 官方改了free credit balance的api, 导致credit_grants请求失败

### ISSUE THREAD

**Issue by xingfanxia** [GaiZhenbiao/ChuanhuChatGPT#505]
### 这个bug是否已存在现有issue了？

- [X] 我确认没有已有issue，且已阅读**常见问题**。

### 错误表现

```
2023-04-01 15:53:47,158 [ERROR] [openai_func.py:81] 获取API使用情况失败:API request failed with status code 403: {
  "error": {
    "message": "Your request to GET /dashboard/billing/credit_grants must be made with a session key (that is, it can only be made from the browser). You made it with the following key type: secret.",
    "type": "server_error",
    "param": null,
    "code": null
  }
}
```

### 复现操作

本地和服务端

### 运行环境

- OS: 
- Browser: 
- Gradio version: 
- Python version: 

### 帮助解决

- [X] 我愿意协助解决！

**Comment by xingfanxia** [comment]
需要pass session cookie来获取这个usage的话感觉很麻烦, 这是个会过期的stats得定期取...可能加个跳转openai登录来获取cookie

**Comment by xingfanxia** [comment]
先推了一个修复monthly usage在free credit获取失败后不会再获取的逻辑错误

**Comment by fcmyoo** [comment]
还是抱这个错呢？

**Comment by Keldos-Li** [comment]
先暂时改为这行字，各位觉得如何（只改前端）
<img width="344" alt="image" src="https://user-images.githubusercontent.com/23137268/229349109-574500a8-854c-4f87-b091-9fe7b1eb0c52.png">

**Comment by xingfanxia** [comment]
> ~先暂时改为这行字，各位觉得如何（只改前端）~ <img alt="image" width="344" src="https://user-images.githubusercontent.com/23137268/229349109-574500a8-854c-4f87-b091-9fe7b1eb0c52.png">
> 
> ~然后付费的还是能用的？~
> 
> **UPDATE**
> 
> 才发现你这样改好像免费额度的使用情况也能显示？

付费的接口没变，如果免费报这个接口错误会尝试显示付费的

**Comment by ehehe066** [comment]
https://api.openai.com/v1/dashboard/billing/subscription先用这个获取订阅有效期和额度然后用https://api.openai.com/v1/dashboard/billing/usage?start_date=(当前时间-90天)&&end_date=(当前时间)获取这90天来的用量total_usage
不过数据好像不太准确 大佬们你看看下是否可行
![微信截图_20230403171540](https://user-images.githubusercontent.com/30278102/229467007-00fad079-714e-4998-b9f4-c2d068ee9250.png)

**Comment by Keldos-Li** [comment]
> `https://api.openai.com/v1/dashboard/billing/subscription`
> 
> 先用这个获取订阅有效期和额度然后用
> 
> `https://api.openai.com/v1/dashboard/billing/usage?start_date=(当前时间-90天)&&end_date=(当前时间)`
> 
> 获取这90天来的用量total_usage
> 
> 不过数据好像不太准确 大佬们你看看下是否可行，当然顺便把有效时间加上就更好了
> 
> 

欢迎您提交 pull request！ @ehehe066

**Comment by xingfanxia** [comment]
> `https://api.openai.com/v1/dashboard/billing/subscription` 先用这个获取订阅有效期和额度然后用 `https://api.openai.com/v1/dashboard/billing/usage?start_date=(当前时间-90天)&&end_date=(当前时间)` 获取这90天来的用量total_usage 不过数据好像不太准确 大佬们你看看下是否可行，当然顺便把有效时间加上就更好了 ![微信截图_20230403171540](https://user-images.githubusercontent.com/30278102/229467007-00fad079-714e-4998-b9f4-c2d068ee9250.png)

赞，原来usage接口也包含免费的，你做了付费的handling吗?

**Comment by xingfanxia** [comment]
> 才发现你这样改好像免费额度的使用情况也能显示？

原来usage接口是包含所有usage， 不管免费还是付费，免费只是扣credit

**Comment by wangfeng35** [comment]
[ERROR] [openai_func.py:82] 获取API使用情况失败:API request failed with status code 403: {
  "error": {
    "message": "Your request to GET /dashboard/billing/credit_grants must be made with a session key (that is, it can only be made from the browser). You made it with the following key type: secret.",
    "type": "server_error",
    "param": null,
    "code": null
  }
}

这个是还没修复么

**Comment by oiuv** [comment]
这个可以通过增加一个 session key的方式修复，先访问网页查余额，获取session key，然后可以用这个session key查，session key的有效期很长。

**Comment by xingfanxia** [comment]
我觉得就sunset free credit那个api, 直接用usage api, usage api covers all usage including free+paid. 
chatgpt-web also went this route https://github.com/xingfanxia/chatgpt-web/commit/1187d88593c75a15147306124a3dc023063d64a3

**Comment by GaiZhenbiao** [comment]
可以，直接显示usage

**Comment by lmmsoft** [comment]
可以用 session key， 这篇文章里有代码 https://lmmsoft.github.io/openai_update_check_balance_api/

**Comment by xingfanxia** [comment]
> 可以用 session key， 这篇文章里有代码 https://lmmsoft.github.io/openai_update_check_balance_api/

感觉没什么必要 现在已经显示了usage 够用了+免费账号快成为过去时

**Comment by Dunmingao** [comment]
> 可以用 session key， 这篇文章里有代码 https://lmmsoft.github.io/openai_update_check_balance_api/

我用你的方法可以在程序中调用了

**Comment by runtimme** [comment]
> `https://api.openai.com/v1/dashboard/billing/subscription` 先用这个获取订阅有效期和额度然后用 `https://api.openai.com/v1/dashboard/billing/usage?start_date=(当前时间-90天)&&end_date=(当前时间)` 获取这90天来的用量total_usage 不过数据好像不太准确 大佬们你看看下是否可行，当然顺便把有效时间加上就更好了 ![微信截图_20230403171540](https://user-images.githubusercontent.com/30278102/229467007-00fad079-714e-4998-b9f4-c2d068ee9250.png)

---

end_date=(当前日期+1) 会获得比较准确的结果

**Comment by LaoYutang** [comment]
哪个大佬参考这个提个PR
https://blog.laoyutang.cn/go/apiKeyGetOpenaiBalance.html

**Comment by Keldos-Li** [comment]
> 哪个大佬参考这个提个PR
> 
> https://blog.laoyutang.cn/go/apiKeyGetOpenaiBalance.html

这个问题我们后来已经解决了，现在是有用量显示的。

**Comment by ddbj66** [comment]
获取API使用情况失败:API request failed with status code 401
这个是怎么回事啊，sos

**Comment by ddbj66** [comment]
获取API使用情况失败:API request failed with status code 401
这个是怎么回事啊，🆘

**Comment by simonsww** [comment]
官网关闭了额度检测接口，有谁知道有新的接口吗？

**Comment by surqing** [comment]
```
 [ERROR] [models.py:90] 获取API使用情况失败:API request failed with status code 403: {
  "error": {
    "message": "Your request to GET /dashboard/billing/usage must be made with a session key (that is, it can only be made from the browser). You made it with the following key type: secret.",
    "type": "server_error",
    "param": null,
    "code": null
  }
}

```
每次对话都报这个错，能不能关闭额度显示？

**Comment by GaiZhenbiao** [comment]
> ```
>  [ERROR] [models.py:90] 获取API使用情况失败:API request failed with status code 403: {
>   "error": {
>     "message": "Your request to GET /dashboard/billing/usage must be made with a session key (that is, it can only be made from the browser). You made it with the following key type: secret.",
>     "type": "server_error",
>     "param": null,
>     "code": null
>   }
> }
> ```
> 
> 每次对话都报这个错，能不能关闭额度显示？

请拉取最新版本，最新版本平息了这个报错，并且默认隐藏了额度显示模块。

**Comment by surqing** [comment]
Thank you very much
