### ISSUE TITLE
[功能请求]: gradio的chatbot组件，chatgpt那一方的信息体宽度太小了，尤其显示代码时，在手机上看到的代码宽度特别窄，希望chatgpt那一方的显示信息的主体的宽度和手机宽度差不多大，就像官方显示信息一样

### ISSUE THREAD

**Issue by weixhishu** [GaiZhenbiao/ChuanhuChatGPT#515]
### 相关问题

[功能请求]: gradio的chatbot组件，chatgpt那一方的信息体宽度太小了，尤其显示代码时，在手机上看到的代码宽度特别窄，希望chatgpt那一方的显示信息的主体的宽度和手机宽度差不多大，就像官方显示信息一样

### 可能的解决办法

修改官方gradio的chatbot组件，或有隐藏api可用

### 帮助开发

- [ ] 我愿意协助开发！

**Comment by Keldos-Li** [comment]
这个好说。我回头改改。

其实是，本来gradio的显示就是宽度撑满的，我给改小了。

**Comment by weixhishu** [comment]
> 这个好说。我回头改改。
> 
> 其实是，本来gradio的显示就是宽度撑满的，我给改小了。

看到了，就在自定义css文件[data-testid = "bot"]这里

**Comment by weixhishu** [comment]
> 这个好说。我回头改改。
> 
> 其实是，本来gradio的显示就是宽度撑满的，我给改小了。
还有个问题，也不算bug，我服务器使用的代理用的是rule模式，检测ip属地的时候检测的是本地地址，不是调用api的地址。
还有个ui问题，设置界面使得手机使用的时候不太方便，希望使用隐藏式侧栏的方式显示设置，就像chatgpt官方一样

**Comment by weixhishu** [comment]
> > 这个好说。我回头改改。
> > 其实是，本来gradio的显示就是宽度撑满的，我给改小了。
> 
> 看到了，就在自定义css文件[data-testid = "bot"]这里
还有个问题，也不算bug，我服务器使用的代理用的是rule模式，检测ip属地的时候检测的是本地地址，不是调用api的地址。
还有个ui问题，设置界面使得手机使用的时候不太方便，希望使用隐藏式侧栏的方式显示设置，就像chatgpt官方一样

**Comment by weixhishu** [comment]
> 这个好说。我回头改改。
> 
> 其实是，本来gradio的显示就是宽度撑满的，我给改小了。
还有个问题，也不算bug，我服务器使用的代理用的是rule模式，检测ip属地的时候检测的是本地地址，不是调用api的地址。
还有个ui问题，设置界面使得手机使用的时候不太方便，希望使用隐藏式侧栏的方式显示设置，就像chatgpt官方一样

**Comment by weixhishu** [comment]
还有个问题，也不算bug，我服务器使用的代理用的是rule模式，检测ip属地的时候检测的是本地地址，不是调用api的地址。
还有个ui问题，设置界面使得手机使用的时候不太方便，希望使用隐藏式侧栏的方式显示设置，就像chatgpt官方一样
