### ISSUE TITLE
[功能请求]: 放开 api key 长度要求限制

### ISSUE THREAD

**Issue by zengbo** [GaiZhenbiao/ChuanhuChatGPT#526]
### 相关问题

 ☹发生了错误：API key长度不是51位，请检查是否输入正确。

### 可能的解决办法

去掉 API key 长度判断

### 帮助开发

- [ ] 我愿意协助开发！

### 补充说明

我使用的是其他人做的 API proxy，使用了自己的 api key 认证，长度和官方的不一样

**Comment by chawxj** [comment]
同样请求增加这个功能，建议不变更现有逻辑，额外增加一个参数，用来定义第三方的api key

**Comment by Keldos-Li** [comment]
Feature added within 18f19f4a4534ec52fe2dd034c976878aef9f6896 ([Chuan Hu](https://github.com/GaiZhenbiao)).
