### ISSUE TITLE
[功能请求]:  不支持token登录嘛

### ISSUE THREAD

**Issue by shuncon** [GaiZhenbiao/ChuanhuChatGPT#536]
### 相关问题

不支持token登录嘛

### 可能的解决办法

不支持token登录嘛

### 帮助开发

- [X] 我愿意协助开发！

### 补充说明

不支持token登录嘛

**Comment by Keldos-Li** [comment]
并不理解。没有必要。技术路线也没考虑。

而且如果先登录ChatGPT再返回使用我们的脚本是不是一种脱裤子放　的行为呢？
