### ISSUE TITLE
[功能请求]: 能否针对多用户登录设置单个账户同一时间只允许登录一次，每个账户分别计算每月总使用的token总数？

### ISSUE THREAD

**Issue by qhdesnldop474** [GaiZhenbiao/ChuanhuChatGPT#538]
### 可能的解决办法

无

### 帮助开发

- [ ] 我愿意协助开发！

**Comment by HsunGong** [comment]
有兴趣研究不同用户分别统计token数量的问题。
但是gradio的state需要使用global信息才行，在尝试。。

**Comment by Keldos-Li** [comment]
> 能否针对多用户登录设置单个账户同一时间只允许登录一次

没有必要，也不现实，我自己就经常多设备用。

> 每个账户分别计算每月总使用的token总数？

- Duplicate with #510

不过也不是很现实……
