### ISSUE TITLE
[功能请求]: 复制对话历史到剪贴板/生成对话历史的jpg图片并复制到剪贴板

### ISSUE THREAD

**Issue by xingfanxia** [GaiZhenbiao/ChuanhuChatGPT#545]
### 相关问题

感觉现在的导出记录方式都比较繁琐, 最近加了markdown file导出方便了一些, 但我觉得可以加个复制内容到剪贴板的功能

### 可能的解决办法

- [ ] 复制raw markdown到剪贴板
- [ ] 复制rendered jpg到剪贴板

### 帮助开发

- [X] 我愿意协助开发！

### 补充说明

可以用这个js lib 生成图片
https://github.com/bubkoo/html-to-image

_No response_

**Comment by Keldos-Li** [comment]
可以可以……虽然觉得生成图片可能意义不大？

以前有尝试过
![image](https://user-images.githubusercontent.com/23137268/229985652-01df92f3-9570-40ed-97d7-4f41a2eaeb0d.jpeg)

**Comment by xingfanxia** [comment]
> 可以可以……虽然觉得生成图片可能意义不大？
> 
> 以前有尝试过 ![image](https://user-images.githubusercontent.com/23137268/229985652-01df92f3-9570-40ed-97d7-4f41a2eaeb0d.jpeg)

1. 分享给non technical的朋友/social media生成长对话图片比起一张张截图方便很多
2. chatgpt给的table也是 markdown syntax, 应该可以export

**Comment by xingfanxia** [comment]
btw, 有tg/discord群之类的交流吗

**Comment by Keldos-Li** [comment]
这两天写了太多js，已经不想再碰js了（

之后我再看看吧，应该能搞的。

**Comment by GaiZhenbiao** [comment]
> btw, 有tg/discord群之类的交流吗

现在Readme里加了tg群的链接

**Comment by shiluanzzz** [comment]
+ 1
当机器人输出的内容包含渲染过后的公式，直接选中文本复制公式会乱码。
直接复制内容到剪贴板应该能解决这个问题。

**Comment by yhweb** [comment]
> 这两天写了太多js，已经不想再碰js了（
> 
> 之后我再看看吧，应该能搞的。

能否在已发送或者已回复的文本框添加一个复制按钮呢? 比如在已发送的外部左上角  或者在已回复文本框的右上角 点击后直接拷贝到粘贴板中 大佬同意我可以尝试提供commit 虽然好几年没写过js了

**Comment by xingfanxia** [comment]
> > 这两天写了太多js，已经不想再碰js了（
> > 之后我再看看吧，应该能搞的。
> 
> 能否在已发送或者已回复的文本框添加一个复制按钮呢? 比如在已发送的外部左上角 或者在已回复文本框的右上角 点击后直接拷贝到粘贴板中 大佬同意我可以尝试提供commit 虽然好几年没写过js了

可以试试交个pr

**Comment by Keldos-Li** [comment]
[Copy Bot Content.js.zip](https://github.com/GaiZhenbiao/ChuanhuChatGPT/files/11166079/Copy.Bot.Content.js.zip)

我把之前写的js放出来好了……你们可以先用或先拿着改。。

不过正如我之前说的，这不仅仅是一个前端问题，要获取bot的对话源数据，是后端也要一起改的。整个代码逻辑会变，到时候弄的话，我写的js应该是完全不一样的思路和逻辑。目前这个做法思路是走不下去的。

**Comment by Keldos-Li** [comment]
导出为图像的试着写过了，问题蛮多的，而且对Safari兼容性不好……后面讨论觉得大家还是自己截图好了，这个功能就不做了……

复制ai源输出的写好了：
7cc0491e4fea088578c387b2b43e477351378b35
