### ISSUE TITLE
Errno2 no such fileor 

### ISSUE THREAD

**Issue by 05lpl** [GaiZhenbiao/ChuanhuChatGPT#55]
<img width="706" alt="image" src="https://user-images.githubusercontent.com/91683680/223324589-f42d2cf1-621d-4518-bf0a-d0254cd0a8ec.png">
安装了py3， requirements 也装完了，但是就运行不了

**Comment by GaiZhenbiao** [comment]
找不到文件……检查一下文件路径吧

**Comment by 05lpl** [comment]
bat怎么改路径啊？
文件里面是 start powershell.exe -NoExit -Command "python path\to\ChuanhuChatbot.py"
<img width="573" alt="image" src="https://user-images.githubusercontent.com/91683680/223401886-d719a5dc-91f3-4019-8e5a-b064a88a18ad.png">

**Comment by 05lpl** [comment]
> bat怎么改路径啊？网上查了半天没查到 文件里面是 start powershell.exe -NoExit -Command "python path\to\ChuanhuChatbot.py" <img alt="image" width="573" src="https://user-images.githubusercontent.com/91683680/223401886-d719a5dc-91f3-4019-8e5a-b064a88a18ad.png">

**Comment by GaiZhenbiao** [comment]
把`path/to/ChuanhuChatbot.py`改成实际路径，比如`C:\\ChuanhuChatbot.py`之类的

**Comment by GaiZhenbiao** [comment]
emm，我手头没有Windows电脑，不好测试……你直接用Powershell吧，不是非得用这个
