### ISSUE TITLE
[功能请求]: 夜间模式切换为白天模式后，字体无法看清

### ISSUE THREAD

**Issue by lijiachang** [GaiZhenbiao/ChuanhuChatGPT#552]
### 相关问题

<img width="1274" alt="Snipaste_2023-04-06_11-43-18" src="https://user-images.githubusercontent.com/28041718/230266982-a5b11be6-ff3d-4f65-a37c-cca0e642dcf9.png">

到了夜晚浏览器会切换到夜间模式，到了第二天自动切换为白天模式后，字体无法看清

### 可能的解决办法

建议增加主题选项，手动调节

### 帮助开发

- [ ] 我愿意协助开发！

**Comment by lijiachang** [comment]
当然，刷新页面可以恢复。那聊天记录也就没了

**Comment by Keldos-Li** [comment]
gradio有一个用于亮暗色显示的预设dark类，但切换机制我有点看不懂……我看看我能不能自己写js一个覆盖一下。
