### ISSUE TITLE
[功能请求]: 添加终止按钮

### ISSUE THREAD

**Issue by a327958099** [GaiZhenbiao/ChuanhuChatGPT#554]
### 可能的解决办法

在使用过程中有时回答内容不符合自己的预期，这时希望能有一个终止按钮能终止当前回答，这样是否有节省tokens的功能？

### 帮助开发

- [ ] 我愿意协助开发！

**Comment by Keldos-Li** [comment]
有的，早的版本写的“取消”，昨天改成了图标，可能太不清楚了，我现在改成了红色的图标（但按钮是灰色的）

**Comment by Keldos-Li** [comment]
发送前：
<img width="452" alt="image" src="https://user-images.githubusercontent.com/23137268/230384523-df944055-9035-41e8-830b-01d657738eb5.png">

GPT回答时：
<img width="460" alt="image" src="https://user-images.githubusercontent.com/23137268/230384397-a36f8dbb-c3df-4975-8da7-853f2ae65032.png">
