### ISSUE TITLE
[Bug]: 请求过于频繁，请5s后再试。

### ISSUE THREAD

**Issue by wenzhenze** [GaiZhenbiao/ChuanhuChatGPT#555]
### 这个bug是否已存在现有issue了？

- [X] 我确认没有已有issue，且已阅读**常见问题**。

### 错误表现

在使用NSFW版本中，输入任意文字均会返回：请求过于频繁，请5s后再试。

### 复现操作

某一天突然复现，已经尝试了新生成的API依旧没有解决

### 运行环境

- OS: 
- Browser: 
- Gradio version: 
- Python version: 

### 帮助解决

- [ ] 我愿意协助解决！

**Comment by GaiZhenbiao** [comment]
那个版本不是我们维护的。
