### ISSUE TITLE
[其他]: 今天突然“读取超时，无法获取对话。请检查网络连接，或者API-Key是否有效。”

### ISSUE THREAD

**Issue by cxx2002** [GaiZhenbiao/ChuanhuChatGPT#559]
### 是否已存在现有反馈与解答？

- [X] 我确认没有已有issue或discussion，且已阅读**常见问题**。

### 错误描述

[其他]: 今天用起来出问题啊，为啥

### 复现操作

[其他]: 今天用起来出问题啊，为啥

### 运行环境

- OS: 
- Browser: 
- Gradio version: 
- Python version: 
(或您的其他运行环境信息)

**Comment by Keldos-Li** [comment]
啥问题？你就这么写我们就当没问题🫥

**Comment by LisnXy** [comment]
确实有些问题，我是部署在了linux服务器上，可以正常获取API的额度，但是对话时显示
`读取超时，无法获取对话。请检查网络连接，或者API-Key是否有效。`
昨天还是好的，并且本地确认过API-Key可以正常使用，并且部署在同一个服务器上的gpt另一个项目也是可用的，非常奇怪。

**Comment by morestart** [comment]
确实，看了后台日志应该是没有返回，验证过key是没问题的

**Comment by LisnXy** [comment]
> 确实，看了后台日志应该是没有返回，验证过key是没问题的

初步怀疑是今天openai的服务器返回有点慢，超过等待时长了，我去排查一下试试

**Comment by morestart** [comment]
> 

是的 我调整超时时间到60就行了

**Comment by peiyun1982** [comment]
我也遇到了童谣的问题，如何调整超时时间呢？

**Comment by LisnXy** [comment]
> 我也遇到了童谣的问题，如何调整超时时间呢？

在`/modules/preset.py`里面调一下，默认是10s，我调到了30s，大概是一个可用的数值。

**Comment by peiyun1982** [comment]
> > 我也遇到了童谣的问题，如何调整超时时间呢？
> 
> 在`/modules/preset.py`里面调一下，默认是10s，我调到了30s，大概是一个可用的数值。

谢谢！我直接调到100了，现在能正常回复了

**Comment by Keldos-Li** [comment]
不知道 issue author 的问题是不是你们说的同一个问题qwq，但既然大家都在讨论这个，那我订正一下标题吧

**Comment by xiaheli** [comment]
我的服务器以及本地主机都确认了OpenAI昨日、今日的反应速度确实下降。

**Comment by OYcedar** [comment]
对，API变得好慢，感觉是不是服务器负载爆了

**Comment by Yike-Ye** [comment]
今天我似乎也遇到了一样的情况。显示的是传输完毕但是界面显示的是空白的长条。macOS 13.2 

2023-04-12 14:56:12,634 [INFO] [chat_func.py:277] 输入为：hi
2023-04-12 14:56:12,642 [INFO] [chat_func.py:353] 使用流式传输
2023-04-12 14:56:12,642 [INFO] [chat_func.py:97] 实时回答模式
2023-04-12 14:56:12,843 [INFO] [chat_func.py:120] 输入token计数: 19
2023-04-12 14:56:13,815 [ERROR] [openai_func.py:82] 获取API使用情况失败:API request failed with status code 403: {
  "error": {
    "message": "Your request to GET /dashboard/billing/credit_grants must be made with a session key (that is, it can only be made from the browser). You made it with the following key type: secret.",
    "type": "server_error",
    "param": null,
    "code": null
  }
}

2023-04-12 14:56:23,471 [INFO] [chat_func.py:389] 传输完毕。当前token计数为[19]
2023-04-12 14:56:23,471 [INFO] [chat_func.py:391] 回答为：
