### ISSUE TITLE
[Bug]: 手机浏览器切至后台生成回复完成后会导致停止按钮恢复不成发送按钮，且之后每次生成完毕后都恢复不了

### ISSUE THREAD

**Issue by weixhishu** [GaiZhenbiao/ChuanhuChatGPT#568]
### 这个bug是否已存在现有issue了？

- [x] 我确认没有已有issue，且已阅读**常见问题**。

### 错误表现

[Bug]: 手机浏览器切至后台生成回复完成后会导致停止按钮恢复不成发送按钮，且之后每次生成完毕后都恢复不了，一直没有发送按钮。
       但可以用再生成按钮来进行对话，对话完后恢复成发送按钮，但再用发送按钮进行一次对话后，对话完，还是恢复不了。也就是对于发送按钮进行的问题，停止按钮永远无法恢复成发送

### 复现操作

发送问题让chatgpt回复，回复过程切换至其他应用，让chatgpt后台生成文字，生成完后切回浏览器，导致停止按钮不恢复成发送按钮

### 错误日志

```shell
正常显示
```

### 运行环境

- OS: 安卓
- Browser: 手机自带浏览器
- Gradio version: 最新
- Python version: python10

### 帮助解决

- [ ] 我愿意协助解决！

### 补充说明

这个操作会使得gradio组件的then方法无法判断yield生成器是否完成，使得最后一个then函数无法执行，使用同一个生成器函数的then都无法再进行判断，所以按enter和发送方式的方法都无法恢复成发送按钮，但按生成的可以。具体原因不明，一个死马当活马医的方法就是在生成器的每个函数yield的时候都附带输出按钮的状态

**Comment by Keldos-Li** [comment]
建议去gradio那边提交issue

**Comment by Keldos-Li** [comment]
在新的 gradio3.33.1 中没有这个问题了（应该）。
