### ISSUE TITLE
[Bug]: TypeError: object of type 'int' has no len()

### ISSUE THREAD

**Issue by chinwh2019** [GaiZhenbiao/ChuanhuChatGPT#569]
### 这个bug是否已存在现有issue了？

- [X] 我确认没有已有issue，且已阅读**常见问题**。

### 错误表现

 in construct_token_message
    for i in range(len(tokens)):
                   ^^^^^^^^^^^
TypeError: object of type 'int' has no len()

### 复现操作

1. Install everything following instructions 
2. Error occurs when switching to deactivate real-time stream or press 'Summarize chat' 

### 运行环境

- OS: MacOS
- Browser: Chrome
- Gradio version: 3.24.1
- Python version: 3.11

### 帮助解决

- [X] 我愿意协助解决！

### 补充说明

I  have fixed the issue and would like to pull the request if you are allowed.

**Comment by Keldos-Li** [comment]
Yes, this is a known bug, but it seems that none of us planned to solve it before... I'm glad to hear that you have fixed it, and you are welcome to submit pull request.

是的，这是一个已知问题，然而似乎之前我们没一个人打算解决它（可能大家都在忙）……很高兴听说你已经修复了它，我们欢迎您提交Pull Request.

**Comment by chenoh** [comment]
这是来自QQ邮箱的假期自动回复邮件。
 
您好，我最近正在休假中，无法亲自回复您的邮件。我将在假期结束后，尽快给您回复。

**Comment by chinwh2019** [comment]
You guys have done a fantastic job! It's my pleasure to submit my pull request. Please let me know your rules for the pull request. I am ready for that.

**Comment by Keldos-Li** [comment]
I have written a pull request template, and will see our comment and suggestions when you open a new pull request.

Here's our [contributing guide](https://github.com/GaiZhenbiao/ChuanhuChatGPT/wiki/贡献指南). I wrote it in Chinese, but hopefully you can read it.

And... In fact, you can just submit your code any way you like. Though we set rules, they are not necessary for some fixes.

**Comment by weixhishu** [comment]
This is the vacation auto reply email from QQmail.
Hello, I am currently on vacation and cannot personally reply to your email. I will reply to you as soon as possible after the holiday ends.

**Comment by chinwh2019** [comment]
> I have written a pull request template, and you will see our comment and suggestions when you open a new pull request.
> 
> Here's our [contributing guide](https://github.com/GaiZhenbiao/ChuanhuChatGPT/wiki/%E8%B4%A1%E7%8C%AE%E6%8C%87%E5%8D%97). I wrote it in Chinese, but hopefully you can read it.
> 
> And... In fact, you can just submit your code any way you like. Though we set rules, they are not necessary for some fixes.

I have submitted my pull request! thanks again for the great work!

**Comment by Keldos-Li** [comment]
Fixed via https://github.com/GaiZhenbiao/ChuanhuChatGPT/pull/574.
