### ISSUE TITLE
fail installing gradio 

### ISSUE THREAD

**Issue by jiang54** [GaiZhenbiao/ChuanhuChatGPT#57]
运行 pip install gradio --upgrade --force-reinstall 遇到错误，求解

Building wheels for collected packages: orjson
  Building wheel for orjson (pyproject.toml) ... error
  error: subprocess-exited-with-error

  × Building wheel for orjson (pyproject.toml) did not run successfully.
  │ exit code: 1
  ╰─> [1462 lines of output]
      Running `maturin pep517 build-wheel -i c:\users\woshi\appdata\local\programs\python\python38-32\python.exe --compatibility off --target i686-pc-windows-msvc`
      馃摝 Including license file "C:\Users\woshi\AppData\Local\Temp\pip-install-l8q22sjy\orjson_67485430601d4ac5858f65d14f071b31\LICENSE-APACHE"
      馃摝 Including license file "C:\Users\woshi\AppData\Local\Temp\pip-install-l8q22sjy\orjson_67485430601d4ac5858f65d14f071b31\LICENSE-MIT"
      馃嵐 Building a mixed python/rust project
      馃敆 Found pyo3-ffi bindings
      馃悕 Found CPython 3.8 at c:\users\woshi\appdata\local\programs\python\python38-32\python.exe
         Compiling target-lexicon v0.12.6
         Compiling autocfg v1.1.0
         Compiling once_cell v1.17.1
         Compiling serde v1.0.152
         Compiling version_check v0.9.4
         Compiling rustversion v1.0.11
         Compiling libc v0.2.139
         Compiling itoa v1.0.5
         Compiling cfg-if v1.0.0
         Compiling ryu v1.0.12
         Compiling cc v1.0.79
         Compiling serde_json v1.0.93
         Compiling num-traits v0.2.15
      error: could not compile `cfg-if` due to 3 previous errors
      warning: build failed, waiting for other jobs to finish...
      error: could not compile `itoa` due to 10 previous errors
      error: could not compile `ryu` due to 39 previous errors
      error: could not compile `once_cell` due to 145 previous errors
      馃挜 maturin failed
        Caused by: Failed to build a native library through cargo
        Caused by: Cargo build finished with "exit code: 101": `"cargo" "rustc" "--release" "--target" "i686-pc-windows-msvc" "--manifest-path" "C:\\Users\\woshi\\AppData\\Local\\Temp\\pip-install-l8q22sjy\\orjson_67485430601d4ac5858f65d14f071b31\\Cargo.toml" "--message-format" "json" "--lib"`
      error[E0463]: can't find crate for `core`
        |
        = note: the `i686-pc-windows-msvc` target may not be installed
        = help: consider downloading the target with `rustup target add i686-pc-windows-msvc`

      error[E0463]: can't find crate for `compiler_builtins`

      error: aborting due to 2 previous errors

      For more information about this error, try `rustc --explain E0463`.

      error[E0463]: can't find crate for `core`
        |
        = note: the `i686-pc-windows-msvc` target may not be installed
        = help: consider downloading the target with `rustup target add i686-pc-windows-msvc`

      error[E0463]: can't find crate for `compiler_builtins`

      error[E0463]: can't find crate for `core`

**Comment by jiang54** [comment]
中间太长了144个错误
error: aborting due to 144 previous errors


      Some errors have detailed explanations: E0405, E0412, E0425, E0432, E0463, E0531.

      For more information about an error, try `rustc --explain E0405`.

      Error: command ['maturin', 'pep517', 'build-wheel', '-i', 'c:\\users\\woshi\\appdata\\local\\programs\\python\\python38-32\\python.exe', '--compatibility', 'off', '--target', 'i686-pc-windows-msvc'] returned non-zero exit status 1
      [end of output]

  note: This error originates from a subprocess, and is likely not a problem with pip.
  ERROR: Failed building wheel for orjson
Failed to build orjson
ERROR: Could not build wheels for orjson, which is required to install pyproject.toml-based projects

**Comment by GaiZhenbiao** [comment]
pip3能行吗？

**Comment by jiang54** [comment]
不行呀，哥，一样的错误

This error originates from a subprocess, and is likely not a problem with pip.
  ERROR: Failed building wheel for orjson
Failed to build orjson
ERROR: Could not build wheels for orjson, which is required to install pyproject.toml-based projects

**Comment by GaiZhenbiao** [comment]
你不会再用32位的ARM架构CPU吧？

**Comment by jiang54** [comment]
不是，我用的那个2600

**Comment by GaiZhenbiao** [comment]
诡异的bug。建议你用Docker。
