### ISSUE TITLE
[功能请求]: 能否添加“使用账号回答”功能而非API回答

### ISSUE THREAD

**Issue by GeekHank** [GaiZhenbiao/ChuanhuChatGPT#577]
### 相关问题

目前api响应很慢，经常报错

### 可能的解决办法

使用账号通过网页授权方式进行回答

### 帮助开发

- [ ] 我愿意协助开发！

**Comment by HsunGong** [comment]
这不太现实，建议你换个梯子更好。。。

**Comment by GeekHank** [comment]
最近api很慢，想看看能不能借鉴gpt插件实现通过账号授权回答，应该不是网络问题



Sent&nbsp;from&nbsp;my&nbsp;iPhone


------------------ 原始邮件 ------------------
From: Xun Gong ***@***.***&gt;
发送时间: 04/09/2023, 20:15
To: GaiZhenbiao/ChuanhuChatGPT ***@***.***&gt;
抄送: GeekHank ***@***.***&gt;, Author ***@***.***&gt;
Subject: Re: [GaiZhenbiao/ChuanhuChatGPT] [功能请求]: 能否添加“使用账号回答”功能而非API回答 (Issue #577)





 
这不太现实，建议你换个梯子更好。。。

**Comment by xingfanxia** [comment]
网页更慢啊

**Comment by GeekHank** [comment]
快很多



Sent&nbsp;from&nbsp;my&nbsp;iPhone


------------------ 原始邮件 ------------------
From: Philo-Sophia ***@***.***&gt;
发送时间: 04/11/2023, 06:13
To: GaiZhenbiao/ChuanhuChatGPT ***@***.***&gt;
抄送: GeekHank ***@***.***&gt;, Author ***@***.***&gt;
Subject: Re: [GaiZhenbiao/ChuanhuChatGPT] [功能请求]: 能否添加“使用账号回答”功能而非API回答 (Issue #577)





 
网页更慢啊
