### ISSUE TITLE
[功能请求]: 有没有和多文件chat的方法?

### ISSUE THREAD

**Issue by ca1123** [GaiZhenbiao/ChuanhuChatGPT#578]
### 相关问题

现在Index只能工作在一个文件上, 但是很多源码之类的东西都是多个文件的. 反正都是llama-index在后面用word2vec控制context, 原理上不妨碍一次index多个文件吧. 我如果git clone下来一个仓库, 那丢很多源码进去要求分析都是合理的不是. 还有就是网页形式的ref doc, 也是有这种多文件index需求的.

### 可能的解决办法

能够一次指定多个文件给word2vec处理, 通过上传的方式, 或者指定URL的方式.

### 帮助开发

- [ ] 我愿意协助开发！

**Comment by GaiZhenbiao** [comment]
从一开始，你就**可以**上传多个文件啊，没有上限

**Comment by ca1123** [comment]
> 从一开始，你就**可以**上传多个文件啊，没有上限

我明白了, 得一下子传上去, 不能一个一个拖拽, 这倒不是大问题.

**Comment by ca1123** [comment]
那我有办法处理文档网站么? 比如javadoc, 比如clj-doc

**Comment by xingfanxia** [comment]
一直支持多文件

**Comment by MZhao-ouo** [comment]
> 那我有办法处理文档网站么? 比如javadoc, 比如clj-doc

转换成markdown或者txt。后续可能会加入这些文档网站的支持，但优先级不高。如果特别希望有这个功能请另开issue，先close了
