### ISSUE TITLE
[功能请求]: 希望能够支持多账户注册使用

### ISSUE THREAD

**Issue by Chan084352** [GaiZhenbiao/ChuanhuChatGPT#579]
### 相关问题

目前仅可默认配置的账户，希望可以支持多账户

### 可能的解决办法

支持前后端分离

### 帮助开发

- [X] 我愿意协助开发！

**Comment by roboger** [comment]
也可以 自定义 密码 访问 更方便

**Comment by GaiZhenbiao** [comment]
支持的呀

**Comment by roboger** [comment]
> 支持的呀

只有填写key，没有填写 自定义 访问码的地方吧

**Comment by GaiZhenbiao** [comment]
请详细阅读一下本项目的readme和wiki，支持多用户、多密码登陆的。
