### ISSUE TITLE
网页修改System prompt好像没有实际效果，是init prompt在起作用

### ISSUE THREAD

**Issue by Ike-yang** [GaiZhenbiao/ChuanhuChatGPT#58]

**Comment by GaiZhenbiao** [comment]
<img width="1024" alt="image" src="https://user-images.githubusercontent.com/51039745/223338988-a921cc93-d6c2-4978-9bea-7a4fbefe0df8.png">
有用的

**Comment by Ike-yang** [comment]
是，我刚发现，是我自己prompt不太对
