### ISSUE TITLE
Something went wrong

### ISSUE THREAD

**Issue by g-wellsa** [GaiZhenbiao/ChuanhuChatGPT#582]
### 这个bug是否已存在现有issue了？

- [X] 我确认没有已有issue，且已阅读**常见问题**。

### 错误表现

![image](https://user-images.githubusercontent.com/4343884/230912083-34791d1b-d17a-4f39-aad6-217c3233a87c.png)
总是报这个!

### 复现操作

搞什么飞机，我按照已有的issue进行解决，但无论怎么弄，都不行，直到我自己写了个请求demo发现ok的，所以我强烈怀疑你们的代码除了bug，严重的bug！！！

### 错误日志

```shell
不会输出任何错误日志
```

### 运行环境

OS: Windows11 22H2
Browser: edge
Gradio version: 3.22.1
Python version: 3.9.5

### 帮助解决

- [X] 我愿意协助解决！

### 补充说明

无

**Comment by Keldos-Li** [comment]
兄弟 冷静……

**Comment by GaiZhenbiao** [comment]
应该是代理了127.0.0.1导致的。请看readme。不要开全局代理。

**Comment by xingfanxia** [comment]
为什么这么激动。。。这是个免费的开源项目有bug很正常

**Comment by Keldos-Li** [comment]
希望你冷静下来了。。QAQ
1. 正如开源协议所述，本程序作为自由软件，**没有品质担保**，确实可能存在问题。
2. 但是这个问题确实不是我们的bug。如果您看过 [常见问题](https://github.com/GaiZhenbiao/ChuanhuChatGPT/wiki/常见问题#something-went-wrong-expecting-value-line-1-column-1-char-0)，或许您就更能理解了……我们这个和您自己写请求确实多走了一步，如果全局代理会导致127.0.0.0网页无法和后端python程序通讯。因此，不要开全局代理，也不要在如clash等的软件中将其设为系统代理。
