### ISSUE TITLE
[本地部署]: ‘str’ object has no attribute ‘api_key’

### ISSUE THREAD

**Issue by chucksylar** [GaiZhenbiao/ChuanhuChatGPT#584]
### 是否已存在现有反馈与解答？

- [X] 我确认没有已有issue或discussion，且已阅读**常见问题**。

### 是否是一个代理配置相关的疑问？

- [X] 我确认这不是一个代理配置相关的疑问。

### 错误描述

本地部署多apikey的时候报错，‘str’ object has no attribute ‘api_key’， 一个apikey的时候使用正常

### 复现操作

1. 开启多账户apikey模式

### 运行环境

```markdown
- OS: mac
- Browser: Chrome
- Gradio version: 3.24.1
- Python version: 3.9
```

**Comment by realnoob007** [comment]
我也出现了这个问题

**Comment by Peanut-GGG** [comment]
是装饰器在返回的时候 将self赋值成了api_key 在modules.shared.State.switching_api_key
