### ISSUE TITLE
[本地部署]: windows本地部署chatglm-6b-int4 报错

### ISSUE THREAD

**Issue by liuyunrui123** [GaiZhenbiao/ChuanhuChatGPT#587]
### 是否已存在现有反馈与解答？

- [X] 我确认没有已有issue或discussion，且已阅读**常见问题**。

### 是否是一个代理配置相关的疑问？

- [X] 我确认这不是一个代理配置相关的疑问。

### 错误描述

该chatglm-6b-int4模型以及python运行环境已经在原有chatglm-6b项目本地部署中验证过可以正常使用。

在ChuanhuChatGPT项目中安装好环境依赖后，并在该项目根目录中新建了models文件夹并放置了模型，运行启动网页正常，
在网页中手动选择模型为chatglm-6b-int4时会报错，错误信息为“ Unable to compare versions for numpy>=1.17: need=1.17 found=None. This is unusual. Consider reinstalling numpy.”

我本地numpy版本为1.24.2

### 复现操作

1.本地部署
2.选择chatglm-6b-int4模型
3.出现报错

### 错误日志

```shell
川虎的温馨提示：访问 http://localhost:7860 查看界面
Reloading javascript...
Running on local URL:  http://127.0.0.1:7860

To create a public link, set `share=True` in `launch()`.
2023-04-10 22:44:57,025 [INFO] [models.py:426] 正在加载ChatGLM模型: chatglm-6b-int4
2023-04-10 22:44:57,065 [ERROR] [models.py:448] Unable to compare versions for numpy>=1.17: need=1.17 found=None. This is unusual. Consider reinstalling numpy.
```

### 运行环境

```markdown
- OS: windows
- Browser: edge
- Gradio version: 3.24.1
- Python version: 3.9
```

### 补充说明

![UOJPZ@T79P09_)ISK CTPWI](https://user-images.githubusercontent.com/57593875/230924911-b726863e-aac8-496d-87dd-c70eaf49dd00.png)

**Comment by GaiZhenbiao** [comment]
按它说的，重装numpy试试？

**Comment by liuyunrui123** [comment]
抱歉，是我的问题，这个问题是由于chatglm环境遭到了破坏，这个报错是transformers导致。按照chatglm那边的issue， 重新配置了下python环境，升级transformers==4.27.1 ，且模型路径必须给绝对路径而不是相对路径，问题就解决了。这个项目中对应的加载chatglm模型后面也需要这样改动。
