### ISSUE TITLE
对于从环境变量和代码内部写入的秘钥, 请不要展示在 UI 界面上

### ISSUE THREAD

**Issue by DIYer22** [GaiZhenbiao/ChuanhuChatGPT#59]
![image](https://user-images.githubusercontent.com/10448025/223341866-09f16259-9eec-40af-a0dd-1aea3e6d246e.png)

对于从环境变量和代码内部写入的秘钥, 请不要展示在 UI 界面上, 否则 别人可以通过F12更改 HTML  password 来盗取 API key

**Comment by GaiZhenbiao** [comment]
现在在源码中提供了一个开关，可以选择是否需要隐藏这个输入框。
