### ISSUE TITLE
[Bug]: windows本地部署chatglm-6b，每多开一个网页或重新刷新网页都会多占一份模型内存，导致爆显存

### ISSUE THREAD

**Issue by liuyunrui123** [GaiZhenbiao/ChuanhuChatGPT#593]
### 这个bug是否已存在现有issue了？

- [X] 我确认没有已有issue，且已阅读**常见问题**。

### 错误表现

windows本地部署chatglm-6b，没多开一个网页或重新加载都会多占一份模型内存，导致爆显存。另外选择模型的话，选过chatglm-6b-int4在切换到chatglm-6b，那么会占用这两份显存，之前模型的显存并不会被释放。

### 复现操作

1.正常完成本地部署
2.直接使用本地chatglm模型可以正常运行
3.新开一个网页，显存占用翻倍，直到爆显存退出

### 运行环境

- OS: windows
- Browser: edge
- Gradio version: 3.24.1
- Python version: 3.9

### 帮助解决

- [ ] 我愿意协助解决！

**Comment by GaiZhenbiao** [comment]
我正在修复这个问题

**Comment by LeeKonyu** [comment]
> 另外还有个现象，如果设置chatglm-6b模型为默认启动选择的模型，那么启动后是直接占用了原有的双倍显存，聊天就会爆显存

大佬，能加个联系方式吗？我才开始接触这个，现在正在用chatglm，想通过chuanhu的方式来传文件索引，想问问你怎么实现的。

**Comment by MZhao-ouo** [comment]
已修复

**Comment by Chrosea** [comment]
这个问题在最新版依然存在，可不可以把默认模型载入和网页渲染的过程分离

**Comment by Evantso** [comment]
最新版，本地加载qwen也是同样的问题，会爆显存
