### ISSUE TITLE
[功能请求]: 请问下api_host填什么格式，有示例么

### ISSUE THREAD

**Issue by ayamzh** [GaiZhenbiao/ChuanhuChatGPT#594]
### 相关问题

请问下api_host填什么格式，有示例么

### 可能的解决办法

请问下api_host填什么格式，有示例么

### 帮助开发

- [X] 我愿意协助开发！

**Comment by Keldos-Li** [comment]
如果你想问的是在config.py里怎么设置的话…………哎呀，这部分的代码还没写，是的，，确实，我当时以为很快 @MZhao-ouo 就能把这个加上，就先把这部分写进了README里，但事实上似乎并没有QAQ

现在你暂时可以在这里设置url：
https://github.com/GaiZhenbiao/ChuanhuChatGPT/blob/9bc06d3a38d945ea7aa8b43df5a0b48f389aa4df/modules/presets.py#L10-L12

**Comment by MZhao-ouo** [comment]
config里设置确实还没有加入。在网页中的高级设置里填写的格式应该是纯主机名，例如`api.openai.com`

**Comment by zezagit** [comment]
请问网页是指的huggingface的那个网页吗，我在那个网页中的高级设置没找到设置主机名啊
![image](https://user-images.githubusercontent.com/78341434/231334167-ead7e829-fb97-4a72-9ebc-2ee00697a806.png)

**Comment by MZhao-ouo** [comment]
> 请问网页是指的huggingface的那个网页吗，我在那个网页中的高级设置没找到设置主机名啊 ![image](https://user-images.githubusercontent.com/78341434/231334167-ead7e829-fb97-4a72-9ebc-2ee00697a806.png)

HuggingFace版不需要设置api-host，毕竟hf上的机器本来就在海外
