### ISSUE TITLE
[功能请求]: 能不能搞一下支持部署在vercel上

### ISSUE THREAD

**Issue by Maddaxman** [GaiZhenbiao/ChuanhuChatGPT#596]
### 可能的解决办法

能不能搞一下支持部署在vercel上，vercel支持cdn加速，把域名配置一下就能访问，不用魔法，很方便，速度还很快

### 帮助开发

- [ ] 我愿意协助开发！

**Comment by Maddaxman** [comment]
还支持自动拉取新代码升级，很方便

**Comment by Keldos-Li** [comment]
要vercel的话整个前后端技术都是不一样的。

建议你看看其他本身就使用vercel搭建的项目，有很多。

**Comment by Maddaxman** [comment]
> 要vercel的话整个前后端技术都是不一样的。
> 
> 建议你看看其他本身就使用vercel搭建的项目，有很多。

明白了，我在用着了，只是问一下能不能搞
