### ISSUE TITLE
[Bug]: chatGPT显示html标签会发生格式错误

### ISSUE THREAD

**Issue by SexySteak** [GaiZhenbiao/ChuanhuChatGPT#603]
### 这个bug是否已存在现有issue了？

- [X] 我确认没有已有issue，且已阅读**常见问题**。

### 错误表现

![B(3B92XGQEVK0Q(CZVH5$A3](https://user-images.githubusercontent.com/86149525/231341377-b2a26eb7-f3f4-4d70-b27b-3bd976cd5fba.png)

![image](https://user-images.githubusercontent.com/86149525/231341362-83eb3e0a-5634-493e-a622-95483956b8d3.png)

### 复现操作

本地部署
向chatGPT发出如上问题

### 错误日志

```shell
无错误日志
```

### 运行环境

- OS: Windows10
- Browser: Edge
- Gradio version: 3.23.0
- Python version: 3.9.13

### 帮助解决

- [X] 我愿意协助解决！

**Comment by Keldos-Li** [comment]
请告诉gpt它的输出处于markdown格式渲染环境中，请将所有代码使用代码块或行内代码的形式。

……如果是svg标签的话确实没法解决。
