### ISSUE TITLE
[Bug]: 切换gpt模型后报错

### ISSUE THREAD

**Issue by jsbyysheng** [GaiZhenbiao/ChuanhuChatGPT#606]
### 这个bug是否已存在现有issue了？

- [X] 我确认没有已有issue，且已阅读**常见问题**。

### 错误表现

☹️发生了错误：{ “error”: { “message”: “Incorrect API key provided: sk-L*******************************************4HZ5. You can find your API key at https://platform.openai.com/account/api-keys.”, “type”: “invalid_request_error”, “param”: null, “code”: “invalid_api_key” }}

### 复现操作

1. 正常完成部署
2. 部署后直接使用（默认为gpt-3.5-turbo），没有任何问题。
3. 切换为gpt-4，使用时出现以上报错。（报错之后，在OpenAI Translator以及OpenAI后台检查过，我的key正常的并且是有权限使用gpt-4的）。
4. 切换回gpt-3.5-turbo，仍然报错。
5. 重启程序，gpt-3.5-turbo可以正常使用。一旦切换，就会一直出错。
6. 修改传输延时不能解决问题。

### 错误日志

```shell
☹️发生了错误：{ “error”: { “message”: “Incorrect API key provided: sk-L*******************************************4HZ5. You can find your API key at https://platform.openai.com/account/api-keys.”, “type”: “invalid_request_error”, “param”: null, “code”: “invalid_api_key” }}
```

### 运行环境

- OS: Ubuntu 20.04
- Browser: Edge
- Gradio version: 3.25.0
- Python version: 3.10.6

### 帮助解决

- [X] 我愿意协助解决！

**Comment by MZhao-ouo** [comment]
已查出问题，还是中间的字符被替换成*了，为什么这个bug又回来了🤔

**Comment by MZhao-ouo** [comment]
已解决，请更新到最新版本
