### ISSUE TITLE
[Bug]: 上传对话历史记录.json报错

### ISSUE THREAD

**Issue by chucksylar** [GaiZhenbiao/ChuanhuChatGPT#607]
### 这个bug是否已存在现有issue了？

- [X] 我确认没有已有issue，且已阅读**常见问题**。

### 错误表现

上传对话历史记.json文件报错

![image](https://user-images.githubusercontent.com/53057530/231393556-ee301c34-3696-4003-ba47-d15cba02e790.png)

### 复现操作

多账户模式下，添加了一个用户名admin
上传之前下载的对话历史记录.json

### 错误日志

```shell
File "/Users/zongheng/Documents/ChuanhuChatGPT/modules/base_model.py", line 507, in load_chat_history
    with open(os.path.join(HISTORY_DIR, user_name, filename), "r") as f:
IsADirectoryError: [Errno 21] Is a directory: 'history/admin/'
```

### 运行环境

- OS: Macos
- Browser:  Chrome
- Gradio version:  3.23.0
- Python version: 3.9.16

### 帮助解决

- [ ] 我愿意协助解决！

**Comment by Keldos-Li** [comment]
确实有问题。可以复现。

**使用账号时无法读取上传的历史记录。**

**Comment by shengwubin** [comment]
我创建了一个PR，虽然可以解决报错问题，但是无法解决加载上传的历史记录问题 [https://github.com/GaiZhenbiao/ChuanhuChatGPT/pull/692](https://github.com/GaiZhenbiao/ChuanhuChatGPT/pull/692)

**Comment by GaiZhenbiao** [comment]
现在解决了
