### ISSUE TITLE
[Bug]: 列表内容没有保留缩进

### ISSUE THREAD

**Issue by HsunGong** [GaiZhenbiao/ChuanhuChatGPT#609]
### 这个bug是否已存在现有issue了？

- [X] 我确认没有已有issue，且已阅读**常见问题**。

## print出来的东西将indent给自动消除了，造成阅读障碍

<img width="1140" alt="image" src="https://user-images.githubusercontent.com/32933986/231400502-8a39976f-8dc7-4589-9a33-95b4ef363694.png">

<img width="710" alt="image" src="https://user-images.githubusercontent.com/32933986/231400546-830910bd-315d-4e58-a4de-191a0522a513.png">

### 复现操作

输入：分治法解决数组inversion问题，并给出伪代码

### 运行环境

- OS: 
- Browser: 
- Gradio version: 
- Python version: 

### 帮助解决

- [X] 我愿意协助解决！

**Comment by Keldos-Li** [comment]
应该说，现在md转html的方式还存在一些问题……

**Comment by HsunGong** [comment]
Good，期待有人提点意见如何解决

**Comment by Keldos-Li** [comment]
Resolved via 8161b722712877e7648705f1d7c066493ed4a1c8.
<img width="1483" alt="image" src="https://github.com/GaiZhenbiao/ChuanhuChatGPT/assets/23137268/23dae0d3-e753-4d4c-ab53-3957f0c9efd7">
