### ISSUE TITLE
生成大量 <br/> 标签

### ISSUE THREAD

**Issue by ackness** [GaiZhenbiao/ChuanhuChatGPT#61]
当第二次输入代码时，第一次对话的代码会自动加上非常多的<br/>标签，然后超过token数，返回失败。

![image](https://user-images.githubusercontent.com/19150500/223368215-69a458cf-eb20-4301-9424-831af3bfda18.png)

![image](https://user-images.githubusercontent.com/19150500/223368324-46fc8856-8a5c-448d-b145-4049f4c3527b.png)

**Comment by GaiZhenbiao** [comment]
最新版代码中，这个问题应该得到缓解了。

**Comment by GaiZhenbiao** [comment]
此问题已解决。感觉是gradio的诡异bug。
