### ISSUE TITLE
[Docker]: 为什么镜像变大了，还是特别大。

### ISSUE THREAD

**Issue by xiedingjie** [GaiZhenbiao/ChuanhuChatGPT#612]
### 是否已存在现有反馈与解答？

- [X] 我确认没有已有issue或discussion，且已阅读**常见问题**。

### 是否是一个代理配置相关的疑问？

- [X] 我确认这不是一个代理配置相关的疑问。

### 错误描述

别乱搞啊，镜像那么大，我网络不好都要拉半个小时。之前镜像几秒钟搞定

### 复现操作

拉取慢

### 运行环境

- OS: 
- Docker version: 
- Gradio version: 
- Python version:

**Comment by GaiZhenbiao** [comment]
因为我默认给docker镜像默认安装了运行本地model的功能……我加一个选项好了

**Comment by sillyboy110** [comment]
实测，vps占用超过10G都没能把镜像构建好，无奈只好终止构建镜像

**Comment by HsunGong** [comment]
ChatGLM的问题

**Comment by yinguohang** [comment]
你好，请问是否可以在docker的使用文档中添加 需要手动安装`requirements_advanced.txt`的提示？

**Comment by MZhao-ouo** [comment]
> 你好，请问是否可以在docker的使用文档中添加 需要手动安装`requirements_advanced.txt`的提示？

是有的，参考[wiki](https://github.com/GaiZhenbiao/ChuanhuChatGPT/wiki/%E4%BD%BF%E7%94%A8%E6%95%99%E7%A8%8B#%E5%AE%89%E8%A3%85%E6%9C%AC%E5%9C%B0%E6%A8%A1%E5%9E%8B%E6%89%80%E9%9C%80%E7%9A%84%E4%BE%9D%E8%B5%96)
