### ISSUE TITLE
[功能请求]: 支持调用AutoGPT

### ISSUE THREAD

**Issue by HsunGong** [GaiZhenbiao/ChuanhuChatGPT#625]
### 相关问题

https://github.com/Torantulino/Auto-GPT

### 可能的解决办法

https://github.com/Torantulino/Auto-GPT

### 帮助开发

- [X] 我愿意协助开发！

### 补充说明

https://github.com/Torantulino/Auto-GPT

**Comment by Keldos-Li** [comment]
我觉得有川虎助理之后这个可以关掉了👀
