### ISSUE TITLE
[Docker]: 使用llama出现错误

### ISSUE THREAD

**Issue by kkkk24juastin** [GaiZhenbiao/ChuanhuChatGPT#627]
### 是否已存在现有反馈与解答？

- [X] 我确认没有已有issue或discussion，且已阅读**常见问题**。

### 是否是一个代理配置相关的疑问？

- [X] 我确认这不是一个代理配置相关的疑问。

### 错误描述

实用llama模型时，没有文件

### 复现操作

正常部署后，选择llama模型

### 错误日志

```shell
decapoda-research/llama-13b-hf-int4 does not appear to have a file named config.json. Checkout 'https://huggingface.co/decapoda-research/llama-13b-hf-int4/main' for available files."]
```

### 运行环境

- OS: 乌班图18.04
- Docker version: 最新
- Gradio version: 3.25.0
- Python version: 3.9.16

**Comment by GaiZhenbiao** [comment]
正如报错所说。这是`decapoda-research `的问题。
