### ISSUE TITLE
[功能请求]: 在线搜索接入快递查询功能

### ISSUE THREAD

**Issue by freebr** [GaiZhenbiao/ChuanhuChatGPT#634]
### 相关问题

-

### 可能的解决办法

目前在线搜索貌似没有接入查询国内主流快递物流信息的功能，可以考虑增加快递100，菜鸟之类的搜索来源。
已有人做出类似下图效果
![微信截图_20230414002427](https://user-images.githubusercontent.com/12162720/231825703-90e5588f-c5ce-4fe1-9096-69c53cc14aab.png)

### 帮助开发

- [X] 我愿意协助开发！

**Comment by Keldos-Li** [comment]
假设未来快递公司做了ChatGPT Plugin，我们也集成了plugins功能那还可以考虑，否则没有必要。快递等特定的信息还是去专门的地方查询吧。
