### ISSUE TITLE
[功能请求]: 联接Wolfram|Alpha赋能GPT数学领域搜索能力

### ISSUE THREAD

**Issue by freebr** [GaiZhenbiao/ChuanhuChatGPT#635]
### 相关问题

-

### 可能的解决办法

Wolfram|Alpha的强大不必多说，利用其知识库可以有效赋能GPT，实现对数学领域问题更精确的回答，如函数性质、（不）等式图像、级数展开式（ChatGPT本身给出的答案很多时候是错的）等，建议增加此功能。
已有人做出类似下图效果
![image](https://user-images.githubusercontent.com/12162720/231829231-7bd9d2c5-38ef-456c-8df4-9ba76e848da5.png)

![image](https://user-images.githubusercontent.com/12162720/231829361-7809c346-4c88-42d3-bdc5-9c2a42a0a0a4.png)

### 帮助开发

- [X] 我愿意协助开发！

**Comment by HsunGong** [comment]
可以参考下面的执行code:

https://github.com/zhayujie/chatgpt-on-wechat/tree/master/plugins/tool

---

但是这个感觉需要对现有仓库code大改，使得其能够支持插件模式。

**Comment by freebr** [comment]
> 可以参考下面的执行code:
> 
> https://github.com/zhayujie/chatgpt-on-wechat/tree/master/plugins/tool
> 
> 但是这个感觉需要对现有仓库code大改，使得其能够支持插件模式。

同感，支持插件生态是GPT对话系统的趋势

**Comment by InitialXKO** [comment]
不如参考这个
https://huggingface.co/spaces/JavaFXpert/Chat-GPT-LangChain
其实只要from langchain.agents import load_tools就可以调用Wolfram|Alpha
