### ISSUE TITLE
建议在readme里加上urllib3版本问题的解决方法

### ISSUE THREAD

**Issue by nekonekocham** [GaiZhenbiao/ChuanhuChatGPT#64]
因为这个问题重装了urllib3也没解决，后来在b站评论里看到说要装1.25.11版本的，才终于搞定，下面是原评论：

如果有人也出现了openai.error.APIConnectionError提示的报错，那可能是urllib3的版本导致的。urllib3版本大于1.25.11，就会出现这个问题。

解决方案是卸载urllib3然后重装至1.25.11版本再重新运行一遍就可以

在终端或命令提示符中卸载urllib3
`pip uninstall urllib3`

然后，您可以通过使用指定版本号的pip install命令来安装所需的版本：
`pip install urllib3==1.25.11`

**Comment by GaiZhenbiao** [comment]
已经加入了呀。很早就加进去了。
