### ISSUE TITLE
[Bug]: 本地部署上传索引文件后页面一直在闪烁

### ISSUE THREAD

**Issue by Maddaxman** [GaiZhenbiao/ChuanhuChatGPT#644]
### 这个bug是否已存在现有issue了？

- [X] 我确认没有已有issue，且已阅读**常见问题**。

### 错误表现

本地部署上传索引文件后页面一直在闪烁，且cpu占用突然升高，温度飙升

<img width="1829" alt="image" src="https://user-images.githubusercontent.com/31379908/231964966-49962c3b-676d-4a23-aa1b-fd066c91c557.png">
<img width="1569" alt="image" src="https://user-images.githubusercontent.com/31379908/231966884-10141448-5589-4395-a6d0-53be5e62c03a.png">
<img width="810" alt="image" src="https://user-images.githubusercontent.com/31379908/231978039-8ae6a2a3-0acb-419a-9c3f-b3dfe11edb7b.png">

### 复现操作

<img width="1829" alt="image" src="https://user-images.githubusercontent.com/31379908/231964966-49962c3b-676d-4a23-aa1b-fd066c91c557.png">

### 运行环境

- OS: macos最新
- Browser: chrome最新
- Gradio version: 
- Python version: 

### 帮助解决

- [ ] 我愿意协助解决！

**Comment by GaiZhenbiao** [comment]
确认是个bug，修复中

**Comment by GaiZhenbiao** [comment]
不是我们的bug，而是我们使用的UI框架，gradio，的新版本（3.26.0）出bug了。请安装它的上一个版本，问题解决：
```shell
pip install gradio==3.25.0
```
我们现在也在requirements中固定了gradio的版本，以后我们会在gradio新版本发布、并且我们测试无误之后，再升级gradio。gradio已经不是第一次出这种问题了🤧

**Comment by Maddaxman** [comment]
OK
