### ISSUE TITLE
[本地部署]: too many values to unpack (expected 2)

### ISSUE THREAD

**Issue by sylar003** [GaiZhenbiao/ChuanhuChatGPT#646]
### 是否已存在现有反馈与解答？

- [X] 我确认没有已有issue或discussion，且已阅读**常见问题**。

### 是否是一个代理配置相关的疑问？

- [X] 我确认这不是一个代理配置相关的疑问。

### 错误描述

![image](https://user-images.githubusercontent.com/126435040/231984439-05eadceb-6618-4685-8090-acc8a8914edf.png)
![image](https://user-images.githubusercontent.com/126435040/231985302-f111ed72-e131-4eae-9758-b9072e657f36.png)
tiktoken已经按照规范

> pip uninstall tiktoken
> pip install --upgrade tiktoken
> 也尝试过pip install tiktoken -i https://pypi.org/simple

**utils.py**文件夹下
```
def count_token(message):
    encoding = tiktoken.get_encoding("cl100k_base")
    input_str = f"role: {message['role']}, content: {message['content']}"
    length = len(encoding.encode(input_str))
    return length 
```

### 复现操作

1. 正常完成本地部署
2. 可以查询token余额
3. 使用python3.10和3.11环境均不行
4. 在同事电脑上用同样的代码则可以正常运行
5. 将base_module中的self.count_token(inputs)替换成len(inputs)则正常运行，只是无法计算token

### 错误日志

```shell
**utils.py**文件夹下
 def count_token(message):
    encoding = tiktoken.get_encoding("cl100k_base")
    input_str = f"role: {message['role']}, content: {message['content']}"
    length = len(encoding.encode(input_str))
    return length ```
```

### 运行环境

```markdown
- OS: windows10
- Browser: Chrome
- Gradio version: 3.26.0
- Python version: Python 3.11.2
- tiktoken version：0.3.3
```

**Comment by sylar003** [comment]
@GaiZhenbiao 是的，我也很奇怪。。因为同样的环境下同事的就可以，我试着用3.10和3.11的python环境都不可以，我现在把这段代码注释掉了，使用len(inputs)进行token计算，暂时可以使用了，感谢回复

**Comment by Keldos-Li** [comment]
比较奇怪的问题，先关掉了。
