### ISSUE TITLE
[Bug]: 我把中文论文一段话想润色一下，选择的语言也是中文，不知道为什么出来时英文

### ISSUE THREAD

**Issue by L-Block-C** [GaiZhenbiao/ChuanhuChatGPT#648]
### 这个bug是否已存在现有issue了？

- [X] 我确认没有已有issue，且已阅读**常见问题**。

### 错误表现

![image](https://user-images.githubusercontent.com/32314558/232067455-f61fe706-8f33-4aef-811f-808281147d0d.png)

### 复现操作

huggingface在线部署，用中文提问润色论文

### 运行环境

- OS: 
- Browser: 
- Gradio version: 
- Python version: 

### 帮助解决

- [ ] 我愿意协助解决！

**Comment by Keldos-Li** [comment]
在prompt中再加一句要求使用原语言吧……
