### ISSUE TITLE
使用在线搜索给的链接是在默认当前标签打开，，返回后所有聊天都没了

### ISSUE THREAD

**Issue by 1353604736** [GaiZhenbiao/ChuanhuChatGPT#652]
### 相关问题

使用在线搜索给的链接是在默认当前标签打开，，返回后所有聊天都没了

### 可能的解决办法

加一个新标签页打开

### 帮助开发

- [ ] 我愿意协助开发！

### 补充说明

使用在线搜索给的链接是在默认当前标签打开，，返回后所有聊天都没了

**Comment by GaiZhenbiao** [comment]
在做啦

**Comment by Keldos-Li** [comment]
现在是最底下的引用网址默认新标签页打开，回答中[1][2]的可能还是会在当前页打开。
