### ISSUE TITLE
[Bug]: 

### ISSUE THREAD

**Issue by Einstein1905** [GaiZhenbiao/ChuanhuChatGPT#656]
### 这个bug是否已存在现有issue了？

- [X] 我确认没有已有issue，且已阅读**常见问题**。

### 错误表现

docker pull后运行错误

### 复现操作

![image](https://user-images.githubusercontent.com/126863247/232147620-ff5b1d12-0c0e-4740-a10a-52f9d717473f.png)

### 运行环境

- OS: 
- Browser: 
- Gradio version: 
- Python version: 

### 帮助解决

- [ ] 我愿意协助解决！

**Comment by Einstein1905** [comment]
是删除本地模型后docker镜像里面的代码没改吗

**Comment by MZhao-ouo** [comment]
你把配置文件创建成一个目录了，删掉重建
