### ISSUE TITLE
[Docker]: IsADirectoryError: [Errno 21] Is a directory: 'config.json'

### ISSUE THREAD

**Issue by adu19922** [GaiZhenbiao/ChuanhuChatGPT#667]
### 是否已存在现有反馈与解答？

- [X] 我确认没有已有issue或discussion，且已阅读**常见问题**。

### 是否是一个代理配置相关的疑问？

- [X] 我确认这不是一个代理配置相关的疑问。

### 错误描述

Traceback (most recent call last):

  File "/app/ChuanhuChatbot.py", line 8, in <module>

    from modules import config

  File "/app/modules/config.py", line 8, in <module>

    from . import shared

  File "/app/modules/shared.py", line 1, in <module>

    from modules.presets import COMPLETION_URL, BALANCE_API_URL, USAGE_API_URL, API_HOST

  File "/app/modules/presets.py", line 7, in <module>

    i18n = I18nAuto()  # internationalization

  File "/app/modules/webui_locale.py", line 8, in __init__

    with open("config.json", "r", encoding='utf-8') as f:

IsADirectoryError: [Errno 21] Is a directory: 'config.json'
	

### 复现操作

Traceback (most recent call last):

  File "/app/ChuanhuChatbot.py", line 8, in <module>

    from modules import config

  File "/app/modules/config.py", line 8, in <module>

    from . import shared

  File "/app/modules/shared.py", line 1, in <module>

    from modules.presets import COMPLETION_URL, BALANCE_API_URL, USAGE_API_URL, API_HOST

  File "/app/modules/presets.py", line 7, in <module>

    i18n = I18nAuto()  # internationalization

  File "/app/modules/webui_locale.py", line 8, in __init__

    with open("config.json", "r", encoding='utf-8') as f:

IsADirectoryError: [Errno 21] Is a directory: 'config.json'

### 运行环境

- OS: 
- Docker version: 
- Gradio version: 
- Python version:

**Comment by plucury** [comment]
```
docker run -d --name chatgpt \
	-e my_api_key="替换成API" \
	-e api_host="替换成自定义的api请求地址" \
	-v ~/chatGPThistory:/app/history \
	-v ~/ChuanhuChatGPT/config.json:/app/config.json \
	-p 7860:7860 \
	tuchuanhuhuhu/chuanhuchatgpt:latest
```

需要绑定一个config.json

**Comment by plucury** [comment]
使用的docker 运行命令是什么？提示config.json是一个目录而不是文件？

**Comment by NekoYu** [comment]
> 使用的docker 运行命令是什么？提示config.json是一个目录而不是文件？

我试了，默认用命令生成的那个是个文件夹，要进到命令的/ChuanhuChatGPT目录里面把config.json这个自动生成的文件夹删掉，然后新建一个config.json的文件自己写好才行

**Comment by Nativu5** [comment]
貌似最新的 Docker 镜像更新后，文档没有相应地更新。
https://github.com/GaiZhenbiao/ChuanhuChatGPT/wiki/%E4%BD%BF%E7%94%A8%E6%95%99%E7%A8%8B#%E5%85%A8%E7%A8%8B%E4%BD%BF%E7%94%A8docker-%E4%B8%BAchuanhuchatgpt-%E5%BC%80%E5%90%AFhttps
