### ISSUE TITLE
[Docker]: 由于 Docker 不再使用环境变量，对应文档需要更新

### ISSUE THREAD

**Issue by Nativu5** [GaiZhenbiao/ChuanhuChatGPT#671]
### 是否已存在现有反馈与解答？

- [X] 我确认没有已有issue或discussion，且已阅读**常见问题**。

### 是否是一个代理配置相关的疑问？

- [X] 我确认这不是一个代理配置相关的疑问。

### 错误描述

根据 #601 ，Docker 镜像部署方式推荐使用配置文件方式。相应的 Wiki 页面需要更新。又因为 GitHub 自身限制，**Wiki 的改动不能提交 PR**，只能通过 Issue 方式提交。以下是我修改后的 Wiki：https://github.com/Nativu5/ChuanhuChatGPT/wiki

关于如何合并 Wiki，供仓库管理者参考：https://gist.github.com/larrybotha/10650410#merging-changes

### 复现操作

#667

**Comment by Keldos-Li** [comment]
可以的！我待会儿回去给你merge～

我们三个应该都不用docker……所以……嗯

----

再次感谢你，也欢迎你为wiki教程的其他部分也继续作出贡献！
（最近太忙了天呐）

**Comment by Keldos-Li** [comment]
wiki已更新。我也稍微再更改了点。

**Comment by noahzark** [comment]
话说能请教一下fork的repo的wiki是怎么来的嘛？我fork出来好像是空的，所以也无法修改
https://github.com/noahzark/ChuanhuChatGPT/wiki

**Comment by Nativu5** [comment]
> 话说能请教一下fork的repo的wiki是怎么来的嘛？我fork出来好像是空的，所以也无法修改 https://github.com/noahzark/ChuanhuChatGPT/wiki

参考 https://gist.github.com/larrybotha/10650410#contributing 这部分就可以了。

**Comment by noahzark** [comment]
> > 话说能请教一下fork的repo的wiki是怎么来的嘛？我fork出来好像是空的，所以也无法修改 https://github.com/noahzark/ChuanhuChatGPT/wiki
> 
> 参考 https://gist.github.com/larrybotha/10650410#contributing 这部分就可以了。

噢，知道了，因为默认fork只会fork main branch，fork的时候要去掉那个选项

**Comment by Keldos-Li** [comment]
<img width="806" alt="image" src="https://github.com/GaiZhenbiao/ChuanhuChatGPT/assets/23137268/b3fe4551-eca8-430d-bf60-1678a584ba60">
repo设置里这个可能要开一下？

**Comment by noahzark** [comment]
> <img alt="image" width="806" src="https://user-images.githubusercontent.com/23137268/240264786-b3fe4551-eca8-430d-bf60-1678a584ba60.png"> repo设置里这个可能要开一下？

<img width="1110" alt="image" src="https://github.com/GaiZhenbiao/ChuanhuChatGPT/assets/4402804/aee86c89-22d5-4b29-8679-fd19167fe1f5">

唔，看起来是开着的呀

**Comment by Nativu5** [comment]
> Should you want to contribute to the wiki of a repo you have forked, do the following:
> * fork the repo
> * clone only the wiki to your machine: $ g clone [FREPO].wiki.git

上面是 Clone Wiki 到本地的方法（摘自我之前回复的链接）。GitHub 不支持发起只修改 Wiki 内容的 PR，所以预期就是在自己 Fork 的仓库里面改好 Wiki，等原仓库 Owner 来手动合并。

**Comment by GaiZhenbiao** [comment]
> > Should you want to contribute to the wiki of a repo you have forked, do the following:
> > 
> > * fork the repo
> > * clone only the wiki to your machine: $ g clone [FREPO].wiki.git
> 
> 上面是 Clone Wiki 到本地的方法（摘自我之前回复的链接）。GitHub 不支持发起只修改 Wiki 内容的 PR，所以预期就是在自己 Fork 的仓库里面改好 Wiki，等原仓库 Owner 来手动合并。

也只能这样了。

**Comment by Keldos-Li** [comment]
@noahzark 我这里也确实fetch不到你的https://github.com/noahzark/ChuanhuChatGPT.wiki.git

**Comment by noahzark** [comment]
> @noahzark 我这里也确实fetch不到你的https://github.com/noahzark/ChuanhuChatGPT.wiki.git

唔，要么我把readme补充到 pr 里吧，然后你们看着采用就行

**Comment by Keldos-Li** [comment]
你可以试着在本地
```
git clone https://github.com/noahzark/ChuanhuChatGPT.wiki.git
git pull https://github.com/GaiZhenbiao/ChuanhuChatGPT.wiki.git （或者 pull https://github.com/GaiZhenbiao/ChuanhuChatGPT.wiki.git master ？？有点忘了语法了）
git push
```
看看有没有wiki
