### ISSUE TITLE
[Docker]: Error occurred when getting dialogue, check the background log

### ISSUE THREAD

**Issue by 7-orion** [GaiZhenbiao/ChuanhuChatGPT#672]
### 是否已存在现有反馈与解答？

- [X] 我确认没有已有issue或discussion，且已阅读**常见问题**。

### 是否是一个代理配置相关的疑问？

- [X] 我确认这不是一个代理配置相关的疑问。

### 错误描述

安装了docker版，部署完后提示☹️Error: Error occurred when getting dialogue, check the background log

之前是正常的，后来用不了就拉了最新版本的部署完就出现这个问题，我也不太清楚后台日志在哪…

### 复现操作

正常部署

### 错误日志

```shell
☹️Error: Error occurred when getting dialogue, check the background log
```

### 运行环境

- OS: 
- Docker version: 
- Gradio version: 
- Python version:

**Comment by Nativu5** [comment]
最新版本的 Docker 镜像弃用了原本的环境变量部署方式，请您移步 Wiki 查看新版 Docker 镜像的部署方式。

**Comment by VoxHwa** [comment]
按照部署方式，在用claude的时候我也碰到这个问题

**Comment by GaiZhenbiao** [comment]
> 按照部署方式，在用claude的时候我也碰到这个问题

后台日志是什么？
