### ISSUE TITLE
[Bug]: $符号导致渲染问题

### ISSUE THREAD

**Issue by libukai** [GaiZhenbiao/ChuanhuChatGPT#674]
### 这个bug是否已存在现有issue了？

- [X] 我确认没有已有issue，且已阅读**常见问题**。

### 错误表现

通过 GPT-3.5-Tubro 和 GPT-4 返回的Markdown 表格格式的内容在对话框中无法正常解析

<img width="1715" alt="CleanShot 2023-04-17 at 15 30 51@2x" src="https://user-images.githubusercontent.com/5654585/232415479-8486c900-bfee-40df-b901-be246ef65c04.png">

<img width="997" alt="CleanShot 2023-04-17 at 15 31 11@2x" src="https://user-images.githubusercontent.com/5654585/232415563-d51369a6-ecb4-4d4f-aa7f-30d9fdc851d9.png">

### 复现操作

输入的 Prompt 如下

In a recent business report presentation, the CEO of Zana Corp. highlighted their remarkable growth in the past fiscal year. She shared that the company experienced a 15% increase in revenue, reaching $50 million, with a 12% profit margin ($6 million in net profit). The report also showcased a 20% growth in their customer base, now totaling 100,000 customers. Additionally, the company's operating expenses went up by 10%, amounting to $10 million, while the employee headcount increased by 25%, resulting in a current workforce of 500 employees. 

Generate a table containing this information:

### 运行环境

- OS: Mac 13.1
- Browser: Edge  112.0.1722.46
- Gradio version: 3.25.0
- Python version:  3.9

### 帮助解决

- [ ] 我愿意协助解决！

**Comment by GaiZhenbiao** [comment]
又是LaTex和美元符冲突……我想想怎么解决

**Comment by libukai** [comment]
又测试了一下，不仅仅是表格中，是只要出现美元符号，就会导致显示不正常

<img width="1168" alt="CleanShot 2023-04-19 at 16 43 48@2x" src="https://user-images.githubusercontent.com/5654585/233020136-808624ba-afe3-4cd6-b3e9-3562018c0a21.png">

**Comment by Keldos-Li** [comment]
emm，现已通过默认取消latex渲染的方式解决（

**Comment by libukai** [comment]
> emm，现已通过默认取消latex渲染的方式解决（

这倒是个釜底抽薪的解决方案，毕竟大多数普通人是用不着 Latex 的

**Comment by Keldos-Li** [comment]
现在换用了mathjax在前端渲染公式，同时提供了勾选框用来刷新页面是否渲染。
