### ISSUE TITLE
[Bug]: config文件把本地索引改成true，然后上传文件后会报错

### ISSUE THREAD

**Issue by Maddaxman** [GaiZhenbiao/ChuanhuChatGPT#676]
### 这个bug是否已存在现有issue了？

- [X] 我确认没有已有issue，且已阅读**常见问题**。

### 错误表现

如题，正常的吗？还是说本地索引是用于本地模型的？

### 复现操作

如题

### 运行环境

- OS: 
- Browser: 
- Gradio version: 
- Python version: 

### 帮助解决

- [ ] 我愿意协助解决！

**Comment by GaiZhenbiao** [comment]
请提供详细的报错信息，要不然没法排查问题

**Comment by Maddaxman** [comment]
原来是没装高级依赖
