### ISSUE TITLE
ws连接超时

### ISSUE THREAD

**Issue by mbskter** [GaiZhenbiao/ChuanhuChatGPT#68]
![image](https://user-images.githubusercontent.com/62868358/223610446-db7e9a61-221f-4153-a75a-42172c96302f.png)
您好，我部署在了国外的vps上，启动后发现ws连接都是超时的，知道是啥情况吗

**Comment by GaiZhenbiao** [comment]
应该是Nginx配置错误；检查一下？

**Comment by mbskter** [comment]
没有 我直接python chuanhuchatgpt.py启动的

**Comment by mbskter** [comment]
#demo.queue().launch(share=False) # 改为 share=True 可以创建公开分享链接
    #demo.queue().launch(server_name="0.0.0.0", server_port=7860, share=False) # 可自定义端口
    demo.queue().launch(server_name="0.0.0.0", server_port=7860,auth=("mbskter", "X")) # 可设置用户名与密码
    
    
    这里也改了

**Comment by GaiZhenbiao** [comment]
检查一下服务器端口放行吧

**Comment by mbskter** [comment]
websocket跑的也是http的端口7680呀，web都打得开，难不成我的vps禁了ws？

**Comment by GaiZhenbiao** [comment]
要不你试试Nginx反向代理

**Comment by mbskter** [comment]
好嘞 我再排查排查 谢谢

**Comment by mqk98** [comment]
> 

同样的问题 目前没有解决

**Comment by dadaoerv** [comment]
我现在Python运行，只能公开链接访问。设置了服务器ip地址提示：（ip是我此处提问修改的假ip，实际用的真实ip）
 [Errno 99] error while attempting to bind on address ('100.001.150.100', 7860): cannot assign requested address
重启了vps还是不行。
如果设置127.0.0.1的话，可以用反向代理访问，但是会出现上面的错误。

**Comment by 2018520520** [comment]
同样的问题ws连接超时

**Comment by binary-husky** [comment]
遇到一样的问题，不是这个项目的问题，是gradio版本的问题。
同一台机器上，自己pip install就这样，直接用docker屁事没有

**Comment by mqk98** [comment]
> 遇到一样的问题，不是这个项目的问题，是gradio版本的问题。 同一台机器上，自己pip install就这样，直接用docker屁事没有

直接docker的话代码还可以自己修改吗 本来是想着把.py自定义一下 然后传到服务器直接运行来着

**Comment by kc8022** [comment]
> 遇到一样的问题，不是这个项目的问题，是gradio版本的问题。 同一台机器上，自己pip install就这样，直接用docker屁事没有
你的gradio版本发一下吗

**Comment by kc8022** [comment]
> 要不你试试Nginx反向代理，操作说明Readme里有

我用了反向代理，也还是ws连接失败

**Comment by GaiZhenbiao** [comment]
这种情况我也遇到过，不过刷新一下网页就又好了。我估计和墙有关，和这个项目没啥关系。另外，可以参考一下这个issue： #100

**Comment by binary-husky** [comment]
> > 遇到一样的问题，不是这个项目的问题，是gradio版本的问题。 同一台机器上，自己pip install就这样，直接用docker屁事没有
> 
> 直接docker的话代码还可以自己修改吗 本来是想着把.py自定义一下 然后传到服务器直接运行来着

可以，我就是这么干的，直接docker里面把你的代码覆盖进去，重新docker commit然后docker run即可

**Comment by binary-husky** [comment]
> 这种情况我也遇到过，不过刷新一下网页就又好了。我估计和墙有关，和这个项目没啥关系。另外，可以参考一下这个issue： #100

不是墙的锅

**Comment by yanzhilzh** [comment]
https://www.xncoding.com/2018/03/12/fullstack/nginx-websocket.html
把这个配置了 就ok了 @mbskter

**Comment by GaiZhenbiao** [comment]
这么说，还是没按Readme里讲的去配置Nginx……这个issue先关了
