### ISSUE TITLE
[功能请求]: 可以支持模拟登陆吗。用session的access token方式

### ISSUE THREAD

**Issue by 120805481** [GaiZhenbiao/ChuanhuChatGPT#685]
### 相关问题

可以支持模拟登陆吗。用session的access token方式

### 可能的解决办法

希望除了apikey，还可以支持模拟登陆吗。用session的access token方式登录。会更完善

### 帮助开发

- [x] 我愿意协助开发！

### 补充说明

https://github.com/binjie09/chatgpt-web

**Comment by waiting0902** [comment]
这个功能有计划开发吗？我也需要

**Comment by XudongLiu** [comment]
Gradio中可以设置一个登录的选项，可以自行完善这个功能。

**Comment by Keldos-Li** [comment]
使用这种方式可能存在法律风险
