### ISSUE TITLE
安装依赖时 Failed to connect to github.com port 443 after xxxx ms

### ISSUE THREAD

**Issue by Maddaxman** [GaiZhenbiao/ChuanhuChatGPT#686]
### 这个bug是否已存在现有issue了？

- [X] 我确认没有已有issue，且已阅读**常见问题**。

### 错误表现

 Cloning https://github.com/huggingface/peft.git (to revision deff03f2c251534fffd2511fc2d440e84cc54b1b) to c:\users\52633\appdata\local\temp\pip-install-cz9j2k_s\peft_7088e296c0874bb284087f41102426bc
  Running command git clone --filter=blob:none --quiet https://github.com/huggingface/peft.git 'C:\Users\52633\AppData\Local\Temp\pip-install-cz9j2k_s\peft_7088e296c0874bb284087f41102426bc'
  fatal: unable to access 'https://github.com/huggingface/peft.git/': Failed to connect to github.com port 443 after 21075 ms: Couldn't connect to server
  error: subprocess-exited-with-error

  git clone --filter=blob:none --quiet https://github.com/huggingface/peft.git 'C:\Users\52633\AppData\Local\Temp\pip-install-cz9j2k_s\peft_7088e296c0874bb284087f41102426bc' did not run successfully.
  exit code: 128

  See above for output.

  note: This error originates from a subprocess, and is likely not a problem with pip.
error: subprocess-exited-with-error

git clone --filter=blob:none --quiet https://github.com/huggingface/peft.git 'C:\Users\52633\AppData\Local\Temp\pip-install-cz9j2k_s\peft_7088e296c0874bb284087f41102426bc' did not run successfully.
exit code: 128

See above for output.

note: This error originates from a subprocess, and is likely not a problem with pip.

### 复现操作

安装高级依赖的时候

### 运行环境

- OS: 
- Browser: 
- Gradio version: 
- Python version: 

### 帮助解决

- [ ] 我愿意协助解决！

**Comment by Keldos-Li** [comment]
是的，是网络原因。

另外，就算网络能连上git了，也不建议直接在Windows上安装高级依赖，因为……你大概率装不上deepspeed。建议使用wsl。

**Comment by GaiZhenbiao** [comment]
> 是的，是网络原因。
> 
> 另外，就算网络能连上git了，也不建议直接在Windows上安装高级依赖，因为……你大概率装不上deepspeed。建议使用wsl。

DeepSpeed就是微软开发的，但是微软不愿意支持自己的平台😂
