### ISSUE TITLE
咨询一下，通过api调用，聊天会话有上下文关联吗？

### ISSUE THREAD

**Issue by jarrywen** [GaiZhenbiao/ChuanhuChatGPT#69]
咨询一下，浏览器打开一次地址，是一个聊天会话记录吗？
多人使用的话会是多个聊天会话吗？还是上下文会被干扰？

**Comment by GaiZhenbiao** [comment]
上下文不会被干扰，但程序同时只能处理一个请求

**Comment by jarrywen** [comment]
good job，多人使用，之前chatgpt api会有超出限制错误
