### ISSUE TITLE
我部署了服务器但是按钮却都是英文啊？

### ISSUE THREAD

**Issue by dkglds** [GaiZhenbiao/ChuanhuChatGPT#695]
### 这个bug是否已存在现有issue了？

- [X] 我确认没有已有issue，且已阅读**常见问题**。

### 错误表现

我阅读代码发现理论上modules文件夹里是不是应该有个config.json啊，里面应该写了和i18n的语言信息吧，可是它似乎和项目主页面里的config.json一并被忽略了，可能是因为这个导致了我部署了服务器但是按钮却都是英文。

webui_locate.py中：
5～20行：
```
class I18nAuto:
    def __init__(self):
        if os.path.exists("config.json"):
            with open("config.json", "r", encoding='utf-8') as f:
                config = json.load(f)
        else:
            config = {}
        lang_config = config.get("language", "auto")
        language = os.environ.get("LANGUAGE", lang_config)
        if language == "auto":
            language = locale.getdefaultlocale()[0] # get the language code of the system (ex. zh_CN)
        self.language_map = {}
        self.file_is_exists = os.path.isfile(f"./locale/{language}.json")
        if self.file_is_exists:
            with open(f"./locale/{language}.json", "r", encoding="utf-8") as f:
                self.language_map.update(json.load(f))
```
其中有：
`with open("config.json", "r", encoding='utf-8') as f:`
正常下载的代码文件这个目录下是没有这个config.json文件的，可能是因为：
.gitignore中141行的：`config.json`
导致忽略了项目中所有名为config.json的文件，正确的做法是不是应该仅仅忽略主目录下的config.json文件？

### 复现操作

1. 正确完成网站部署
2. 运行成功确实能提问，但是UI全是英文，体验可能不太好。
3. 检查了你们的在线体验网站，确实全是中文UI

### 运行环境

- OS: 
- Browser: 
- Gradio version: 
- Python version: 

### 帮助解决

- [ ] 我愿意协助解决！

**Comment by Keldos-Li** [comment]
modules文件夹下没有config.json。

您将项目主文件夹下的config.json中的language的键值改为"zh_CN"即可。

**Comment by dkglds** [comment]
哦，好的，是我没注意这个地方

**Comment by xiangfeigao** [comment]
我用docker部署的，发现没有中文包

**Comment by GaiZhenbiao** [comment]
> 我用docker部署的，发现没有中文包

在docker的环境变量里设置`LANGUAGE`的值为`zh_CN`就行了
