### ISSUE TITLE
部署到服务器后回复内容只有第一个字

### ISSUE THREAD

**Issue by sundayYa** [GaiZhenbiao/ChuanhuChatGPT#70]
![image](https://user-images.githubusercontent.com/121467830/223637740-7bcff827-25a1-4506-98df-d33d3e5ce686.png)

**Comment by GaiZhenbiao** [comment]
这也太怪了。试试最新版代码？

**Comment by sundayYa** [comment]
更新了 
换了个代理也不行

**Comment by sundayYa** [comment]
以前是直接回复所有内容的时候还正常的

**Comment by GaiZhenbiao** [comment]
有错误报告吗？

**Comment by sundayYa** [comment]
![image](https://user-images.githubusercontent.com/121467830/223641583-b8651740-dac8-4aeb-8948-98e70989fd32.png)
![image](https://user-images.githubusercontent.com/121467830/223641661-5d72819b-31ee-4ca7-ad1a-f7654a7ec675.png)

**Comment by sundayYa** [comment]
这是python报错了吗

**Comment by sundayYa** [comment]
![image](https://user-images.githubusercontent.com/121467830/223642535-819d9e8c-c2f2-44de-8596-952cdbf6a316.png)

**Comment by GaiZhenbiao** [comment]
试试最新的版本？

**Comment by sundayYa** [comment]
关掉实时回答就正常了

打开后现在不显示对话内容

**Comment by GaiZhenbiao** [comment]
试试最新的代码，加入了更多诊断信息的打印。

**Comment by GaiZhenbiao** [comment]
现在看来，这应该是OpenAI那边的API不稳定。
