### ISSUE TITLE
[本地部署]:  获取API使用情况失败:HTTPSConnectionPool(host='api.openai.com', port=443): Max retries exceeded with url: /dashboard/billing/usage?start_d ate=2023-04-01&end_date=2023-04-30 (Caused by ProxyError('Cannot connect to proxy.', OSError(0, 'Error')))

### ISSUE THREAD

**Issue by rickformorty** [GaiZhenbiao/ChuanhuChatGPT#701]
### 是否已存在现有反馈与解答？

- [X] 我确认没有已有issue或discussion，且已阅读**常见问题**。

### 是否是一个代理配置相关的疑问？

- [X] 我确认这不是一个代理配置相关的疑问。

### 错误描述

 获取API使用情况失败:HTTPSConnectionPool(host='api.openai.com', port=443): Max retries exceeded with url: /dashboard/billing/usage?start_d
ate=2023-04-01&end_date=2023-04-30 (Caused by ProxyError('Cannot connect to proxy.', OSError(0, 'Error')))

### 复现操作

openai-key正确
使用代理    "http":  "socks5h://localhost:7890",
    "https": "socks5h://localhost:7890",
Clash代理

### 错误日志

```shell
2023-04-24 10:29:51,140 [INFO] [base_model.py:281] 输入为：你好
2023-04-24 10:29:51,172 [INFO] [base_model.py:345] 回答为：☹️发生了错误：获取对话时发生错误，请查看后台日志
2023-04-24 10:29:52,393 [ERROR] [models.py:89] 获取API使用情况失败:HTTPSConnectionPool(host='api.openai.com', port=443): Max retries exceeded with url: /dashboard/billing/usage?start_d
ate=2023-04-01&end_date=2023-04-30 (Caused by ProxyError('Cannot connect to proxy.', OSError(0, 'Error')))
```

### 运行环境

```markdown
- OS: 
- Browser: 
- Gradio version: 
- Python version: 3.8.1
```

**Comment by Qwerty4401** [comment]
就是代理问题。。

**Comment by wg961** [comment]
很怪，我不是很懂，我改了api_host，但是我填的api还是不能用，无聊又填在前端，然后就好了
我是纯小白
