### ISSUE TITLE
[功能请求]: 是否可以提供类似官方一样的浏览/保存历史对话功能

### ISSUE THREAD

**Issue by Yamhao** [GaiZhenbiao/ChuanhuChatGPT#702]
### 可能的解决办法

左侧是Tab栏可以切换，使用上更加方便。

### 帮助开发

- [ ] 我愿意协助开发！

**Comment by GaiZhenbiao** [comment]
可以在保存/加载列表的对话下拉列表中选择，用起来差不多。现在川虎Chat也会自动保存每一轮对话了。

**Comment by Yamhao** [comment]
不是太直观，感觉

**Comment by Keldos-Li** [comment]
您要求还挺高哈……
