### ISSUE TITLE
[功能请求]: 优化对话历史记录提交的功能。

### ISSUE THREAD

**Issue by dkglds** [GaiZhenbiao/ChuanhuChatGPT#705]
### 相关问题

尊敬的开发团队：
您好！
我已经将你们网页部署到服务器了，在使用了几天我还是觉得在对话历史记录方面，你们可以进行一些针对远程部署的一些优化。
在使用远程服务器的过程中，情况可能与个人本地部署有些不同。部署远程服务器后，往往将会是多人使用同一个服务器。这就会导致，如果历史记录不分用户存储，那么所有人共享同一个历史记录空间，而且没有删除历史记录的权限，只有添加和覆盖历史记录的权限。
在没有设置完整的登录注册系统时，这会可能导致严重的隐私问题，因为用户进行的任何保存对话操作都会在服务器留下痕迹，而且其内容将和所以用户共享。而且我看到你们都在线体验页面里似乎可以在历史记录中找到很多记录。
当然，也可能我自己使用不规范没有仔细考察你们是否在某个配置文件中设置了类似的功能避免这点，或者你们可能能想到更好的办法解决这个问题。不过，我作为一名普通的使用者，目的是搭建一个网站可小规模供同学使用，且省略登录这种麻烦的步骤。而至少仅通过config.json，我好像没有找到可以解决我提出问题的办法。
如果你们其实没有考虑到这个问题，我建议尽快想办法解决它，它可能是个设计上的缺陷，如果短时间没有办法解决，至少在安装教程里声明一下这个问题，避免它被别人忽略。

### 可能的解决办法

我认为可以添加另一种读取对话模式。开关可以设置在config.json文件中。
在这种新模式下，服务器不会长期保存任何历史对话记录，仅在用户点击保存对话的时候激活下载，在下载完成以后就删除此记录。而用户上传文件的时候，服务器在读取完成文件后立刻删除，避免记录被其他人读取。且服务器仅支持上传式读取记录而不支持读取本地记录，避免在服务器读取文件到删除过程中的短暂存留过程被读取到。

当然，更好的解决方式其实是使用cookies，这样可以极度简化用户的操作，但是也必须考虑到cookies可能丢失，可以结合两种方法一起使用。

不过我看你们主要还是倾向于设计个人客户端，而且程序已经在无cookies的情况下设计了很多部分了，如果这个时候才开始用cookies，可能会很棘手，我也只是提出下我的想法，请你们视实际情况处理。

当然，你们可能有更好的办法，或者更简单的办法，但是我个人认为，至少要能支持本地对话上传。远程的对话还可以直接覆盖内容的方式删除，但是如果不支持本地上传对话记录，那么服务器上的内容一旦被覆盖了就丢失了，但是如果支持本地对话上传，虽然对用户会麻烦点，但至少不用担心对话记录丢失以及对话内容泄露。

### 帮助开发

- [ ] 我愿意协助开发！

**Comment by Keldos-Li** [comment]
感谢您认真的说明！

不过，一般来说，只要部署到远程了，就应该默认：
```
不登录 = 个人使用
登录　 = 多人使用
```
哪有既要方便（不登录），又要隐私（区分用户记录）的道理……只要不登录就当在不同浏览器访问服务器使用的人都是你自己，所以不太可能又区分记录的。

huggingface如果直接用公开的空间，确实可能有点隐私问题。因此推荐复制到个人空间。

至于有没有必要做你说的什么的服务器短期保留的什么的功能……改变对话历史记录的提交逻辑……看看老大有没有这个计划

不过我们确实正在做通过针对不登录用户，通过浏览器的存储保存对话记录的功能。但它可能和官方的不太一样，由于一些历史包袱，现在只能保留页面刷新前**对话框中的所有对话记录**，不能保留整个对话列表。同时，页面刷新后的这些对话仅供显示查看，语言模型并不能进一步读取历史对话数据。
<img width="691" alt="image" src="https://user-images.githubusercontent.com/23137268/234737439-680425ea-1973-48ac-b9fa-860174f6cc8e.png">

对登录用户，我们将能默认保存上一次对话记录，而不用在浏览器中存储的方式。可以期待一下~

**Comment by dkglds** [comment]
那至少能不能支持本地上传对话记录，我看到你们明明是可以上传对话记录到浏览器里，但是时候语言模型不会按照对话的方式去读取内容，只会按照读取文本的方式读，这正常你们既然提供了保存/加载对话，而且保存下来的对话也可以下载下来，是不是本来也应该支持上传对话让gpt就上传的上下文来回答呢？

**Comment by GaiZhenbiao** [comment]
> 那至少能不能支持本地上传对话记录，我看到你们明明是可以上传对话记录到浏览器里，但是时候语言模型不会按照对话的方式去读取内容，只会按照读取文本的方式读，这正常你们既然提供了保存/加载对话，而且保存下来的对话也可以下载下来，是不是本来也应该支持上传对话让gpt就上传的上下文来回答呢？

支持的呀，在保存/加载面板里上传历史记录就行了

**Comment by Keldos-Li** [comment]
哦，另外，关于登录之后上传对话历史记录，这里是有一个bug：
- #607

**Comment by GaiZhenbiao** [comment]
感谢反馈！现在

- 登录后可以自动保存、加载对话
- 未登录时可以在浏览器本地保存历史记录（仅供查看）
- 未设置账户密码系统时不再向用户展示历史记录列表
