### ISSUE TITLE
docker 部署 使用在线搜索功能时出错 

### ISSUE THREAD

**Issue by sky-xx** [GaiZhenbiao/ChuanhuChatGPT#708]
### 是否已存在现有反馈与解答？

- [X] 我确认没有已有issue或discussion，且已阅读**常见问题**。

### 是否是一个代理配置相关的疑问？

- [X] 我确认这不是一个代理配置相关的疑问。

### 错误描述

大佬们 我这 大概是代理问题 duckduckgo.com 访问不了  我用clash代理了一下 在浏览器可以访问了  可怎么让服务器能访问到啊

### 复现操作

部署之后 使用在线搜索功能

### 错误日志

```shell
requests.exceptions.ConnectTimeout: HTTPSConnectionPool(host='duckduckgo.com', port=443): Max retries exceeded with url: / (Caused by ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x7f071b7aeca0>, 'Connection to duckduckgo.com timed out. (connect timeout=10)')) 2023-04-25 09:08:46,133 [WARNING] [utils.py:59] keywords=你好. _get_vqd() is None. Refresh SESSION and retry... Traceback (most recent call last):   File "/home/user/.local/lib/python3.8/site-packages/gradio/routes.py", line 395, in run_predict     output = await app.get_blocks().process_api(   File "/home/user/.local/lib/python3.8/site-packages/gradio/blocks.py", line 1193, in process_api     result = await self.call_function(   File "/home/user/.local/lib/python3.8/site-packages/gradio/blocks.py", line 930, in call_function     prediction = await anyio.to_thread.run_sync(   File "/home/user/.local/lib/python3.8/site-packages/anyio/to_thread.py", line 31, in run_sync     return await get_asynclib().run_sync_in_worker_thread(   File "/home/user/.local/lib/python3.8/site-packages/anyio/_backends/_asyncio.py", line 937, in run_sync_in_worker_thread     return await future   File "/home/user/.local/lib/python3.8/site-packages/anyio/_backends/_asyncio.py", line 867, in run     result = context.run(func, *args)   File "/home/user/.local/lib/python3.8/site-packages/gradio/utils.py", line 491, in async_iteration     return next(iterator)   File "/home/user/app/modules/utils.py", line 39, in predict     for i in iter:   File "/home/user/app/modules/base_model.py", line 283, in predict     limited_context, fake_inputs, display_append, inputs, chatbot = self.prepare_inputs(real_inputs=inputs, use_websearch=use_websearch, files=files, reply_language=reply_language, chatbot=chatbot)   File "/home/user/app/modules/base_model.py", line 243, in prepare_inputs     for idx, result in enumerate(search_results): TypeError: 'NoneType' object is not iterable[Docker]:
```

### 运行环境

- OS: 
- Docker version: 
- Gradio version: 
- Python version:

**Comment by wantiedaishu** [comment]
我在linux上部署也遇到这个问题

**Comment by popoleaf** [comment]
我也是，老版本成功过，新做的docker版本就没有成功过

**Comment by GaiZhenbiao** [comment]
这个是连接到搜索引擎（DuckDuckGo）的时候失败了，应该是网络原因，DockDuckGo需要翻墙。

**Comment by Qwerty4401** [comment]
> 这个是连接到搜索引擎（DuckDuckGo）的时候失败了，应该是网络原因，DockDuckGo需要翻墙。

可以自定义修改为不需要翻墙的搜索引擎吗，类似Bing、baidu之类的。

**Comment by GaiZhenbiao** [comment]
> > 这个是连接到搜索引擎（DuckDuckGo）的时候失败了，应该是网络原因，DockDuckGo需要翻墙。
> 
> 可以自定义修改为不需要翻墙的搜索引擎吗，类似Bing、baidu之类的。

可以试试，但这可能受到搜索引擎反爬虫策略的制约。

**Comment by zodostffaa** [comment]
duckduckgo_search 2.9.4 现在又不能用了

**Comment by GaiZhenbiao** [comment]
> > 这个是连接到搜索引擎（DuckDuckGo）的时候失败了，应该是网络原因，DockDuckGo需要翻墙。
> 
> 我的云服务器在日本，也是“error”。

应该是duckduckgo_search的版本太低了。我在最新版docker中指定了duckduckgo搜索的版本，你可以试试

**Comment by GaiZhenbiao** [comment]
> > 这个是连接到搜索引擎（DuckDuckGo）的时候失败了，应该是网络原因，DockDuckGo需要翻墙。
> 
> 我的云服务器在日本，也是“error”。

本地部署的话就更简单了，用下面的命令升级一下它的版本就行了：
```
pip install duckduckgo_search --upgrade
```

**Comment by zodostffaa** [comment]
> duckduckgo_search 2.9.4 现在又不能用了

现在问题是相同问题只有第一次可以搜索，之后会没有结果。

**Comment by ULHI-xin** [comment]
最近 ddg 似乎又改了 API, 现在duckduckgo_search 2.9.5 以上包括最新的也无法使用了.

**Comment by wxtt522** [comment]
升级也不行，我的已经3.1.1版本了，一样用不了
anguage, chatbot=chatbot)
  File "/home/ubuntu/code/ChuanhuChatGPT/modules/models/base_model.py", line 252, in prepare_inputs
    search_results = ddg(real_inputs, max_results=5)
  File "/home/ubuntu/miniconda3/envs/chuanhugpt/lib/python3.10/site-packages/duckduckgo_search/compat.py", line 33, in ddg
    for r in DDGS().text(
  File "/home/ubuntu/miniconda3/envs/chuanhugpt/lib/python3.10/site-packages/duckduckgo_search/duckduckgo_search.py", line 149, in text
    for row in page_data:
TypeError: 'NoneType' object is not iterable
^C
(chuanhugpt) ubuntu@VM:~/code/ChuanhuChatGPT$ pip list|grep duckduckgo
duckduckgo-search       3.1.1

**Comment by Keldos-Li** [comment]
在 ee70a9daa732022302fcf6effab2dd6370b4f188 中去除了duckduckgo，改为了使用Google搜索

**Comment by tanpengsccd** [comment]
Google 搜索 直接 429 了.  
![image](https://github.com/GaiZhenbiao/ChuanhuChatGPT/assets/13959880/9ccbac68-bcbd-48d5-8b41-fae107d9c364)
可以开WARP 代理吗?

**Comment by Keldos-Li** [comment]
开warp不影响功能的使用，是可以正确代理向谷歌的请求的。

**Comment by tanpengsccd** [comment]
> 开warp不影响功能的使用，是可以正确代理向谷歌的请求的。
我是Docker 部署的, 有没有方式 给Google搜索 开WARP 呢?  我也一直遇到429 这个 报错.

**Comment by Keldos-Li** [comment]
@tanpengsccd 429是请求过于频繁而被拒绝，与warp代理无关。

---

鉴于原ISSUE是由duckduckgo相关包失败引起的，现在换用了Google，之后可能的问题与原issue无关，暂时关闭该ISSUE。更新的问题反馈请前往
-  #784 .
