### ISSUE TITLE
能否让GPT-INDEX库加入这个库中？或者本身就让CHuanhu拥有读取本地文件的能力？

### ISSUE THREAD

**Issue by difaandailisi** [GaiZhenbiao/ChuanhuChatGPT#71]
https://github.com/jerryjliu/gpt_index   是一个很好的库，能读取本地文件夹、网络连接等。
而现在大多数OPENA AI 的API网站都不支持这种能力。
作者是否能够让CHUANHU的优化能力加持到本地文件的读取上？
谢谢。

**Comment by GaiZhenbiao** [comment]
正在做👀
（你怎么知道我在研究这个（bushi

**Comment by difaandailisi** [comment]
> 正在做👀（你怎么知道我在研究这个（bushi



> 正在做👀（你怎么知道我在研究这个（bushi
这个是一个读取本地页面的文档。

https://1ofi34mygplywk9.studio.us-east-2.sagemaker.aws/studiolab/default/jupyter/files/Chatbot_with_custom_knowledge_base.ipynb?_xsrf=2%7Cbdecc207%7C51f8e1969fca7f176978b9bf3b1c04e5%7C1678043287

**Comment by difaandailisi** [comment]
> 



> 正在做👀（你怎么知道我在研究这个（bushi
这是一个简单的读取本地文件的例子，请直接去掉zip的后缀，他是一个IPYNB文件。
[Chatbot_with_custom_knowledge_base .ipynb.zip](https://github.com/GaiZhenbiao/ChuanhuChatGPT/files/10920994/Chatbot_with_custom_knowledge_base.ipynb.zip)

**Comment by difaandailisi** [comment]
> 正在做👀（你怎么知道我在研究这个（bushi

GPT-INDEX提供的例子太多，又太简陋了。我就在想要是有个图形界面就好了、

**Comment by GaiZhenbiao** [comment]
这个文件从哪里来的？请给出源repo

**Comment by difaandailisi** [comment]
> 这个文件从哪里来的？请给出源repo。这个文件看上去是一个文件被劣质翻译的结果。

这是被CHATGPT web自己注释的结果，源文件没有注释，只有介绍。

**Comment by difaandailisi** [comment]
> 这个文件从哪里来的？请给出源repo。这个文件看上去是一个文件被劣质翻译的结果。

我相信库中的大量文件，应该你们有研究吧。https://github.com/jerryjliu/gpt_index/tree/main/examples
https://gpt-index.readthedocs.io/en/latest/       https://github.com/jerryjliu/gpt_index
