### ISSUE TITLE
[Bug]: 我的api key支持gpt4，但是我切换到4之后，显示使用的还是gpt-3的模型

### ISSUE THREAD

**Issue by baiyi-os** [GaiZhenbiao/ChuanhuChatGPT#714]
### 这个bug是否已存在现有issue了？

- [X] 我确认没有已有issue，且已阅读**常见问题**。

### 错误表现

我的api key支持gpt4，但是我切换到4之后，显示使用的还是gpt-3的模型

### 复现操作

我的api key支持gpt4，但是我切换到4之后，显示使用的还是gpt-3的模型

### 运行环境

- OS: 
- Browser: 
- Gradio version: 
- Python version: 

### 帮助解决

- [ ] 我愿意协助解决！

**Comment by baiyi-os** [comment]
![image](https://user-images.githubusercontent.com/58473561/235046306-0cb44d71-13b5-4cd8-a707-3154a852f7b3.png)

**Comment by GaiZhenbiao** [comment]
不用纠结这个，这只是因为GPT4不知道自己是GPT4. 实际上回答质量是有明显提升的（与此同时，回答速度也明显变慢了qwq）

**Comment by baiyi-os** [comment]
好的
