### ISSUE TITLE
[功能请求]: 刷新页面默认显示对话记录时，将滚动条自动定位至最下方

### ISSUE THREAD

**Issue by libukai** [GaiZhenbiao/ChuanhuChatGPT#721]
### 相关问题

目前在显示历史对话记录时，滚动条处于最上方，如果对话记录过多则整个页面看起来是白屏状态，会给用户带来很多的迷惑

### 可能的解决办法

刷新页面默认显示对话记录时，将滚动条自动定位至最下方

### 帮助开发

- [ ] 我愿意协助开发！

**Comment by Keldos-Li** [comment]
好，这个应该能做。

**Comment by libukai** [comment]
- 不使用账号登录时，此功能已实现
- 使用账号登录时，刷新当前页面的滚动条没有自动定位至最下方

**Comment by Keldos-Li** [comment]
> * 使用账号登录时，刷新当前页面的滚动条没有自动定位至最下方

这个目前可能做不了……🤔
