### ISSUE TITLE
[功能请求]: 加入和Waifu对话的功能

### ISSUE THREAD

**Issue by binary-husky** [GaiZhenbiao/ChuanhuChatGPT#728]
### 相关问题

- 加入waifu的PR：
https://github.com/GaiZhenbiao/ChuanhuChatGPT/pull/727

- 效果：
![image](https://user-images.githubusercontent.com/96192199/235742282-2d982636-de05-41e6-9e74-14494410769c.png)

- 更进一步的功能请求：
有没有可能把对话通过waifu聊天框显示出来？

### 可能的解决办法

也许能通过调用一些javascript函数实现交互？

### 帮助开发

- [x] 我愿意协助开发！

**Comment by Keldos-Li** [comment]
> 有没有可能把对话通过waifu聊天框显示出来？

我大致想了一下，应该确实是可以的。

但是我们不加live2d，这个也就不做了 :-)

如果有空的话我给你们的学术版看一看。（天哪你们真的把整个库放进去了，真的……）
