### ISSUE TITLE
[功能请求]: 希望能增加一键复制回答的功能，官网现在都已经有这个功能了

### ISSUE THREAD

**Issue by sscc9** [GaiZhenbiao/ChuanhuChatGPT#732]
### 可能的解决办法

就做成像官方的那样就行

### 帮助开发

- [ ] 我愿意协助开发！

**Comment by GaiZhenbiao** [comment]
已经有了呀，更新到最新版吧。

**Comment by sscc9** [comment]
> 已经有了呀，更新到最新版吧。

嗯，我用了最新版，确实有了，不过感觉复制按钮是在顶上不太方便，能移到底下就好了

**Comment by Keldos-Li** [comment]
笑死了，我一开始做的就是在底下，但是为了方便切换md渲染和源输出显示时不跳来跳去时改到顶上了。

**Comment by sscc9** [comment]
> 已经有了呀，更新到最新版吧。



> 笑死了，我一开始做的就是在底下，但是为了方便切换md渲染和源输出显示时不跳来跳去时改到顶上了。

能不能做成对话生成完，复制按钮再显示出来，这样应该就不会跳了吧

**Comment by Keldos-Li** [comment]
1. 我一开始说的 _跳来跳去_ 是指，切换渲染显示时对话气泡高度会不一样，如果放在底下按钮也会根据气泡高度逃走\_(:з」∠)\_
2. 刚把这几个按钮又改回到底下了
3. 我也想做对话生成完再显示按钮……但做不到QAQ，是我太菜了😢😢😢

**Comment by sscc9** [comment]
> 1. 我一开始说的 _跳来跳去_ 是指，切换渲染显示时对话气泡高度会不一样，如果放在底下按钮也会根据气泡高度逃走_(:з」∠)_
> 2. 刚把这几个按钮又改回到底下了
> 3. 我也想做对话生成完再显示按钮……但做不到QAQ，是我太菜了😢😢😢

你们已经很厉害了，川虎gpt很好用

**Comment by oldfishoh** [comment]
> 1. 我一开始说的 _跳来跳去_ 是指，切换渲染显示时对话气泡高度会不一样，如果放在底下按钮也会根据气泡高度逃走\_(:з」∠)\_
> 2. 刚把这几个按钮又改回到底下了
> 3. 我也想做对话生成完再显示按钮……但做不到QAQ，是我太菜了😢😢😢

已经是GitHub里最棒的ChatGPT开源项目了
