### ISSUE TITLE
[本地部署]:在config.json中没有看到API host选项，安装说明中提到过

### ISSUE THREAD

**Issue by popoleaf** [GaiZhenbiao/ChuanhuChatGPT#737]
### 是否已存在现有反馈与解答？

- [X] 我确认没有已有issue或discussion，且已阅读**常见问题**。

### 是否是一个代理配置相关的疑问？

- [X] 我确认这不是一个代理配置相关的疑问。

### 错误描述

安装说明中提到过API host。但是本地json文件中没有看到，自己加入，docker重启，不知道为啥。

### 复现操作

正常

### 运行环境

```markdown
docker
```

**Comment by Keldos-Li** [comment]
json_example里忘记加了，但确实可以在config里配置。形如：
```jsonc
    ...
    "api_host": "host.example.com",
    ...
```

请确保你写的json文件格式正确。

**Comment by popoleaf** [comment]
搞定
试过"api-host"
试过“api host”
就是没试过api_host


popo
***@***.***



&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "GaiZhenbiao/ChuanhuChatGPT"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2023年5月8日(星期一) 下午3:12
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [GaiZhenbiao/ChuanhuChatGPT] [本地部署]:在config.json中没有看到API host选项，安装说明中提到过 (Issue #737)





 
json_example里忘记加了，但确实可以在config里配置。形如：
     ...     "api_host": "host.example.com",     ...
 
请确保你写的json文件格式正确。

**Comment by Keldos-Li** [comment]
随着模型与api的增加，后续开发可能会考虑把`api_host`改成`openai_api_host`……请各位留意。

**Comment by maxage** [comment]
我就试写的openai_api_host，报错。。。原来是api_host  emmmm

**Comment by Keldos-Li** [comment]
……等我们之后改成openai_api_host我们再写进example吧……这样如果我们不能做到向前兼容，影响的人也应该少点……
