### ISSUE TITLE
使用docker部署到nas后无法share=true

### ISSUE THREAD

**Issue by yemaxul** [GaiZhenbiao/ChuanhuChatGPT#74]
根据以下代码，我配置了USERNAME和PASSWORED的变量，但是仍然无法生成公开访问链接，能否更新一个可以配置share变量的docker
```
#if running in Docker
if dockerflag:
    if authflag:
        demo.queue().launch(server_name="0.0.0.0", server_port=7860,auth=(username, password))
    else:
        demo.queue().launch(server_name="0.0.0.0", server_port=7860, share=False)
```
感谢！

**Comment by GaiZhenbiao** [comment]
你把Share改成True就行了呗
```
if authflag:
        demo.queue().launch(server_name="0.0.0.0", server_port=7860,auth=(username, password), share=True)
    else:
        demo.queue().launch(server_name="0.0.0.0", server_port=7860, share=True)
```

**Comment by yemaxul** [comment]
> 你把Share改成True就行了呗
> ```
> if authflag:
>         demo.queue().launch(server_name="0.0.0.0", server_port=7860,auth=(username, password), share=True)
>     else:
>         demo.queue().launch(server_name="0.0.0.0", server_port=7860, share=True)
> ```

但是我用的是大佬你打包好的docker，刚刚了解还不知道怎么打包😭

**Comment by yilin-gong** [comment]
1. 下载整个code
2. Mac：用terminal： `cd download/ChuanhuChatGPT-main`
3. 打开ChuanhuChatbot.py， 修改150行 `share=True`
4. 保存
5. 打开terminal， 运行docker build .
6. 运行```
docker run -d --name chatgpt \
	-e my_api_key="替换成API" \
	-v ~/chatGPThistory:/app/history \
	-p 7860:7860 \
	chuanhuchatgpt:latest
```
7. 齐活

**Comment by yemaxul** [comment]
用nginx进行代理后问题已解决
