### ISSUE TITLE
[功能请求]: 添加对azure openai api的支持

### ISSUE THREAD

**Issue by debugAllTheTime** [GaiZhenbiao/ChuanhuChatGPT#740]
### 可能的解决办法

请求添加对azure openai api的支持。azure的openai服务可以不用翻墙

### 帮助开发

- [ ] 我愿意协助开发！

**Comment by GaiZhenbiao** [comment]
你可以自定义API Host为Azure的，应该就可以用了。

**Comment by baiyi-os** [comment]
我这边自定义了API Host为Azure的(我将/modules/presets.py文件中的api.openai.com均改为了openai4kol.openai.azure.com)，并且key也改为了Azure的，请求时报错：
2023-05-18 10:17:12,366 [ERROR] [models.py:91] 获取API使用情况失败:API request failed with status code 404: {"error":{"code":"404","message": "Resource not found"}}

**Comment by baiyi-os** [comment]
目前的版本应该还不支持微软api吧

**Comment by baiyi-os** [comment]
您好，后面会支持微软的openapi吗

**Comment by GaiZhenbiao** [comment]
> 您好，后面会支持微软的openapi吗

我没有微软API的使用权限，所以没法适配QAQ

**Comment by baiyi-os** [comment]
嗯嗯，好的，如果后面支持了，辛苦也回复一下

**Comment by HEXtoDEC** [comment]
AZURE的API实例化之前有多个参数，比如：
之后不管是PATH，还是任何调用方式，返回都与OPENAI的API保持一致

例：
```python


import os
from langchain.llms import AzureOpenAI
from langchain.prompts import PromptTemplate

os.environ["OPENAI_API_TYPE"] = "azure"
os.environ["OPENAI_API_VERSION"] = "2022-12-01"
os.environ["OPENAI_API_BASE"] = "https://domain.openai.azure.com/"
os.environ["OPENAI_API_KEY"] = "****"

# Create an instance of Azure OpenAI
# Replace the deployment name with your own
llm = AzureOpenAI(
    deployment_name="gpt-35-turbo",
    model_name="gpt-35-turbo",
)

# Run the LLM
llm.max_tokens = 500    
llm.temperature = 0.7   
llm.top_p = 0.95        

prompt = PromptTemplate(
    input_variables=["address"],
    template="Hello, {address}，今天气怎么样?"
)

print(llm(prompt.format(address="Shanghai")))

```

**Comment by HEXtoDEC** [comment]
查阅了代码，发现并不是通过实例化langchain的OpenAI类进行请求的，而是原生包装了`requests`

所以我把代码中header部分的`Authorization` 改为 `api-key` （因为azure这边就要这么写）

请求的URL，还是由config.json引入

请求的url改为完整的azure的endpoint `https://domain.openai.azure.com/openai/deployments/gpt-35-turbo/chat/completions?api-version=2023-03-15-preview`即可使用

@Keldos-Li

**Comment by HEXtoDEC** [comment]
最后一个问题，这个使用在线搜索，似乎不是在用SERPAPI的API，得到的结果质量有问题。
想问下，除非自己改`tools()`之外，还有其他方式么。

**Comment by Keldos-Li** [comment]
昨日 4b9ef74bc3072b241e6d4dae4ac3b1248fc3040c ([Chuan Hu](https://github.com/GaiZhenbiao)) 加入了对 Azure OpenAI API 的支持。

**Comment by YunzhaoLu** [comment]
still not work with following setting:

    //== Azure ==
    "openai_api_type": "azure", // 可选项：azure, openai
    "azure_openai_api_key": "3*****************************6", // 你的 Azure OpenAI API Key，用于 Azure OpenAI 对话模型
    "azure_openai_api_base_url": "https://openai-****.openai.azure.com/", // 你的 Azure Base URL
    "azure_openai_api_version": "2023-07-01-preview", // 你的 Azure OpenAI API 版本
    "azure_deployment_name": "my-gpt", // 你的 Azure OpenAI Chat 模型 Deployment 名称
    "azure_embedding_deployment_name": "my-text-embedding", // 你的 Azure OpenAI Embedding 模型 Deployment 名称
    "azure_embedding_model_name": "text-embedding-ada-002", // 你的 Azure OpenAI Embedding 模型名称

Does anyone have a reference?
