### ISSUE TITLE
[功能请求]: 可同一个账号在不同地方登录不展示历史对话

### ISSUE THREAD

**Issue by pumpkin-nangua** [GaiZhenbiao/ChuanhuChatGPT#742]
### 可能的解决办法

目前同一个账号在不同浏览器，不同IP登录会展示之前的历史对话，能否添加可选是否展示历史对话

### 帮助开发

- [ ] 我愿意协助开发！

**Comment by Keldos-Li** [comment]
应当使用不同的账户
