### ISSUE TITLE
[本地部署]: 怎么自定义模型路径？

### ISSUE THREAD

**Issue by ReefJones** [GaiZhenbiao/ChuanhuChatGPT#745]
### 是否已存在现有反馈与解答？

- [X] 我确认没有已有issue或discussion，且已阅读**常见问题**。

### 是否是一个代理配置相关的疑问？

- [X] 我确认这不是一个代理配置相关的疑问。

### 错误描述

怎么自定义模型路径？

### 复现操作

1. 正常完成本地部署
2. 怎么自定义模型路径？

### 运行环境

```markdown
- OS: 
- Browser: 
- Gradio version: 
- Python version:
```

**Comment by GaiZhenbiao** [comment]
用软链接
