### ISSUE TITLE
[Bug]: 引用问题 

### ISSUE THREAD

**Issue by oldfishoh** [GaiZhenbiao/ChuanhuChatGPT#747]
### 这个bug是否已存在现有issue了？

- [X] 我确认没有已有issue，且已阅读**常见问题**。

### 错误表现

引用错误

### 复现操作

chanhuchatbot.py 第13行 

from modules.models.models import get_model
应为
from modules.models import get_model

### 错误日志

```shell
Traceback (most recent call last):
  File "/Users/laoyu/Documents/chat/ChuanhuChatbot.py", line 13, in <module>
    from modules.models.models import get_model
ModuleNotFoundError: No module named 'modules.models.models'; 'modules.models' is not a package
```

### 运行环境

- OS: 
- Browser: 
- Gradio version: 
- Python version: 

### 帮助解决

- [ ] 我愿意协助解决！

**Comment by Keldos-Li** [comment]
参考 [常见问题这部分](https://github.com/GaiZhenbiao/ChuanhuChatGPT/wiki/%E5%B8%B8%E8%A7%81%E9%97%AE%E9%A2%98#modulenotfounderror-no-module-named-modulesmodule-name-modules-is-not-a-package)，在modules/models/文件夹下新建__init__.py空文件。
