### ISSUE TITLE
[本地部署]: Something went wrongExpecting value: line 1 column 1 (char 0)

### ISSUE THREAD

**Issue by z-x-x136** [GaiZhenbiao/ChuanhuChatGPT#750]
### 是否已存在现有反馈与解答？

- [X] 我确认没有已有issue或discussion，且已阅读**常见问题**。

### 是否是一个代理配置相关的疑问？

- [X] 我确认这不是一个代理配置相关的疑问。

### 错误描述

![微信截图_20230512230006](https://github.com/GaiZhenbiao/ChuanhuChatGPT/assets/87004536/f9a0874c-ecfe-470e-9022-b8669deb019e)
![微信截图_20230512230026](https://github.com/GaiZhenbiao/ChuanhuChatGPT/assets/87004536/42d9623d-1fbb-4431-9c1f-9c3672e81aed)

### 复现操作

pip install -r requirements.txt

![微信截图_20230512230942](https://github.com/GaiZhenbiao/ChuanhuChatGPT/assets/87004536/b1787c31-dfae-425a-9e96-1a96a7a5f1e9)

python ChuanhuChatbot.py

### 错误日志

```shell
No terminal reported an error
```

### 运行环境

```markdown
- OS: win10
- Browser: chrome
- Gradio version: 3.28.0
- Python version: 3.9
```

### 补充说明

no

**Comment by Keldos-Li** [comment]
<img width="1040" alt="image" src="https://github.com/GaiZhenbiao/ChuanhuChatGPT/assets/23137268/dd99c921-8212-43f3-8aa3-76b02b50d988">

-----

🤧看在issue填写比较规范的份上，还是回复一下这个issue…… 一般来说这都是您的代理软件开启了系统代理导致的问题……请关闭系统代理。

您可以尝试先关闭代理，然后启动程序，然后再开启代理，再与ChatGPT对话。如果按照这个流程没有出现问题，那确实就是您的代理配置问题。
