### ISSUE TITLE
[Bug]: 更新后，API KEY疑似被盗

### ISSUE THREAD

**Issue by kiddog99** [GaiZhenbiao/ChuanhuChatGPT#752]
### 这个bug是否已存在现有issue了？

- [X] 我确认没有已有issue，且已阅读**常见问题**。

### 错误表现

我是将api key写到config文件里的....然后部署在本地终端使用.....
我是使用账号，账号里就5刀....
原本一直每天的用量也就是0.05刀左右.....

更新了0507版本之后，3天后，突然之间api用量爆炸，短短6个小时，使用额度全部被用完.....

我不信邪，又注册了一个试用账户.....还是0507版本，还是3天，api用量爆炸，6个小时，全部额度被用完....

建议检查一下是否有api key泄露风险.....

### 复现操作

我是将api key写到config文件里的....然后部署在本地终端使用.....
我是使用账号，账号里就5刀....
原本一直每天的用量也就是0.05刀左右.....

更新了0507版本之后，3天后，突然之间api用量爆炸，短短6个小时，使用额度全部被用完.....

我不信邪，又注册了一个试用账户.....还是0507版本，还是3天，api用量爆炸，6个小时，全部额度被用完....

建议检查一下是否有api key泄露风险.....

### 错误日志

```shell
/
```

### 运行环境

OS: Windows11 22H2
Browser: Chrome
Gradio version: 3.22.1
Python version: 3.11.1

### 帮助解决

- [ ] 我愿意协助解决！

### 补充说明

/

**Comment by oldfishoh** [comment]
检查下自己的代理？

**Comment by GaiZhenbiao** [comment]
看一下OpenAI的API历史？看一下是什么原因导致的？

**Comment by kiddog99** [comment]
> 看一下OpenAI的API历史？看一下是什么原因导致的？

查看了，确实是大量的prompt和completion，消耗了大量的promt

**Comment by kiddog99** [comment]
> 检查下自己的代理？

代理是自建的海外服务器，用V2RAY过去的

**Comment by kiddog99** [comment]
现在注册一个号是真的难...T.T....伤心啊.....

**Comment by oldfishoh** [comment]
> > 看一下OpenAI的API历史？看一下是什么原因导致的？
> 
> 查看了，确实是大量的prompt和completion，消耗了大量的token~
> 从每小时稳定的60~70requests，一直到每小时140requests....然后就消耗完了.....T.T

你得看看你是哪里泄露了 我觉得你检查一下浏览器？

**Comment by kiddog99** [comment]
> > > 看一下OpenAI的API历史？看一下是什么原因导致的？
> > 
> > 
> > 查看了，确实是大量的prompt和completion，消耗了大量的token~
> > 从每小时稳定的60~70requests，一直到每小时140requests....然后就消耗完了.....T.T
> 
> 你得看看你是哪里泄露了 我觉得你检查一下浏览器？

检查浏览器...感觉就很困难了....
有没有什么方式，对本项目的代码进行修改的，可以不显示或者不明文显示key？

我目前是写在config文件里....

**Comment by oldfishoh** [comment]
> > > > 看一下OpenAI的API历史？看一下是什么原因导致的？
> > > 
> > > 
> > > 查看了，确实是大量的prompt和completion，消耗了大量的token~
> > > 从每小时稳定的60~70requests，一直到每小时140requests....然后就消耗完了.....T.T
> > 
> > 你得看看你是哪里泄露了 我觉得你检查一下浏览器？
> 
> 检查浏览器...感觉就很困难了....
> 有没有什么方式，对本项目的代码进行修改的，可以不显示或者不明文显示key？
> 
> 我目前是写在config文件里....

跟本项目没关系

**Comment by kiddog99** [comment]
> > > > > 看一下OpenAI的API历史？看一下是什么原因导致的？
> > > > 
> > > > 
> > > > 查看了，确实是大量的prompt和completion，消耗了大量的token~
> > > > 从每小时稳定的60~70requests，一直到每小时140requests....然后就消耗完了.....T.T
> > > 
> > > 
> > > 你得看看你是哪里泄露了 我觉得你检查一下浏览器？
> > 
> > 
> > 检查浏览器...感觉就很困难了....
> > 有没有什么方式，对本项目的代码进行修改的，可以不显示或者不明文显示key？
> > 我目前是写在config文件里....
> 
> 跟本项目没关系

好的~我也是想问问看，是否有同样的反馈.....如果没有类似的反馈，估计问题定位还是在我自己的部署上.....

谢谢大佬~

**Comment by Keldos-Li** [comment]
>  有没有什么方式，对本项目的代码进行修改的，可以不显示或者不明文显示key？

🤧 是可以的，将该文件该行的值改为 True ，整个api输入框不会再显示。
https://github.com/GaiZhenbiao/ChuanhuChatGPT/blob/5e37a04b868fa0e0bdc00f02418e1c19434547cb/modules/presets.py#L39

不过这完全不影响……**_如果后端设定了apikey_**，前端网页**完全不会获取到**这个值，就算检查元素获取到的也是shadow content （useragent），硬要查看也是类似这样的：
<img width="285" alt="image" src="https://github.com/GaiZhenbiao/ChuanhuChatGPT/assets/23137268/a0309382-5a0a-454f-b11f-9b4c8b4d3cc6">，里面是真实的`*`字符串而不是啥掩饰方法，目前如果后端设定key，整个程序从头到尾就没有明文过……

而且我们的cookies里或浏览器本地存储里也不会存任何这方面相关的内容。
<img width="812" alt="image" src="https://github.com/GaiZhenbiao/ChuanhuChatGPT/assets/23137268/8ba55623-0c5e-40c4-a625-f53891737f72">
这里只存储了对话历史用于刷新时显示（未登录用户）和用户名和登录判断。

而cookies中，如果是登录用户，会有Gradio存储的登录access-token，未登录用户甚至不会有cookies。

总之，应该不会从浏览器层面泄露……

-----

而且最近的更新也没有动过这块内容，不太可能以前没事现在突然出事orz。

**Comment by kiddog99** [comment]
我大概找到问题了……是我太蠢了……
本项目不是在huggingface上部署了一个space嘛……我duplicate到了自己的space里，然后修改了其中的config文件，配置了密码，写入了api key，然后public了这个空间……然后……
我发现在file的界面里，不需要密码，可以直接看到space文件和历史记录……其中就有明文的config文件……T^T
我太蠢了……



---- 回复的原邮件 ----
| 发件人 | ***@***.***> |
| 日期 | 2023年05月13日 23:34 |
| 收件人 | ***@***.***> |
| 抄送至 | ***@***.***>、State ***@***.***> |
| 主题 | Re: [GaiZhenbiao/ChuanhuChatGPT] 是否有api key泄露风险？ (Issue #752) |

有没有什么方式，对本项目的代码进行修改的，可以不显示或者不明文显示key？

🤧 是可以的，将该文件该行的值改为 True ，整个api输入框不会再显示。
https://github.com/GaiZhenbiao/ChuanhuChatGPT/blob/5e37a04b868fa0e0bdc00f02418e1c19434547cb/modules/presets.py#L39

不过这完全不影响……如果后端设定了apikey，前端网页完全不会获取到这个值，就算检查元素获取到的也是shadow content （useragent），硬要查看也是类似这样的：
，里面是真实的*字符串而不是啥掩饰方法，目前如果后端设定key，整个程序从头到尾就没有明文过……

而且我们的cookies里或浏览器本地存储里也不会存任何这方面相关的内容。

这里只存储了对话历史用于刷新时显示（未登录用户）和用户名和登录判断。

而cookies中，如果是登录用户，会有Gradio存储的登录access-token，未登录用户甚至不会有cookies。

总之，应该不会从浏览器层面泄露……

而且最近的更新也没有动过这块内容，不太可能以前没事现在突然出事orz。

**Comment by Keldos-Li** [comment]
好吧……是有点惨……

下次记得参考 [wiki教程](https://github.com/GaiZhenbiao/ChuanhuChatGPT/wiki/使用教程#设置space) 的方法在space设置的Secret中设置私密的orz

**Comment by kiddog99** [comment]
> 好吧……是有点惨……
> 
> 下次试试参考 [wiki教程](https://github.com/GaiZhenbiao/ChuanhuChatGPT/wiki/%E4%BD%BF%E7%94%A8%E6%95%99%E7%A8%8B#%E8%AE%BE%E7%BD%AEspace) 的方法在space设置的Secret中设置私密的orz

谢谢大佬！

**Comment by kiddog99** [comment]
> 

对了，亲，我记得咱们可以设置访问的用户名和密码，这部分，是否也可以做成Secret？
