### ISSUE TITLE
代码块样式适配 gradio 3.28.3

### ISSUE THREAD

**Issue by ChenziSC** [GaiZhenbiao/ChuanhuChatGPT#755]
### 这个bug是否已存在现有issue了？

- [X] 我确认没有已有issue，且已阅读**常见问题**。

### 错误表现

![image](https://github.com/GaiZhenbiao/ChuanhuChatGPT/assets/20588811/955e746f-ea71-42d4-9a0a-b6c0d7e6a9d2)

### 复现操作

今天拉了最新的代码，跑了pip3 install -r requirements.txt  和   pip3 install gradio --upgrade --force-reinstall，重新启动项目后代码块的背景颜色就不对了

### 运行环境

- OS: 
- Browser: 
- Gradio version: 
- Python version: 

### 帮助解决

- [ ] 我愿意协助解决！

**Comment by GaiZhenbiao** [comment]
不要随便升级gradio的版本，requirements里指定了版本。

**Comment by ChenziSC** [comment]
> 不要随便升级gradio的版本，requirements里指定了版本。

可我是照着readme来操作的呀

**Comment by Keldos-Li** [comment]
被你发现了！是的，亮色模式时的代码块背景色会比深色模式时的浅一些。是这么写的。

**Comment by Keldos-Li** [comment]
我有空再做一下对新版本gradio的适配……有点点麻烦……

**Comment by Keldos-Li** [comment]
Resolved via de613b48355a2594dabca66b2192723b67bf92b4
