### ISSUE TITLE
[功能请求]: 建议新增历史文件删除功能

### ISSUE THREAD

**Issue by wxtt522** [GaiZhenbiao/ChuanhuChatGPT#756]
### 相关问题

用户似乎不能自己删除聊天历史文件，只能后台自己删history文件夹

### 可能的解决办法

除了保存和导入对话，建议新增个删除历史对话文件，

### 帮助开发

- [ ] 我愿意协助开发！

**Comment by themis0009** [comment]
同求这个功能，有些问题保留着确实不太好

**Comment by GaiZhenbiao** [comment]
现在加入这个功能啦

<img width="344" alt="image" src="https://github.com/GaiZhenbiao/ChuanhuChatGPT/assets/51039745/4d098651-e935-49a8-b124-0e91766a61d3">
