### ISSUE TITLE
错误 

### ISSUE THREAD

**Issue by hi609** [GaiZhenbiao/ChuanhuChatGPT#76]
"☹️发生了错误
返回值：
异常：Expecting value: line 1 column 1 (char 0)"
有时候会这样，刷新一下就可以了

**Comment by 5akki** [comment]
☹️发生了错误
返回值：
异常：Expecting value: line 1 column 1 (char 0)
我也遇到这个问题 怎么解决? 刷新没用

**Comment by hi609** [comment]
可以

> ☹️发生了错误 返回值： 异常：Expecting value: line 1 column 1 (char 0) 我也遇到这个问题 怎么解决? 刷新没用

可以重开一下.py文件

**Comment by GaiZhenbiao** [comment]
看Readme
