### ISSUE TITLE
[功能请求]: 回复框标注由哪个模型生成。

### ISSUE THREAD

**Issue by hawhuang** [GaiZhenbiao/ChuanhuChatGPT#760]
### 可能的解决办法

回复框标注由哪个模型生成。

### 帮助开发

- [ ] 我愿意协助开发！

**Comment by Keldos-Li** [comment]
20230507 677b142 之后的代码均有此功能。

**Comment by hawhuang** [comment]
和 https://github.com/GaiZhenbiao/ChuanhuChatGPT/commit/677b142d5bf6b9369deff99c21d8ade88f340dfa 中的实现需求不一样，比如历史中有多个对话，每个对话可能是不同模型生成的，希望每个回复分别标注是哪个模型

**Comment by Keldos-Li** [comment]
感觉其实不是很现实……但如果有人愿意画一个原型的话，倒还有可能探讨一下怎么做

**Comment by hawhuang** [comment]
<img width="861" alt="image" src="https://github.com/GaiZhenbiao/ChuanhuChatGPT/assets/24662392/4555c5ce-1b4a-44ba-964f-67e02cd76e5e">
每条回答加个注释就行，当然可以直接加在返回的文字里，就是可能影响上下文对话。

**Comment by hawhuang** [comment]
> <img alt="image" width="861" src="https://user-images.githubusercontent.com/24662392/240118781-4555c5ce-1b4a-44ba-964f-67e02cd76e5e.png">

每条回答加个注释就行，当然可以直接加在返回的文字里，就是可能影响上下文对话。

**Comment by Keldos-Li** [comment]
大部分人倒并不会频繁切换模型……所以会觉得不是一个必要的功能……

直接放气泡里也太丑了，也太重复了……
现在气泡的padding是比较小的，没地方再加这些信息……
