### ISSUE TITLE
[Docker]: 

### ISSUE THREAD

**Issue by rlznfhkppf0281** [GaiZhenbiao/ChuanhuChatGPT#766]
### 是否已存在现有反馈与解答？

- [X] 我确认没有已有issue或discussion，且已阅读**常见问题**。

### 是否是一个代理配置相关的疑问？

- [X] 我确认这不是一个代理配置相关的疑问。

### 错误描述

使用最新版docker镜像启动失败。切换为上一版镜像后运行成功

### 复现操作

docker run -d --name ChuanhuChat \
	-v ~/www/ChuanhuChatGPT/history:/app/history \
	-v ~/www/ChuanhuChatGPT/config.json:/app/config.json \
	-p 7860:7860 \
	tuchuanhuhuhu/chuanhuchatgpt:latest

### 错误日志

```shell
2023-05-19 07:57:06,888 [INFO] [models.py:562] 正在加载OpenAI模型: gpt-3.5-turbo
2023-05-19 07:57:06,892 [INFO] [models.py:607] 模型设置为了： gpt-3.5-turbo
2023-05-19 07:57:07,771 [INFO] [utils.py:407] 您的IP区域：United States。
Traceback (most recent call last):
  File "/app/ChuanhuChatbot.py", line 290, in <module>
    autogpt_mode,
NameError: name 'autogpt_mode' is not defined
```

### 运行环境

- OS:  Centos7
- Docker version: 
- Gradio version: 
- Python version:

**Comment by AceLing** [comment]
I'm in the same situation. :(

**Comment by Keldos-Li** [comment]
刚重新push了一版docker，试试行不行？

**Comment by miaowmint** [comment]
> 刚重新push了一版docker，试试行不行？

可以正常运行了

**Comment by rlznfhkppf0281** [comment]
此问题涉及的docker版本为：[23.05.18](https://hub.docker.com/layers/tuchuanhuhuhu/chuanhuchatgpt/23.05.18/images/sha256-8ed6a0cb77ec07827240389ebfda4362de1e6c8b1e730c72b6bb6201a515c6ac?context=explore)，现在关闭这个问题
