### ISSUE TITLE
[Bug]: 回答含有代码的问题时会转义为代码并运行，无法以文字形式输出

### ISSUE THREAD

**Issue by mctds** [GaiZhenbiao/ChuanhuChatGPT#767]
### 这个bug是否已存在现有issue了？

- [X] 我确认没有已有issue，且已阅读**常见问题**。

### 错误表现

回答含有代码的问题时会转义为代码并运行，无法以文字形式输出。
比如：提问“给我一段完整的html框架代码”
![微信截图_20230519190307](https://github.com/GaiZhenbiao/ChuanhuChatGPT/assets/77908808/4cb0e066-d223-4b6b-bfa9-01f336d37ea9)

### 复现操作

无

### 运行环境

- OS: 
- Browser: 
- Gradio version: 
- Python version: 

### 帮助解决

- [ ] 我愿意协助解决！

**Comment by Keldos-Li** [comment]
请更新，更新后可以切换原始输出和渲染后输出。

**Comment by mctds** [comment]
> 请更新，更新后可以切换原始输出和渲染后输出。

Hugging Face 是最新版本吗？

**Comment by Keldos-Li** [comment]
hugging face上的好久没更新了🤧

**Comment by mctds** [comment]
> hugging face上的好久没更新了🤧

啊！这~什么时候可以更一下哇，哈哈

**Comment by GaiZhenbiao** [comment]
现在更新啦
