### ISSUE TITLE
部署在公网服务器的问题。

### ISSUE THREAD

**Issue by dadaoerv** [GaiZhenbiao/ChuanhuChatGPT#77]
不好意思，又开了一个issue。
我在debian的vps上，本地运行Python，设置ip和端口后，提示：
[Errno 99] error while attempting to bind on address ('155.177.158.177', 7860): cannot assign requested address
如果设置127.0.0.1的话，不报错，但是主机公网ip不能访问。
如果设置反向代理，出现something went wrong的问题，外面大佬的解释是127.0.0.1被代理了，设置直连。我的问题是，不会设置直连
目前唯一可以使用，无故障的是公开链接。

请教大佬，到底如何设置公网服务器的地址。我是在最下面的一行，密码那个里设置的

**Comment by GaiZhenbiao** [comment]
server_name 设置 127.0.0.1 就行了，server_port不用设置

**Comment by valetzx** [comment]
![image](https://user-images.githubusercontent.com/45054400/223693132-c3e482c5-0b79-410b-9197-6345c8e09296.png)
最后一行的 `demo.queue().launch(share=False)` 
改成 `demo.launch(server_name="0.0.0.0", server_port=7860)` 端口任意

**Comment by Keldos-Li** [comment]
参考：
* #89

**Comment by Nativu5** [comment]
> 参考：
> 
> * [网站设置登录账号密码后`Connection errored out` #89](https://github.com/GaiZhenbiao/ChuanhuChatGPT/issues/89)

这个其实不应该算是一个解决方案，因为修改了 Python 包，而且不兼容 Docker 镜像（Docker 镜像没法修改 Python 代码）。

我解决这个问题的做法是，在 Nginx 里面启用 SSL。可以套一层 Cloudflare 来解决证书的问题，也可以选择用 acme.sh 申请证书来部署。

**Comment by yqty** [comment]
上面的兄弟怎么解决的，我也是公网访问不了，分享没有问题，docker也没问题，就是设置成自己的ip访问不了

**Comment by yuke0929** [comment]
我也是 本地可以访问 nginx反代本地ip就不行了 使用公网IP也不行

**Comment by surqing** [comment]
> 不好意思，又开了一个issue。 我在debian的vps上，本地运行Python，设置ip和端口后，提示： [Errno 99] error while attempting to bind on address ('155.177.158.177', 7860): cannot assign requested address 如果设置127.0.0.1的话，不报错，但是主机公网ip不能访问。 如果设置反向代理，出现something went wrong的问题，外面大佬的解释是127.0.0.1被代理了，设置直连。我的问题是，不会设置直连 目前唯一可以使用，无故障的是公开链接。
> 
> 请教大佬，到底如何设置公网服务器的地址。我是在最下面的一行，密码那个里设置的

你好，请问你的问题解决了吗，我是不太会用Nginx进行反向代理，如果要用Nginx反向代理的话需要做哪些事情嘞？

**Comment by surqing** [comment]
解决了，如果想使用Nginx进行反向代理的话，在.py文件中不用修改任何参数，直接在本地运行，在configue.json中底下修改成一下内容    
```
// 如果使用自定义端口、自定义ip，请取消注释并替换对应内容
    "server_name": "0.0.0.0",
    "server_port": 7860,
```
    之后使用后台运行的命令后台运行 
    `nohup python ChuanhuChatbot.py > ./runningLog.log 2>&1 &`
    在Nginx的配置中必须使用ssl，
