### ISSUE TITLE
[其他]: Edge 浏览器访问 报错，什么都干不了，谷歌浏览器访问正常

### ISSUE THREAD

**Issue by melooy** [GaiZhenbiao/ChuanhuChatGPT#776]
### 是否已存在现有反馈与解答？

- [X] 我确认没有已有issue或discussion，且已阅读**常见问题**。

### 错误描述

 Edge 浏览器访问 报错：ncaught (in promise) DOMException: Failed to execute 'insertBefore' on 'Node': The node before which the new node is to be inserted is not a child of this node.  
火箭图标那一直显示 getting user info… 获取用户信息..
打字点发送什么的都没有反应。
使用谷歌浏览器正常，用户也能正常获取到。

### 复现操作

Edge 浏览器访问 报错，什么都干不了，谷歌浏览器访问正常

### 错误日志

```shell
index.mjs:369 
 Uncaught (in promise) DOMException: Failed to execute 'insertBefore' on 'Node': The node before which the new node is to be inserted is not a child of this node.
    at k (index-29e08d05.js:1:9235)
    at Object.m (index-29e08d05.js:8:8313)
    at Object.p (index-29e08d05.js:8:6371)
    at Object.p (index-29e08d05.js:8:13530)
    at Cr (index-29e08d05.js:4:1913)
    at $t (index-29e08d05.js:4:1548)
m	@	StatusTracker.svelte:218
p	@	StatusTracker.svelte:195
p	@	StatusTracker.svelte:301
Promise.then(异步)		
(匿名)	@	Blocks.svelte:44
i	@	stores.ts:110
(匿名)	@	Blocks.svelte:250
(匿名)	@	index.js:134
E	@	index.js:134
R.onmessage	@	index.js:235
Show 8 more frames
```

### 运行环境

- OS: Windows 11 家庭中文版 22H2
- Edge：版本 115.0.1851.0 (正式版本) dev (64 位) 和 版本 113.0.1774.50 (正式版本) (64 位) 都不行

**Comment by Keldos-Li** [comment]
看上去出错点在gradio框架的js……如果是这样可能得等gradio解决。
你可以先试试清除缓存，退出edge再重新打开。
