### ISSUE TITLE
一直在主界面显示加载中 Loading...

### ISSUE THREAD

**Issue by a6225301** [GaiZhenbiao/ChuanhuChatGPT#777]
### 是否已存在现有反馈与解答？

- [X] 我确认没有已有issue或discussion，且已阅读**常见问题**。

### 是否是一个代理配置相关的疑问？

- [X] 我确认这不是一个代理配置相关的疑问。

### 错误描述

用chrome浏览器，会一直在主界面加载，console会报错

![image](https://github.com/GaiZhenbiao/ChuanhuChatGPT/assets/22911232/360fb9c1-413c-4caf-86e2-fa9c656025de)
![image](https://github.com/GaiZhenbiao/ChuanhuChatGPT/assets/22911232/b65f77d1-44bd-4e24-bf75-5044a3348741)

### 复现操作

已经正常完成部署

### 错误日志

```shell
用chrome浏览器，会一直在主界面加载，console会报错
Failed to load resource: net::ERR_CONNECTION_RESET
```

### 运行环境

- OS: win
- Server: linux
- Gradio version: 3.28.0
- Python version: 3

### 补充说明

无

**Comment by Keldos-Li** [comment]
如果其他浏览器可用而Chrome不可用，请尝试
1. 使用无痕模式重试
2. 清除浏览器所有缓存，完全退出浏览器，重新启动chuanhu chat再打开浏览器

这是一个和gradio更相关的问题，由于国内对fonts.googleapi.com访问的特殊的网络环境，我们擦不了屁股……

**Comment by Keldos-Li** [comment]
如果还是不行或有更多疑问，欢迎在此ISSUE下继续反馈~先关闭了
