### ISSUE TITLE
[Bug]: 一键复制部署到huggingface，复制弹框填写的API_KEY和在私有环境setting填写的API_KEY不会同步到主界面

### ISSUE THREAD

**Issue by T97-coffee** [GaiZhenbiao/ChuanhuChatGPT#778]
### 这个bug是否已存在现有issue了？

- [X] 我确认没有已有issue，且已阅读**常见问题**。

### 错误表现

不管是在复制时弹出的弹框填写还是在复制后的私有环境setting都不会生效，如果在主界面那个输入框填写的刷新就没了，也不是持久的。之前某个版本我复制之后在setting填写的key还是可以持久的

### 复现操作

1.从https://github.com/GaiZhenbiao/ChuanhuChatGPT点击一键部署
2.复制空间填写XMCHAT_API_KEY:自己的API_KEY;
3.部署成功发现主界面的api_key输入框是空的；
4.到setting填写XMCHAT_API_KEY,回来刷新还是空的

### 运行环境

- OS: 
- Browser: 
- Gradio version: 
- Python version: 

### 帮助解决

- [ ] 我愿意协助解决！

**Comment by GaiZhenbiao** [comment]
尽管输入框是空的，实际上是可以使用的。只是没有把API Key显示出来。

**Comment by T97-coffee** [comment]
并没有啊，Error: { “error”: { “message”: “You didn’t provide an API key. You need to provide your API key in an Authorization header using Bearer auth (i.e. Authorization: Bearer YOUR_KEY), or as the password field (with blank username) if you’re accessing the API from your browser and are prompted for a username and password. You can obtain an API key from https://platform.openai.com/account/api-keys.”, “type”: “invalid_request_error”, “param”: null, “code”: null }}，还是会报这个，之前某个版本复制后在setting填写会显示一串*号。这和从主界面填写后表现是一致的

**Comment by GaiZhenbiao** [comment]
XMCHAT_API_KEY 是用于 XMChat模型的，你想用GPT的话需要填写的是 OPENAI_API_KEY

**Comment by T97-coffee** [comment]
ok，在settings新增Repository secrets 新增OPENAI_API_KEY已解决，误认为XMCHAT_API_KEY 是原来的OPENAI_API_KEY了。感谢感谢！！！
