### ISSUE TITLE
[功能请求]: 环境变量希望加入OPENAI_API_BASE

### ISSUE THREAD

**Issue by xiangfeigao** [GaiZhenbiao/ChuanhuChatGPT#779]
### 相关问题

国内转发这样就更加方便了

### 可能的解决办法

解决国内使用

### 帮助开发

- [ ] 我愿意协助开发！

**Comment by GaiZhenbiao** [comment]
刚push了一个更新，现在支持啦。如果有任何问题，欢迎反馈👏

**Comment by Keldos-Li** [comment]
链接一下相关issue
- #737
