### ISSUE TITLE
[Docker]: 最新版本docker部署运行失败

### ISSUE THREAD

**Issue by wanghuan6887** [GaiZhenbiao/ChuanhuChatGPT#781]
### 是否已存在现有反馈与解答？

- [X] 我确认没有已有issue或discussion，且已阅读**常见问题**。

### 是否是一个代理配置相关的疑问？

- [X] 我确认这不是一个代理配置相关的疑问。

### 错误描述

最新代码使用docker部署后，运行的时候报错

### 复现操作

mkdir ~/ChuanhuChatGPT
mkdir ~/ChuanhuChatGPT/history
docker run --rm tuchuanhuhuhu/chuanhuchatgpt:latest cat /app/config_example.json > ~/ChuanhuChatGPT/config.json
docker run -d --name ChuanhuChat \
	-v ~/ChuanhuChatGPT/history:/app/history \
	-v ~/ChuanhuChatGPT/config.json:/app/config.json \
	-p 7860:7860 \
	tuchuanhuhuhu/chuanhuchatgpt:latest

### 错误日志

```shell
Traceback (most recent call last):
  File "/app/ChuanhuChatbot.py", line 13, in <module>
    from modules.models.models import get_model
  File "/app/modules/models/models.py", line 18, in <module>
    from duckduckgo_search import ddg
ModuleNotFoundError: No module named 'duckduckgo_search'
```

### 运行环境

- OS: Linux
- Docker version: 23.0.1

**Comment by GaiZhenbiao** [comment]
非常抱歉，依赖没有删除干净。现在已经修复！

**Comment by vshen009** [comment]
我在requirements.txt 加入了 duckduckgo_search 重新构建了镜像就OK了. 申请duckduckgo_search加入requirements.txt

**Comment by GaiZhenbiao** [comment]
> 我在requirements.txt 加入了 duckduckgo_search 重新构建了镜像就OK了. 申请duckduckgo_search加入requirements.txt

duckduckgo_search这个依赖工作不正常，我现在把它换成google_search了。依赖没有删除干净，非常抱歉！
