### ISSUE TITLE
[功能请求]: 申请加入AZURE的GPT3.5的API支持

### ISSUE THREAD

**Issue by HEXtoDEC** [GaiZhenbiao/ChuanhuChatGPT#783]
### 可能的解决办法

希望加入AZURE的API支持，按官方说法AZURE的API与OPENAI的一致。

### 帮助开发

- [X] 我愿意协助开发！

### 补充说明

AZURE的API调用方式与OPENAI的方式一样
但AZURE的API在实例化之前需要一些额外的AZURE独有的参数，比如：API地区，部署的模型昵称等

**Comment by Keldos-Li** [comment]
感谢反馈，也希望您能在 #740 中继续说明~

您勾选了“_我愿意协助开发！_”，如果您愿意之后帮忙引入并提交pr就太好啦
