### ISSUE TITLE
[功能请求]: 换了google搜索后使用在线搜索功能报错

### ISSUE THREAD

**Issue by Maddaxman** [GaiZhenbiao/ChuanhuChatGPT#784]
### 相关问题

<img width="2109" alt="image" src="https://github.com/GaiZhenbiao/ChuanhuChatGPT/assets/31379908/f9c75c2d-c571-4da2-a3cc-a3fc15054ceb">

### 帮助开发

- [ ] 我愿意协助开发！

**Comment by GaiZhenbiao** [comment]
你可以正常访问google吗？奇怪，按理说之前用的ddg也需要代理的😂

**Comment by Maddaxman** [comment]
可以的，我在海外服务器部署的

**Comment by Maddaxman** [comment]
> 可以的，我在海外服务器部署的

可以的，我在海外服务器部署的

**Comment by Maddaxman** [comment]
> 你可以正常访问google吗？奇怪，按理说之前用的ddg也需要代理的😂

可以的，我在海外服务器部署的

**Comment by GaiZhenbiao** [comment]
始终会有这个错误吗？

**Comment by Maddaxman** [comment]
> 始终会有这个错误吗？

是的，重新运行了再试也有

**Comment by GaiZhenbiao** [comment]
> > 始终会有这个错误吗？
> 
> 川虎，我看这日志，感觉好像是触发了谷歌反爬机制了。大部分主流的搜索引擎都有反爬机制，建议在线搜索功能还是换成duckduckgo吧，借这位兄弟的楼反馈一个问题，用川虎助理pro，大部分问题都是显示tokens超限，我设置的模型是3.5-turbo，是不是应该用4才行？。

等duckduckgo_search这个包工作正常之后，就换回去。川虎助理最好用GPT4，我看看能不能优化一下，让3.5能不能token不超限。

**Comment by Keldos-Li** [comment]
（歪个楼，@LaoJiuYes ～～知道你❤️川虎了QAQ～～ ，但是能不能不要每次都把自己的评论**_删掉再重发_**QAQ，评论可以编辑的🤧

（收到一堆通知结果点进来发现啥也没有让人有点怀疑自己🥲

**Comment by tanpengsccd** [comment]
同样问题. 
<img width="1041" alt="image" src="https://github.com/GaiZhenbiao/ChuanhuChatGPT/assets/13959880/2d4df191-973f-4ac7-9a69-0f9948a77fa6">

能不能搜索  独立出来一个 代理配置列表 轮训? 或者 warp ?

**Comment by zhiqing0205** [comment]
同这个问题，疯狂error，就开局用了几次，怕不是ip被封了

**Comment by zhiqing0205** [comment]
IP访问谷歌是没问题的，应该是触发反爬了，就类似需要进行谷歌验证点图片什么的阻止了正常的搜索结果的返回

**Comment by GaiZhenbiao** [comment]
现在 DuckDuckGo 正常了，最新版换回了 DuckDuckGo，你们试试？
