### ISSUE TITLE
[Bug]: 索引构建失败

### ISSUE THREAD

**Issue by scjiaer** [GaiZhenbiao/ChuanhuChatGPT#789]
### 这个bug是否已存在现有issue了？

- [X] 我确认没有已有issue，且已阅读**常见问题**。

### 错误表现
上传txt文本文件
```
[ERROR] [index_func.py:139] 索引构建失败！'list' object has no attribute 'page_content'
Traceback (most recent call last):
  File "/data/repo/ChuanhuChatGPT/modules/index_func.py", line 127, in construct_index
    documents = get_documents(file_src)
  File "/data/repo/ChuanhuChatGPT/modules/index_func.py", line 86, in get_documents
    texts = text_splitter.split_documents([texts])
  File "/data/anaconda3/envs/llm/lib/python3.9/site-packages/langchain/text_splitter.py", line 69, in split_documents
    texts = [doc.page_content for doc in documents]
  File "/data/anaconda3/envs/llm/lib/python3.9/site-packages/langchain/text_splitter.py", line 69, in <listcomp>
    texts = [doc.page_content for doc in documents]
AttributeError: 'list' object has no attribute 'page_content'
```

### 复现操作

1. 正常完成本地部署
2. 上传文件
3. 提示`索引构建失败！'list' object has no attribute 'page_content'`

### 运行环境

- OS: CentOS 7
- Browser: Chrome
- Gradio version: 3.3.30
- Python version: 3.9.16

### 帮助解决

- [X] 我愿意协助解决！

### 补充说明

langchain库(v0.0.173)BaseLoader类的load方法返回的是List[Document]，
TextSplitter类split_documents接收的是List[Document]，
而ChuanhuChatGPT库modules/index_func.py中texts = text_splitter.split_documents([texts])
意味着text_splitter实例实际接受的参数是[List[List[Document]]]
可以统一将texts对象类型设置为为List[Document]，2点改动
1. `texts = text_splitter.split_documents([texts])`改成`texts = text_splitter.split_documents(texts)`
2. pdf文件，texts使用list封装一层，`texts = Document(page_content=pdftext, metadata={"source": filepath})`改成`texts = [Document(page_content=pdftext, metadata={"source": filepath})]`

另外，xlsx文件的处理逻辑没看明白
```python
for elem in text_list:
    documents.append(Document(page_content=elem, metadata={"source": filepath}))
continue
```
改成如下更合适?
```python
for elem in text_list:
    texts.append(Document(page_content=elem, metadata={"source": filepath}))
```

**Comment by GaiZhenbiao** [comment]
感谢建议！修复啦
