### ISSUE TITLE
The formation of code went wrong in my website

### ISSUE THREAD

**Issue by forestmgy** [GaiZhenbiao/ChuanhuChatGPT#79]
demo here:
![image](https://user-images.githubusercontent.com/101162387/223697207-481a2b8c-8d99-456c-8a75-0254567cb5d4.png)
it just happened when I use the latest version

**Comment by forestmgy** [comment]
It's a little weird because when I try this again, it works.
![image](https://user-images.githubusercontent.com/101162387/223699012-1c63bbbd-f95f-4896-a534-b4aaf66b634f.png)

**Comment by forestmgy** [comment]
It's a little weird because when I try this again, it works.
![image](https://user-images.githubusercontent.com/101162387/223699012-1c63bbbd-f95f-4896-a534-b4aaf66b634f.png)

**Comment by Keldos-Li** [comment]
Should be resolved with bd419af2ec56000875251c3958d047b4d0a920b6  ([Chuanhu](https://github.com/GaiZhenbiao))
