### ISSUE TITLE
[Bug]: 23年6月2日，在线搜索功能不再可用了

### ISSUE THREAD

**Issue by RickPratts** [GaiZhenbiao/ChuanhuChatGPT#790]
### 这个bug是否已存在现有issue了？

- [X] 我确认没有已有issue，且已阅读**常见问题**。

### 错误表现

当打开在线搜索问GPT需要在线搜索的问题时，会有以下情况：
1.拒绝查询或者搜索，或者说未找到信息
2.伪造假网址后来引用，来回答问题
3.未在线搜索，使用了过时的资料
![图片](https://github.com/GaiZhenbiao/ChuanhuChatGPT/assets/131772683/0190e9e5-8c40-4b41-8327-33dba396c19f)
![图片](https://github.com/GaiZhenbiao/ChuanhuChatGPT/assets/131772683/d3001ca8-b618-4297-a431-acfccddf691b)
![图片](https://github.com/GaiZhenbiao/ChuanhuChatGPT/assets/131772683/e2b33e24-ae28-4c96-9ec0-74951416ad8c)

### 复现操作

我之前尝试过用不干净的IP登录过openai.com，以及我绑定的是depay卡，目前depay卡已经不可支付了。项目的运行一切正常

### 错误日志

```shell
我之前尝试过用不干净的IP登录过openai.com，以及我绑定的是depay卡，目前depay卡已经不可支付了，所以我想知道：
1.是我触发了极高风控，导致API被ban了吗?
2.是openai官方把API的在线搜索关闭了,变成了这样吗?
3.目前使用的是最新版本项目,是这个项目本身的问题吗?
```

### 运行环境

- OS: windows11
- Browser: firefox
- Gradio version: 3.28.0
- Python version: 3.10.10

### 帮助解决

- [ ] 我愿意协助解决！

### 补充说明

暂无更多参考资料

**Comment by GaiZhenbiao** [comment]
你有勾选上“使用在线搜索”勾选框吗？

**Comment by GaiZhenbiao** [comment]
那可能是软件没有抓取到搜索结果。这个不是OpenAI 提供的功能，是川虎 Chat 的功能。我看能不能改进下。

**Comment by GaiZhenbiao** [comment]
现在应该可以了
