### ISSUE TITLE
[功能请求]: 能否添加gpt-3.5-turbo-16k模型呢？

### ISSUE THREAD

**Issue by Rooooooobin** [GaiZhenbiao/ChuanhuChatGPT#808]
### 相关问题

近日，OpenAI提供了最新的模型（gpt-3.5-turbo-16k），能否添加到ChuanhuChatGPT中呢？并且希望能都在hugging face中同步，谢谢。

### 可能的解决办法

如题

### 帮助开发

- [X] 我愿意协助开发！

**Comment by GaiZhenbiao** [comment]
https://github.com/GaiZhenbiao/ChuanhuChatGPT/commit/cc3510282d4fe932b800970f238bb853e77c6297 已经加入了，HuggingFace 上也已经同步过去了。 

<img width="308" alt="image" src="https://github.com/GaiZhenbiao/ChuanhuChatGPT/assets/51039745/1d210c13-cddd-4550-92a4-c21a0d007a3c">
