### ISSUE TITLE
支持新模型

### ISSUE THREAD

**Issue by Passerby1011** [GaiZhenbiao/ChuanhuChatGPT#811]
### 相关问题

支持新模型

### 可能的解决办法

支持新模型

### 帮助开发

- [X] 我愿意协助开发！

### 补充说明

openai发布了新模型，gpt-3.5-turbo有了16k

**Comment by Keldos-Li** [comment]
Hi, 感谢您的提醒！如果您关注我们的项目更新，你会发现昨日我们已经在第一时间支持了相关新模型啦~

您可以进一步参阅：
- **[更新日志](https://github.com/GaiZhenbiao/ChuanhuChatGPT/wiki/更新日志#20230614)**
- **[如何更新？](https://github.com/GaiZhenbiao/ChuanhuChatGPT/wiki/常见问题#故障排除)**

**Comment by Passerby1011** [comment]
川虎助理和助理pro不支持最新的3.5-16k，它们使用4太贵，原来的3.5上下文限制4096token

**Comment by Passerby1011** [comment]
> Hi, 感谢您的提醒！如果您关注我们的项目更新，你会发现昨日我们已经在第一时间支持了相关新模型啦~
> 
> 您可以进一步参阅：
> 
> * **[更新日志](https://github.com/GaiZhenbiao/ChuanhuChatGPT/wiki/%E6%9B%B4%E6%96%B0%E6%97%A5%E5%BF%97#20230614)**
> * **[如何更新？](https://github.com/GaiZhenbiao/ChuanhuChatGPT/wiki/%E5%B8%B8%E8%A7%81%E9%97%AE%E9%A2%98#%E6%95%85%E9%9A%9C%E6%8E%92%E9%99%A4)**

川虎助理和助理pro不支持最新的3.5-16k，它们使用4太贵，原来的3.5上下文限制4096token
