### ISSUE TITLE
使用docker 部署后，命令行的问题

### ISSUE THREAD

**Issue by Jfef** [GaiZhenbiao/ChuanhuChatGPT#82]
命令行存在格式问题
`sudo docker run -d --name chatgpt -e my_api_key="用户的api token" -v /home/chatGPThistory:/app/history -p 7860:7860 tuchuanhuhuhu/chuanhuchatgpt:latest
 `
`-v `后面的路径有问题

我也不知道什么错误，chatgpt 免费版给出的原答案

docker: Error response from daemon: invalid volume specification: '/home/chatGPThistory:app/history': invalid mount config for type "bind": invalid mount path: 'app/history' mount path must be absolute.

The error message you are seeing suggests that there is an issue with the way you are trying to mount a volume using the bind type in Docker.

Specifically, the error message indicates that the mount path you have specified for the volume, app/history, is not an absolute path. When using bind type volume mounts, the mount path must be an absolute path starting with a forward slash (/).

To fix this issue, you should modify your volume specification to use an absolute path for the mount point. For example, if you want to mount the directory /home/chatGPThistory on your host machine to the app/history directory in your Docker container, you should use the following volume specification:

javascript

-v /home/chatGPThistory:/app/history

This specifies an absolute path (/home/chatGPThistory) for the host directory and an absolute path (/app/history) for the mount point in the container.

**Comment by Jfef** [comment]
我在ubuntu 安装的
1.安装docker.io ：这一步ubuntu 会给出命令行提示
2.题主给的第一步，第二步骤：有错误已经指出，如上所示
3.访问，ip:port 即可

**Comment by qingqingziying** [comment]
正确的命令：
docker run -d --name chatgpt \
	-e my_api_key="替换成API" \
	-v /root/chatGPThistory:/app/history \
	-p 7860:7860 \
	tuchuanhuhuhu/chuanhuchatgpt:latest

**Comment by GaiZhenbiao** [comment]
好的，readme已经更新。
