### ISSUE TITLE
[功能请求]: 

### ISSUE THREAD

**Issue by tutianyu101** [GaiZhenbiao/ChuanhuChatGPT#821]
### 相关问题

是这样的，我部署在我的服务器上的，大家一起用，我发现聊天记录可以互相查看，这个怎么避免呢？可以后台设置不保存聊天记录吗？或者保存在浏览器缓存里？

### 可能的解决办法

实现：默认不保存聊天记录，或者实现保存在对方浏览器缓存中

### 帮助开发

- [X] 我愿意协助开发！

**Comment by tutianyu101** [comment]
@GaiZhenbiao 大佬这个可以实现吗？目前我有8个小伙伴等着用。。

**Comment by GaiZhenbiao** [comment]
设置多个账号，每个账号的历史记录是独立的。

**Comment by Keldos-Li** [comment]
刚才补了下wiki：[未登录时隐藏历史对话记录](https://github.com/GaiZhenbiao/ChuanhuChatGPT/wiki/使用教程#未登录时隐藏历史对话记录)

- 另请参考：[设置用户登录密码](https://github.com/GaiZhenbiao/ChuanhuChatGPT/wiki/使用教程#设置用户登录密码)
