### ISSUE TITLE
[远程部署]: 对话气泡复制按钮错误

### ISSUE THREAD

**Issue by LBEILC** [GaiZhenbiao/ChuanhuChatGPT#826]
### 是否已存在现有反馈与解答？

- [X] 我确认没有已有issue或discussion，且已阅读**常见问题**。

### 是否是一个代理配置相关的疑问？

- [X] 我确认这不是一个代理配置相关的疑问。

### 错误描述

将项目部署到服务器本地后,通过内网穿透的方式远程访问服务端的网站,但在远程访问时,对话气泡的复制按钮失效,并报错
Uncaught TypeError: Cannot read properties of undefined (reading 'writeText')
    at HTMLButtonElement.<anonymous> ((索引):459:14)
    
    索引对应的代码部分:
    copyButton.addEventListener('click', ()=>{
                const textToCopy = rawMessage.innerText;
                navigator.clipboard.writeText(textToCopy).then(()=>{   //报错位置
                    copyButton.innerHTML = copiedIcon;
                    setTimeout(()=>{
                        copyButton.innerHTML = copyIcon;
                    }
                    , 1500);
                }
                ).catch(()=>{
                    console.error("copy failed");
                }
                );
            }

但远程复制代码块的时候是正常的

### 复现操作

将项目部署到服务器本地后,通过内网穿透的方式远程访问服务端的网站,但在远程访问时,对话气泡的复制按钮失效
在服务器端访问网站的话是可以正常复制的

### 错误日志

```shell
终端未报错
```

### 运行环境

- OS: Windows11 22H2
- Server: WinServe
- Gradio version: 3.33.1
- Python version: 3.11.1

**Comment by Keldos-Li** [comment]
这个功能应该和远程或本地部署无关，复制仅是javascript在浏览器层面提供的功能。如果本地能用，不至于远程不能用。

希望您能提供一些更具体的复现步骤，如使用了什么浏览器？远程使用的是什么对话、对话了什么导致复制失败？

以及希望您做一些检查：切换markdown渲染显示是否正确？川虎Chat是否使用了最新版？

另外，需要提醒您，更新新版本的川虎Chat之后，一些老版历史记录的读取可能会有兼容性问题。

**Comment by Kilig947** [comment]
https://github.com/gradio-app/gradio/pull/4350/commits/c5577c67563b3fac8ae0554eeb59ff3d838b0440

https://github.com/gradio-app/gradio/issues/4324

这个问题导致的，当部署在内网，http访问时点击复制按钮，会报错

**Comment by Keldos-Li** [comment]
> https://github.com/gradio-app/gradio/issues/4324
> 
> 
> 
> 这个问题导致的，当部署在内网，http访问时点击复制按钮，会报错

谢谢！

**Comment by Kilig947** [comment]
> 
@Keldos-Li @LBEILC 
已解决，提交pr啦～
https://github.com/GaiZhenbiao/ChuanhuChatGPT/pull/827

**Comment by LBEILC** [comment]
> > 
> 
> @Keldos-Li @LBEILC 已解决，提交pr啦～ #827

辛苦了
