### ISSUE TITLE
[功能请求]: 关于川虎助理能否增加支持gpt-3.5-turbo-16k

### ISSUE THREAD

**Issue by LaoJiuYes** [GaiZhenbiao/ChuanhuChatGPT#828]
### 相关问题

关于川虎助理PRO能否增加支持gpt-3.5-turbo-16k

### 可能的解决办法

川虎助理PRO使用gpt-3.5-turbo字数总是超出限制，而gpt-3.5-turbo-16k刚好就能解决这个问题。

### 帮助开发

- [ ] 我愿意协助开发！

**Comment by GaiZhenbiao** [comment]
在 config 的 "default_chuanhu_assistant_model" 字段中填写 gpt-3.5-turbo-16k 即可
