### ISSUE TITLE
是否考虑支持 vercel 一键部署呢？

### ISSUE THREAD

**Issue by xdtxAM** [GaiZhenbiao/ChuanhuChatGPT#83]
是否考虑支持 vercel 一键部署呢？
没有服务器，而且必须是外面的服务器。参考：https://github.com/ddiu8081/chatgpt-demo 可以一键部署到vercel上面。

**Comment by GaiZhenbiao** [comment]
为什么不用Hugging Face呢

**Comment by liujuntao123** [comment]
我在hugging face上填写key，报错了。但是使用vercel部署，key就不报错，不知道为啥
