### ISSUE TITLE
请问能否布置在vultr的服务器上呢，需要操作什么嘛

### ISSUE THREAD

**Issue by hebinglin1313** [GaiZhenbiao/ChuanhuChatGPT#84]
请问能否布置在vultr的服务器上呢，为了翻墙弄了一个vultr的服务器，想着能不能利用上，直接把IP地址放进去没用，是需要在服务器上操作什么嘛，服务器系统是CentOS SELinux 7 x64

**Comment by GaiZhenbiao** [comment]
参见Readme的“部署相关”部分。这个issue先关闭了。
