### ISSUE TITLE
Docker-助手p

### ISSUE THREAD

**Issue by guoguodada12321** [GaiZhenbiao/ChuanhuChatGPT#841]
### 是否已存在现有反馈与解答？

- [X] 我确认没有已有issue或discussion，且已阅读**常见问题**。

### 是否是一个代理配置相关的疑问？

- [X] 我确认这不是一个代理配置相关的疑问。

### 错误描述

Error
☹️发生了错误：: 1 validation error for SerpAPIWrapper root Could not import serpapi python package. Please install it with pip install google-search-results. (type=value_error)

### 复现操作

~# pip install google-search-results
Requirement already satisfied: google-search-results in /usr/local/lib/python3.7/dist-packages (2.4.2)
Requirement already satisfied: requests in /usr/lib/python3/dist-packages (from google-search-results) (2.21.0)
WARNING: Running pip as the 'root' user can result in broken permissions and conflicting behaviour with the system package manager. It is recommended to use a virtual environment instead: https://pip.pypa.io/warnings/venv

### 运行环境

debian

### 补充说明

1

**Comment by Keldos-Li** [comment]
你是在Linux系统中使用sudo pip install了吗……那确实会产生调用问题。不要用sudo……

**Comment by Keldos-Li** [comment]
如果你仍有疑问，可以继续回复，先关闭了……

**Comment by 503611908** [comment]
请问是该怎么操作呢？我在ssh里执行了pip install google-search-results，但是还是会有相同的问题
