### ISSUE TITLE
[其他]: 长传了文档后，一提问，马上就出错。后台一直显示的是构建索引失败。上传百十个字的文档也是这样。

### ISSUE THREAD

**Issue by ddbj66** [GaiZhenbiao/ChuanhuChatGPT#842]
### 是否已存在现有反馈与解答？

- [X] 我确认没有已有issue或discussion，且已阅读**常见问题**。

### 错误描述

长传了文档后，一提问，马上就出错。后台一直显示的是构建索引失败。上传百十个字的文档也是这样。

### 复现操作

启动网页
填入密匙成功
上传文档成功
开始提问，会出错

### 错误日志

```shell
2023-07-14 13:56:44,987 [ERROR] [index_func.py:139] 索引构建失败！cannot access local variable 'texts' where it is not associated with a value
```

### 运行环境

- OS: 
- 谷歌浏览器

**Comment by GaiZhenbiao** [comment]
这是我们的一个 bug，现在已经修复了。请更新到最新版代码，应该就没这个问题了。如果仍然出错，请检查 langchain 的版本是否与 requirements.txt 中的一致。
