### ISSUE TITLE
[Bug]: “message”: “The model: gpt-4 does not exist”

### ISSUE THREAD

**Issue by alwang35** [GaiZhenbiao/ChuanhuChatGPT#843]
### 这个bug是否已存在现有issue了？

- [X] 我确认没有已有issue，且已阅读**常见问题**。

### 错误表现

安装方式：通过Git拉取，以Windows.bat安装
已完成更新
启动正常
API正常，上网环境正常，openclash设置了专属chatGP与OpenAi的规则
在选择模型之后，不论选择GPT那个模型
都会出现以下错误：
☹️发生了错误：{ “error”: { “message”: “The model: gpt-4 does not exist”, “type”: “invalid_request_error”, “param”: null, “code”: “model_not_found” }}

### 复现操作

1.正常完成部署
2.选择chatGPT模型
3.无法运作，出现☹️发生了错误：{ “error”: { “message”: “The model: gpt-4 does not exist”, “type”: “invalid_request_error”, “param”: null, “code”: “model_not_found” }}

### 错误日志

```shell
☹️发生了错误：{ “error”: { “message”: “The model: gpt-4 does not exist”, “type”: “invalid_request_error”, “param”: null, “code”: “model_not_found” }}
```

### 运行环境

VSCode版本: 1.80.1 (user setup)
Chromium: 108.0.5359.215
Node.js: 16.17.1
V8: 10.8.168.25-electron.0
OS: Windows_NT x64 10.0.23493
Python版本：3.11.4

### 帮助解决

- [ ] 我愿意协助解决！

**Comment by Keldos-Li** [comment]
不论选择 ChatGPT 的哪个模型（包括3.5-turbo），都报错“The model: **gpt-4** does not exist”吗？太奇怪了吧。

如果选择了gpt4相关模型报这个错，那是因为你没有gpt-4 API的使用权限。

**Comment by Keldos-Li** [comment]
请看openai的这篇文章：
- [How can I access GPT-4?](https://help.openai.com/en/articles/7102672-how-can-i-access-gpt-4)
<img width="701" alt="image" src="https://github.com/GaiZhenbiao/ChuanhuChatGPT/assets/23137268/fba89991-d06c-47a9-8ae8-7f6d001c4b74">

**Comment by alwang35** [comment]
谢谢大佬的回复。
我刚才看完这个回头就去用GPT3.5TURBO消耗了1095token
请问是这样就会自动开通GPT4的权限了吗？
还是我需要另外再申请？
谢谢大佬耐心回复
小白感激不尽

**Comment by MZhao-ouo** [comment]
应该需要Pay as you go成功支付至少一次，才会开通gpt-4
