### ISSUE TITLE
如何隐藏 Chatbot 对话框左上角的模型 Label？

### ISSUE THREAD

**Issue by nguyenquocduongqnu** [GaiZhenbiao/ChuanhuChatGPT#844]
### 相关问题

如何像这样隐藏当前的 gpt 模型显示。 我想隐藏它，但还没有找到解决方案。
![image](https://github.com/GaiZhenbiao/ChuanhuChatGPT/assets/63329565/30d69e26-8b04-4cef-a032-a142c9ae73cc)

### 可能的解决办法

我想隐藏它，但还没有找到解决方案。 你能帮助我吗。

### 帮助开发

- [X] 我愿意协助开发！

**Comment by MZhao-ouo** [comment]
在`ChuanhuChatbot.py`中给chatbot添加参数`show_label=False`
![image](https://github.com/GaiZhenbiao/ChuanhuChatGPT/assets/70903329/ac8254b9-ee72-4444-94b9-4c032e64133d)
