### ISSUE TITLE
What is sensitive_id?

### ISSUE THREAD

**Issue by cone387** [GaiZhenbiao/ChuanhuChatGPT#849]
### 相关问题

what is sensitive_id? where to find it

### 可能的解决办法

![image](https://github.com/GaiZhenbiao/ChuanhuChatGPT/assets/20832275/a484d71d-7da5-4e20-a097-31313fe6fdbd)

### 帮助开发

- [ ] 我愿意协助开发！

**Comment by Keldos-Li** [comment]
Hi, you can check this out here: [使用教程#额度显示](https://github.com/GaiZhenbiao/ChuanhuChatGPT/wiki/使用教程#额度显示)
