### ISSUE TITLE
Something went wrong Expecting value: line 1 column 1 (char 0)

### ISSUE THREAD

**Issue by 123tietuo** [GaiZhenbiao/ChuanhuChatGPT#85]
Something went wrong
Expecting value: line 1 column 1 (char 0)
![image](https://user-images.githubusercontent.com/99629950/223738388-3bfb9d4f-d90c-49b2-89b3-566a4529da57.png)
不知道什么原因 终端没有报错 f12没有报错

**Comment by GaiZhenbiao** [comment]
看Readme。不能开全局代理。

**Comment by 123tietuo** [comment]
我没有开启全局代理 我看b站评论区说要配置规则&nbsp; 到这卡住了




------------------&nbsp;原始邮件&nbsp;------------------
发件人: "Chuan ***@***.***&gt;; 
发送时间: 2023年3月8日(星期三) 晚上10:26
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [GaiZhenbiao/ChuanhuChatGPT] Something went wrong Expecting value: line 1 column 1 (char 0) (Issue #85)





 
看Readme。不能开全局代理。
