### ISSUE TITLE
[功能请求]: 能否加入claude

### ISSUE THREAD

**Issue by Diaoxiaozhang** [GaiZhenbiao/ChuanhuChatGPT#851]
### 可能的解决办法

在github上发现KoushikNavuluri/Claude-API这个非官方claude api，是否可以利用这个api给这个项目加入claude

### 帮助开发

- [x] 我愿意协助开发！

**Comment by Keldos-Li** [comment]
Resolved via d98791824586846e9871d4630b572a5bc10c9488
