### ISSUE TITLE
[本地部署]:发生了错误：: No module named ‘transformers_modules.models/chatglm2-6b-int4’

### ISSUE THREAD

**Issue by Myra009** [GaiZhenbiao/ChuanhuChatGPT#859]
### 是否已存在现有反馈与解答？

- [X] 我确认没有已有issue或discussion，且已阅读**常见问题**。

### 是否是一个代理配置相关的疑问？

- [X] 我确认这不是一个代理配置相关的疑问。

### 错误描述

全部都按照文档更新过了，模型是点击选项里，让他自动下载的，
下载完后，哪怕是重启了，还是出现
发生了错误：: No module named ‘transformers_modules.models/chatglm2-6b-int4’

### 复现操作

下载了模型

### 运行环境

```markdown
- OS: 
- Browser: 
- Gradio version: 
- Python version:
```

**Comment by GaiZhenbiao** [comment]
你安装`requirements_advanced.txt`了吗？为了运行本地模型，需要安装这里面的额外依赖

**Comment by Myra009** [comment]
> 你安装`requirements_advanced.txt`了吗？为了运行本地模型，需要安装这里面的额外依赖。安装命令是：
> 
> ```
> pip install -r requirements_advanced.txt
> ```

是的，这个也安装了，也更新过最新版

**Comment by Keldos-Li** [comment]
应该已经解决了（许久之前）？
