### ISSUE TITLE
关于gradio重新安装强制重启后再次报错的问题

### ISSUE THREAD

**Issue by Alexzspace** [GaiZhenbiao/ChuanhuChatGPT#86]
`/usr/local/lib/python3.8/dist-packages/gradio/deprecation.py:40: UserWarning: The 'type' parameter has been deprecated. Use the Number component instead.
  warnings.warn(value)
Traceback (most recent call last):
  File "ChuanhuChatbot.py", line 278, in <module>
    history = gr.State([])
AttributeError: module 'gradio' has no attribute 'State'`

依然报错，python3.8和3.9都试过了，不知道如何解决~~

**Comment by GaiZhenbiao** [comment]
查看一下gradio的版本，是多少？
（说实话这种问题更适合在gradio的repo提）

**Comment by GaiZhenbiao** [comment]
请安装最新版本的gradio。如果仍然报错，建议换一个pip源，比如清华源。
