### ISSUE TITLE
如何在聊天机器人回复中添加喜欢和不喜欢按钮？

### ISSUE THREAD

**Issue by nguyenquocduongqnu** [GaiZhenbiao/ChuanhuChatGPT#861]
### 相关问题

我想在聊天机器人的回复内容中自定义添加喜欢和不喜欢按钮，如图所示。 你能给我解决方案吗？ 谢谢

![Untitled](https://github.com/GaiZhenbiao/ChuanhuChatGPT/assets/63329565/d2951913-006f-434d-aae4-8c9f6a14768a)

### 可能的解决办法

我想在聊天机器人的回复内容中自定义添加喜欢和不喜欢按钮，如图所示。 你能给我解决方案吗？ 谢谢

![Untitled](https://github.com/GaiZhenbiao/ChuanhuChatGPT/assets/63329565/d2951913-006f-434d-aae4-8c9f6a14768a)

### 帮助开发

- [X] 我愿意协助开发！

**Comment by Keldos-Li** [comment]
I'm glad to see that you used our program as prototype (and even opened the same issue in gradio-app/gradio#5250...) 

In fact, this is feasible to some extent, for example, we have like and dislike buttons for the XMChat model. If you need to add it to the conversation message elements, you just need to write a little more JavaScript.

The question is, what do you want to do with the back end of the click event? We haven't import FastAPI yet, and of course, it's possible to use js to write the whole event handling. 

~~Maybe we should also consider adding extension functions..~~

**Comment by nguyenquocduongqnu** [comment]
> 

We want to create a feature to rate feedback.

We use mongo db to statistic like or dislike from user feedback. I want to display these 2 buttons in the response from chatbot, can you suggest me the direction. Thank you

**Comment by Keldos-Li** [comment]
OK, I will explain this in short:

1. Use gradio to add like and dislike buttons anywhere you like, and bind functions to them. If you want, set visible=False.
2. Use javascript (with HTML and CSS) to create custom like and dislike buttons, and use mutation observer to add them to messages when popped.
3. Add js functions to your custom buttons, and bind click event with the click events of gradio buttons.
4. Done! You can make everything prettier now.

The direction is simple, right?

I'm really thinking about extention methods now...

**Comment by nguyenquocduongqnu** [comment]
> OK, I will explain this in short:
> 
> 1. Use gradio to add like and dislike buttons anywhere you like, and bind functions to them. If you want, set visible=False.
> 2. Use javascript (with HTML and CSS) to create custom like and dislike buttons, and use mutation observer to add them to messages when popped.
> 3. Add js functions to your custom buttons, and bind click event with the click events of gradio buttons.
> 4. Done! You can make everything prettier now.
> 
> The direction is simple, right?
> 
> I'm really thinking about extention methods now...

Thank you very much. I will try.

**Comment by Keldos-Li** [comment]
The outcome is actually like this：

<img width="542" alt="image" src="https://github.com/GaiZhenbiao/ChuanhuChatGPT/assets/23137268/2ae84ddd-4942-4786-8cb5-ae01a77c0cd7">

I will close this issue for now.
