### ISSUE TITLE
ModuleNotFoundError: No module named 'lmflow'

### ISSUE THREAD

**Issue by MSZ-MGS** [GaiZhenbiao/ChuanhuChatGPT#862]
### 是否已存在现有反馈与解答？

- [X] 我确认没有已有issue或discussion，且已阅读**常见问题**。

### 错误描述

I created new conda environment and install the requirements and advance requirements.

When I run the app and select LLama-2-hf + Lora

I receive error:
ModuleNotFoundError: No module named 'lmflow'

I tried to install it but didn't work.

### 复现操作

Install

Select LLama-2-hf

Prompt

### 错误日志

```shell
File "G:\Users\mazen\OneDrive\Desktop\AI\ChuanhuChatGPT\modules\models\models.py", line 312, in __init__
    from lmflow.datasets.dataset import Dataset
ModuleNotFoundError: No module named 'lmflow'
```

### 运行环境

- OS: Windows 11
- Browser: Chrome & Edge
- Gradio version: 3.36.1
- Python version: 3.11.4

**Comment by GaiZhenbiao** [comment]
你应该安装额外的依赖`requirements_advanced.txt`

**Comment by MSZ-MGS** [comment]
Thanks for quick reply:
![image](https://github.com/GaiZhenbiao/ChuanhuChatGPT/assets/65172063/9751e047-2cc2-48d8-ae65-31f72e00fda3)

**Comment by GaiZhenbiao** [comment]
It's not recommended to use Windows, many ML libraries doesn't work on Windows. Try use WSL.
