### ISSUE TITLE
docker下部署设置密码在哪里？

### ISSUE THREAD

**Issue by dadaoerv** [GaiZhenbiao/ChuanhuChatGPT#88]
if dockerflag:
    if authflag:
        demo.queue().launch(server_name="0.0.0.0", server_port=7860,auth=(username, password))
    else:
        demo.queue().launch(server_name="0.0.0.0", server_port=7860, share=False)
#if not running in Docker
else:
    demo.queue().launch(share=False) # 改为 share=True 可以创建公开分享链接
    #demo.queue().launch(server_name="0.0.0.0", server_port=7860, share=False) # 可自定义端口
    #demo.queue().launch(server_name="0.0.0.0", server_port=7860,auth=("在这里填写用户名", "在这里填写密码")) # 可设置用户名与密码

请问如果是docker下，向加入用户名密码访问。
1. 修改  if authflag:
        demo.queue().launch(server_name="0.0.0.0", server_port=7860,auth=(username, password))
这里的，重启后无效。
2. 修改  #demo.queue().launch(server_name="0.0.0.0", server_port=7860,auth=("在这里填写用户名", "在这里填写密码")) # 可设置用户名与密码，重启后也没有生效。其他地方的修改都生效了。
请教大佬

**Comment by dadaoerv** [comment]
已经清除浏览器换成，改去掉#的也去掉了。

**Comment by Keldos-Li** [comment]
见#89
