### ISSUE TITLE
[Bug]: "if filename.endswith(".md"):" in utils.py, AttributeError: 'NoneType' object has no attribute 'endswith'

### ISSUE THREAD

**Issue by JohnZ03** [GaiZhenbiao/ChuanhuChatGPT#883]
### 这个bug是否已存在现有issue了？

- [X] 我确认没有已有issue，且已阅读**常见问题**。

### 错误表现

Launched as a localhost. After each prompt, AttributeError is raised.

# Traceback
```
File "C:\Users\*****\Documents\git\ChuanhuChatGPT\modules\models\base_model.py", line 512, in predict
    self.auto_save(chatbot)
  File "C:\Users\*****\Documents\git\ChuanhuChatGPT\modules\models\base_model.py", line 691, in auto_save
    save_file(self.history_file_path, self.system_prompt,
  File "C:\Users\*****\Documents\git\ChuanhuChatGPT\modules\utils.py", line 338, in save_file
    if filename.endswith(".md"):
       ^^^^^^^^^^^^^^^^^
AttributeError: 'NoneType' object has no attribute 'endswith'
```

The function `auto_save` under `base_model.py` is first being called, which triggers `save_file` in `utils.py`.
However in this case the `filename` object passed to `save_file` is set to `None`.

# Suspected causing issue
`filename` was passed from `self.history_file_path` under the `BaseLLMModel` class.
Where `self.history_file_path` is initialized as `self.history_file_path = get_first_history_name(user)`.
Looking at the `get_first_history_name` function,
```
def get_first_history_name(user_name=""):
    history_names = get_history_names(user_name)
    return history_names[0] if history_names else None
```
the returned value is None if `history_names` is not set.
This suggests that the None object used by the `save_file` function is caused by a false initialization of `self.history_file_path`.

# A quick proof
After changing the line
```
self.history_file_path = get_first_history_name(user)
```

to 

```
self.history_file_path = "test.md"
```

The error is gone. However this might damage the app logic so cannot be taken as a fix.

### 复现操作

1. Configured following the steps in the documentation.
2. First time launch.
3. Error triggers for every user prompt.

### 错误日志

```shell
File "C:\Users\*****\Documents\git\ChuanhuChatGPT\modules\models\base_model.py", line 512, in predict
    self.auto_save(chatbot)
  File "C:\Users\*****\Documents\git\ChuanhuChatGPT\modules\models\base_model.py", line 691, in auto_save
    save_file(self.history_file_path, self.system_prompt,
  File "C:\Users\*****\Documents\git\ChuanhuChatGPT\modules\utils.py", line 338, in save_file
    if filename.endswith(".md"):
       ^^^^^^^^^^^^^^^^^
AttributeError: 'NoneType' object has no attribute 'endswith'
```

### 运行环境

- OS: Windows 11 Pro English
- Browser: Chrome
- Gradio version: 3.43.2
- Python version: 3.11.4

### 帮助解决

- [X] 我愿意协助解决！

**Comment by XiaolongYang-HZAU** [comment]
遇到了相同的问题

**Comment by GaiZhenbiao** [comment]
I'm confident to say that this issue is resolved now. Please pull the latest version. Let me know if there's still bugs sitting around.

**Comment by GaiZhenbiao** [comment]
Now this bug is finally resolved... Sorry for the inconvenience!

**Comment by alexxchen** [comment]
还是会出现这个错误，我这边hide_history_when_not_logged_in=true 就会出现

**Comment by ParkerLyu01** [comment]
> 还是会出现这个错误，我这边hide_history_when_not_logged_in=true ，users : [] 就会出现

我也是

**Comment by GaiZhenbiao** [comment]
> > 还是会出现这个错误，我这边hide_history_when_not_logged_in=true ，users : [] 就会出现
> 
> 我也是

我等会儿再调查下

**Comment by GaiZhenbiao** [comment]
@ParkerLyu01 @alexxchen 现在修复了
