### ISSUE TITLE
[Bug]: 在使用chatglm模型在问答的时候，产生回答错误

### ISSUE THREAD

**Issue by xxWeiDG** [GaiZhenbiao/ChuanhuChatGPT#892]
### 这个bug是否已存在现有issue了？

- [X] 我确认没有已有issue，且已阅读**常见问题**。

### 错误表现

![Uploading QQ图片20230919112652.png…]()
![Uploading QQ图片20230919112640.png…]()

### 复现操作

正常使用，但是进行对话时产生错误

### 运行环境

- OS: linux
- Browser: Chrome 
- Gradio version: 3.44.3
- Python version: 3.10.8

### 帮助解决

- [ ] 我愿意协助解决！

**Comment by GaiZhenbiao** [comment]
图片没传上来👀另外请贴出错误日志以方便排查原因

**Comment by xxWeiDG** [comment]
> 图片没传上来👀另外请贴出错误日志以方便排查原因

![QQ图片20230919112640](https://github.com/GaiZhenbiao/ChuanhuChatGPT/assets/140797957/6d7b800e-fc0f-45cc-8101-5475c4d3a959)
![QQ图片20230919112652](https://github.com/GaiZhenbiao/ChuanhuChatGPT/assets/140797957/be57e8d7-526e-4ecc-a636-63d2eb9fe5f9)

**Comment by GaiZhenbiao** [comment]
<img width="719" alt="image" src="https://github.com/GaiZhenbiao/ChuanhuChatGPT/assets/51039745/7d7ab497-92a3-426b-88e1-5cc4abc384a0">
<img width="727" alt="image" src="https://github.com/GaiZhenbiao/ChuanhuChatGPT/assets/51039745/18088e60-613c-4d66-8f41-8215f1fb4900">
我测试了一下好像没问题。请检查依赖版本是否正确，主要是`transformers`要使用最新版，`protobuf`应该使用`3.20.x`的版本。
