### ISSUE TITLE
[Bug]: 对话的历史记录没有隔离？不同电脑都能够看到相同的会话记录！！！

### ISSUE THREAD

**Issue by bigbigtooth** [GaiZhenbiao/ChuanhuChatGPT#893]
### 这个bug是否已存在现有issue了？

- [X] 我确认没有已有issue，且已阅读**常见问题**。

### 错误表现

我在电脑A上与川虎对话，同事在电脑B上也能够看到，会话历史记录没有隔离，请问是我们部署配置问题导致吗？还是系统有bug？

### 复现操作

部署在本地服务器后
A电脑通过局域网访问该服务器与AI正常对话
B电脑通过局域网访问该服务器，可以看到A电脑的所有对话。

### 错误日志

```shell
没有报错
```

### 运行环境

- OS: windows
- Browser: Chrome
- Gradio version: 
- Python version: 3.10

### 帮助解决

- [ ] 我愿意协助解决！

**Comment by Keldos-Li** [comment]
请参阅：
- [设置用户登录密码](https://github.com/GaiZhenbiao/ChuanhuChatGPT/wiki/%E4%BD%BF%E7%94%A8%E6%95%99%E7%A8%8B#%E8%AE%BE%E7%BD%AE%E7%94%A8%E6%88%B7%E7%99%BB%E5%BD%95%E5%AF%86%E7%A0%81)
- [未登录时隐藏历史对话记录](https://github.com/GaiZhenbiao/ChuanhuChatGPT/wiki/%E4%BD%BF%E7%94%A8%E6%95%99%E7%A8%8B#%E6%9C%AA%E7%99%BB%E5%BD%95%E6%97%B6%E9%9A%90%E8%97%8F%E5%8E%86%E5%8F%B2%E5%AF%B9%E8%AF%9D%E8%AE%B0%E5%BD%95)

**Comment by GaiZhenbiao** [comment]
1. 登录之后，不同用户的对话历史相互隔离
2. 如果不想登录，可以在config中将`hide_history_when_not_logged_in`设置为true

**Comment by bigbigtooth** [comment]
果然解决了。
看来缺一个比较详细一点的config文件说明文档，我都没留意这个参数。

**Comment by Keldos-Li** [comment]
> 果然解决了。
> 
> 看来缺一个比较详细一点的config文件说明文档，我都没留意这个参数。

还不详细吗？example里也给出了wiki链接，wiki里整张表列了所有config参数，也都有链接指向具体的说明，你想让我们详细到哪里去呢？
