### ISSUE TITLE
请教一下哥咋弄到服务器里

### ISSUE THREAD

**Issue by wvwb** [GaiZhenbiao/ChuanhuChatGPT#9]
如题，小白不会弄，闲的时候看到了如果可以的话，教一下，视频没看明白，谢了

**Comment by GaiZhenbiao** [comment]
如果部署到服务器，将程序最后一句改成demo.launch(server_name="0.0.0.0", server_port=99999)。其中99999是端口号，应该是1000-65535任意可用端口，请自行更改为实际端口号。

**Comment by wvwb** [comment]
谢谢哥
