### ISSUE TITLE
第一次运行服务后，以后再启动就会报错。

### ISSUE THREAD

**Issue by peiyun1982** [GaiZhenbiao/ChuanhuChatGPT#90]
第一次在服务器端运行服务是正常的。
接下来修改ChuanhuChatbot.py文件，kill掉进程。
再次启动之后就会出现下图的错误。比如我这个错误，第一次我用的是8080端口，但现在py文件已经修改成别的了，可还是提示我8080端口被占用。
我还尝试了在新建文件夹下复制工程运行，重新启动再次运行。都是这样的。
可在任何位置都没有8080的字样了呀。
（上面的报错并不影响网站正常使用，只是在服务器端启动时报错）
![微信截图_20230309114904](https://user-images.githubusercontent.com/16250376/223915610-bdcf6680-9b6a-4bc1-af9d-4a988cc48bf0.png)

**Comment by GaiZhenbiao** [comment]
这应该是 gradio 的bug。可以通过下面的命令解决，但彻底解决需要 gradio 修复：
```
python3
import gradio
gradio.close_all()
exit()
```

**Comment by peiyun1982** [comment]
> 这应该是 gradio 的bug。可以通过下面的命令解决，但彻底解决需要 gradio 修复：
> 
> ```
> python3
> import gradio
> gradio.close_all()
> exit()
> ```

在什么时候运行这段代码呢？进入项目文件夹，运行`python3 ChuanhuChatbot.py`之前？

**Comment by GaiZhenbiao** [comment]
是的
