### ISSUE TITLE
[Bug]: 在最新的 gradio 3.45.2下面聊天界面显示错误

### ISSUE THREAD

**Issue by stockcoder** [GaiZhenbiao/ChuanhuChatGPT#905]
### 这个bug是否已存在现有issue了？

- [X] 我确认没有已有issue，且已阅读**常见问题**。

### 错误表现

 聊天界面的回复显示不出来

### 复现操作

升级 gradio 版本到最新的 3.45.2

### 运行环境

- OS: 
- Browser: 
- Gradio version: 
- Python version: 

### 帮助解决

- [ ] 我愿意协助解决！

**Comment by Keldos-Li** [comment]
您好，这是gradio 3.45.2 的问题。由于gradio每次更新都会产生大量变动，都需要我们重新适配，因此请不要随意升级gradio版本，而应当使用我们在`requirements.txt`中指定的版本。

如果你在其他项目需要不同版本的gradio，请使用Python或conda的虚拟环境。

**Comment by stockcoder** [comment]
> 您好，这有可能gradio 3.45.2 的问题。由于gradio每次更新都会产生大量变动，都需要我们重新适配，因此请不要随意升级gradio版本，而应当使用我们在`requirements.txt`中指定的版本。
> 
> 如果你在其他项目需要不同版本的gradio，请使用Python或conda的虚拟环境。



> 您好，这有可能gradio 3.45.2 的问题。由于gradio每次更新都会产生大量变动，都需要我们重新适配，因此请不要随意升级gradio版本，而应当使用我们在`requirements.txt`中指定的版本。
> 
> 如果你在其他项目需要不同版本的gradio，请使用Python或conda的虚拟环境。

您好，请问下什么时候可以适配到 3.45 以上呢，有个新的功能需要用到这个版本以上

**Comment by Keldos-Li** [comment]
方便问问具体是什么功能吗？ 刚才看了gradio的更新日志又看了实际的源码，感觉有点棘手

**Comment by Keldos-Li** [comment]
现已经更新适配到 gradio 4.26 ~
