### ISSUE TITLE
[功能请求]: 在開啟新對話時, 希望可以保留"System Prompt"的內容不要消除掉

### ISSUE THREAD

**Issue by tomkuo1124** [GaiZhenbiao/ChuanhuChatGPT#907]
### 相关问题

To 川虎的developer大神, 
目前的川虎版本會在我們開啟新對話時順便消除掉System Prompt的內容(請參考下圖紅框處), 這樣對於我們使用者想要測試System Prompt會有點點不方便, 請問大神, 有沒有哪邊可以設定"開啟新對話時可以保留System Prompt的內容"?
謝謝您的閱讀, 感恩。 ☺

![image](https://github.com/GaiZhenbiao/ChuanhuChatGPT/assets/137477635/dc374d40-7386-45f1-ae03-79b733ce447c)

### 可能的解决办法

有沒有哪邊可以設定"開啟新對話時可以保留System Prompt的內容"?

### 帮助开发

- [ ] 我愿意协助开发！

**Comment by GaiZhenbiao** [comment]
@MZhao-ouo 你怎么说，之前这个行为是你做的hhh

**Comment by tomkuo1124** [comment]
wow, 是製作川虎app的大神! 感謝您們的付出與分享這麼棒的產品讓我們體驗AI的學習 (我只用川虎, 沒有在用其他有的沒的ChatGPT聊天app)

**Comment by Keldos-Li** [comment]
<img width="314" alt="image" src="https://github.com/GaiZhenbiao/ChuanhuChatGPT/assets/23137268/2ced9e7b-089c-481d-8b85-411a19771f1b">

不过说起来，像openai那样加一个开关也问题不大……？

**Comment by MZhao-ouo** [comment]
开关加上啦
![image](https://github.com/GaiZhenbiao/ChuanhuChatGPT/assets/70903329/b6f60f29-3e00-47a7-a733-339d30cdea41)

**Comment by tomkuo1124** [comment]
感謝大神們!! ^^
