### ISSUE TITLE
[功能请求]: 请求增加api服务商功能

### ISSUE THREAD

**Issue by GeekHank** [GaiZhenbiao/ChuanhuChatGPT#909]
### 相关问题

现在有很多三方服务商提供私密api连接，希望可以增加带服务地址的私密api使用功能，详细可以参照gpt nextweb

### 可能的解决办法

增加带服务地址的私密api使用功能，详细可以参照gpt nextweb

### 帮助开发

- [ ] 我愿意协助开发！

**Comment by MZhao-ouo** [comment]
有的，可以在`config.json`文件里面改。
![image](https://github.com/GaiZhenbiao/ChuanhuChatGPT/assets/70903329/1ebc9643-f7c1-48cc-a6a9-7450d2d35bd5)

**Comment by GeekHank** [comment]
十分感谢🙏



Sent&nbsp;from&nbsp;my&nbsp;iPhone


------------------ 原始邮件 ------------------
From: MZhao ***@***.***&gt;
发送时间: 10/07/2023, 15:55
To: GaiZhenbiao/ChuanhuChatGPT ***@***.***&gt;
抄送: GeekHank ***@***.***&gt;, Author ***@***.***&gt;
Subject: Re: [GaiZhenbiao/ChuanhuChatGPT] [功能请求]: 请求增加api服务商功能 (Issue #909)
