### ISSUE TITLE
[功能请求]: 

### ISSUE THREAD

**Issue by zhulibing** [GaiZhenbiao/ChuanhuChatGPT#911]
### 相关问题

怎么把chatbot默认的output 改为英文显示

### 可能的解决办法

英文显示output

### 帮助开发

- [ ] 我愿意协助开发！

**Comment by MZhao-ouo** [comment]
可以在`config.json`里面设置语言
![image](https://github.com/GaiZhenbiao/ChuanhuChatGPT/assets/70903329/a096e1df-1e4c-46b2-bcce-92332ea9bfc0)

**Comment by Keldos-Li** [comment]
他的意思应该是模型输出的语言，要输出英语，建议使用英文提问；或者输入时/system prompt里附带一句请使用英文回复。
