### ISSUE TITLE
是否支持llama2系列及其衍生模型？

### ISSUE THREAD

**Issue by xxm1668** [GaiZhenbiao/ChuanhuChatGPT#915]
### 是否已存在现有反馈与解答？

- [X] 我确认没有已有issue或discussion，且已阅读**常见问题**。

### 错误描述

是否支持llama2系列及其衍生模型？

### 复现操作

是否支持llama2系列及其衍生模型？

### 错误日志

```shell
是否支持llama2系列及其衍生模型？
```

### 运行环境

- OS: 
- Browser: 
- Gradio version: 
- Python version: 
(或您的其他运行环境信息)

### 补充说明

是否支持llama2系列及其衍生模型？

**Comment by GaiZhenbiao** [comment]
支持的
