### ISSUE TITLE
[远程部署]: 回复不完整，并且报错: data: [DONE]

### ISSUE THREAD

**Issue by cooffer** [GaiZhenbiao/ChuanhuChatGPT#916]
### 是否已存在现有反馈与解答？

- [X] 我确认没有已有issue或discussion，且已阅读**常见问题**。

### 是否是一个代理配置相关的疑问？

- [X] 我确认这不是一个代理配置相关的疑问。

### 错误描述

我在更新到最新版本后，使用之前的对话进行提问，回复不完整，然后就报错，错误信息如下：
Traceback (most recent call last):
  File "/home/ubuntu/ChuanhuChatGPT/modules/models/base_model.py", line 473, in predict
    for chatbot, status_text in iter:
  File "/home/ubuntu/ChuanhuChatGPT/modules/models/base_model.py", line 282, in stream_next_chatbot
    for partial_text in stream_iter:
  File "/home/ubuntu/ChuanhuChatGPT/modules/models/OpenAI.py", line 44, in get_answer_stream_iter
    for i in iter:
  File "/home/ubuntu/ChuanhuChatGPT/modules/models/OpenAI.py", line 221, in _decode_chat_response
    raise Exception(error_msg)
Exception: data: [DONE]

### 复现操作

我之前部署的是老版本的，之后更新到了最新的版本，然后我在使用更新之前的对话进行提问，出现回复不完整的情况；
还有一种情况，在我新建对话后，切换过其他对话，然后再回到新建的这个对话提问，也会出现报错，回复不完整，或者没有回复的情况

### 运行环境

- OS: ubuntu 22.04 LTS
- Gradio version: 3.43.2
- Python version: 3.10.12

**Comment by GaiZhenbiao** [comment]
多久之前的旧版本呢

**Comment by GaiZhenbiao** [comment]
你有在使用第三方API服务吗？

**Comment by cooffer** [comment]
> 多久之前的旧版本呢

我部署的版本应该是916的版本，现在上次更新到926的版本，也出现过相同的问题

**Comment by cooffer** [comment]
> 你有在使用第三方API服务吗？

没有使用第三方的API服务，只使用了OpenAI的API

**Comment by GaiZhenbiao** [comment]
你在用什么模型呢？如果方便的话，可以给我提供一份有问题的历史记录文件（.json）吗？

**Comment by cooffer** [comment]
> 你在用什么模型呢？如果方便的话，可以给我提供一份有问题的历史记录文件（.json）吗？

我使用的是gpt-3.5-turbo-0613这个模型，可以提供有问题的历史文件，但是我刚才找有问题的历史记录文件的时候，发现历史记录文件中的对话记录和网页上面显示的对话记录不一致

**Comment by cooffer** [comment]
> 你在用什么模型呢？如果方便的话，可以给我提供一份有问题的历史记录文件（.json）吗？

我现在找不到有问题的历史记录文件了，因为网页上的对话名和历史记录文件的名字一致，但是内容不同，有问题的对话内容对应的文件内容都不一致

**Comment by GaiZhenbiao** [comment]
奇怪，不应该内容对不上呀。历史文件的内容可能比较多，你可以发一份我来看看。我这边测试是没有任何问题的。

**Comment by cooffer** [comment]
> 奇怪，不应该内容对不上呀。历史文件的内容可能比较多，你可以发一份我来看看。我这边测试是没有任何问题的。

好的，我发现不是内容对不是，是在新对话中，多了其他的对话记录，但是网页上面并没有显示出来
[1697101885396.zip](https://github.com/GaiZhenbiao/ChuanhuChatGPT/files/12879533/1697101885396.zip)

**Comment by cooffer** [comment]
> 能复现问题了，我调查一下

好的，辛苦大佬

**Comment by GaiZhenbiao** [comment]
现在应该修好了，试试最新主线版本吧～

**Comment by cooffer** [comment]
> 现在应该修好了，试试最新主线版本吧～

今天试了下，暂时没出现这个问题了
