### ISSUE TITLE
[Bug]: 英文显示错误

### ISSUE THREAD

**Issue by zhulibing** [GaiZhenbiao/ChuanhuChatGPT#917]
### 这个bug是否已存在现有issue了？

- [X] 我确认没有已有issue，且已阅读**常见问题**。

### 错误表现

attention显示成atten�on ， simulation显示成simula�on。  文件里面都是正确的单词。但是output里面出现这个� 不知道为啥哦。谢谢您。

### 复现操作

正常上传文件，但是output出现�

### 运行环境

- OS: 
- Browser: 
- Gradio version: 
- Python version: 

### 帮助解决

- [X] 我愿意协助解决！

**Comment by Keldos-Li** [comment]
是个比较奇怪的问题，推测是字符编码出错。这个大概和文件的编码格式有关，也许需要文件也统一使用UTF-8编码。如果您还有问题，可以进一步回复。
