### ISSUE TITLE
[功能请求]: 什么时候支持讯飞星火认知大模型3.0？

### ISSUE THREAD

**Issue by ryanbai** [GaiZhenbiao/ChuanhuChatGPT#925]
### 相关问题

获得了[讯飞星火认知大模型](https://xinghuo.xfyun.cn/)3.0的使用权限，发现目前只支持到2.0

### 可能的解决办法

求支持3.0

### 帮助开发

- [ ] 我愿意协助开发！

**Comment by GaiZhenbiao** [comment]
现在支持啦！去试试吧！
