### ISSUE TITLE
请问“一键总结”功能是不是没有办法只用本地大模型进行？报错需要调用api-key

### ISSUE THREAD

**Issue by MOLIZHU2023** [GaiZhenbiao/ChuanhuChatGPT#926]
### 可能的解决办法

使用本地模型进行一键总结

### 帮助开发

- [ ] 我愿意协助开发！

### 补充说明

请问“一键总结”功能是不是没有办法只用本地大模型进行？加载本地千问14B，知识库文件上传和问答功能正常，点击“总结”，报错需要调用api-key

**Comment by Keldos-Li** [comment]
也许请在配置中启用local embedding

**Comment by wayfare11** [comment]
遇到了同样的问题
<img width="886" alt="Snipaste_2024-01-15_14-05-37" src="https://github.com/GaiZhenbiao/ChuanhuChatGPT/assets/81129160/dc2f3065-53c6-47b1-8b90-7dc37cb33fee">

**Comment by Keldos-Li** [comment]
现在一键总结没了）
