### ISSUE TITLE
[功能请求]: 希望添加GPT 4.0-turbo的完整相关支持

### ISSUE THREAD

**Issue by slideslide** [GaiZhenbiao/ChuanhuChatGPT#927]
### 相关问题

GPT 4.0-turbo支持多模态，输入方式得改进一下了。

### 可能的解决办法

在输入框添加图片输入选项

### 帮助开发

- [ ] 我愿意协助开发！

### 补充说明

New GPT-4 Turbo:
We announced GPT-4 Turbo, our most advanced model. It offers a 128K context window and knowledge of world events up to April 2023. 
We’ve reduced pricing for GPT-4 Turbo considerably: input tokens are now priced at $0.01/1K and output tokens at $0.03/1K, making it 3x and 2x cheaper respectively compared to the previous GPT-4 pricing. 
We’ve improved function calling, including the ability to call multiple functions in a single message, to always return valid functions with JSON mode, and improved accuracy on returning the right function parameters.
Model outputs are more deterministic with our new reproducible outputs beta feature.
You can access GPT-4 Turbo by passing gpt-4-1106-preview in the API, with a stable production-ready model release planned later this year.

**GPT-4 Turbo now supports visual inputs in the Chat Completions API**, enabling use cases like caption generation and visual analysis. You can access the vision features by using the gpt-4-vision-preview model. This vision capability will be integrated into the production-ready version of GPT-4 Turbo when it comes out of preview later this year.

**Comment by middle-chunjie** [comment]
并且官方自己已经制作Assistant API了，感觉可以跟进

**Comment by GaiZhenbiao** [comment]
正在做～

**Comment by slideslide** [comment]
> 正在做～

目前vision通过原本文件上传图片会出现两个图片对话气泡，以及是不是不需要3.5 16k了？现在的3.5 turbo默认是16k了。

**Comment by MZhao-ouo** [comment]
![image](https://github.com/GaiZhenbiao/ChuanhuChatGPT/assets/70903329/39b14fda-ac42-4b0f-8b97-b690cda6c355)
11.11才改，现在还在测试版

**Comment by slideslide** [comment]
> ![image](https://user-images.githubusercontent.com/70903329/281783646-39b14fda-ac42-4b0f-8b97-b690cda6c355.png) 11.11才改，现在还在测试版

噢，看漏了hhh

**Comment by Keldos-Li** [comment]
> 目前vision通过原本文件上传图片会出现两个图片对话气泡

应该不会有俩气泡呀？也许应该检查一下是否是正确的gradio版本？

可以使用[该版本](https://github.com/GaiZhenbiao/ChuanhuChatGPT/releases/tag/20231110)测试。
