### ISSUE TITLE
[功能请求]: 1.新增对ChatGLM3-6B的支持  2.同步更新对GPT支持

### ISSUE THREAD

**Issue by rutther** [GaiZhenbiao/ChuanhuChatGPT#929]
### 相关问题

两个主要诉求：
1.接入ChatGLM3-6B  
2.同步更新GPT支持

### 可能的解决办法

1.我认为国内本地模型目前表现最好，最有希望的是GLM系列。是较为值得持续更新的。
2.GPT新版本的支持
这两个事务是否有开发计划？

### 帮助开发

- [ ] 我愿意协助开发！

**Comment by Keldos-Li** [comment]
Resolved via 2c3fb9f62d2a92634cf8408564220a64249b7a3b and other commits...
