### ISSUE TITLE
[Bug]: 切换到星火大模型再切换回openai chatgpt api后报错

### ISSUE THREAD

**Issue by youqie** [GaiZhenbiao/ChuanhuChatGPT#930]
### 这个bug是否已存在现有issue了？

- [X] 我确认没有已有issue，且已阅读**常见问题**。

### 错误表现

切换使用星火大模型后再切换回ChatGPT系列API时报错，报错显示在给OpenAI接口发送API KEY时发送了之前星火大模型的API

### 复现操作

1. 正常本地部署；
2. 默认使用ChatGPT-3.5-Turbo模型；
3. 切换至星火大模型并进行对话；
4. 切换回ChatGPT-3.5-Turbo模型并对话；
5. 右上角显示报错信息。

### 错误日志

```shell
☹️Error: { "error": { "message": "Incorrect API key provided: [[Config中配置的星火大模型API KEY]]. You can find your API key at https://platform.openai.com/account/api-keys.", "type": "invalid_request_error", "param": null, "code": "invalid_api_key" }}
```

### 运行环境

- Server OS: Ubuntu 20.04 LTS x86_64
- Client Browser: Chrome
- Gradio version:  3.43.2
- Python version:  3.8.0

### 帮助解决

- [ ] 我愿意协助解决！

**Comment by GaiZhenbiao** [comment]
我相信这个bug已经被修复了。
