### ISSUE TITLE
[其他]:  huggingface部署，使用3.5报错，☹️Error: 剩余配额不足

### ISSUE THREAD

**Issue by youtehub** [GaiZhenbiao/ChuanhuChatGPT#936]
### 是否已存在现有反馈与解答？

- [X] 我确认没有已有issue或discussion，且已阅读**常见问题**。

### 错误描述

huggingface部署，使用3.5报错，☹️Error: 剩余配额不足
返回错误：☹️Error: 剩余配额不足，实际情况是完全够用。如图所示
访问你们官方的也会返回这个错误
[JohnSmith9982](https://huggingface.co/JohnSmith9982)/[ChuanhuChatGPT](https://huggingface.co/spaces/JohnSmith9982/ChuanhuChatGPT)
![image](https://github.com/GaiZhenbiao/ChuanhuChatGPT/assets/18629921/c2717aee-d165-43d9-b21a-217091db994f)

### 复现操作

输入密匙后，使用gpt3.5都会报这个错误，主要不知道是什么问题，无法使用。
发起会话后，显示回来的内容为空，在huggingface看不到日志
![image](https://github.com/GaiZhenbiao/ChuanhuChatGPT/assets/18629921/ad59589e-8dea-48ed-943f-f9a3e4c740d5)

### 运行环境

使用 huggingface 的免费配置部署的

**Comment by GaiZhenbiao** [comment]
你的免费增金过期了。免费增金只能在一定期限（三个月）内使用，超过这个期限就会过期没法用。

**Comment by youtehub** [comment]
好的，谢谢了
