### ISSUE TITLE
[Bug]: GPT4 Vision 上传非图片文件报错

### ISSUE THREAD

**Issue by LaoJiuYes** [GaiZhenbiao/ChuanhuChatGPT#938]
### 这个bug是否已存在现有issue了？

- [X] 我确认没有已有issue，且已阅读**常见问题**。

### 错误表现

![QQ截图20231111143553](https://github.com/GaiZhenbiao/ChuanhuChatGPT/assets/53503340/a23e66fb-b917-481c-9117-aacf2470578e)

### 复现操作

9月份版本是正常的，但是我更新以后就出现这个问题，我尝试过10.20那个版本同样如此，我排查了反代，关了反代依然如此

### 错误日志

```shell
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/dist-packages/gradio/queueing.py", line 388, in call_prediction
    output = await route_utils.call_process_api(
  File "/usr/local/lib/python3.10/dist-packages/gradio/route_utils.py", line 219, in call_process_api
    output = await app.get_blocks().process_api(
  File "/usr/local/lib/python3.10/dist-packages/gradio/blocks.py", line 1440, in process_api
    data = self.postprocess_data(fn_index, result["prediction"], state)
  File "/usr/local/lib/python3.10/dist-packages/gradio/blocks.py", line 1341, in postprocess_data
    prediction_value = block.postprocess(prediction_value)
  File "/usr/GPT_chuanhu/modules/overwrites.py", line 36, in postprocess
    self._postprocess_chat_messages(message_pair[0], "user"),
  File "/usr/GPT_chuanhu/modules/overwrites.py", line 52, in postprocess_chat_messages
    file_uri = chat_message[0]
IndexError: list index out of range
```

### 运行环境

- OS: Ubuntu 22.04.2 LTS
- Browser: edge 119.0.2151.44
- Gradio version: Version: 3.43.2
- Python version: Python 3.10.12

### 帮助解决

- [ ] 我愿意协助解决！

**Comment by GaiZhenbiao** [comment]
请尝试安装目前本项目支持的gradio版本：
```
pip install gradio==3.43.2
```

**Comment by GaiZhenbiao** [comment]
你在使用哪个模型？

**Comment by GaiZhenbiao** [comment]
应该是你在使用GPT4 Vision，但是上传了非图片的文件，导致的问题。请在使用Vision模型时只上传图片。我之后会在这里加一个限制，不允许选择图片以外的文件。

**Comment by QYlichuyou** [comment]
川虎大哥你好，我有类似的问题，使用docker部署后，能正常使用GPT-4-turbo，但是切换模型为gpt-4-vision-preview后会报错：
Error: { "error": { "message": "The model gpt-4-vision-preview does not exist or you do not have access to it. Learn more: https://help.openai.com/en/articles/7102672-how-can-i-access-gpt-4.", "type": "invalid_request_error", "param": null, "code": "model_not_found" }}
无法正常使用。
后台log也类似：
JSON parsing error, received content: {

JSON parsing error, received content:     "error": {

JSON parsing error, received content:         "message": "The model `gpt-4-vision-preview` does not exist or you do not have access to it. Learn more: https://help.openai.com/en/articles/7102672-how-can-i-access-gpt-4.",

JSON parsing error, received content:         "type": "invalid_request_error",

JSON parsing error, received content:         "param": null,

JSON parsing error, received content:         "code": "model_not_found"

JSON parsing error, received content:     }

JSON parsing error, received content: }

Traceback (most recent call last):

  File "/app/modules/models/base_model.py", line 512, in predict

    for chatbot, status_text in iter:

  File "/app/modules/models/base_model.py", line 291, in stream_next_chatbot

    for partial_text in stream_iter:

  File "/app/modules/models/OpenAIVision.py", line 52, in get_answer_stream_iter

    for i in iter:

  File "/app/modules/models/OpenAIVision.py", line 297, in _decode_chat_response

    raise Exception(error_msg)

Exception: {    "error": {        "message": "The model `gpt-4-vision-preview` does not exist or you do not have access to it. Learn more: https://help.openai.com/en/articles/7102672-how-can-i-access-gpt-4.",        "type": "invalid_request_error",        "param": null,        "code": "model_not_found"    }}

请问如何解决呢，多谢！

> 应该是你在使用GPT4 Vision，但是上传了非图片的文件，导致的问题。请在使用Vision模型时只上传图片。我之后会在这里加一个限制，不允许选择图片以外的文件。

**Comment by GaiZhenbiao** [comment]
这应该只是OpenAI没有给你Vision模型的preview权限

**Comment by GaiZhenbiao** [comment]
我测试没问题。请附上完整的命令行报错？

**Comment by GaiZhenbiao** [comment]
这个是由于一个依赖（Pillow）的新版本的API变化导致的。我更新了代码，使得现在可以与Pillow的最新版本工作。如果你暂时不想更新，可以安装Pillow的旧版本：
```
pip install Pillow==9.5.0
```

**Comment by Keldos-Li** [comment]
🤨
1. better在requirements.txt里要求一下pillow>=xxx
2. 原issue如果是因为下面这个问题，不应该被自动关闭，我重新开一下……？
   > 应该是你在使用GPT4 Vision，但是上传了非图片的文件，导致的问题。请在使用Vision模型时只上传图片。我之后会在这里加一个限制，不允许选择图片以外的文件。

**Comment by GaiZhenbiao** [comment]
已经在 https://github.com/GaiZhenbiao/ChuanhuChatGPT/commit/414815f44ca0741fa6bdbf50fbe44184e8ed5ff0 （最新版）中修复
