### ISSUE TITLE
finish_reason: None

### ISSUE THREAD

**Issue by wz36125** [GaiZhenbiao/ChuanhuChatGPT#94]
不超过几句 就会报这个错误，这是为什么？

**Comment by wz36125** [comment]
> 这不是错误，这是正常的。

@GaiZhenbiao 怎么解决呢？出现这个错误后就不能继续下去了，AI的回答只会回答一个字，然后就没了

**Comment by GaiZhenbiao** [comment]
奇怪，不应该呀。你的网络连接正常吗？

**Comment by wz36125** [comment]
> 奇怪，不应该呀。你的网络连接正常吗？

如何知道是网络的问题呢？

**Comment by GaiZhenbiao** [comment]
终端有输出错误报告吗？

**Comment by wz36125** [comment]
> 终端有输出错误报告吗？

@GaiZhenbiao 请问 `ParseException: Expected end of text, found '$' (at char 0), (line:1, col:1)` 这个问题是我的操作问题吗？还是说？

**Comment by GaiZhenbiao** [comment]
提供一下你问的问题/步骤，我试着复现一下

**Comment by wz36125** [comment]
> 提供一下你问的问题/步骤，我试着复现一下

@GaiZhenbiao 我已经关了，我就跟它聊怎么实现一个功能的代码，然后我说它给出的代码有问题的时候，得一下句话就一定会触发这个问题。它刚打出抱歉的抱，第一个字“抱”时，就报我说的这个错。

**Comment by GaiZhenbiao** [comment]
最新版代码支持无限聊天了，试试？

**Comment by wz36125** [comment]
> 最新版代码支持无限聊天了，试试？

@GaiZhenbiao 好的我试试

**Comment by wz36125** [comment]
@GaiZhenbiao 随着对话的长度，越到后面，还是会触发这个错误 `json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)`  ，但是可以继续对话，之后的对话不再是一个字一个字的慢慢生成，而是整个答案一起出现。我不知道这个算不算的问题

**Comment by GaiZhenbiao** [comment]
一起出现是正常的。应该只有一次对话是一次性出现的，然后又是一个字一个字出现的。如果是终端里打印了这个`json.decoder.JSONDecodeError`这个错误，是正常的。如果在UI里出现了，是不应该的。你能描述更详细一些吗？

**Comment by wz36125** [comment]
> 一起出现是正常的。应该只有一次对话是一次性出现的，然后又是一个字一个字出现的。如果是终端里打印了`json.decoder.JSONDecodeError`这个错误，是正常的。如果在UI里出现了，是不应该的。你能描述更详细一些吗？
就是在那四个按钮的下面，会出现一次我提这个issue的错误，但是可以重新输入问题继续对话

**Comment by GaiZhenbiao** [comment]
`finish_reason: None` 和 `finish_reason: Stop` 不算是错误。除非你看到了 `status: ERROR`

**Comment by wz36125** [comment]
> `finish_reason: None` 和 `finish_reason: Stop` 不算是错误。除非你看到了 `status: ERROR`

对 就是显示了 红色 ERROR

**Comment by wz36125** [comment]
@GaiZhenbiao 
有两个建议：
1. AI 给出的代码建议加个一键复制的按钮
2. AI 给出的代码中的双引号，不能直接拿过来粘贴用，得替换它的双引号

**Comment by wz36125** [comment]
@GaiZhenbiao 
还有一个问题，就是AI给代码的时候 容易出现生成很大一块空白换行，特别长，之后与之对话时，生成答案的过程中 非常的卡顿，几句话用时200s多

**Comment by Keldos-Li** [comment]
> 有两个建议：
> 
> 1. AI 给出的代码建议加个一键复制的按钮
> 
> 2. AI 给出的代码中的双引号，不能直接拿过来粘贴用，得替换它的双引号

如果原 issue 中的问题已被解决，建议关闭本 issue，然后**开一个新的 issue 提出您的功能请求**。

然后是关于建议的部分，我先替川虎答一下我的看法：
1. 有必要吗？（看起来引用的库会越来越多）
2. 在最新的脚本中这个问题已经被解决了，请更新。

**Comment by wz36125** [comment]
> > 有两个建议：
> > 
> > 1. AI 给出的代码建议加个一键复制的按钮
> > 2. AI 给出的代码中的双引号，不能直接拿过来粘贴用，得替换它的双引号
> 
> 如果原 issue 中的问题已被解决，建议关闭本 issue，然后**开一个新的 issue 提出您的功能请求**。
> 
> 然后是关于建议的部分，我先替川虎答一下我的看法：
> 
> 1. 有必要吗？（看起来引用的库会越来越多）
> 2. 在最新的脚本中这个问题已经被解决了，请更新。

好的

**Comment by GaiZhenbiao** [comment]
复制按钮我觉得可以加，依赖项增多我觉得问题不大。不过得调查一下如何实现这个功能。

**Comment by Keldos-Li** [comment]
> 复制按钮我觉得可以加，依赖项增多我觉得问题不大。不过得调查一下如何实现这个功能。

（了解了下，似乎也不用增加更多依赖）似乎引入一下某些现成的js，再写一点css就可以_(:з」∠)_回头试试。

**Comment by Keldos-Li** [comment]
> > 复制按钮我觉得可以加，依赖项增多我觉得问题不大。不过得调查一下如何实现这个功能。
> 
> （了解了下，似乎也不用增加更多依赖）似乎引入一下某些现成的js，再写一点css就可以_(:з」∠)_回头试试。

我收回之前的话，又研究了一下，发现gradio好像没法在head引入js脚本……
