### ISSUE TITLE
[功能请求]: 请求增加限制用户可用模型配置项

### ISSUE THREAD

**Issue by morrigank12** [GaiZhenbiao/ChuanhuChatGPT#943]
### 相关问题

公司内部使用的GPT key使用川虎搭的网站，最近GPT4 Turbo发布后GPT4的使用价格高于GPT4 Turbo，但仍然有人会选择GPT4使用

### 可能的解决办法

config.json中增加一个json配置项来决定用户可选择哪些模型，不需要根据用户区分，全部统一即可
配置项类似于"available_model": ["GPT4 Turbo", "GPT4 Vision"]

### 帮助开发

- [ ] 我愿意协助开发！

**Comment by GaiZhenbiao** [comment]
好的

**Comment by GaiZhenbiao** [comment]
现在加入了这个功能啦
