### ISSUE TITLE
[功能请求]: 使用ENV代替config.json

### ISSUE THREAD

**Issue by yongtao-wang** [GaiZhenbiao/ChuanhuChatGPT#945]
### 可能的解决办法

目前的程序框架使用config.json储存相关设置，但这种方法并非业界标准，更通用的方法是使用ENV文件，其主要好处是支持注释，甚至添加范例。

### 帮助开发

- [X] 我愿意协助开发！

**Comment by MZhao-ouo** [comment]
你可以给出例子吗？config.json 也是挺常用的一种配置方法，并且我们也支持注释，范例可以写在注释里面

**Comment by yongtao-wang** [comment]
JSON does not really support comment, see: https://stackoverflow.com/questions/244777/can-comments-be-used-in-json
And here is an example of using .env to load local variables: https://dev.to/jakewitcher/using-env-files-for-environment-variables-in-python-applications-55a1

Sorry for being unable to type Chinese ATM.

**Comment by Keldos-Li** [comment]
We are actually using jsonc for JSON with comments... I am not sure whether it's worth transferring the configuration file to `.env`. 🤔

**Comment by GaiZhenbiao** [comment]
我们目前使用`comment_json`(JSON with Comments)来在JSON中添加注释，并没有问题～
