### ISSUE TITLE
[Bug]: 为什么官方的Hugging Face 演示站点总结PDF报错

### ISSUE THREAD

**Issue by onlinedear** [GaiZhenbiao/ChuanhuChatGPT#946]
### 这个bug是否已存在现有issue了？

- [X] 我确认没有已有issue，且已阅读**常见问题**。

### 错误表现

![WX20231115-165950@2x](https://github.com/GaiZhenbiao/ChuanhuChatGPT/assets/10751712/107f0fa0-262f-4fce-ab16-81890466050e)

### 复现操作

我添加了Key，上传了一个pdf文件，点击总结之后报错了。

### 运行环境

- OS: mac 14.2 Beta版(23C5030f)
- Browser: Chrome
- Gradio version: 官方演示站点
- Python version: 官方演示站点

### 帮助解决

- [X] 我愿意协助解决！

### 补充说明

https://huggingface.co/spaces/JohnSmith9982/ChuanhuChatGPT
我在官方的演示站点尝试PDF总结的。

**Comment by cfanlu** [comment]
好像是langchain和openai版本有冲突，我本地部署也是一样，文档已上传后台就报错”索引构建失败“
后来参考这个帖子，改了下版本就可以了。
https://community.openai.com/t/attributeerror-module-openai-has-no-attribute-error/486676/9
langchain==0.0.316
openai==0.28.1

**Comment by GaiZhenbiao** [comment]
我更新了演示的版本，现在和GitHub同步了，应该没问题了。
