### ISSUE TITLE
[Bug]: 歷史記綠 .md檔問題

### ISSUE THREAD

**Issue by ixqkedp** [GaiZhenbiao/ChuanhuChatGPT#950]
### 这个bug是否已存在现有issue了？

- [X] 我确认没有已有issue，且已阅读**常见问题**。

### 错误表现

1. 刪除歷史記錄時只會刪除.json檔，不會刪除.md檔，例如將歷史記綠A刪除，history資料夾夾裡的檔案會由A.json、A.md變成A.md。
2. 重新命名歷史記錄時，原本的.md檔不會被刪除，例如將歷史記錄A改名成B，history資料夾夾裡的檔案會由A.json、A.md變成A.md、B.json、B.md。

### 复现操作

1.將歷史記綠A刪除，history資料夾夾裡的檔案會由A.json、A.md變成A.md。
2. 將歷史記錄A改名成B，history資料夾夾裡的檔案會由A.json、A.md變成A.md、B.json、B.md。

### 运行环境

- OS: 
- Browser: 
- Gradio version: 
- Python version: 

### 帮助解决

- [ ] 我愿意协助解决！

**Comment by GaiZhenbiao** [comment]
修复啦
