### ISSUE TITLE
[功能请求]: 集成GPT-4 turbo的多模态模型吗，包括图片和语音功能，并且适配手机平台使用

### ISSUE THREAD

**Issue by gupeihua** [GaiZhenbiao/ChuanhuChatGPT#951]
### 可能的解决办法

集成GPT-4 turbo的多模态模型吗，包括图片和语音功能，并且适配手机平台使用

### 帮助开发

- [ ] 我愿意协助开发！

**Comment by GaiZhenbiao** [comment]
现在就支持GPT4 Turbo，也支持图片，也适配了手机平台。语音功能暂不考虑，可以用输入法自带的语音转文字功能，和openai的差不了多少。
