### ISSUE TITLE
[功能请求]: GPT-4 Turbo模型的Token长度限制似乎有问题？

### ISSUE THREAD

**Issue by moerail** [GaiZhenbiao/ChuanhuChatGPT#953]
### 相关问题

使用GPT-4 Turbo模型时，进行了三四轮对话就开始忘掉之前的内容了。但是GPT-4 Turbo模型是支持128K的，是不是忘了更改相关内容了？

### 可能的解决办法

更改检查Token是否超限的相关代码。

### 帮助开发

- [ ] 我愿意协助开发！

**Comment by GaiZhenbiao** [comment]
确实存在这个问题，现在修复了～

**Comment by moerail** [comment]
> 确实存在这个问题，现在修复了～

请问怎么更新呢？我在Hugging Face和本地部署的依然有同样问题。

**Comment by GaiZhenbiao** [comment]
git clone 主线代码；huggingface的版本我刚刚更新啦

**Comment by moerail** [comment]
谢谢提示！已经更新了，然后看到修好了!
________________________________
