### ISSUE TITLE
[其他]: token计算是否正确？

### ISSUE THREAD

**Issue by longjq** [GaiZhenbiao/ChuanhuChatGPT#954]
### 是否已存在现有反馈与解答？

- [X] 我确认没有已有issue或discussion，且已阅读**常见问题**。

### 错误描述

我使用GPT-3.5使用时，发现token计算对不上，请问token是否有问题？

第一次计算的结果
![image](https://github.com/GaiZhenbiao/ChuanhuChatGPT/assets/6935703/d2508383-6ba0-4536-a5e1-2760c8c2deeb)

第二次计算结果
![image](https://github.com/GaiZhenbiao/ChuanhuChatGPT/assets/6935703/6b886780-03fb-4619-a10c-96d73835938e)

使用官方的计算结果(官方计算地址:https://platform.openai.com/tokenizer)
![image](https://github.com/GaiZhenbiao/ChuanhuChatGPT/assets/6935703/e6fa6cfb-bbec-4d03-b144-0340e4e050bc)

### 复现操作

1，在本地成功部署
2，打开对话框，使用GPT-3.5模型对话输入，1+1=？，连续两次
3，每次计算结果都和官方Token计算对不上

### 运行环境

- OS: 
- Browser: 
- Gradio version: 
- Python version: 
(或您的其他运行环境信息)

**Comment by GaiZhenbiao** [comment]
这是因为Chat模型存在一些额外开销。OpenAI没有提供流式传输时的准确token计数，因此流式传输时显示的token计数只是一个比较准确的估算。在设置里关闭流式传输，就可以看到OpenAI提供的准确的token消耗，如下图：
<img width="853" alt="image" src="https://github.com/GaiZhenbiao/ChuanhuChatGPT/assets/51039745/e9f0feed-533a-4f5b-9c9b-a0bd2122b3d6">
