### ISSUE TITLE
[功能请求]:或者说疑问，关于本地部署gradio外链的问题 

### ISSUE THREAD

**Issue by yaya6630170** [GaiZhenbiao/ChuanhuChatGPT#964]
### 相关问题

![image](https://github.com/GaiZhenbiao/ChuanhuChatGPT/assets/72657813/53955909-c7cc-4e31-b8d3-1c6693463962)
在云服务器上部署的，但是有点奇怪
![image](https://github.com/GaiZhenbiao/ChuanhuChatGPT/assets/72657813/2dd7f88b-c7d2-455b-9ee3-e1f42258ed69)
以前这一项我从来都不打开，但是可以外链，直接用IP：7860就能进入。现在不行了，生成了一个gradio外链，但是说是会72小时过期，让我自己去抱脸上部署一个
![image](https://github.com/GaiZhenbiao/ChuanhuChatGPT/assets/72657813/66ea3457-d05f-43c0-abca-9053d7e53b9a)

### 可能的解决办法

想请问一下，以前没生成gradio外链的时候是怎么进行连接的。现在必须按GPT说的那种自己弄一个gradio库么？

### 帮助开发

- [ ] 我愿意协助开发！

**Comment by GaiZhenbiao** [comment]
1. IP+端口的方式如果以前能用，现在也应该能用才对，这方面没有什么改动。
2. Gradio链接确实会过期，因为它提供了免费的frp服务。部署到Huggingface意味着不需要自己的服务器了。

**Comment by yaya6630170** [comment]
> 1. IP+端口的方式如果以前能用，现在也应该能用才对，这方面没有什么改动。
> 2. Gradio链接确实会过期，因为它提供了免费的frp服务。部署到Huggingface意味着不需要自己的服务器了。
请教一下，我share那行注释掉的，为啥会自动用gradio生成外链啊

**Comment by GaiZhenbiao** [comment]
那就不应该哇，你看看是不是编辑器没保存更改什么的
