### ISSUE TITLE
Code refactor required

### ISSUE THREAD

**Issue by LaChimere** [GaiZhenbiao/ChuanhuChatGPT#97]
The code is all in one file. It comes hard when adding new features.

**Comment by Keldos-Li** [comment]
为什么 不用 “功能请求” issue模板🥲🥲🥲（

**Comment by LaChimere** [comment]
> 为什么 不用 “功能请求” issue模板🥲🥲🥲（

Noted, thanks.

**Comment by GaiZhenbiao** [comment]
现在把这一个文件拆分成了三个文件，应该更优雅一些了。
