### ISSUE TITLE
[Bug]: DALL-E 3 API调用没有应用 openai_api_base 配置项

### ISSUE THREAD

**Issue by devforma** [GaiZhenbiao/ChuanhuChatGPT#973]
### 这个bug是否已存在现有issue了？

- [X] 我确认没有已有issue，且已阅读**常见问题**。

### 错误表现

config.json中配置了openai_api_base，DALL-E 3的API调用还是走的 api.openai.com，GPT4 Turbo的API调用正常走配置的api_base地址

以下为关闭clash，配置了openai_api_base情况下，调用DALL-E 3的日志
<img width="1143" alt="image" src="https://github.com/GaiZhenbiao/ChuanhuChatGPT/assets/3469890/58448973-e31b-4526-b086-a23b043b3cdc">

以下为开启clash后clash代理日志，其中api.openai.com那行为DALL-E 3 API调用，其他的为GPT4 Turbo API调用(代理地址)
![image](https://github.com/GaiZhenbiao/ChuanhuChatGPT/assets/3469890/a4ba8006-20e9-4fb9-a2dc-aaffa514d0e6)

### 复现操作

git clone main分支最新代码，配置config后启动服务

### 运行环境

- OS: Ubuntu 22.04
- Browser: Chrome 119
- Gradio version: 3.43.2
- Python version: 3.11.2

### 帮助解决

- [ ] 我愿意协助解决！

**Comment by astorm-z** [comment]
+1

**Comment by slideslide** [comment]
解决这个问题的代码已上传，等待merge后就可以关闭这个issue了
