### ISSUE TITLE
[功能请求]: 能够支持chatglm3吗

### ISSUE THREAD

**Issue by ilovejava15** [GaiZhenbiao/ChuanhuChatGPT#981]
### 可能的解决办法

本地启动后，上传txt文件系统报错2023-12-11 15:11:29,663 [ERROR] [index_func.py:137] 索引构建失败！Incorrect API key provided: sk-xxxxxxx. You can find your API key at https://platform.openai.com/account/api-keys.。

显示需要连接openai。能否用本地的模型？是否支持chatglm3？

### 帮助开发

- [ ] 我愿意协助开发！

**Comment by GaiZhenbiao** [comment]
可以的。请在config中设置“local_embedding”选项。
