### ISSUE TITLE
[本地部署]:  Connection Error

### ISSUE THREAD

**Issue by TigrisRiva** [GaiZhenbiao/ChuanhuChatGPT#982]
### 是否已存在现有反馈与解答？

- [X] 我确认没有已有issue或discussion，且已阅读**常见问题**。

### 是否是一个代理配置相关的疑问？

- [X] 我确认这不是一个代理配置相关的疑问。

### 错误描述

本地部署，并用nginx做好端口映射后，会出现一个错误 Connection Error
在浏览器的console里可以看到错误：
index.js:494 WebSocket connection to 'ws://我的域名/queue/join' failed:  
ping过域名，ip是正常的。

### 复现操作

1. 正常完成部署
2. 在nginx做好端口配置，7860映射到60端口并配置域名

### 运行环境

```markdown
- OS: CENTOS 7.0
- Browser: CHROME
- Gradio version: 
- Python version: 3.8
```

**Comment by GaiZhenbiao** [comment]
请检查是否打开了不必要的Nginx安全设置。例如这个就不应该打开：
![telegram-cloud-photo-size-5-6163304746258118899-y](https://github.com/GaiZhenbiao/ChuanhuChatGPT/assets/51039745/29f56f91-91b9-4a10-a3ab-a3466f3321a7)
