### ISSUE TITLE
[Bug]: 模型切换问题

### ISSUE THREAD

**Issue by TigrisRiva** [GaiZhenbiao/ChuanhuChatGPT#985]
### 这个bug是否已存在现有issue了？

- [X] 我确认没有已有issue，且已阅读**常见问题**。

### 错误表现

模型切换时会出现apikey丢失的情况
分析了下

### 复现操作

1. 正常完成部署
2. 先选择azure 模型
3. 上传知识库文件并完成索引
4. 删除知识库文件，切换到gpt3.5模型
报错，看起来时apikey丢失了
不确定是否是删除知识库文件时发生的丢失

### 错误日志

```shell
发生了错误：{ "error": { "message": "Incorrect API key provided: sk-xxxxxxx. You can find your API key at https://platform.openai.com/account/api-keys.", "type": "invalid_request_error", "param": null, "code": "invalid_api_key" }}
```

### 运行环境

OPENAI版本：>1.0
OPENAI版本如果超过1.0，会出现知识库无法索引的情况，修改代码construct_index代码中的Azure部分
embeddings = AzureOpenAIEmbeddings(
                model=os.environ["AZURE_EMBEDDING_MODEL_NAME"],
                azure_deployment=os.environ["AZURE_EMBEDDING_DEPLOYMENT_NAME"], 
                api_key=os.environ["AZURE_OPENAI_API_KEY"],
                openai_api_type = os.environ["OPENAI_API_TYPE"],
                azure_endpoint=os.environ["AZURE_OPENAI_API_BASE_URL"], 
                api_version = os.environ["AZURE_OPENAI_API_VERSION"])

### 帮助解决

- [ ] 我愿意协助解决！

**Comment by TigrisRiva** [comment]
已经解决

**Comment by Xtaiyang** [comment]
> 已经解决

怎么解决的
