### ISSUE TITLE
[Bug]: 使用vision模型识别图片时，无法生成答案

### ISSUE THREAD

**Issue by Scolism** [GaiZhenbiao/ChuanhuChatGPT#992]
### 这个bug是否已存在现有issue了？

- [X] 我确认没有已有issue，且已阅读**常见问题**。

### 错误表现

答案框为空, 使用了第三方API，可能存在json解析问题。

### 复现操作

![1](https://github.com/GaiZhenbiao/ChuanhuChatGPT/assets/43903287/92114ba9-f798-4643-98d5-590c911726f0)
![2](https://github.com/GaiZhenbiao/ChuanhuChatGPT/assets/43903287/5f7080d8-02d9-4161-8346-eb5c1c0c94c9)

### 帮助解决

- [ ] 我愿意协助解决！ 愿意提供API和token协助解决。

**Comment by ddffwyb** [comment]
我也遇到了同样的问题。答案应该是生成了的，你的截图里在 ‘content’ 后面也能看到生成的答案变成了一个一个单个的字，最后报错我这边是 “JSON解析错误,收到的内容: data: [DONE]“，在 OpenAI 网站那边也能看到模型被调用了，就是答案显出不出来。之前用 GPT4 Vision 都没有这个问题，就是今天更新了最新版本后出现的。

**Comment by Scolism** [comment]
> 我也遇到了同样的问题。答案应该是生成了的，你的截图里在 ‘content’ 后面也能看到生成的答案变成了一个一个单个的字，最后报错我这边是 “JSON解析错误,收到的内容: data: [DONE]“，在 OpenAI 网站那边也能看到模型被调用了，就是答案显出不出来。之前用 GPT4 Vision 都没有这个问题，就是今天更新了最新版本后出现的。

我也看到了单个字的答案，但是连起来的话，答案也太短了。

**Comment by ddffwyb** [comment]
对！我在尝试关掉实时传输回答的选项后，不再是空白的回答框了。但是传回的答案特别短，而且是那种半截的活都没说完就停了。只有在用 GPT4 Vision 的时候遇到了这种情况，原因不明。我也可以确定不是网络的问题，因为用的是部署在新加坡的服务器。

**Comment by GaiZhenbiao** [comment]
我修复一下

**Comment by Scolism** [comment]
> 我修复一下

谢谢大佬！

**Comment by Scolism** [comment]
已修复。
