### ISSUE TITLE
[功能请求]: 通过clipboard上传图片

### ISSUE THREAD

**Issue by v2rockets** [GaiZhenbiao/ChuanhuChatGPT#993]
### 相关问题

目前gradio4.4以上版本已经支持gr.inputs.Image(source="clipboard")，是否可以考虑将剪切板粘贴图片也添加进来，在粘贴截图之类的信息时会方便很多。

### 可能的解决办法

目前我试验过直接升级gradio似乎会导致很多兼容性的问题，希望作者可以考虑是否有比较好的解决方案。

### 帮助开发

- [X] 我愿意协助开发！

**Comment by Keldos-Li** [comment]
是的……升级gradio会有大量大量的兼容性问题……🥲不想适配……🥲

**Comment by Keldos-Li** [comment]
这个功能在做了
