### ISSUE TITLE
[功能请求]: 希望在未登录的状态下，通过浏览器缓存保留对话记录

### ISSUE THREAD

**Issue by Mchousexuxu** [GaiZhenbiao/ChuanhuChatGPT#999]
### 相关问题

fyi

### 可能的解决办法

目前已知只有在登录状态下实现聊天记录隔壁。
可是现在的使用场景想在不登陆的状态下也可以实现保存对话的记录，是否可以通过读取浏览器缓存的方式实现未登录状态下的对话记录隔离？

烦请各位指点迷津，谢谢拉

### 帮助开发

- [X] 我愿意协助开发！

**Comment by Keldos-Li** [comment]
可以在config.json中设置
```
    "hide_history_when_not_logged_in": true,
```

此时只在聊天框中通过浏览器缓存记录聊天历史。注意，此时新建对话，聊天历史会被清除。

参见 [https://github.com/GaiZhenbiao/ChuanhuChatGPT/wiki/使用教程#未登录时隐藏历史对话记录](未登录时隐藏历史对话记录)
